package it.tndigitale.a4g.proxy.services;

enum VerificaFirmaErrorCodeEnum {
	FILE_NON_FIRMATO,
	FIRMA_NON_VALIDA,
	DATI_FIRMATARIO_MANCANTI,
	FIRMATARIO_NON_UNIVOCO,
	FIRMATARIO_NUMERO_ERRATO,
	FIRMATARIO_TITOLARE_DIVERSI;
}