DELETE FROM A4GT_ISTRUTTORE_DISACCOPPIATO WHERE ID=12456201;
DELETE FROM A4GT_ISTRUTTORE_DISACCOPPIATO WHERE ID=12456202;
DELETE FROM A4GT_ISTRUTTORE_DIS_PASCOLI WHERE ID=1;
DELETE FROM A4GT_ISTRUTTORE_DIS_PASCOLI WHERE ID=2;
DELETE FROM A4GT_ISTRUTTORE_DISACCOPPIATO WHERE ID_ISTRUTTORIA IN (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (7, 8, 9, 10, 13, 14));
DELETE FROM A4GT_ISTRUTTORE_DIS_PASCOLI WHERE ID_ISTRUTTORIA IN (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (7, 8, 9, 10, 13, 14));
DELETE FROM A4GT_ISTRUTTORIA where ID_DOMANDA in (7, 8, 9, 10, 13, 14);
DELETE FROM A4GT_ISTRUTTORIA WHERE ID BETWEEN 1 AND 15;
DELETE FROM A4GT_SOSTEGNO WHERE ID BETWEEN 1 AND 15;
DELETE FROM A4GT_DOMANDA WHERE ID BETWEEN 1 AND 15;
DELETE FROM A4GD_STATO_LAV_SOSTEGNO WHERE ID=13115;
DELETE FROM A4GD_STATO_LAV_SOSTEGNO WHERE ID=13117;
DELETE FROM A4GT_PICCOLO_AGRICOLTORE;

COMMIT;