delete FROM A4GT_ERRORE_RICEVIBILITA WHERE ID_DOMANDA = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO ='PMPBRN63C17L378V');
delete FROM A4GT_SOSTEGNO WHERE ID_DOMANDA = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO ='CMARTI52E68B006T');
delete FROM A4GT_SOSTEGNO WHERE ID_DOMANDA = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO ='PMPBRN63C17L378V');
delete FROM A4GT_SOSTEGNO WHERE ID_DOMANDA = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO ='BRGNGL64C30C7941');
COMMIT;

delete FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CMARTI52E68B006T';
delete FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'PMPBRN63C17L378V';
delete FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'BRGNGL64C30C7941';

COMMIT;