-- Creazione oggetti comuni del sistema fascicolo-anagrafica
DROP ALL OBJECTS;

-- Versione 1.0

CREATE ALIAS TO_DATE_ALT AS '
java.util.Date toDate(String s, String dateFormat) throws Exception { 
  return new java.text.SimpleDateFormat(dateFormat).parse(s); 
} 
';

-- 1. Sequence
CREATE SEQUENCE NXTNBR
    START WITH 100000
    NOCYCLE
    NOCACHE;

-- 2. Tabella di Log
CREATE TABLE A4GT_LOGGING (
    ID BIGINT NOT NULL,    
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    UTENTE VARCHAR2(500 CHAR) NOT NULL,
    TIPO_EVENTO VARCHAR2(500 CHAR) NOT NULL,
    TABELLA VARCHAR2(4000) NOT NULL,
    ID_ENTITA BIGINT NOT NULL,
    DT_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT A4GT_LOGGING_PK PRIMARY KEY (ID)
);

CREATE TABLE A4GT_LOGGING_VALIDAZIONE (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    UTENTE VARCHAR2(500 CHAR) NOT NULL,
    TIPO_EVENTO VARCHAR2(500 CHAR) NOT NULL,
    TABELLA VARCHAR2(4000) NOT NULL,
    ID_ENTITA BIGINT NOT NULL,
    DT_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT A4GT_LOGGING_VALIDAZIONE_PK PRIMARY KEY (ID)
);

CREATE TABLE A4GT_PERSONA (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    CODICE_FISCALE VARCHAR2(16) NOT NULL,
    CONSTRAINT PK_PERSONA PRIMARY KEY (ID, ID_VALIDAZIONE)
);
CREATE UNIQUE INDEX IDU_CODICE_FISCALE ON A4GT_PERSONA (ID_VALIDAZIONE, CODICE_FISCALE);

CREATE TABLE A4GT_PERSONA_FISICA (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    COGNOME VARCHAR2(50) NOT NULL,
    SESSO VARCHAR2(7),
    DATA_NASCITA DATE,
    COMUNE_NASCITA VARCHAR2(100),
    PROVINCIA_NASCITA VARCHAR2(100),
    DECEDUTO NUMBER(1),

    DESCRIZIONE_ESTESA VARCHAR(300),
    TOPONIMO VARCHAR(50),
    VIA VARCHAR(200),
    NUMERO_CIVICO VARCHAR(10),
    CAP VARCHAR(10),
    CODICE_ISTAT VARCHAR(10),
    FRAZIONE VARCHAR(100),
    PROVINCIA VARCHAR(100),
    COMUNE VARCHAR(100),

    DENOMINAZIONE VARCHAR2(200),
    PARTITA_IVA VARCHAR2(11),

    FORMA_GIURIDICA VARCHAR2(100),
    DATA_ISCRIZIONE DATE,
    PROVINCIA_CCIAA VARCHAR(2),
    NUMERO_REPERTORIO NUMBER(10),
    CESSATA NUMBER(1),

    SEDE_DESCRIZIONE_ESTESA VARCHAR(300),
    SEDE_TOPONIMO VARCHAR(50),
    SEDE_VIA VARCHAR(200),
    SEDE_NUMERO_CIVICO VARCHAR(10),
    SEDE_CAP VARCHAR(10),
    SEDE_CODICE_ISTAT VARCHAR(10),
    SEDE_FRAZIONE VARCHAR(100),
    SEDE_PROVINCIA VARCHAR(100),
    SEDE_COMUNE VARCHAR(100),

    SEDE_CC_DESCRIZIONE_ESTESA VARCHAR(300),
    SEDE_CC_TOPONIMO VARCHAR(50),
    SEDE_CC_VIA VARCHAR(200),
    SEDE_CC_NUMERO_CIVICO VARCHAR(10),
    SEDE_CC_CAP VARCHAR(10),
    SEDE_CC_CODICE_ISTAT VARCHAR(10),
    SEDE_CC_FRAZIONE VARCHAR(100),
    SEDE_CC_PROVINCIA VARCHAR(100),
    SEDE_CC_COMUNE VARCHAR(100),

    PEC VARCHAR(200),
    TELEFONO VARCHAR(30),
    DATA_MORTE DATE,

    CONSTRAINT PK_PERSONA_FISICA PRIMARY KEY (ID, ID_VALIDAZIONE),
    FOREIGN KEY (ID, ID_VALIDAZIONE) REFERENCES A4GT_PERSONA (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_PERSONA_GIURIDICA (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    PARTITA_IVA VARCHAR2(11) NOT NULL,
    DENOMINAZIONE VARCHAR2(100) NOT NULL,
    FORMA_GIURIDICA VARCHAR2(100),
    OGGETTO_SOCIALE CLOB,
    DATA_COSTITUZIONE DATE,
    DATA_TERMINE DATE,
    CAPITALE_SOCIALE_DELIBERATO NUMBER(10,2),
    CF_RAPPRESENTANTE_LEGALE VARCHAR2(16) NOT NULL,
    NOME_RAPPRESENTANTE_LEGALE VARCHAR2(200) NOT NULL,

    DATA_ISCRIZIONE DATE,
    PROVINCIA_CCIAA VARCHAR(2),
    NUMERO_REPERTORIO NUMBER(10),
    CESSATA NUMBER(1),

    SEDE_DESCRIZIONE_ESTESA VARCHAR(300),
    SEDE_TOPONIMO VARCHAR(50),
    SEDE_VIA VARCHAR(200),
    SEDE_NUMERO_CIVICO VARCHAR(10),
    SEDE_CAP VARCHAR(10),
    SEDE_CODICE_ISTAT VARCHAR(10),
    SEDE_FRAZIONE VARCHAR(100),
    SEDE_PROVINCIA VARCHAR(100),
    SEDE_COMUNE VARCHAR(100),

    SEDE_CC_DESCRIZIONE_ESTESA VARCHAR(300),
    SEDE_CC_TOPONIMO VARCHAR(50),
    SEDE_CC_VIA VARCHAR(200),
    SEDE_CC_NUMERO_CIVICO VARCHAR(10),
    SEDE_CC_CAP VARCHAR(10),
    SEDE_CC_CODICE_ISTAT VARCHAR(10),
    SEDE_CC_FRAZIONE VARCHAR(100),
    SEDE_CC_PROVINCIA VARCHAR(100),
    SEDE_CC_COMUNE VARCHAR(100),

	PEC VARCHAR(200),
    TELEFONO VARCHAR(30),

    CONSTRAINT PK_PERSONA_GIURIDICA PRIMARY KEY (ID, ID_VALIDAZIONE),
    FOREIGN KEY (ID, ID_VALIDAZIONE) REFERENCES A4GT_PERSONA (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_CAA (
    ID NUMBER(20,0) NOT NULL,
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL, 
	CODICE_FISCALE VARCHAR2(16), 
	DENOMINAZIONE VARCHAR2(100) NOT NULL, 
	PARTITA_IVA VARCHAR2(11), 
	FORMA_GIURIDICA VARCHAR2(100), 
	ATTO_RICONOSCIMENTO VARCHAR2(500), 
	SOCIETA_SERVIZI VARCHAR2(100), 
	CF_SOCIETA_SERVIZI VARCHAR2(11), 
	DESCRIZIONE_ESTESA VARCHAR2(300), 
	CODICE_ISTAT VARCHAR2(1), 
	FRAZIONE VARCHAR2(100), 
	TOPONIMO VARCHAR2(50), 
	VIA VARCHAR2(200), 
	NUMERO_CIVICO VARCHAR2(10), 
	CAP VARCHAR2(10), 
	PROVINCIA VARCHAR2(100), 
	COMUNE VARCHAR2(100), 
	EMAIL VARCHAR2(100),
    CONSTRAINT "PK_CAA" PRIMARY KEY ("ID")
);

CREATE TABLE A4GT_SPORTELLO (
    ID BIGINT NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    IDENTIFICATIVO NUMBER(22) NOT NULL,
    DENOMINAZIONE VARCHAR2(100) NOT NULL,
    COMUNE VARCHAR2(100),
    ID_CAA NUMBER(20) NOT NULL,
    INDIRIZZO VARCHAR2(200),
    CAP VARCHAR2(10),
    PROVINCIA VARCHAR2(100),
    TELEFONO VARCHAR2(30),
    EMAIL VARCHAR2(200),
    
    CONSTRAINT PK_SPORTELLO PRIMARY KEY (ID),
    FOREIGN KEY (ID_CAA) REFERENCES A4GT_CAA (ID),
);
CREATE UNIQUE INDEX IDU_SPORTELLO_ID_SPORTELLO_AGS ON A4GT_SPORTELLO (IDENTIFICATIVO);

CREATE TABLE A4GT_FASCICOLO (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    CUAA VARCHAR2(16) NOT NULL,
    STATO VARCHAR2(30) NOT NULL,
    DENOMINAZIONE VARCHAR2(100) NOT NULL,
    ID_PERSONA BIGINT,
    PERSONA_ID_VALIDAZIONE INTEGER DEFAULT 0,
    ORGANISMO_PAGATORE VARCHAR2(30) NOT NULL,
    DATA_APERTURA DATE,
    DATA_MODIFICA DATE,
    UTENTE_MODIFICA VARCHAR2(100) NOT NULL,
    DATA_VALIDAZIONE DATE,
    UTENTE_VALIDAZIONE VARCHAR2(200),
    SCHEDA_VALIDAZIONE_FIRMATA BLOB,
    DT_PROTOCOLLAZIONE DATE,
	ID_PROTOCOLLO VARCHAR2(255),
    DT_AGGIORNAMENTO_FONTI_ESTERNE DATE,
    DT_CHIUSURA_TRASFERIMENTO_OP DATE,
    SCHEDA_VALIDAZIONE BLOB,
    ID_SCHEDA_VALIDAZIONE BIGINT,
    CONSTRAINT PK_FASCICOLO PRIMARY KEY (ID, ID_VALIDAZIONE),
    FOREIGN KEY (ID_PERSONA, PERSONA_ID_VALIDAZIONE) REFERENCES A4GT_PERSONA (ID, ID_VALIDAZIONE),
);


CREATE INDEX IDU_DENOMINAZIONE ON A4GT_FASCICOLO (DENOMINAZIONE);
CREATE UNIQUE INDEX IDU_CUAA ON A4GT_FASCICOLO (ID_VALIDAZIONE, CUAA);

CREATE TABLE A4GT_DETENZIONE (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    DATA_INIZIO DATE NOT NULL,
    DATA_FINE DATE,
    ID_FASCICOLO BIGINT NOT NULL,
	FASCICOLO_ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
	
    CONSTRAINT PK_DETENZIONE PRIMARY KEY (ID, ID_VALIDAZIONE),
    CONSTRAINT FK_DETENZIONE_FASCICOLO FOREIGN KEY (ID_FASCICOLO, FASCICOLO_ID_VALIDAZIONE) REFERENCES A4GT_FASCICOLO (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_MANDATO (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    CONTRATTO BLOB NOT NULL,
	IDENTIFICATIVO_SPORTELLO BIGINT,
	DATA_SOTTOSCRIZIONE DATE NOT NULL,

    CONSTRAINT PK_MANDATO PRIMARY KEY (ID, ID_VALIDAZIONE),
    CONSTRAINT FK_IDENTIFICATIVO_SPORTELLO FOREIGN KEY (IDENTIFICATIVO_SPORTELLO) REFERENCES A4GT_SPORTELLO (IDENTIFICATIVO)
);

CREATE TABLE A4GT_UNITA_TECNICO_ECONOMICHE (
	ID BIGINT NOT NULL,
	VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
	IDENTIFICATIVO_UTE VARCHAR2(20 BYTE), 
	DATA_APERTURA DATE, 
	DATA_CESSAZIONE DATE, 
	DATA_DENUNCIA_CESSAZIONE DATE, 
	CAUSALE_CESSAZIONE VARCHAR2(4000 BYTE), 
	ATTIVITA VARCHAR2(4000 BYTE), 
	DATA_DENUNCIA_INIZIO_ATTIVITA DATE, 
	SETTORE_MERCEOLOGICO VARCHAR2(100 BYTE), 
	TELEFONO VARCHAR2(100 BYTE), 
	INDIRIZZO_PEC VARCHAR2(100 BYTE), 
	TOPONIMO VARCHAR2(100 BYTE), 
	VIA VARCHAR2(100 BYTE), 
	NUMERO_CIVICO VARCHAR2(100 BYTE), 
	COMUNE VARCHAR2(100 BYTE), 
	CAP VARCHAR2(100 BYTE), 
	CODICE_ISTAT_COMUNE VARCHAR2(100 BYTE), 
	FRAZIONE VARCHAR2(100 BYTE), 
	PROVINCIA VARCHAR2(100 BYTE), 
	ID_PERSONA NUMBER(20,0),
	PERSONA_ID_VALIDAZIONE INTEGER DEFAULT 0,
	ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT PK_UNITA_LOCALE PRIMARY KEY (ID, ID_VALIDAZIONE),
	FOREIGN KEY (ID_PERSONA, PERSONA_ID_VALIDAZIONE) REFERENCES A4GT_PERSONA (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_DESTINAZIONE_USO (
	ID NUMBER(20,0) NOT NULL,
	VERSIONE NUMBER(10) DEFAULT 0 NOT NULL, 
	DESCRIZIONE VARCHAR2(100 BYTE), 
	ID_UNITA_TECNICO_ECONOMICHE NUMBER(20),
	ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
	UNITA_TECNICO_ECONOMICHE_IDVAL INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT PK_DESTINAZIONE_USO PRIMARY KEY (ID, ID_VALIDAZIONE),
	FOREIGN KEY (ID_UNITA_TECNICO_ECONOMICHE, UNITA_TECNICO_ECONOMICHE_IDVAL) REFERENCES A4GT_UNITA_TECNICO_ECONOMICHE (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_ATTIVITA_ATECO (
    ID BIGINT NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    ID_SEDE INTEGER,
    SEDE_ID_VALIDAZIONE INTEGER DEFAULT 0,
    CODICE VARCHAR2(50) NOT NULL,
    DESCRIZIONE VARCHAR2(300) NOT NULL,
    IMPORTANZA VARCHAR2(100),
    FONTE VARCHAR2(20) NOT NULL,
	ID_UNITA_TECNICO_ECONOMICHE VARCHAR2(20),
	ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
	UNITA_TECNICO_ECONOMICHE_IDVAL INTEGER DEFAULT 0,
    CONSTRAINT PK_ATTIVITA_ATECO PRIMARY KEY (ID, ID_VALIDAZIONE),
	CONSTRAINT FK_ATT_ATECO_UNITA_TECNICO_EC FOREIGN KEY (ID_UNITA_TECNICO_ECONOMICHE, UNITA_TECNICO_ECONOMICHE_IDVAL) REFERENCES A4GT_UNITA_TECNICO_ECONOMICHE (ID, ID_VALIDAZIONE)
    -- Per ora non gestisco la foreign key su ID_SEDE dato che ho deciso di denormalizzarle in persona fisica e giuridica
    -- e non sporco la struttura dati di A4GT_PERSONA
    -- CONSTRAINT FK_MANDATO_SPORTELLO FOREIGN KEY (ID_SEDE) REFERENCES A4GT_PERSONA (ID)
    -- CONSTRAINT FK_MANDATO_CAA FOREIGN KEY (ID_CAA) REFERENCES A4GT_PERSONA_GIURIDICA (ID)
);


CREATE TABLE A4GT_PERSONA_FISICA_CON_CARICA (
    ID NUMBER(20) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    CODICE_FISCALE VARCHAR2(16),
    NOME VARCHAR2(50),
    COGNOME VARCHAR2(50),
    SESSO VARCHAR2(7),
    DATA_NASCITA DATE,
    COMUNE_NASCITA VARCHAR2(100),
    PROVINCIA_NASCITA VARCHAR2(100),
    DECEDUTO NUMBER(1),
    DESCRIZIONE_ESTESA VARCHAR(300),
    TOPONIMO VARCHAR(50),
    VIA VARCHAR(200),
    NUMERO_CIVICO VARCHAR(10),
    CAP VARCHAR(10),
    CODICE_ISTAT VARCHAR(10),
    FRAZIONE VARCHAR(100),
    PROVINCIA VARCHAR(100),
    COMUNE VARCHAR(100),
	ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
	VERIFICA_CODICE_FISCALE VARCHAR(20),
    CONSTRAINT PK_PERSONA_FISICA_CON_CARICA PRIMARY KEY (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_PERSONA_GIURIDICA_CARICA (
    ID NUMBER(20) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
	DENOMINAZIONE VARCHAR2(2000),
    CODICE_FISCALE VARCHAR2(16),
	ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PERSONA_GIURIDICA_CARICA PRIMARY KEY (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_CARICA (
    ID NUMBER(20) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL, 
    DESCRIZIONE VARCHAR2(100 BYTE) NOT NULL, 
    IDENTIFICATIVO VARCHAR2(20 BYTE), 
    DATA_INIZIO_CARICA DATE,
    ID_PERSONA_FISICA_CON_CARICA NUMBER(20),
    ID_PERSONA_GIURIDICA NUMBER(20),
    PERS_GIURIDICA_ID_VALIDAZIONE  INTEGER DEFAULT 0,
	PERSONA_FISICA_CARICA_IDVAL  INTEGER DEFAULT 0,
	ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
	PERSONA_GIURIDICA_CARICA_IDVAL INTEGER DEFAULT 0,
	ID_PERSONA_GIURIDICA_CARICA INTEGER DEFAULT 0,
    PERSONA_FISICA_ID NUMBER(20),
    PERSONA_FISICA_ID_VALIDAZIONE INTEGER,
	FIRMATARIO NUMBER(1) NOT NULL,
    CONSTRAINT PK_CARICA PRIMARY KEY (ID, ID_VALIDAZIONE),
    CONSTRAINT FK_PERSONA_FISICA_CON_CARICA FOREIGN KEY (ID_PERSONA_FISICA_CON_CARICA, PERSONA_FISICA_CARICA_IDVAL) REFERENCES A4GT_PERSONA_FISICA_CON_CARICA (ID, ID_VALIDAZIONE),
    CONSTRAINT FK_CARICA_PERSONA_GIURIDICA FOREIGN KEY (ID_PERSONA_GIURIDICA, PERS_GIURIDICA_ID_VALIDAZIONE) REFERENCES A4GT_PERSONA_GIURIDICA (ID, ID_VALIDAZIONE),
    CONSTRAINT FK_CARICA_PERSONA_FISICA FOREIGN KEY (PERSONA_FISICA_ID, PERSONA_FISICA_ID_VALIDAZIONE) REFERENCES A4GT_PERSONA_FISICA (ID, ID_VALIDAZIONE),
	CONSTRAINT FK_PERSONA_GIURIDICA_CARICA FOREIGN KEY (ID_PERSONA_GIURIDICA_CARICA, PERSONA_GIURIDICA_CARICA_IDVAL) REFERENCES A4GT_PERSONA_GIURIDICA_CARICA (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_EVENTSTORED(
    ID NUMBER(20,0) NOT NULL,
    VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL,
    EVENTO VARCHAR2(500) NOT NULL,
    JSON_EVENT CLOB NOT NULL,
    USER_NAME VARCHAR2(100) NOT NULL,
    DATA_INSERIMENTO DATE NOT NULL,
    NUMERO_RETRY NUMBER(3,0) DEFAULT 0 NOT NULL,
    ERRORE CLOB,
    CONSTRAINT PK_EVENTSTORED PRIMARY KEY (ID)
);

CREATE TABLE A4GT_REVOCA_IMMEDIATA (
	ID NUMBER(20, 0),
	VERSIONE NUMBER(10, 0) DEFAULT 0, 
	DATA_SOTTOSCRIZIONE DATE, 
	STATO VARCHAR2(30 BYTE),	
	ID_MANDATO NUMBER(20, 0), 
	MANDATO_ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
	CODICE_FISCALE VARCHAR2(255 BYTE), 
	ID_PROTOCOLLO VARCHAR2(255 BYTE), 
	DT_PROTOCOLLO DATE, 
	DATA_VALUTAZIONE DATE, 
	MOTIVAZIONE_RIFIUTO VARCHAR2(4000 BYTE), 
	CAUSA_RICHIESTA VARCHAR2(4000 BYTE), 
	RICHIESTA_FIRMATA BLOB,
	ID_SPORTELLO_DICHIARATO NUMBER(20, 0),
	
    CONSTRAINT PK_REVOCA_IMMEDIATA PRIMARY KEY (ID),
    CONSTRAINT FK_REVOCA_IMMEDIATA_MANDATO FOREIGN KEY (ID_MANDATO, MANDATO_ID_VALIDAZIONE) REFERENCES A4GT_MANDATO (ID, ID_VALIDAZIONE),
	CONSTRAINT FK_REVOCA_IMMEDIATA_SPORTELLO FOREIGN KEY (ID_SPORTELLO_DICHIARATO) REFERENCES A4GT_SPORTELLO (ID)
);

CREATE TABLE A4GT_MODO_PAGAMENTO(
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10,0) DEFAULT 0,
    IBAN VARCHAR2(34 BYTE), 
    BIC VARCHAR2(11 BYTE), 
    DENOMINAZIONE VARCHAR2(400 BYTE), 
    ID_FASCICOLO NUMBER(20,0),
    DENOMINAZIONE_ISTITUTO VARCHAR2(400 BYTE),
    DENOMINAZIONE_FILIALE VARCHAR2(400 BYTE),
    CITTA_FILIALE VARCHAR2(200 BYTE),
    FASCICOLO_ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_MODO_PAGAMENTO PRIMARY KEY (ID, ID_VALIDAZIONE),
    CONSTRAINT FK_PAGAMENTO_FASCICOLO FOREIGN KEY (ID_FASCICOLO, FASCICOLO_ID_VALIDAZIONE) REFERENCES A4GT_FASCICOLO (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_ISCRIZIONE_SEZIONE (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    SEZIONE VARCHAR2(30) NOT NULL,
    DATA_ISCRIZIONE DATE NOT NULL,
    QUALIFICA VARCHAR2(100),
    COLTIVATORE_DIRETTO VARCHAR2(100),
    ID_PERSONA BIGINT,
    PERSONA_ID_VALIDAZIONE INTEGER DEFAULT 0,
    CONSTRAINT PK_ISCRIZIONE_SEZIONE PRIMARY KEY (ID, ID_VALIDAZIONE),
    FOREIGN KEY (ID_PERSONA, PERSONA_ID_VALIDAZIONE) REFERENCES A4GT_PERSONA (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_ORGANIZZAZIONE (    
    ID BIGINT NOT NULL, 
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    DENOMINAZIONE VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ORGANIZZAZIONE PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UIDX_ORGANIZZAZIONE ON A4GT_ORGANIZZAZIONE (DENOMINAZIONE);

CREATE TABLE A4GT_FASCICOLO_ORGANIZZAZIONE (   
    ID BIGINT NOT NULL, 
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    CUAA VARCHAR2(16) NOT NULL,
    ORGANIZZAZIONE_ID NUMBER(20,0) NOT NULL, 
    UTENTE_INSERIMENTO VARCHAR2(100) NOT NULL, 
    DT_INIZIO_ASSOCIAZIONE TIMESTAMP, 
    DT_FINE_ASSOCIAZIONE TIMESTAMP, 
    DT_INSERIMENTO_ASSOCIAZIONE TIMESTAMP, 
    DT_CANCELLAZIONE_ASSOCIAZIONE TIMESTAMP,
    UTENTE_CANCELLAZIONE VARCHAR2(100), 
    CONSTRAINT PK_FASCICOLO_ORGANIZZAZIONE PRIMARY KEY (ID),
    CONSTRAINT FK_FASCICOLO_ORGANIZZAZIONE_1 FOREIGN KEY (ORGANIZZAZIONE_ID) REFERENCES A4GT_ORGANIZZAZIONE (ID)
);

CREATE TABLE A4GT_DETENZIONE_IN_PROPRIO (   
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DETENZIONE_IN_PROPRIO PRIMARY KEY (ID, ID_VALIDAZIONE),
    CONSTRAINT FK_DETENZIONE_IN_PROPRIO FOREIGN KEY (ID, ID_VALIDAZIONE) REFERENCES A4GT_DETENZIONE (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_DOCUMENTO_IDENTITA(
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10,0) DEFAULT 0,
    CODICE_FISCALE VARCHAR2(16 BYTE), 
	NUMERO VARCHAR2(100 BYTE), 
	TIPOLOGIA VARCHAR2(100 BYTE), 
	DATA_RILASCIO DATE, 
	DATA_SCADENZA DATE, 
	DOCUMENTO BLOB, 
    FASCICOLO_ID NUMBER(20,0),
    FASCICOLO_ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DOCUMENTO_IDENTITA PRIMARY KEY (ID, ID_VALIDAZIONE),
    CONSTRAINT FK_DOC_IDENTITA_FASCICOLO FOREIGN KEY (FASCICOLO_ID, FASCICOLO_ID_VALIDAZIONE) REFERENCES A4GT_FASCICOLO (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_CONTROLLO_COMPLETEZZA(
    ID BIGINT NOT NULL,
    VERSIONE NUMBER(10,0) DEFAULT 0,
    TIPO_CONTROLLO VARCHAR2(100 BYTE) NOT NULL,
    ESITO INTEGER,
    ID_CONTROLLO INTEGER,
    DATA_ESECUZIONE DATE,
    UTENTE VARCHAR2(100 BYTE) NOT NULL,
    FASCICOLO_ID NUMBER(20,0),
    FASCICOLO_ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CONTROLLO_COMPLETEZZA PRIMARY KEY (ID),
    CONSTRAINT FK_CONTROLLO_FASCICOLO FOREIGN KEY (FASCICOLO_ID, FASCICOLO_ID_VALIDAZIONE) REFERENCES A4GT_FASCICOLO (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_MOVIMENTAZIONE_FASCICOLO(
    ID BIGINT NOT NULL,
    VERSIONE NUMBER(10,0) DEFAULT 0,
    FASCICOLO_ID NUMBER(20,0),
    FASCICOLO_ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    DATA_INIZIO DATE NOT NULL,
    MOTIVAZIONE_INIZIO VARCHAR2(100 BYTE),
    DATA_FINE DATE,
    MOTIVAZIONE_FINE VARCHAR2(100 BYTE),
    UTENTE VARCHAR2(100 BYTE) NOT NULL,
    TIPO VARCHAR2(100 BYTE) NOT NULL,
    CONSTRAINT PK_SOSPENSIONE PRIMARY KEY (ID),
    CONSTRAINT FK_SOSPENSIONE_FASCICOLO FOREIGN KEY (FASCICOLO_ID, FASCICOLO_ID_VALIDAZIONE) REFERENCES A4GT_FASCICOLO (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GT_EREDE (
    ID BIGINT NOT NULL,
    VERSIONE NUMBER(10,0) DEFAULT 0,
    PERSONA_FISICA_ID NUMBER(20,0),
    PERSONA_FISICA_ID_VALIDAZIONE NUMBER(20,0),
    FASCICOLO_ID NUMBER(20,0),
    FASCICOLO_ID_VALIDAZIONE NUMBER(20,0),
    FIRMATARIO NUMBER(1,0),
    CONSTRAINT PK_EREDE PRIMARY KEY (ID),
    CONSTRAINT FK_EREDE_PERSONA_FISICA FOREIGN KEY (PERSONA_FISICA_ID, PERSONA_FISICA_ID_VALIDAZIONE) REFERENCES A4GT_PERSONA_FISICA (ID, ID_VALIDAZIONE),
    CONSTRAINT FK_EREDE_FASCICOLO FOREIGN KEY (FASCICOLO_ID, FASCICOLO_ID_VALIDAZIONE) REFERENCES A4GT_FASCICOLO (ID, ID_VALIDAZIONE)
);

  CREATE TABLE TCUAA_LOCK 
   (	CUAA VARCHAR2(16), 
	UTENTE VARCHAR2(20), 
	TIMESTAMP DATE, 
	TIPO_LOCK NUMBER(1,0)
   );


