DELETE FROM A4GT_ISTRUTTORE_DISACCOPPIATO WHERE ID_ISTRUTTORIA IN (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA = 8669820);
DELETE FROM A4GT_ISTRUTTORE_DIS_PASCOLI WHERE ID_ISTRUTTORIA IN (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA = 8669820);
DELETE FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA = 8669820 AND SOSTEGNO='DISACCOPPIATO';
DELETE FROM A4GT_SOSTEGNO WHERE ID = 12374799;
DELETE FROM A4GT_DOMANDA WHERE ID = 8669820;
COMMIT;