export enum TipoIntestazioneUma {
    RICHIESTA = 'RICHIESTA',
    DICHIARAZIONE_CONSUMI = 'DICHIARAZIONE_CONSUMI',
    RETTIFICA = 'RETTIFICA',
    GESTIONE_CARBURANTE_IN_ESUBERO = "GESTIONE_CARBURANTE_IN_ESUBERO"
}
