-- DOMANDE 2020
INSERT INTO A4GT_DOMANDA(ID, VERSIONE, NUMERO_DOMANDA, COD_MODULO_DOMANDA, DESC_MODULO_DOMANDA, ANNO_CAMPAGNA, STATO, CUAA_INTESTATARIO, DT_PRESENTAZIONE,DT_PROTOCOLLAZIONE,
COD_ENTE_COMPILATORE, DESC_ENTE_COMPILATORE, RAGIONE_SOCIALE)
VALUES (1, 0, 1, 'BPS_2020', 'PAGAMENTI DIRETTI', 2020, 'ACQUISITA', 'FRSLBT76H42E6251',
TO_DATE('06/04/2018 22:00:00', 'DD/MM/YYYY HH24:MI:SS'),TO_DATE('26/04/2018 15:26:20', 'DD/MM/YYYY HH24:MI:SS'), 6, 'CAA COLDIRETTI DEL TRENTINO - 005', 'AZIENDA TEST 1');

insert into A4GT_SOSTEGNO (id, versione, id_domanda, sostegno)
values (
1, 0,
1, 'DISACCOPPIATO');

INSERT INTO A4GT_CONF_ISTRUTTORIA
	(ID, VERSIONE, ANNO_CAMPAGNA, DT_SCADENZA_DOMANDE_INIZIALI, PERC_PAGAMENTO, PERC_DISCIPLINA_FINANZIARIA)
VALUES
	(10, 0 , 2020, '2019-07-10', 0.7, 0.01252145);

insert into A4GT_ISTRUTTORIA 
	(id, versione, id_domanda, ID_STATO_LAVORAZIONE, tipologia, sostegno)
values 
	(1, 0, 1, (select id from a4gd_stato_lav_sostegno where identificativo = 'RICHIESTO'), 'ANTICIPO', 'DISACCOPPIATO');

commit;