Insert into A4ST_RICHIESTA_MODIFICA_SUOLO (ID,VERSIONE,UTENTE,DATA_RICHIESTA,TIPO,STATO,ESITO,CUAA,AZIENDA,CAMPAGNA,ID_ISTANZA_RIESAME,VISIBILE_IN_ORTOFOTO,TIPO_INTERVENTO_COLTURALE,INTERVENTO_INIZIO,INTERVENTO_FINE) values 
('136475','0','USER',to_date('06/06/2020', 'DD/MM/YYYY'),'ISTANZA_DI_RIESAME','CONCLUSA',null,'ZNTPLA46L20H330F','ZONTINI PAOLO','2022','9439',null,null,null,null);
