export enum StatoIstruttoriaEnum {
    RICHIESTO = 'RICHIESTO',
    INTEGRATO = 'INTEGRATO',
    CONTROLLI_CALCOLO_KO = "CONTROLLI_CALCOLO_KO",
    CONTROLLI_CALCOLO_OK = "CONTROLLI_CALCOLO_OK",
    NON_AMMISSIBILE = "NON_AMMISSIBILE",
    LIQUIDABILE = "LIQUIDABILE",
    CONTROLLI_LIQUIDABILE_KO = "CONTROLLI_LIQUIDABILE_KO",
    DEBITI = "DEBITI",
    NON_LIQUIDABILE = "NON_LIQUIDABILE",
    PAGAMENTO_AUTORIZZATO = "PAGAMENTO_AUTORIZZATO",
    PAGAMENTO_NON_AUTORIZZATO = "PAGAMENTO_NON_AUTORIZZATO",
    CONTROLLI_INTERSOSTEGNO_OK = "CONTROLLI_INTERSOSTEGNO_OK"
}
