DELETE FROM A4GT_PASSO_TRANSIZIONE 
where ID_TRANSIZ_SOSTEGNO in (select id FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA in (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'ZTTTZN91P04L3781')));

DELETE FROM A4GT_TRANSIZIONE_ISTRUTTORIA 
WHERE ID_ISTRUTTORIA IN (SELECT ID FROM A4GT_ISTRUTTORIA where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'ZTTTZN91P04L3781'));

DELETE FROM A4GT_ISTRUTTORIA 
where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'ZTTTZN91P04L3781');

DELETE FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'ZTTTZN91P04L3781';

COMMIT;