DELETE FROM A4GT_TRANSIZIONE_ISTRUTTORIA WHERE ID_ISTRUTTORIA IN (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'BRGNGL64C30C7941'));
DELETE FROM A4GT_ISTRUTTORIA WHERE id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'BRGNGL64C30C7941');
DELETE FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'BRGNGL64C30C7941';

COMMIT;