insert into A4GT_DOMANDA (
	ID, VERSIONE, NUMERO_DOMANDA, COD_MODULO_DOMANDA, DESC_MODULO_DOMANDA,
	ANNO_CAMPAGNA,
	STATO,
	CUAA_INTESTATARIO, DT_PROTOCOLLAZIONE,
	NUM_DOMANDA_RETTIFICATA, COD_ENTE_COMPILATORE, DESC_ENTE_COMPILATORE,
	RAGIONE_SOCIALE, DT_PRESENTAZIONE, DT_PRESENTAZ_ORIGINARIA, DT_PROTOCOLLAZ_ORIGINARIA)
values(
	NXTNBR.NEXTVAL, 4,9183430,'BPS_2018', 'PAGAMENTI DIRETTI',
	2018,
	'IN_ISTRUTTORIA',
	'BRGNGL64C30C79XX', to_date('26/12/2018 02:00:00','dd/mm/yyyy hh24:mi:ss'),
	null, '19', 'CAA CIA - CLES - 002', 'AZ. AGR. BERGAMO ANGELO', 
	to_date('26/04/2018 02:00:00','dd/mm/yyyy hh24:mi:ss'), null, null);

Insert into A4GT_ISTRUTTORIA(ID,VERSIONE,ID_DOMANDA,SOSTEGNO,ID_STATO_LAVORAZIONE, TIPOLOGIA)
values(86789, 0,
	(SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'BRGNGL64C30C79XX' and COD_MODULO_DOMANDA = 'BPS_2018'),
	'DISACCOPPIATO',
	(select id from a4gd_stato_lav_sostegno where identificativo = 'RICHIESTO'), 'SALDO');
INSERT INTO A4GT_ISTRUTTORE_DISACCOPPIATO (
	ID, BPS_IMP_SAN, BPS_SANZ_ANNO_PREC,
	BPS_SUPERFICIE, DOM_ANNO_PREC_NON_LIQ, GIO_IMP_SAN,
	GIO_SANZ_ANNO_PREC, NOTE_ISTRUTTORE, VERSIONE, ID_ISTRUTTORIA) 
VALUES (
	NXTNBR.nextval, 1000.0000, 1,
	184.1398, 1, 1000.0000, 1,
	'segnalazione di miriam aricocchi  la 072tn037 e 072tn039 sono in realt� la stessa malga', 0, 86789);

INSERT INTO A4GT_TRANSIZIONE_ISTRUTTORIA(
	ID, VERSIONE, ID_ISTRUTTORIA, ID_STATO_INIZIALE, ID_STATO_FINALE, DATA_ESECUZIONE
) VALUES (
	86789,
	1,
	86789,
	(select id from a4gd_stato_lav_sostegno where identificativo = 'RICHIESTO'),
	(select id from a4gd_stato_lav_sostegno where identificativo = 'CONTROLLI_CALCOLO_OK'),
	TO_DATE('05/21/2019 18:40:30', 'MM/DD/YYYY HH24:MI:SS')
);