export const Costanti = {

    cruscotto: ':idIstruttoria/cruscottoIstruttoria', // path richiamato nel routing
    elencoDomande: 'elencoDomande', // path richiamato nel routing
    cruscottoDisaccoppiato: 'cruscottoDisaccoppiato', // path per il component cruscotto-sostegno
    CALCOLO_DISACCOPPIATO: 'calcoloDisaccoppiato',
    cruscottoAccoppiatoSuperficie: 'cruscottoAccoppiatoSuperficie',
    calcoloAccoppiatoSuperficie: 'calcoloAccoppiatoSuperficie',
    cruscottoAccoppiatoZootecnia: 'cruscottoAccoppiatoZootecnia',
    calcoloAccoppiatoZootecnia: 'calcoloAccoppiatoZootecnia',
    controlliLiquidabilita: 'controlliLiquidabilita',
    liquidazione: 'liquidazione',
    // dettaglioDomanda
    dettaglioDomandaParam: 'idDomanda',
    dettaglioDomanda: ':idDomanda/dettaglioDomanda',
    dettaglioIstruttoria: 'istruttoria/:idIstruttoria',
    disaccoppiatoControlliSuperati: 'calcoloDisaccoppiato',
    accoppiatoZootecniaRichiesto: 'accoppiatoZootecniaRichiesto',
    accoppiatoSuperficiRichiesto: 'accoppiatoSuperficiRichiesto',
    superficiImpegnate: 'superficiImpegnate',
    dichiarazioni: 'dichiarazioni',
    informazioniDomanda: 'informazioniDomanda',
    controlliSostegno: 'controlliSostegno',
    datiDomanda: 'datiDomanda',
    esiticalcoli: 'esiticalcoli',
    datiParticella: 'datiParticella',
    esitiParticelle: 'esitiParticelle',
    datiIstruttoria: 'datiIstruttoria',
    datiLiquidazione: 'datiLiquidazione',
    datiPerPascolo: 'datiPerPascolo',
    dettaglioDomandeCollegate: 'dettaglioDomandeCollegate',
    // accoppiatoZootecniaRichiesto
    allevamentiImpegnati: 'allevamentiImpegnati',
    capiAmmessi: 'capiAmmessi',
    capiRichiesti: 'capiRichiesti',
    // tab Sostegno ACZ ACS per recupero dettaglio domanda
    tabAllevamentiImpegnati: 'ALLEVAMENTI_IMPEGNATI',
    tabCapiAmmessi: 'CAPI_AMMESSI',
    tabCapiRichiesti: 'CAPI_RICHIESTI',
    tabControlliSostego: 'CONTROLLI_SOSTEGNO',
    tabDatiDomanda: 'DATI_DOMANDA',
    tabDatiIstruttoria: 'INSERIMENTO_DATI_ISTRUTTORIA',
    tabDichiarazioni: 'DICHIARAZIONI',
    tabDatiParticella: 'DATI_PARTICELLA',
    tabSuperficiImpegnate: 'SUPERFICI_IMPEGNATE',
    datiDisciplinaFinanziaria: 'DATI_DISCIPLINA_FINANZIARIA',
    // tipologia Sostegno ACZ ACS per recupero dettaglio domanda
    acs: 'accoppiatosuperficie',
    acz: 'accoppiatozootecnia',
    // descrizione esito Controlli Sostegno Accoppiati
    BRIDUSDC009_infoAgricoltoreAttivo_SI: null,
    BRIDUSDC009_infoAgricoltoreAttivo_NO: 'Informazione sull’agricoltore attivo non presente',
    BRIDUSDC010_agricoltoreAttivo_SI: null,
    BRIDUSDC010_agricoltoreAttivo_NO: 'L’agricoltore risulta non attivo',
    BRIDUSDC022_idDomandaCampioneAcs_SI: 'Azienda estratta a campione superfici',
    BRIDUSDC022_idDomandaCampioneAcs_NO: null,
    BRIDUSDC022_idDomandaCampioneAcz_SI: 'Azienda estratta a campione zootecnia',
    BRIDUSDC022_idDomandaCampioneAcz_NO: null,
    BRIDUSDC034_sigeco_SI: null,
    BRIDUSDC034_sigeco_NO: 'Il controllo in loco è ancora in corso',
    BRIDUACS090_olivo75_SI: 'Superficie determinata da Istruttore per intervento Olivo con pendenza 7,5%',
    BRIDUACS090_olivo75_NO: 'Superficie determinata da Istruttore per intervento Olivo con pendenza 7,5% assente',
    BRIDUACS090_olivo75_NA: null,
    BRIDUACS091_olivoNazionale_SI: null,
    BRIDUACS091_olivoNazionale_NO: 'Azienda non risulta regolarmente iscritta al registro telematico nazionale',
    BRIDUACS091_olivoNazionale_NA: null,
    BRIDUACS092_olivoQualita_SI: null,
    BRIDUACS092_olivoQualita_NO: 'Azienda non certificata DOP o IGP',
    BRIDUACS092_olivoQualita_NA: null,
    BRIDUACS083_supMinima_SI: null,
    BRIDUACS083_supMinima_NO: 'La superficie impegnata non raggiunge la soglia minima di 0,5 ha',
    BRIDUACZ107_UbaAmmessi_SI: null,
    BRIDUACZ107_UbaAmmessi_NO: 'L’azienda non presenta le 3 UBA minime richieste',
    BRIDUACZ123_VerificaControlliInLoco_SI: null,
    BRIDUACZ123_VerificaControlliInLoco_NO: 'Il controllo in loco non risulta chiuso da Istruttore',
    BRIDUACZ126_VerificaSanzioni_NESSUNA_SANZIONE: null,
    BRIDUACZ126_VerificaSanzioni_CON_SANZIONI: 'Alcuni interventi presentano sanzioni',
    BRIDUACZ126_VerificaSanzioni_TUTTI_SANZIONATI: 'Tutti gli interventi non sono pagabili poiché la sanzione applicata è del 100%',
    BRIDUACZ127_Riduzioni_SI: 'Sono presenti delle riduzioni del premio',
    BRIDUACZ127_Riduzioni_NO: null,
    BRIDUSDL133_importoErogabilePositivo_NO: 'Nessun importo da erogare e Azienda da iscrivere al registro debitori: importo calcolato inferiore ai pagamenti già effettuati',
    BRIDUSDL133_importoErogabilePositivo_SI: 'Il premio da liquidare è maggiore di quanto già precedentemente erogato.',
    
    BRIDUSDL134_importoErogabileNegativo_SI: 'Nessun importo da erogare e Azienda da iscrivere al registro debitori: importo calcolato inferiore ai pagamenti già effettuati',
    BRIDUSDL134_importoErogabileNegativo_NO: null,
    BRIDUSDL135_importoErogabileZero_SI: 'Nessun importo da erogare: importo calcolato uguale a zero',
    BRIDUSDL135_importoErogabileZero_NO: null,
    BRIDUSDL135_importoErogabileIrrilevante_SI: 'Nessun importo da erogare: importo calcolato irrilevante',
    BRIDUSDL135_importoErogabileIrrilevante_NO: null,
    
    importoMinimoPagamento_NON_DETERMINABILE: 'L’importo minimo per il pagamento non è determinabile',
    importoMinimoPagamento_NON_RAGGIUNTO: 'L’importo minimo per il pagamento non è stato raggiunto',
    importoMinimoPagamento_RAGGIUNTO: 'L’importo minimo per il pagamento è stato raggiunto',
    BRIDUSDI050_SI: 'L’azienda è in possesso dei requisiti anfimafia',
    BRIDUSDI050_NO: 'L’azienda non è in possesso dei requisiti anfimafia',
    importoMinimoAntimafia_NON_DETERMINABILE: 'L’importo minimo per antimafia non è determinabile',
    importoMinimoAntimafia_NON_RAGGIUNTO: 'L’importo minimo per antimafia non è stato raggiunto',
    importoMinimoAntimafia_RAGGIUNTO: 'L’importo minimo per antimafia è stato raggiunto',
    BRIDUSDS050_esitoAntimafia_SI: 'L’azienda è in possesso dei requisiti anfimafia',
    BRIDUSDS050_esitoAntimafia_NO: 'L’azienda non è in possesso dei requisiti anfimafia',
    BRIDUSDS049_importoMinimoAntimafia_SI: 'L’importo minimo per antimafia è stato raggiunto',
    BRIDUSDS049_importoMinimoAntimafia_NO: 'L’importo minimo per antimafia non è stato raggiunto',
    BRIDUSDS049_importoMinimoAntimafia_NA: 'L’importo minimo per antimafia non è determinabile',
    BRIDUSDS040_importoMinimo_SI: 'L’importo minimo per il pagamento è stato raggiunto',
    BRIDUSDS040_importoMinimo_NO: 'L’importo minimo per il pagamento non è stato raggiunto',
    BRIDUSDS040_importoMinimo_NA: 'L’importo minimo per il pagamento non è determinabile',

    // interventi ACS
    m8: 'Misura 8 - Soia (122)',
    m9: 'Misura 9 - Frumento (124)',
    m10: 'Misura 10 - Proteaginose (123)',
    m11: 'Misura 11 - Leguminose (125)',
    m14: 'Misura 14 - Pomodoro (128)',
    m15: 'Misura 15 - Olivi Standard (129)',
    m16: 'Misura 16 - Olivi 7.5% (132)',
    m17: 'Misura 17 - Olivi Qualità (138)',
    // interventi ACZ
    int310: 'M1 - Vacche da latte (310)',
    int311: 'M2 - Vacche da latte in zone di montagna (311)',
    int313: 'M4 - Vacche nutrici (313)',
    int315: 'M5- Bovini macellati (315)',
    int320: 'M6 - Agnelle (320)',
    int321: 'M7 - Ovicaprini macellati (321)',
    int316: 'M19 - Bovini macellati - Allevati 12 mesi (316)',
    int318: 'M19 - Bovini macellati - Etichettatura (318)',
    int322: 'M20 - Vacche nutrici non iscritte (322)',
    // descrizioni Dati di Domanda ACS
    ACSIMPCALCTOT: 'Importo Calcolato Finale Accoppiato Superficie',
    ACSIMPRIDTOT: 'Importo Riduzioni',
    ACSIMPRIDRITTOT: 'Importo Riduzioni Ritardo',
    ACSSUPIMP: 'Superficie Impegnata',
    ACSSUPDETIST: 'Superficie Determinata Istruttore',
    ACSVAL: 'Valore Unitario',
    ACSSUPRIC: 'Superficie Richiesta',
    ACSSUPDET: 'Superficie Determinata',
    ACSSUPAMM: 'Superficie Ammessa',
    ACSIMPRIC: 'Importo Richiesto',
    ACSIMPRID: 'Importo Riduzione',
    ACSIMPAMM: 'Importo Ammesso',
    ACSIMPRIDRIT: 'Importo Riduzione Ritardo',
    ACSIMPCALC: 'Importo Calcolato',
    AGRATT: 'Agricoltore in attività',
    ISCAMP: 'Domanda estratta a campione',
    DOMSIGECOCHIUSA: 'Controllo in loco chiuso',
    PERCRIT: 'Percentuale riduzione ritardata presentazione',
    PERCRITISTR: 'Verifica istruttoria: la domanda di modifica in ritardo è in riduzione',
    OLIONAZ: 'Registro nazionale olivo',
    OLIOQUAL: 'Registro olivo qualità',
    // descrizioni Dati di Domanda ACZ
    ACZIMPCALCTOT: 'Importo Calcolato Finale Accoppiato Zootecnia',
    ACZIMPRIDTOT: 'Importo Riduzione Capi Anomali',
    ACZIMPRIDSANZTOT: 'Importo Sanzioni',
    ACZIMPRIDRITTOT: 'Importo Riduzione Ritardo',
    ACZCAPIRIC: 'Numero Capi Richiesti Lordi',
    ACZCAPIRICNET: 'Numero Capi Richiesti Netti',
    ACZCAPIDUP: 'Numero Capi Duplicati Totali',
    ACZCAPISANZ: 'Numero Capi Anomali',
    ACZCAPIACC: 'Numero Capi Accertati',
    ACZUBALAT: 'Numero UBA Ammessi Interventi 310-311-313-322',
    ACZUBAMAC: 'Numero UBA Ammessi Interventi 315-316-318',
    ACZUBAOVI: 'Numero UBA Ammessi Interventi 320-321',
    ACZVAL: 'Valore Unitario',
    AZCMPBOV: 'Azienda Campione Bovini',
    AZCMPOVI: 'Azienda Campione Ovicaprini',
    PERCSANZDET: 'Percentuale Sanzione Determinata',
    PERCSANZ: 'Percentuale Sanzione Applicata',
    ACZIMPRICNET: 'Importo Richiesto Netto',
    ACZIMPRID: 'Importo Riduzione Capi Anomali',
    ACZIMPACC: 'Importo Accertato',
    ACZIMPRIDSANZ: 'Importo Riduzione Sanzione',
    ACZIMPRIDRIT: 'Importo Riduzione Ritardo',
    ACZIMPCALC: 'Importo Calcolato Intervento',
    ACZOVIADULTI: 'Numero Ovini Adulti',
    BRIDUSDL037_iban_SI: 'L’iban per il pagamento è corretto',
    BRIDUSDL037_iban_NO: 'L’iban per il pagamento non è corretto',
    BRIDUSDL038_titolare_NO: 'L’agricoltore è ancora in vita',
    BRIDUSDL038_titolare_SI: 'L’agricoltore è deceduto',
    BRIDUSDL039_agea_NO: 'L’agricoltore non è in lista nera agea',
    BRIDUSDL039_agea_SI: 'L’agricoltore è in lista nera agea',
    BRIDUNVL129_erede_NO: 'Dati dell’erede mancanti o non certificati',
    BRIDUNVL129_erede_SI: 'Dati erede certificati',

    PREMIO: 'premio',
    LIQUIDABILITA: 'liquidabilita',
    LIQUIDAZIONE: 'liquidazione',
    ACC_ZOOTECNIA: 'az',

    // label variabili Disciplina Finanziaria
    DFPERC: 'Disciplina - Percentuale disciplina finanziaria',
    DFFR: 'Disciplina - Soglia della franchigia',
    BPSIMPCALCFIN: 'BPS - Importo Calcolato finale',
    GREIMPCALCFIN: 'Greening - Importo Calcolato finale',
    GIOIMPCALCFIN: 'Giovane - Importo Calcolato finale',
    DFDISIMPCALC: 'Importo Calcolato Finale Disaccoppiato',
    DFACZIMPCALC: 'Importo Calcolato finale sostegno accoppiato zootecnia',
    DFACSIMPCALC: 'Importo Calcolato finale sostegno accoppiato superficie',
    DFFRAPPDIS: 'Disciplina - Franchigia già applicata sostegno disaccoppiato',
    DFFRAPPDISBPS : 'Disciplina - BPS - Franchigia già applicata',
    DFFRAPPDISGRE : 'Disciplina - Greening - Franchigia già applicata',
    DFFRAPPDISGIO : 'Disciplina -  Giovane - Franchigia già applicata',


    DFFRAPPACZ: 'Disciplina - Franchigia già applicata sostegno accoppiato zootecnia',
    DFFRAPPACS: 'Disciplina - Franchigia già applicata sostegno accoppiato superficie',

    DFFRPAGACZ: 'Disciplina - Franchigia sostegno accoppiato zootecnia',

    DFIMPRIDACZ: 'Disciplina - Importo riduzione sostegno accoppiato zootecnia al netto degli importi già pagati',
    DFIMPLIQACZ: 'Disciplina - Importo liquidato sostegno accoppiato zootecnia al netto degli importi già pagati',

    // input ACZ
    DFACZIMPCALC_310: 'Importo Calcolato finale sostegno accoppiato zootecnia Vacche da Latte',
    DFACZIMPCALC_311: 'Importo Calcolato finale sostegno accoppiato zootecnia Vacche Da Latte in zona di montagna',
    DFACZIMPCALC_313: 'Importo Calcolato finale sostegno accoppiato zootecnia Vacche Nutrici',
    DFACZIMPCALC_322: 'Importo Calcolato finale sostegno accoppiato zootecnia Vacche nutrici non iscritte',
    DFACZIMPCALC_315: 'Importo Calcolato finale sostegno accoppiato zootecnia Bovini macellati',
    DFACZIMPCALC_316: 'Importo Calcolato finale sostegno accoppiato zootecnia Capi bovini macellati e allevati almeno 12 mesi',
    DFACZIMPCALC_318: 'Importo Calcolato finale sostegno accoppiato zootecnia Capi bovini macellati - Etichettatura',
    DFACZIMPCALC_320: 'Importo Calcolato finale sostegno accoppiato zootecnia Agnelle',
    DFACZIMPCALC_321: 'Importo Calcolato finale sostegno accoppiato zootecnia Ovicaprini macellati',

    DFACZIMPCALCLORDO_310: 'Importo Calcolato al lordo degli importi già pagati Intervento Vacche da Latte',
    DFACZIMPCALCLORDO_311: 'Importo Calcolato al lordo degli importi già pagati Intervento Vacche Da Latte in zona di montagna',
    DFACZIMPCALCLORDO_313: 'Importo Calcolato al lordo degli importi già pagati Intervento Vacche Nutrici',
    DFACZIMPCALCLORDO_322: 'Importo Calcolato al lordo degli importi già pagati Intervento Vacche nutrici non iscritte',
    DFACZIMPCALCLORDO_315: 'Importo Calcolato al lordo degli importi già pagati Intervento Bovini macellati',
    DFACZIMPCALCLORDO_316: 'Importo Calcolato al lordo degli importi già pagati Intervento Capi bovini macellati e allevati almeno 12 mesi',
    DFACZIMPCALCLORDO_318: 'Importo Calcolato al lordo degli importi già pagati Intervento Capi bovini macellati - Etichettatura',
    DFACZIMPCALCLORDO_320: 'Importo Calcolato al lordo degli importi già pagati Intervento Agnelle',
    DFACZIMPCALCLORDO_321: 'Importo Calcolato al lordo degli importi già pagati Intervento Ovicaprini macellati',
    DFACZIMPCALCLORDOTOT: 'Importo Calcolato al lordo degli importi già pagati Totale',
    DFACZIMPCALCLORDO: 'Importo Calcolato al lordo degli importi già pagati Totale',

    DFIMPLIPAGACZ_310: 'ACZ - Importo già erogato per la domanda al netto della df intervento Vacche da Latte',
    DFIMPLIPAGACZ_311: 'ACZ - Importo già erogato per la domanda al netto della df intervento Vacche Da Latte in zona di montagna',
    DFIMPLIPAGACZ_313: 'ACZ - Importo già erogato per la domanda al netto della df intervento Vacche Nutrici',
    DFIMPLIPAGACZ_322: 'ACZ - Importo già erogato per la domanda al netto della df intervento Vacche nutrici non iscritte',
    DFIMPLIPAGACZ_315: 'ACZ - Importo già erogato per la domanda al netto della df intervento Bovini macellati',
    DFIMPLIPAGACZ_316: 'ACZ - Importo già erogato per la domanda al netto della df intervento Capi bovini macellati e allevati almeno 12 mesi',
    DFIMPLIPAGACZ_318: 'ACZ - Importo già erogato per la domanda al netto della df intervento Capi bovini macellati - Etichettatura',
    DFIMPLIPAGACZ_320: 'ACZ - Importo già erogato per la domanda al netto della df intervento Agnelle',
    DFIMPLIPAGACZ_321: 'ACZ - Importo già erogato per la domanda al netto della df intervento Ovicaprini macellati',

    //input ACZ A4G
    DFFRAPPACZ_310 : "Disciplina - Franchigia già applicata sostegno accoppiato zootecnia intervento Vacche da Latte",
	DFFRAPPACZ_311 : "Disciplina - Franchigia già applicata sostegno accoppiato zootecnia intevento Vacche Da Latte in zona di montagna",
	DFFRAPPACZ_313 : "Disciplina - Franchigia già applicata sostegno accoppiato zootecnia intevento Vacche Nutrici",
	DFFRAPPACZ_322 : "Disciplina - Franchigia già applicata sostegno accoppiato zootecnia intervento Vacche nutrici non iscritte",
	DFFRAPPACZ_315 : "Disciplina - Franchigia già applicata sostegno accoppiato zootecnia intervento Bovini macellati",
	DFFRAPPACZ_316 : "Disciplina - Franchigia già applicata sostegno accoppiato zootecnia intervento Capi bovini macellati e allevati almeno 12 mesi",
	DFFRAPPACZ_318 : "Disciplina - Franchigia già applicata sostegno accoppiato zootecnia intervento Capi bovini macellati - Etichettatura",
	DFFRAPPACZ_320 : "Disciplina - Franchigia già applicata sostegno accoppiato zootecnia intervento Agnelle",
	DFFRAPPACZ_321 : "Disciplina - Franchigia già applicata sostegno accoppiato zootecnia intervento Ovicaprini macellati",

    // output ACZ
    DFIMPLIQACZLORDO: 'Disciplina - Importo liquidabile sostegno accoppiato zootecnia al lordo degli importi già pagati',
    DFFRPAGLORACZ: 'Disciplina - Franchigia sostegno ACZ al lordo degli importi già pagati',
    DFFRPAGLORACZ_310: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Vacche da Latte al lordo degli importi già pagati',
    DFFRPAGLORACZ_311: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Vacche Da Latte in zona di montagna al lordo degli importi già pagati',
    DFFRPAGLORACZ_313: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Vacche Nutrici al lordo degli importi già pagati',
    DFFRPAGLORACZ_322: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Vacche nutrici non iscritte al lordo degli importi già pagati',
    DFFRPAGLORACZ_315: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Bovini macellati al lordo degli importi già pagati',
    DFFRPAGLORACZ_316: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Capi bovini macellati e allevati almeno 12 mesi al lordo degli importi già pagati',
    DFFRPAGLORACZ_318: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Capi bovini macellati - Etichettatura al lordo degli importi già pagati',
    DFFRPAGLORACZ_320: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Agnelle al lordo degli importi già pagati',
    DFFRPAGLORACZ_321: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Ovicaprini macellati al lordo degli importi già pagati',

    // DFFRPAGACZ
    DFFRPAGACZ_310: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Vacche da Latte',
    DFFRPAGACZ_311: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Vacche Da Latte in zona di montagna',
    DFFRPAGACZ_313: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Vacche Nutrici',
    DFFRPAGACZ_322: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Vacche nutrici non iscritte',
    DFFRPAGACZ_315: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Bovini macellati',
    DFFRPAGACZ_316: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Capi bovini macellati e allevati almeno 12 mesi',
    DFFRPAGACZ_318: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Capi bovini macellati - Etichettatura',
    DFFRPAGACZ_320: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Agnelle',
    DFFRPAGACZ_321: 'Disciplina - Franchigia sostegno accoppiato zootecnia intervento Ovicaprini macellati',

    DFIMPDFDISACZ_310: 'Disciplina - Importo oltre franchigia sostegno accoppiato zootecnia con disciplina finanziaria interventi Vacche da Latte',
    DFIMPDFDISACZ_311: 'Disciplina - Importo oltre franchigia sostegno accoppiato zootecnia con disciplina finanziaria interventi Vacche Da Latte in zona di montagna',
    DFIMPDFDISACZ_313: 'Disciplina - Importo oltre franchigia sostegno accoppiato zootecnia con disciplina finanziaria interventi Vacche Nutrici',
    DFIMPDFDISACZ_322: 'Disciplina - Importo oltre franchigia sostegno accoppiato zootecnia con disciplina finanziaria interventi Vacche nutrici non iscritte',
    DFIMPDFDISACZ_315: 'Disciplina - Importo oltre franchigia sostegno accoppiato zootecnia con disciplina finanziaria interventi Bovini macellati',
    DFIMPDFDISACZ_316: 'Disciplina - Importo oltre franchigia sostegno accoppiato zootecnia con disciplina finanziaria interventi Capi bovini macellati e allevati almeno 12 mesi',
    DFIMPDFDISACZ_318: 'Disciplina - Importo oltre franchigia sostegno accoppiato zootecnia con disciplina finanziaria interventi Capi bovini macellati - Etichettatura',
    DFIMPDFDISACZ_320: 'Disciplina - Importo oltre franchigia sostegno accoppiato zootecnia con disciplina finanziaria interventi Agnelle',
    DFIMPDFDISACZ_321: 'Disciplina - Importo oltre franchigia sostegno accoppiato zootecnia con disciplina finanziaria interventi Ovicaprini macellati',

    // INPUT Superficie A4G
    DFFRAPPACS_M8:  'Disciplina - Franchigia già applicata sostegno accoppiato superficie Soia',
	DFFRAPPACS_M9:  'Disciplina - Franchigia già applicata sostegno accoppiato superficie Frumento',
	DFFRAPPACS_M10: 'Disciplina - Franchigia già applicata sostegno accoppiato superficie Proteaginose',
	DFFRAPPACS_M11: 'Disciplina - Franchigia già applicata sostegno accoppiato superficie Leguminose',
	DFFRAPPACS_M14 : 'Disciplina - Franchigia già applicata sostegno accoppiato superficie Pomodoro',
	DFFRAPPACS_M15: 'Disciplina - Franchigia già applicata sostegno accoppiato superficie Olivo Standard',
	DFFRAPPACS_M16: 'Disciplina - Franchigia già applicata sostegno accoppiato superficie Olivo 7.5%',
	DFFRAPPACS_M17: 'Disciplina - Franchigia già applicata sostegno accoppiato superficie Olivo Qualità',
	
    DFACSIMPCALC_M8: 'Importo Calcolato finale sostegno accoppiato superficie Soia',
    DFACSIMPCALC_M9: 'Importo Calcolato finale sostegno accoppiato superficie Frumento',
    DFACSIMPCALC_M10: 'Importo Calcolato finale sostegno accoppiato superficie Proteaginose',
    DFACSIMPCALC_M11: 'Importo Calcolato finale sostegno accoppiato superficie Leguminose',
    DFACSIMPCALC_M14: 'Importo Calcolato finale sostegno accoppiato superficie Pomodoro',
    DFACSIMPCALC_M15: 'Importo Calcolato finale sostegno accoppiato superficie Olivo Standard',
    DFACSIMPCALC_M16: 'Importo Calcolato finale sostegno accoppiato superficie Olivo 7,5%',
    DFACSIMPCALC_M17: 'Importo Calcolato finale sostegno accoppiato superficie Olivo Qualità',
    // DFACSIMPCALC: 'Importo Calcolato',
    DFACSIMPCALCLORDO_M8: 'Importo Calcolato al lordo degli importi già pagati Soia',
    DFACSIMPCALCLORDO_M9: 'Importo Calcolato al lordo degli importi già pagati Frumento',
    DFACSIMPCALCLORDO_M10: 'Importo Calcolato al lordo degli importi già pagati Proteaginose',
    DFACSIMPCALCLORDO_M11: 'Importo Calcolato al lordo degli importi già pagati Leguminose',
    DFACSIMPCALCLORDO_M14: 'Importo Calcolato al lordo degli importi già pagati  Pomodoro',
    DFACSIMPCALCLORDO_M15: 'Importo Calcolato al lordo degli importi già pagati  Olivo Standard',
    DFACSIMPCALCLORDO_M16: 'Importo Calcolato al lordo degli importi già pagati  Olivo 7,5%',
    DFACSIMPCALCLORDO_M17: 'Importo Calcolato al lordo degli importi già pagati  Olivo Qualità',
    DFACSIMPCALCLORDOTOT: 'Importo Calcolato al lordo degli importi già pagati Totale',

    DFIMPLIPAGACS_M8: 'Importo già erogato per la domanda al netto della df Soia',
    DFIMPLIPAGACS_M9: 'Importo già erogato per la domanda al netto della df Frumento',
    DFIMPLIPAGACS_M10: 'Importo già erogato per la domanda al netto della df Proteaginose',
    DFIMPLIPAGACS_M11: 'Importo già erogato per la domanda al netto della df Leguminose',
    DFIMPLIPAGACS_M14: 'Importo già erogato per la domanda al netto della df Pomodoro',
    DFIMPLIPAGACS_M15: 'Importo già erogato per la domanda al netto della df Olivo Standard',
    DFIMPLIPAGACS_M16: 'Importo già erogato per la domanda al netto della df Olivo 7,5%',
    DFIMPLIPAGACS_M17: 'Importo già erogato per la domanda al netto della df Olivo Qualità',
    // DFFRAPPDIS:
    // DFFRAPPACZ:
    // DFFRAPPACS: 'Disciplina - Franchigia sostegno accoppiato superficie',

    // OUTPUT superficie disciplina finanziaria superficie superficie
    DFIMPLIQACSLORDO: 'Disciplina - Importo liquidabile sostegno accoppiato superficie al lordo degli importi già pagati',
    DFFRPAGLORACS: 'Disciplina - Franchigia sostegno accoppiato superficie al lordo degli importi già pagati',
    DFFRPAGLORACS_M8: 'Disciplina - Franchigia sostegno accoppiato superficie Soia al lordo degli importi già pagati',
    DFFRPAGLORACS_M9: 'Disciplina - Franchigia sostegno accoppiato superficie Frumento al lordo degli importi già pagati',
    DFFRPAGLORACS_M10: 'Disciplina - Franchigia sostegno accoppiato superficie Proteaginose al lordo degli importi già pagati',
    DFFRPAGLORACS_M11: 'Disciplina - Franchigia sostegno accoppiato superficie Leguminose al lordo degli importi già pagati',
    DFFRPAGLORACS_M14: 'Disciplina - Franchigia sostegno accoppiato superficie Pomodoro al lordo degli importi già pagati',
    DFFRPAGLORACS_M15: 'Disciplina - Franchigia sostegno accoppiato superficie Olivo Standard al lordo degli importi già pagati',
    DFFRPAGLORACS_M16: 'Disciplina - Franchigia sostegno accoppiato superficie Olivo 7.5% al lordo degli importi già pagati',
    DFFRPAGLORACS_M17: 'Disciplina - Franchigia sostegno accoppiato superficie Olivo Qualità al lordo degli importi già pagati',
    // DFFRPAGACS
    DFFRPAGACS: 'Disciplina - Franchigia sostegno accoppiato superficie',
    DFFRPAGACS_M8: 'Disciplina - Franchigia sostegno accoppiato superficie Soia',
    DFFRPAGACS_M9: 'Disciplina - Franchigia sostegno accoppiato superficie Frumento',
    DFFRPAGACS_M10: 'Disciplina - Franchigia sostegno accoppiato superficie Proteaginose',
    DFFRPAGACS_M11: 'Disciplina - Franchigia sostegno accoppiato superficie Leguminose',
    DFFRPAGACS_M14: 'Disciplina - Franchigia sostegno accoppiato superficie Pomodoro',
    DFFRPAGACS_M15: 'Disciplina - Franchigia sostegno accoppiato superficie Olivo Standard',
    DFFRPAGACS_M16: 'Disciplina - Franchigia sostegno accoppiato superficie Olivo 7.5%',
    DFFRPAGACS_M17: 'Disciplina - Franchigia sostegno accoppiato superficie Olivo Qualità',

    DFIMPDFDISACS_M8: 'Disciplina - Importo oltre franchigia sostegno accoppiato superficie con disciplina finanziaria Soia',
    DFIMPDFDISACS_M9: 'Disciplina - Importo oltre franchigia sostegno accoppiato superficie con disciplina finanziaria Frumento',
    DFIMPDFDISACS_M10: 'Disciplina - Importo oltre franchigia sostegno accoppiato superficie con disciplina finanziaria Proteaginose',
    DFIMPDFDISACS_M11: 'Disciplina - Importo oltre franchigia sostegno accoppiato superficie con disciplina finanziaria Leguminose',
    DFIMPDFDISACS_M14: 'Disciplina - Importo oltre franchigia sostegno accoppiato superficie con disciplina finanziaria Pomodoro',
    DFIMPDFDISACS_M15: 'Disciplina - Importo oltre franchigia sostegno accoppiato superficie con disciplina finanziaria Olivo Standard',
    DFIMPDFDISACS_M16: 'Disciplina - Importo oltre franchigia sostegno accoppiato superficie con disciplina finanziaria Olivo 7.5%',
    DFIMPDFDISACS_M17: 'Disciplina - Importo oltre franchigia sostegno accoppiato superficie con disciplina finanziaria Olivo Qualità',


    DFIMPRIDACS: 'Disciplina - Importo riduzione sostegno accoppiato superficie',
    DFIMPLIQACS: 'Disciplina - Importo liquidato sostegno accoppiato superficie',

    ACZIMPDEB: 'Importo da iscrivere a registro debitori',
    ACZIMPDEBCTOT: 'Importo da iscrivere a registro debitori',
    ACZCAPIDEB: 'Numero capi da iscrivere a registro debitori',

    // Elenco domande ricevibili e non ricevibili
    domandeRicevibli: 'domande/ricevibili',
    domandeNonRicevibili: 'domande/nonRicevibili',
    domandeInIstruttoria: 'domande/inIstruttoria',

};
