export enum AmbitoTipologia {
    MACCHINE = 'MACCHINE',
    FABBRICATI = 'FABBRICATI',
    ZOOTECNIA = 'ZOOTECNIA'
}

export enum TipologiaFabbricato {
    FABBRICATI_STRUMENTALI = 'FABBRICATI_STRUMENTALI',
    STRUTTURE_ZOOTECNICHE = 'STRUTTURE_ZOOTECNICHE',
    SERRE_E_PROTEZIONI = 'SERRE_E_PROTEZIONI'
}

export enum SottoTipologiaZootecnia {
    STOCCAGGIO_LIQUAMI = 'STOCCAGGIO_LIQUAMI',
    STOCCAGGIO_LETAMI = 'STOCCAGGIO_LETAMI',
    AREE_SCOPERTE = 'AREE_SCOPERTE',
    STALLE = 'STALLE'
}