package it.tndigitale.a4g.psr.dto;

public enum StatoOperazione {
	
	AMMISSIBILE,
	ASSEGNABILE,
	ASSEGNATA,
	IN_ISTRUTTORIA,
	IN_LIQUIDAZIONE,
	IN_SOSPENSIONE,
	INIZIO_ISTRUTTORIA,
	INIZIO_ISTRUTTORIA_DOMANDE_A_CAMPIONE,
	INTEGRAZIONE,
	ISTRUTTORIA_CONCLUSA,
	ISTRUTTORIA_PARZIALE,
	ISTRUTTORIA_PARZIALE_DOMANDE_A_CAMPIONE,
	LIQUIDABILE,
	NON_AMMISSIBILE,
	NON_ASSEGNATA,
	NON_LIQUIDABILE,
	NON_RICEVIBILE,
	PROPOSTA_LIQUIDAZIONE,
	PROTOCOLLATA,
	REVISI_REVISIONE,
	RICEVIBILE

}
