export default {
    "allevamenti":[
        {
            "descAllevamento":"104TN027",
            "descProprietario":"MASCOTTO GIANNI",
            "capi":[
                {
                    "codCapo":"IT022990164492",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530032,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530004,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"DE0815153442",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530034,
                            "selezionato":false
                        },
                        {
                            "codice":"313",
                            "esito":"AMMISSIBILE_CON_SANZIONE",
                            "idEsito":1530062,
                            "selezionato":true
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530006,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990210579",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530033,
                            "selezionato":false
                        },
                        {
                            "codice":"313",
                            "esito":"AMMISSIBILE_CON_SANZIONE",
                            "idEsito":1530061,
                            "selezionato":true
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530005,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990168730",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530035,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530007,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"AT047024228",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530036,
                            "selezionato":false
                        },
                        {
                            "codice":"313",
                            "esito":"AMMISSIBILE",
                            "idEsito":1530060,
                            "selezionato":true
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530008,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990168714",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530038,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530010,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990210574",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530037,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530009,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990210575",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530039,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530011,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990253603",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530040,
                            "selezionato":false
                        },
                        {
                            "codice":"313",
                            "esito":"AMMISSIBILE",
                            "idEsito":1530065,
                            "selezionato":true
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530012,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990210576",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530041,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530013,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990210577",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530043,
                            "selezionato":false
                        },
                        {
                            "codice":"313",
                            "esito":"AMMISSIBILE_CON_SANZIONE",
                            "idEsito":1530066,
                            "selezionato":true
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530015,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990253604",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530042,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530014,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990210570",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530044,
                            "selezionato":false
                        },
                        {
                            "codice":"313",
                            "esito":"AMMISSIBILE_CON_SANZIONE",
                            "idEsito":1530067,
                            "selezionato":true
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530016,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990210571",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530045,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530017,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990168719",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530046,
                            "selezionato":false
                        },
                        {
                            "codice":"313",
                            "esito":"AMMISSIBILE_CON_SANZIONE",
                            "idEsito":1530069,
                            "selezionato":true
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530018,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990210572",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530047,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530019,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990210573",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530048,
                            "selezionato":false
                        },
                        {
                            "codice":"313",
                            "esito":"AMMISSIBILE_CON_SANZIONE",
                            "idEsito":1530070,
                            "selezionato":true
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530020,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990168721",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530049,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530021,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990168722",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530050,
                            "selezionato":false
                        },
                        {
                            "codice":"313",
                            "esito":"AMMISSIBILE_CON_SANZIONE",
                            "idEsito":1530063,
                            "selezionato":true
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530022,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990168720",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530051,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530023,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990189089",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530052,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530024,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990189087",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530053,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530025,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990189088",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530054,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530026,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"AT811593328",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530055,
                            "selezionato":false
                        },
                        {
                            "codice":"313",
                            "esito":"AMMISSIBILE",
                            "idEsito":1530064,
                            "selezionato":true
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530027,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990168726",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530056,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530028,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990168724",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530057,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530029,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990210581",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530058,
                            "selezionato":false
                        },
                        {
                            "codice":"313",
                            "esito":"AMMISSIBILE_CON_SANZIONE",
                            "idEsito":1530068,
                            "selezionato":true
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530030,
                            "selezionato":false
                        }
                    ]
                },
                {
                    "codCapo":"IT022990168727",
                    "codSpecie":"BOVINI",
                    "interventi":[
                        {
                            "codice":"310",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530059,
                            "selezionato":false
                        },
                        {
                            "codice":"311",
                            "esito":"NON_AMMISSIBILE",
                            "idEsito":1530031,
                            "selezionato":false
                        }
                    ]
                }
            ]
        }
    ],
    "stato":"CALCOLATO",
    "identificativo":null
};
