export enum StatoBdna {
    CHIUSA_CON_ESITO_NEGATIVO = "CHIUSA_CON_ESITO_NEGATIVO",
    ANOMALIA = "ANOMALIA",
    IN_LAVORAZIONE = "IN_LAVORAZIONE",
    IN_ISTRUTTORIA = "IN_ISTRUTTORIA",
    IN_INSERIMENTO = "IN_INSERIMENTO",
    IN_CODA = "IN_CODA",
    ATTI = "ATTI",
    ESITO_POSITIVO = "ESITO_POSITIVO",
    RIFIUTATO = "RIFIUTATO",
    NON_CARICATO = "NON_CARICATO"
}