export enum MotivazioneConsuntivoTipo {
	AMMISSIBILE_GASOLIO_TERZI = 'AMMISSIBILE_GASOLIO_TERZI',
	RECUPERO_GASOLIO_PROPRIO = 'RECUPERO_GASOLIO_PROPRIO',
	RECUPERO_GASOLIO_TERZI = 'RECUPERO_GASOLIO_TERZI',
    RECUPERO_BENZINA = 'RECUPERO_BENZINA',
	RECUPERO_GASOLIO_SERRE = 'RECUPERO_GASOLIO_SERRE'
}
