export enum TipologiaLavorazioneEnum {
    BASE = 'BASE',
    STRAORDINARIA = 'STRAORDINARIA',
    BOVINI_BUFALINI_LATTE_CARNE = 'BOVINI E BUFALINI DA LATTE/CARNE (OLTRE 6 MESI)',
    VITELLI = 'VITELLI (FINO A 6 MESI)',
    SUINI_DA_RIPRODUZIONE = 'SUINI DA RIPRODUZIONE',
    SUINI_DA_INGRASSO = 'SUINI DA INGRASSO',
    SUINI_A_CICLO_CHIUSO = 'SUINI A CICLO CHIUSO',
    OVINI_E_CAPRINI = 'OVINI E CAPRINI',
    AVICOLI_CUNICOLI_STRUZZI = 'AVICOLI, CUNICOLI E STRUZZI',
    EQUINI_E_UNGULATI = 'EQUINI E UNGULATI',
    PISCICOLTURA_INTENSIVA = 'PISCICOLTURA INTENSIVA',
    PISCICOLTURA_ESTENSIVA = 'PISCICOLTURA ESTENSIVA',
    APICOLTURA = 'APICOLTURA'
}