INSERT INTO A4GT_ISTRUTTORIA(ID,VERSIONE,ID_DOMANDA,SOSTEGNO,ID_STATO_LAVORAZIONE, TIPOLOGIA)
values(1240981,1,
(SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'URRRED82B02F839U'),
'DISACCOPPIATO',
(select id from a4gd_stato_lav_sostegno where identificativo = 'RICHIESTO'), 'SALDO');

INSERT INTO A4GT_ISTRUTTORIA(ID,VERSIONE,ID_DOMANDA,SOSTEGNO,ID_STATO_LAVORAZIONE, TIPOLOGIA)
values(1240982,0,
(SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'URRRED82B02F839U'),
'DISACCOPPIATO',
(select id from a4gd_stato_lav_sostegno where identificativo = 'PAGAMENTO_AUTORIZZATO'), 'SALDO');

commit;