export enum TipoInterventoColturale  {
  BONIFICA_PULIZIA_O_RECUPERO_PARZIALE = 'BONIFICA_PULIZIA_O_RECUPERO_PARZIALE',
  ESPIANTO_E_IMPIANTO = 'ESPIANTO_E_IMPIANTO',
  IMPIANTO_EX_NOVO = 'IMPIANTO_EX_NOVO',
  ESTIRPO =   'ESTIRPO',
  ALTRO_CAMBIO_COLTURALE = 'ALTRO_CAMBIO_COLTURALE',
  ABBANDONO = 'ABBANDONO',
  DESTINAZIONE_NON_AGRICOLA_PER_INTERVENTO_UMANO = 'DESTINAZIONE_NON_AGRICOLA_PER_INTERVENTO_UMANO'
 }
