delete from A4GT_RICHIESTA_SUPERFICIE where id_domanda in (SELECT ID FROM A4GT_DOMANDA WHERE NUMERO_DOMANDA = 189674);
delete from A4GT_DATI_PARTICELLA_COLTURA where id_domanda in (SELECT ID FROM A4GT_DOMANDA WHERE NUMERO_DOMANDA = 189674);
delete from A4GT_DATI_FILTRO_DOMANDA where id_domanda in (SELECT ID FROM A4GT_DOMANDA WHERE NUMERO_DOMANDA = 189674);

delete from A4GT_ANOM_DOMANDA_SOSTEGNO where ID_PASSO_LAVORAZIONE in (
	select id FROM A4GT_PASSO_TRANSIZIONE where ID_TRANSIZ_SOSTEGNO in (
	select id FROM A4GT_TRANSIZIONE_ISTRUTTORIA where id_istruttoria in	(
		select id FROM A4GT_ISTRUTTORIA where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'SGNNLN54T28A372J')
	)
	)
);

delete from A4GT_PASSO_TRANSIZIONE where ID_TRANSIZ_SOSTEGNO in (
	select id FROM A4GT_TRANSIZIONE_ISTRUTTORIA where id_istruttoria in	(
		select id FROM A4GT_ISTRUTTORIA where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'SGNNLN54T28A372J')
	)
	);
delete from A4GT_TRANSIZIONE_ISTRUTTORIA where id_istruttoria in	(
		select id FROM A4GT_ISTRUTTORIA where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'SGNNLN54T28A372J')
	);
delete from a4gt_dati_particella_coltura where id_istruttoria in (select id from 
A4GT_ISTRUTTORIA where id_domanda in (SELECT ID FROM A4GT_DOMANDA WHERE NUMERO_DOMANDA = 189674));
delete from A4GT_ISTRUTTORIA where id_domanda in (SELECT ID FROM A4GT_DOMANDA WHERE NUMERO_DOMANDA = 189674);
delete from A4GT_DICHIARAZIONE_DU where id_domanda in (SELECT ID FROM A4GT_DOMANDA WHERE NUMERO_DOMANDA = 189674);
delete from A4GT_DATI_LAVORAZIONE where id_domanda in (SELECT ID FROM A4GT_DOMANDA WHERE NUMERO_DOMANDA = 189674);
delete from a4gt_domanda where numero_domanda = 189674;

delete from A4GT_CONF_ISTRUTTORIA where id = 10;

COMMIT;