/*Insert into A4GT_PASSO_TRANSIZIONE (ID,VERSIONE,ID_TRANSIZ_SOSTEGNO,CODICE_PASSO,ESITO,CODICE_ESITO,DATI_INPUT,DATI_OUTPUT,DATI_SINTESI_LAVORAZIONE) values
(NXTNBR.nextval,
0,
15645645549,
'DISCIPLINA_FINANZIARIA','OK','no esito',
--'{"variabiliCalcolo":[{"tipoVariabile":"DFPERC","valNumber":0.01411917},{"tipoVariabile":"DFFR","valNumber":2000.00},{"tipoVariabile":"BPSIMPCALCFIN","valNumber":1368.79},{"tipoVariabile":"GREIMPCALCFIN","valNumber":197.43},{"tipoVariabile":"GIOIMPCALCFIN","valNumber":0.00},{"tipoVariabile":"DISIMPCALC","valNumber":1566.22},{"tipoVariabile":"ACZIMPCALC","valNumber":0.00},{"tipoVariabile":"ACSIMPCALC","valNumber":0.00},{"tipoVariabile":"DFFRAPPDIS","valNumber":0.00},{"tipoVariabile":"DFFRAPPACZ","valNumber":0.00},{"tipoVariabile":"DFFRAPPACS","valNumber":0.00}],"variabiliCalcoloDaStampare":[{"tipoVariabile":"DFPERC","valNumber":0.01411917},{"tipoVariabile":"DFFR","valNumber":2000.00},{"tipoVariabile":"BPSIMPCALCFIN","valNumber":474.83},{"tipoVariabile":"GREIMPCALCFIN","valNumber":251.18},{"tipoVariabile":"GIOIMPCALCFIN","valNumber":0.00},{"tipoVariabile":"DISIMPCALC","valNumber":726.01},{"tipoVariabile":"ACZIMPCALC","valNumber":0.00},{"tipoVariabile":"ACSIMPCALC","valNumber":0.00},{"tipoVariabile":"DFFRAPPDIS","valNumber":0.00},{"tipoVariabile":"DFFRAPPACZ","valNumber":0.00},{"tipoVariabile":"DFFRAPPACS","valNumber":0.00}]}',
'{"variabiliCalcolo":[{"tipoVariabile":"DFPERC","valNumber":0.01411917},{"tipoVariabile":"DFFR","valNumber":2000.00},{"tipoVariabile":"BPSIMPCALCFIN","valNumber":1368.79},{"tipoVariabile":"GREIMPCALCFIN","valNumber":197.43},{"tipoVariabile":"GIOIMPCALCFIN","valNumber":0.00},{"tipoVariabile":"DISIMPCALC","valNumber":1566.22},{"tipoVariabile":"ACZIMPCALC","valNumber":0.00},{"tipoVariabile":"ACSIMPCALC","valNumber":0.00},{"tipoVariabile":"DFFRAPPDIS","valNumber":0.00},{"tipoVariabile":"DFFRAPPACZ","valNumber":0.00},{"tipoVariabile":"DFFRAPPACS","valNumber":0.00},{"tipoVariabile": "DFFRAPPDISBPS","valNumber": 50.0},{"tipoVariabile": "DFFRAPPDISGRE","valNumber": 20.0},{"tipoVariabile": "DFFRAPPDISGIO","valNumber": 1.0}],"variabiliCalcoloDaStampare":[{"tipoVariabile":"DFPERC","valNumber":0.01411917},{"tipoVariabile":"DFFR","valNumber":2000.00},{"tipoVariabile":"BPSIMPCALCFIN","valNumber":474.83},{"tipoVariabile":"GREIMPCALCFIN","valNumber":251.18},{"tipoVariabile":"GIOIMPCALCFIN","valNumber":0.00},{"tipoVariabile":"DISIMPCALC","valNumber":726.01},{"tipoVariabile":"ACZIMPCALC","valNumber":0.00},{"tipoVariabile":"ACSIMPCALC","valNumber":0.00},{"tipoVariabile":"DFFRAPPDIS","valNumber":0.00},{"tipoVariabile":"DFFRAPPACZ","valNumber":0.00},{"tipoVariabile":"DFFRAPPACS","valNumber":0.00}]}',

'{"variabiliCalcolo":[{"tipoVariabile":"DFFRPAGDIS","valNumber":1566.22},{"tipoVariabile":"DFIMPLIQDIS","valNumber":1566.22},{"tipoVariabile":"DFIMPRIDDIS","valNumber":0.00},{"tipoVariabile":"DFFRPAGDISBPS","valNumber":474.83},{"tipoVariabile":"DFFRPAGDISGRE","valNumber":251.18},{"tipoVariabile":"DFFRPAGDISGIO","valNumber":0.00},{"tipoVariabile":"DFIMPDFDISBPS","valNumber":0.00},{"tipoVariabile":"DFIMPDFDISGRE","valNumber":0.00},{"tipoVariabile":"DFIMPDFDISGIO","valNumber":0.00}],"variabiliCalcoloDaStampare":[{"tipoVariabile":"DFFRPAGDIS","valNumber":726.01},{"tipoVariabile":"DFIMPLIQDIS","valNumber":726.01},{"tipoVariabile":"DFIMPRIDDIS","valNumber":0.00},{"tipoVariabile":"DFFRPAGDISBPS","valNumber":474.83},{"tipoVariabile":"DFFRPAGDISGRE","valNumber":251.18},{"tipoVariabile":"DFFRPAGDISGIO","valNumber":0.00},{"tipoVariabile":"DFIMPDFDISBPS","valNumber":0.00},{"tipoVariabile":"DFIMPDFDISGRE","valNumber":0.00},{"tipoVariabile":"DFIMPDFDISGIO","valNumber":0.00}]}',
'{"variabiliCalcolo":[],"esitiControlli":[],"variabiliParticellaColtura":null,"variabiliCalcoloDaStampare":[]}'
);
*/

update A4GT_PASSO_TRANSIZIONE 
set DATI_INPUT = '{"variabiliCalcolo":[{"tipoVariabile":"DFPERC","valNumber":0.01411917},{"tipoVariabile":"DFFR","valNumber":2000.00},{"tipoVariabile":"BPSIMPCALCFIN","valNumber":1368.79},{"tipoVariabile":"GREIMPCALCFIN","valNumber":197.43},{"tipoVariabile":"GIOIMPCALCFIN","valNumber":0.00},{"tipoVariabile":"DISIMPCALC","valNumber":1566.22},{"tipoVariabile":"ACZIMPCALC","valNumber":0.00},{"tipoVariabile":"ACSIMPCALC","valNumber":0.00},{"tipoVariabile":"DFFRAPPDIS","valNumber":0.00},{"tipoVariabile":"DFFRAPPACZ","valNumber":0.00},{"tipoVariabile":"DFFRAPPACS","valNumber":0.00},{"tipoVariabile": "DFFRAPPDISBPS","valNumber": 50.0},{"tipoVariabile": "DFFRAPPDISGRE","valNumber": 20.0},{"tipoVariabile": "DFFRAPPDISGIO","valNumber": 1.0}],"variabiliCalcoloDaStampare":[{"tipoVariabile":"DFPERC","valNumber":0.01411917},{"tipoVariabile":"DFFR","valNumber":2000.00},{"tipoVariabile":"BPSIMPCALCFIN","valNumber":474.83},{"tipoVariabile":"GREIMPCALCFIN","valNumber":251.18},{"tipoVariabile":"GIOIMPCALCFIN","valNumber":0.00},{"tipoVariabile":"DISIMPCALC","valNumber":726.01},{"tipoVariabile":"ACZIMPCALC","valNumber":0.00},{"tipoVariabile":"ACSIMPCALC","valNumber":0.00},{"tipoVariabile":"DFFRAPPDIS","valNumber":0.00},{"tipoVariabile":"DFFRAPPACZ","valNumber":0.00},{"tipoVariabile":"DFFRAPPACS","valNumber":0.00}]}'
where CODICE_PASSO = 'DISCIPLINA_FINANZIARIA'
and ID_TRANSIZ_SOSTEGNO = 15645645549;

commit;
