-- cuaa MFFFBA75B28L174A
DELETE FROM A4GT_ANOM_DOMANDA_SOSTEGNO where id_passo_lavorazione in (
			select distinct(id) from A4GT_PASSO_TRANSIZIONE 
			where ID_TRANSIZ_SOSTEGNO in 
				(select id FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA in 
					(SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'MFFFBA75B28L174A' and numero_domanda = 1191062)
					)
				));
DELETE FROM A4GT_PASSO_TRANSIZIONE where ID_TRANSIZ_SOSTEGNO in (select id FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA in (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'MFFFBA75B28L174A' and numero_domanda = 1191062)));
delete FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA in (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'MFFFBA75B28L174A' and numero_domanda = 1191062));

delete FROM A4GT_ISTRUTTORIA where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'MFFFBA75B28L174A');
delete FROM A4GT_DATI_LAVORAZIONE where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'MFFFBA75B28L174A');
delete FROM A4GT_ELENCO_LIQUIDAZIONE where COD_ELENCO = '009-801-20190806-8517929';
delete FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'MFFFBA75B28L174A';

delete from A4GT_CONF_ISTRUTTORIA where 
ID = 10 and
VERSIONE = 0 and 
ANNO_CAMPAGNA = 2020 and 
DT_SCADENZA_DOMANDE_INIZIALI = '2019-07-10' and
PERC_PAGAMENTO = 0.7
and PERC_DISCIPLINA_FINANZIARIA =  0.01252145;

COMMIT;


