insert into vUTENTI (ID_PERSONA_FISICA,CF_UTENTE,PROFILO,ENTE,ATTIVO) values (1,'ABCDEF11A22B123C','Amministratore','Amministrazione',1);
insert into vUTENTI (ID_PERSONA_FISICA,CF_UTENTE,PROFILO,ENTE,ATTIVO) values (2,'AAAAAA11A11A111A','Utente','Helpdesk',1);
insert into vUTENTI (ID_PERSONA_FISICA,CF_UTENTE,PROFILO,ENTE,ATTIVO) values (3,'BBBBBB22B22B222B','Operatore','Operatore Caa',1);
insert into vUTENTI (ID_PERSONA_FISICA,CF_UTENTE,PROFILO,ENTE,ATTIVO) values (4,'CCCCCC33C33C333C','Operatore','Operatore Caa',0);

insert into vUTENTI (ID_PERSONA_FISICA,CF_UTENTE,PROFILO,ENTE,ATTIVO) values (5,'TRRSRG66D28C794B','Amministratore','Amministrazione',1);
insert into PERSONA_FISICA (ID_PERSONA,CODICE_FISCALE,NOME,COGNOME) values (5,'TRRSRG66D28C794B','SERGIO','TORRESANI');