CREATE TABLE vUTENTI (
	ID_PERSONA_FISICA INTEGER not null,
	CF_UTENTE		VARCHAR2(16) not null,
	PROFILO			VARCHAR2(255) not null,
	ENTE			VARCHAR2(255) not null,
	ATTIVO			INTEGER not null
);

CREATE TABLE PERSONA_FISICA (
	ID_PERSONA 			INTEGER not null,
	CODICE_FISCALE 		VARCHAR2(16) not null,
	NOME		 		VARCHAR2(255) not null,
	COGNOME			 	VARCHAR2(255) not null
)