--  Creazione oggetti sistema A4G
--1. Sequence unica di generazione ID
DROP ALL OBJECTS;
CREATE SEQUENCE NXTNBR
  START WITH 1100  
  NOCYCLE
  NOCACHE
  ORDER;


-- Tabella di Log unificata
CREATE TABLE A4GT_LOGGING (
   ID NUMBER(19) NOT NULL,
   VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
   UTENTE VARCHAR2(500 CHAR) NOT NULL,
   TIPO_EVENTO VARCHAR2(500 CHAR) NOT NULL,
   TABELLA VARCHAR2(4000) NOT NULL,
   ID_ENTITA NUMBER(19) NOT NULL,
   DT_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
   CONSTRAINT A4GT_LOGGING_PK PRIMARY KEY (ID)
);

-- Tabella gestione utenti
CREATE TABLE A4GT_UTENTE (
    ID NUMBER(19) NOT NULL,
    VERSIONE      NUMBER(10) DEFAULT 0 NOT NULL,
    IDENTIFICATIVO         VARCHAR2(50 CHAR) NOT NULL,
	CODICE_FISCALE         VARCHAR2(20 CHAR),
	EMAIL	VARCHAR2(100 CHAR),
	TELEFONO	VARCHAR2(100 CHAR),
    CONSTRAINT A4GT_UTENTE_PK PRIMARY KEY (ID),
	CONSTRAINT A4GT_UTENTE_UIDX UNIQUE (IDENTIFICATIVO)
) ; 

--Profili previsti dal sistema A4G
-- Tabella gestione profili
CREATE TABLE A4GT_PROFILO (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    IDENTIFICATIVO VARCHAR2(500 CHAR) NOT NULL,
    DESCRIZIONE VARCHAR2(4000 CHAR),
    RESPONSABILITA VARCHAR2(100 CHAR),
    CONSTRAINT A4GT_PROFILO_PK PRIMARY KEY (ID) ,
    CONSTRAINT A4GT_PROFILO_UIDX UNIQUE (IDENTIFICATIVO) 
);

-- Associazioni utente-profilo
CREATE TABLE A4GR_UTENTE_PROFILO
(
  ID_UTENTE  NUMBER(19) NOT NULL,
  ID_PROFILO NUMBER(19) NOT NULL,
  CONSTRAINT A4GR_UTENTE_PROFILO_PK PRIMARY KEY (ID_UTENTE, ID_PROFILO),
  CONSTRAINT A4GR_UTENTE_PROFILO_UIDX UNIQUE (ID_UTENTE, ID_PROFILO),
  CONSTRAINT A4GR_UTENTE_PROFILO_FK1 FOREIGN KEY (ID_UTENTE) REFERENCES A4GT_UTENTE (ID),
  CONSTRAINT A4GR_UTENTE_PROFILO_FK2 FOREIGN KEY (ID_PROFILO) REFERENCES A4GT_PROFILO (ID)
) ;

CREATE TABLE A4GT_ENTE
(
  ID             NUMBER(19) NOT NULL,
  VERSIONE       NUMBER(10) DEFAULT 0 NOT NULL,
  IDENTIFICATIVO NUMBER(9) NOT NULL,
  DESCRIZIONE    VARCHAR2(150),
  CAA			 VARCHAR2(50),
  CONSTRAINT A4GT_ENTE_PK PRIMARY KEY (ID)
) ;

-- CREATE TABLE
CREATE TABLE A4GR_UTENTE_ENTE
(
  ID_UTENTE NUMBER(19) NOT NULL,
  ID_ENTE   NUMBER(19) NOT NULL,
  CONSTRAINT A4GR_UTENTE_ENTE_PK PRIMARY KEY (ID_UTENTE, ID_ENTE),
  CONSTRAINT A4GR_UTENTE_ENTE_UIDX UNIQUE (ID_UTENTE, ID_ENTE),
  CONSTRAINT A4GR_UTENTE_ENTE_FK1 FOREIGN KEY (ID_UTENTE) REFERENCES A4GT_UTENTE (ID),
  CONSTRAINT A4GR_UTENTE_ENTE_FK2 FOREIGN KEY (ID_ENTE) REFERENCES A4GT_ENTE (ID)
)
;

--Funzioni del sistema A4G che prevedono abilitazione
CREATE TABLE A4GT_FUNZIONE (
  ID NUMBER(19) NOT NULL, 
  VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
  IDENTIFICATIVO VARCHAR2(500) NOT NULL,
  DESCRIZIONE VARCHAR2(4000) NOT NULL,
  CONSTRAINT A4GT_FUNZIONE_PK PRIMARY KEY (ID) ,
  CONSTRAINT A4GT_FUNZIONE_UIDX UNIQUE (IDENTIFICATIVO) 
);

--Associazioni profilo-funzione
CREATE TABLE A4GR_PROFILO_FUNZIONE (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    ID_PROFILO NUMBER(19) NOT NULL,
    ID_FUNZIONE NUMBER(19) NOT NULL,
    CONSTRAINT A4GR_PROFILO_FUNZIONE_FK1 FOREIGN KEY (ID_FUNZIONE) REFERENCES A4GT_FUNZIONE (ID),
    CONSTRAINT A4GR_PROFILO_FUNZIONE_FK2 FOREIGN KEY (ID_PROFILO) REFERENCES A4GT_PROFILO (ID),
    CONSTRAINT A4GR_PROFILO_FUNZIONE_UIDX UNIQUE (ID_PROFILO, ID_FUNZIONE) ,
    CONSTRAINT A4GR_PROFILO_FUNZIONE_PK PRIMARY KEY (ID) 
);

-- Riferimenti aziende agricole
CREATE TABLE A4GT_AZIENDA_AGRICOLA (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    CUAA VARCHAR2(16) NOT NULL,
    CONSTRAINT A4GT_AZIENDA_AGRICOLA_UIDX UNIQUE (CUAA) ,
    CONSTRAINT A4GT_AZIENDA_AGRICOLA_PK PRIMARY KEY (ID) 
) ;

CREATE TABLE A4GR_UTENTE_AZIENDA (
    ID NUMBER(19) NOT NULL,
    VERSIONE      NUMBER(10) DEFAULT 0 NOT NULL,
    ID_UTENTE     NUMBER(19) NOT NULL,
    CUAA    	 VARCHAR2(16) NOT NULL,
    ID_CARICA     NUMBER(19) NOT NULL,
    DATA_AGGIORNAMENTO DATE,
    CONSTRAINT A4GR_UTENTE_AZIENDA_PK PRIMARY KEY (ID),
    CONSTRAINT A4GR_UTENTE_AZIENDA_UIDX UNIQUE (ID_UTENTE, CUAA),
	CONSTRAINT A4GR_UTENTE_AZIENDA_FK1 FOREIGN KEY (ID_UTENTE) REFERENCES A4GT_UTENTE (ID)
) ; 

-- Creazione tabelle di lavoro sistema a4gutenti - registrazione domanda

CREATE TABLE A4GT_DOMANDA_REGISTRAZIONE (
    ID NUMBER(19) NOT NULL,
    VERSIONE      NUMBER(10) DEFAULT 0 NOT NULL,
    IDENTIFICATIVO_UTENTE         VARCHAR2(50 CHAR) NOT NULL,
    STATO     VARCHAR2(15 CHAR) NOT NULL,
    CODICE_FISCALE         VARCHAR2(20 CHAR) NOT NULL,
    NOME           VARCHAR2(31 CHAR) NOT NULL,
    COGNOME     VARCHAR2(31 CHAR) NOT NULL,
    EMAIL           VARCHAR2(50 CHAR) NOT NULL,
    TELEFONO     VARCHAR2(50 CHAR) NOT NULL,
    RESPONSABILITA           CLOB NOT NULL,
    A4G               NUMBER(1)  DEFAULT 0 NOT NULL,
    SRT               NUMBER(1) DEFAULT 0 NOT NULL,
    AGS               NUMBER(1) DEFAULT 0 NOT NULL,
    DOCUMENTO         BLOB,
    ID_PROTOCOLLO     VARCHAR2(255 CHAR),
    DT_PROTOCOLLAZIONE     DATE,
    CONFIGURATO NUMBER(1) DEFAULT 0 NOT NULL,
    TIPO_DOMANDA_REGISTRAZIONE VARCHAR2(16 CHAR),
    CONSTRAINT A4GT_DOM_REGISTRAZ_PK PRIMARY KEY (ID)
);

CREATE TABLE A4GT_ALLEGATO_RESPONSABILITA (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    ID_DOMANDA_REGISTRAZIONE NUMBER(19) NOT NULL,
    ID_RESPONSABILITA NUMBER(19) NOT NULL,
    COD_RESPONSABILITA VARCHAR2(50) NOT NULL,
    ALLEGATO BLOB,
    DT_INSERIMENTO DATE,
    CONSTRAINT A4GT_ALLEGATO_RESP_FK1 FOREIGN KEY (ID_DOMANDA_REGISTRAZIONE) REFERENCES A4GT_DOMANDA_REGISTRAZIONE (ID),
    CONSTRAINT A4GT_ALLEGATO_RESP PRIMARY KEY (ID)
);

-- Creazione tabella persona e privacy

CREATE TABLE A4GT_PERSONA (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,

  CODICE_FISCALE  VARCHAR2(16 BYTE)             NOT NULL,
  NOME            VARCHAR2(63 BYTE)             NOT NULL,
  COGNOME         VARCHAR2(63 BYTE)             NOT NULL,
    CONSTRAINT A4GT_PERSONA_PK PRIMARY KEY (ID) ,
    CONSTRAINT A4GT_PERSONA_CODFISCALE_UIDX
  UNIQUE (CODICE_FISCALE)
);

CREATE TABLE A4GT_PRIVACY_PERSONA (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,

    ID_PERSONA         NUMBER(19) NOT NULL,
    TIPO_INFORMATIVA VARCHAR2(15 CHAR) NOT NULL,

    DT_ACCETTAZIONE DATE DEFAULT SYSDATE NOT NULL,
    DT_PROTOCOLLAZIONE DATE NOT NULL,
    NR_PROTOCOLLO VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT A4GT_PRIVACY_PERSONA_PK PRIMARY KEY (ID),
    CONSTRAINT A4GT_PRIVACY_PERSONA_FK FOREIGN KEY (ID_PERSONA) REFERENCES A4GT_PERSONA (ID)
);

----- Ruolo e carica-profilo
CREATE TABLE A4GD_RUOLO (
  IDENTIFICATIVO VARCHAR2(63) NOT NULL,
  DESCRIZIONE VARCHAR2(127) NOT NULL,
  CONSTRAINT A4GD_RUOLO_PK PRIMARY KEY (IDENTIFICATIVO)
);

--Associazioni profilo-funzione
CREATE TABLE A4GR_PROFILO_RUOLO (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    ID_PROFILO NUMBER(19) NOT NULL,
    ID_RUOLO VARCHAR2(63) NOT NULL,
    CONSTRAINT A4GR_PROFILO_RUOLO_FK1 FOREIGN KEY (ID_RUOLO) REFERENCES A4GD_RUOLO (IDENTIFICATIVO),
    CONSTRAINT A4GR_PROFILO_RUOLO_FK2 FOREIGN KEY (ID_PROFILO) REFERENCES A4GT_PROFILO (ID),
    CONSTRAINT A4GR_PROFILO_RUOLO_UIDX UNIQUE (ID_PROFILO, ID_RUOLO) ,
    CONSTRAINT A4GR_PROFILO_RUOLO_PK PRIMARY KEY (ID) 
);

CREATE TABLE A4GT_FIRMA_DOMANDA_REG (
	ID NUMBER(20) NOT NULL, 
	VERSIONE NUMBER(10) DEFAULT 0 NOT NULL, 
	ID_DOMANDA NUMBER(20) NOT NULL, 
	XML CLOB NOT NULL, 
	PDF BLOB NOT NULL, 
	CONSTRAINT A4GT_FIRMA_DOMANDA_REG_PK PRIMARY KEY (ID), 
	CONSTRAINT A4GT_FIRMA_DOM_REG_DOM_FK FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA_REGISTRAZIONE(ID), 
	CONSTRAINT A4GT_FIRMA_DOM_REG_DOM_UIDX UNIQUE (ID_DOMANDA)
);
-- caricamento utenti caa
  CREATE TABLE A4GT_LOAD_UTENTE_CAA 
   (	
	COGNOME VARCHAR2(100 BYTE) NOT NULL,
	NOME VARCHAR2(100 BYTE) NOT NULL,
	CODICE_FISCALE VARCHAR2(16 BYTE) NOT NULL,
	EMAIL VARCHAR2(100 BYTE) NOT NULL,
	TELEFONO VARCHAR2(20 BYTE) NOT NULL,
	CAA VARCHAR2(100 BYTE) NOT NULL,
	UFFICIO VARCHAR2(100 BYTE) NOT NULL,
	RESPONSABILE VARCHAR2(100 BYTE) NOT NULL,
	NR_FASCICOLO_PRIVACY VARCHAR2(100 BYTE) NOT NULL,
	NR_PROTOCOLLO_PRIVACY VARCHAR2(100 BYTE) NOT NULL,
	CARICATO NUMBER(10,0), 
	CONSTRAINT A4GT_LOAD_UTENTE_CAA_PK PRIMARY KEY (CODICE_FISCALE, UFFICIO)
   );

CREATE TABLE A4GUTE_LOGGING (
	ID NUMBER(20) NOT NULL, 
	VERSIONE NUMBER(10) DEFAULT 0 NOT NULL, 
	UTENTE VARCHAR2(31) NOT NULL, 
	TIPO_EVENTO VARCHAR2(63) NOT NULL, 
	TABELLA VARCHAR2(127) NOT NULL, 
	ID_ENTITA NUMBER(20) NOT NULL, 
	DT_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, 
	CONSTRAINT A4GUTE_LOGGING_PK PRIMARY KEY (ID)

);

CREATE TABLE A4GT_ISTRUTTORIA
(
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    VARIAZIONE_RICHIESTA VARCHAR2(2000 CHAR),
    TESTO_COMUNICAZIONE VARCHAR2(4000 CHAR),
    MOTIVAZIONE_RIFIUTO VARCHAR2(2000 CHAR),
    NOTE VARCHAR2(2000 CHAR),
    ID_DOMANDA NUMBER(19),
    ID_UTENTE NUMBER(19),
    TESTO_MAIL_INVIATA VARCHAR2(2000 CHAR),
    DATA_TERMINE_ISTRUTTORIA DATE,
    ID_ISTRUTTORE NUMBER(19),
    MOTIVO_DISATTIVAZIONE VARCHAR2(2000 CHAR),
    CONSTRAINT A4GT_ISTRUTTORIA_DOMANDA_FK FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA_REGISTRAZIONE (ID)
);

CREATE TABLE A4GR_PROFILO_ISTRUTTORIA
(
    ID_ISTRUTTORIA NUMBER(19) NOT NULL,
    ID_PROFILO NUMBER(19) NOT NULL,
    CONSTRAINT A4GR_PROFILO_ISTRUTTORIA_FK1 FOREIGN KEY (ID_ISTRUTTORIA) REFERENCES A4GT_ISTRUTTORIA (ID),
    CONSTRAINT A4GR_PROFILO_ISTRUTTORIA_FK2 FOREIGN KEY (ID_PROFILO) REFERENCES A4GT_PROFILO (ID)
);


CREATE TABLE A4GR_ENTE_ISTRUTTORIA
(
    ID_ISTRUTTORIA NUMBER(19) NOT NULL,
    ID_ENTE NUMBER(19) NOT NULL,
    CONSTRAINT A4GR_ENTE_ISTRUTTORIA_FK1 FOREIGN KEY (ID_ISTRUTTORIA) REFERENCES A4GT_ISTRUTTORIA (ID),
    CONSTRAINT A4GR_ENTE_ISTRUTTORIA_FK2 FOREIGN KEY (ID_ENTE) REFERENCES A4GT_ENTE (ID)
);


CREATE TABLE A4GR_PROFILO_DIS_ISTRUTTORIA
(
    ID_ISTRUTTORIA NUMBER(19) NOT NULL,
    ID_PROFILO NUMBER(19) NOT NULL,
    CONSTRAINT A4GR_PROFILO_D_ISTRUTTORIA_FK1 FOREIGN KEY (ID_ISTRUTTORIA) REFERENCES A4GT_ISTRUTTORIA (ID),
    CONSTRAINT A4GR_PROFILO_D_ISTRUTTORIA_FK2 FOREIGN KEY (ID_PROFILO) REFERENCES A4GT_PROFILO (ID)
);


CREATE TABLE A4GT_EVENTSTORED (
   ID NUMBER(19) NOT NULL,
   VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
   EVENTO VARCHAR2(500 CHAR) NOT NULL,
   JSON_EVENT CLOB NOT NULL,
   USER_NAME VARCHAR2(100) NOT NULL,
   DATA_INSERIMENTO DATE NOT NULL,  
   NUMERO_RETRY NUMBER(3) DEFAULT 0 NOT NULL,
   ERRORE CLOB,
   CONSTRAINT A4GT_EVENTSTORED_PK PRIMARY KEY (ID)
);

  CREATE TABLE A4GT_DISTRIBUTORE
   (	"ID" NUMBER(20,0) NOT NULL,
	"VERSIONE" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"DENOMINAZIONE_AZIENDA" VARCHAR2(128 BYTE) NOT NULL,
	"COMUNE_DISTRIBUTORE" VARCHAR2(50 BYTE) NOT NULL,
	"PROVINCIA" VARCHAR2(100 BYTE) NOT NULL,
	"INDIRIZZO" VARCHAR2(100 BYTE) NOT NULL,
	"DATA_INIZIO" DATE NOT NULL,
	"DATA_FINE" DATE,
	 CONSTRAINT A4GT_DISTRIBUTORE_PK PRIMARY KEY (ID)
   );


-- Associazioni utente-distributore
CREATE TABLE A4GR_UTENTE_DISTRIBUTORE
(
    ID_UTENTE  NUMBER(19) NOT NULL,
    ID_DISTRIBUTORE NUMBER(19) NOT NULL,
    CONSTRAINT A4GR_UTENTE_DISTRIBUTORE_PK PRIMARY KEY (ID_UTENTE, ID_DISTRIBUTORE),
    CONSTRAINT A4GR_UTENTE_DISTRIBUTORE_UIDX UNIQUE (ID_UTENTE, ID_DISTRIBUTORE),
    CONSTRAINT A4GR_UTENTE_DISTRIBUTORE_FK1 FOREIGN KEY (ID_UTENTE) REFERENCES A4GT_UTENTE (ID),
    CONSTRAINT A4GR_UTENTE_DISTRIBUTORE_FK2 FOREIGN KEY (ID_DISTRIBUTORE) REFERENCES A4GT_DISTRIBUTORE (ID)
) ;
