package it.tndigitale.a4gutente.dto;

public enum Responsabilita {

    DIPENDENTE_PAT,
    DIPENDENTE_CAA,
    TITOLARE_AZIENDA_AGRICOLA,
    LIBERO_PROFESSIONISTA,
    UTENZA_TECNICA,
    DIPENDENTE_ALTRI_ENTI,
    DIPENDENTE_TNDIGIT,
    DIPENDENTE_DISTRIBUTORE,
    DIPENDENTE_DOGANE;
}
