package it.tndigitale.a4g.fascicolo.anagrafica.business.service.mandato;

public enum RevocaImmediataMandatoNotification {
	RICHIESTA_REVOCA_IMMEDIATA_ASSENTE, 
	SPORTELLO_NON_TROVATO,
	NOTIFICA_APPAG_FALLITA,
	NOTIFICA_TITOLARE_FALLITA,
	NESSUNA_RICHIESTA_REVOCA_IMMEDIATA_DA_VALUTARE,
	RICHIESTA_REVOCA_IMMEDIATA_FASCICOLO_NON_ASSOCIATO_A_CODICE_FISCALE,
	RICHIESTA_REVOCA_IMMEDIATA_CODICE_FISCALE_INVALIDO,
	DATA_NON_VALIDA,
	MANDATO_MANCANTE,
	RICHIESTA_REVOCA_IMMEDIATA_PRESENTE_E_DA_VALUTARE,
	FASCICOLO_NON_ACCESSIBILE,
	TITOLARE_NO_PEC,
	ERRORE_GENERICO
}
