/*
 * A4G - Proxy integration
 * Servizio di integrazione e colloquio con sistemi esterni ad A4G
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.tndigitale.a4g.fascicolo.territorio.dto.conduzione;

/**
 * DTO del documento giustificativo
 */
public class DocumentoConduzioneDto {
  private String dataRilascio;

  private String dataScadenza;

  private String numeroDocumento;

  private String tipoDocumento;


   /**
   * Data rilascio
   * @return dataRilascio
  **/
  public String getDataRilascio() {
    return dataRilascio;
  }

  public DocumentoConduzioneDto setDataRilascio(String dataRilascio) {
    this.dataRilascio = dataRilascio;
	return this;
  }

   /**
   * Data scadenza
   * @return dataScadenza
  **/
  public String getDataScadenza() {
    return dataScadenza;
  }

  public DocumentoConduzioneDto setDataScadenza(String dataScadenza) {
    this.dataScadenza = dataScadenza;
	return this;
  }

   /**
   * Numero documento
   * @return numeroDocumento
  **/
  public String getNumeroDocumento() {
    return numeroDocumento;
  }

  public DocumentoConduzioneDto setNumeroDocumento(String numeroDocumento) {
    this.numeroDocumento = numeroDocumento;
	return this;
  }

   /**
   * Tipo documento
   * @return tipoDocumento
  **/
  public String getTipoDocumento() {
    return tipoDocumento;
  }

  public DocumentoConduzioneDto setTipoDocumento(String tipoDocumento) {
    this.tipoDocumento = tipoDocumento;
	return this;
  }
}

