/*
 * A4G - Proxy integration
 * Servizio di integrazione e colloquio con sistemi esterni ad A4G
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.tndigitale.a4g.fascicolo.territorio.dto.conduzione;

import java.io.Serializable;

/**
 * DTO della dei dati della particella del terreno recuperato dal SIAN
 */
public class ParticellaSianDto  implements Serializable {

	private static final long serialVersionUID = -5190459625254433248L;
	private String provincia;
	private String comune;
	private String sezione;
	private String foglio;
	private String particella;
	private String subalterno;

	public String getProvincia() {
		return provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getComune() {
		return comune;
	}

	public void setComune(String comune) {
		this.comune = comune;
	}

	public String getSezione() {
		return sezione;
	}

	public void setSezione(String sezione) {
		this.sezione = sezione;
	}

	public String getFoglio() {
		return foglio;
	}

	public void setFoglio(String foglio) {
		this.foglio = foglio;
	}

	public String getParticella() {
		return particella;
	}

	public void setParticella(String particella) {
		this.particella = particella;
	}

	public String getSubalterno() {
		return subalterno;
	}

	public void setSubalterno(String subalterno) {
		this.subalterno = subalterno;
	}
}

