DELETE FROM A4GT_PASSO_TRANSIZIONE where ID_TRANSIZ_SOSTEGNO in (select id FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA in (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (SELECT ID FROM A4GT_DOMANDA WHERE numero_domanda = 1200002)));
delete FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA in (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (SELECT ID FROM A4GT_DOMANDA WHERE numero_domanda = 1200002));
DELETE FROM A4GT_PASSO_TRANSIZIONE where ID_TRANSIZ_SOSTEGNO in (select id FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA in (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (SELECT ID FROM A4GT_DOMANDA WHERE numero_domanda = 1200000)));
delete FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA in (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (SELECT ID FROM A4GT_DOMANDA WHERE numero_domanda = 1200000));
delete FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA in (SELECT ID FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (SELECT ID FROM A4GT_DOMANDA WHERE numero_domanda = 1200002));
delete FROM A4GT_ISTRUTTORIA where id_domanda in (SELECT ID FROM A4GT_DOMANDA WHERE numero_domanda = 1200000);
delete FROM A4GT_ISTRUTTORIA where id_domanda in (SELECT ID FROM A4GT_DOMANDA WHERE numero_domanda = 1200002);


-- DELETE a4gr_domanda_elenco
-- WHERE id_domanda = (SELECT ID FROM a4gt_domanda WHERE numero_domanda = 1200000)
-- AND id_elenco = 9999999;

-- DELETE a4gr_domanda_elenco
-- WHERE id_domanda = (SELECT ID FROM a4gt_domanda WHERE numero_domanda = 1200002)
-- ND id_elenco = 9999999;

delete FROM A4GT_DOMANDA WHERE numero_domanda = 1200000;
delete FROM A4GT_DOMANDA WHERE numero_domanda = 1200002;

DELETE a4gt_elenco_liquidazione
WHERE ID = 9999999
AND cod_elenco = '009-801-20190513-9999999';

COMMIT;