INSERT INTO A4G_IMPORTO_LIQUIDATO (
	CUAA,
	NUMERO_DOMANDA,
	NUMERO_ELENCO,
	TIPO_BILANCIO,
	ANNO_ESERCIZIO,
	PROGRESSIVO_CREDITO,
	NUMERO_AUTORIZZAZIONE,
	DATA_AUTORIZZAZIONE,
	TIPO_PAGAMENTO,
	CAPITOLO,
	CODICE_PRODOTTO,
	DATA_ESECUZIONE,
	PROGRESSIVO_PAGAMENTO,
	INCASSATO_NETTO)
VALUES (
	'BRTMRA56H20H612O',
	'009201500001888',
	712,
	'FF',
	2015,
	10665,
	NULL,
	NULL,
	'SALDO',
	1,
	NULL,
	NULL,
	NULL,
	196.86);

INSERT INTO A4G_IMPORTO_RECUPERATO (
	TIPO_BILANCIO, ANNO_ESERCIZIO, PROGRESSIVO_CREDITO, IMPORTO_INCASSO, DESCRIZIONE_CAPITOLO)
VALUES (
	'FF', 2015, 10665, 12.50, 'descrittore capitolo importo 1');

INSERT INTO A4G_IMPORTO_RECUPERATO (
	TIPO_BILANCIO, ANNO_ESERCIZIO, PROGRESSIVO_CREDITO, IMPORTO_INCASSO, DESCRIZIONE_CAPITOLO)
VALUES (
	'FF', 2015, 10665, 22.50, 'descrittore capitolo importo 2');

INSERT INTO A4G_IMPORTO_RECUPERATO (
	TIPO_BILANCIO, ANNO_ESERCIZIO, PROGRESSIVO_CREDITO, IMPORTO_INCASSO, DESCRIZIONE_CAPITOLO)
VALUES (
	'CC', 2015, 10665, 12.50, 'descrittore capitolo importo 3');


INSERT INTO A4G_IMPORTO_LIQUIDATO (
	CUAA,
	NUMERO_DOMANDA,
	NUMERO_ELENCO,
	TIPO_BILANCIO,
	ANNO_ESERCIZIO,
	PROGRESSIVO_CREDITO,
	NUMERO_AUTORIZZAZIONE,
	DATA_AUTORIZZAZIONE,
	TIPO_PAGAMENTO,
	CAPITOLO,
	CODICE_PRODOTTO,
	DATA_ESECUZIONE,
	PROGRESSIVO_PAGAMENTO,
	INCASSATO_NETTO)
VALUES (
	'BRTMRA56H20H612O',
	'SF00013144',
	712,
	'FF',
	2015,
	10665,
	NULL,
	NULL,
	'SALDO',
	1,
	NULL,
	NULL,
	NULL,
	196.86);
