DELETE FROM TAB_AGRI_UMAL_TRASFERIMENTI;

DELETE FROM TAB_AGRI_UMAL_CONSUNTIVI_CONSUMI;

DELETE FROM TAB_AGRI_UMAL_DICHIARAZIONE_CONSUMI;

DELETE FROM TAB_AGRI_UMAL_PRELIEVI;

DELETE FROM TAB_AGRI_UMAL_RICHIESTA_CARBURANTE;

commit;