package it.tndigitale.a4gistruttoria.repository.model;

public enum TipoProcesso {

	// RICEV_AGS
	RICEVIBILITA_AGS,
	// ("AVV_IST")
	AVVIO_ISTRUTTORIA,
	// ("CTRL_ANTIMAFIA")
	CONTROLLO_ANTIMAFIA,
	// ("CLC_ACCOPPIATO_ZOOTECNIA")
	CALCOLO_ACCOPPIATO_ZOOTECNIA,
	// ("CLC_PREMIO_ACCOPPIATO_ZOOTECNIA")
	CALCOLO_PREMIO_ACCOPPIATO_ZOOTECNIA,
	// ("NON_AMMISSIBILITA")
	NON_AMMISSIBILITA,
	// ("LIQUIDAZIONE")
	LIQUIDAZIONE, //viene creato anche elenco di liquidazione
	// ("CTRL_INTERSOSTEGNO_ACC_ZOOTECNIA")
	CTRL_INTERSOSTEGNO_ACC_ZOOTECNIA,
	// ("CTRL_INTERSOSTEGNO_ACC_SUPERFICIE")
	CTRL_INTERSOSTEGNO_ACC_SUPERFICIE,
	// "CS-21" (TipologiaStatistica.CS21.name())
	STATISTICA_CS21,
	// "CS-22" (TipologiaStatistica.CS22.name())
	STATISTICA_CS22,
	// "CS-25" (TipologiaStatistica.CS25.name())
	STATISTICA_CS25,
	// "CS-27" (TipologiaStatistica.CS27.name())
	STATISTICA_CS27,
	// "SYNC-SUPE-ACCE" (TipologiaSincronizzazioneAGEA.SINCRONIZZAZIONE_SUPERFICI_ACCERTATE.name())
	SINCRONIZZAZIONE_SUPERFICI_ACCERTATE,
	// "SYNC-PAGAMENTI" (TipologiaSincronizzazioneAGEA.SINCRONIZZAZIONE_PAGAMENTI.name())
	SINCRONIZZAZIONE_PAGAMENTI,
	// ("CLC_DISACCOPPIATO_ISTRUTTORIA")
	CALCOLO_DISACCOPPIATO_ISTRUTTORIA,
	// ("CTRL_LIQUIDABILITA_ISTRUTTORIA")
	CONTROLLO_LIQUIDABILITA_ISTRUTTORIA,

	// ("BLOCCO_ISTRUTTORIE")
	BLOCCO_ISTRUTTORIE,
	// ("SBLOCCO_ISTRUTTORIE")
	SBLOCCO_ISTRUTTORIE,
	// ("CALCOLO_ACCOPPIATO_SUPERFICIE_ISTRUTTORIA")
	CALCOLO_ACCOPPIATO_SUPERFICIE_ISTRUTTORIA,
	// ("CALCOLO_ACCOPPIATO_ZOOTECNIA_ISTRUTTORIA")
	CALCOLO_ACCOPPIATO_ZOOTECNIA_ISTRUTTORIA,
	// ("CALCOLO_CAPI_ISTRUTTORIE")
	CALCOLO_CAPI_ISTRUTTORIE,
	RESET_ISTRUTTORIA,
	INTEGRAZIONE_ISTRUTTORIE,
	IMPORTA_DOMANDE_PSR_SUPERFICIE
}
