package it.tndigitale.a4g.fascicolo.anagrafica.business.service.fascicolo;

public enum FascicoloValidazioneEnum {
	FASCICOLO_LOCALE_ESISTENTE,
	SIAN_NON_DISPONIBILE,
	COMPETENZA_ALTRO_OP,
	COMPETENZA_APPAG,
	ANAGRAFE_TRIBUTARIA_NON_DISPONIBILE,
	CUAA_NON_PRESENTE,
	PROVINCIA_DIVERSA_DA_TRENTO,
	DECEDUTO,
	ALLEGATO_NON_PRESENTE,
	CUAA_DIVERSO_CODICEFISCALE_UTENTE,
	PROVINCIA_ATTUALE_TRENTO,
	FASCICOLO_SIAN_ESISTENTE,
	FASCICOLO_SIAN_NON_ESISTENTE,
	DATA_CHIUSURA_FUTURA,
	FASCIOLO_LOCALE_DIVERSO_DA_CHIUSO,
	FASCICOLO_IN_CHIUSURA_SENZA_EREDI,
	DECEDUTO_DA_OLTRE_UN_ANNO
}
