package it.tndigitale.a4g.fascicolo.anagrafica.business.service.fascicolo;

public enum FascicoloOperationEnum {
	APRI, AGGIORNA, APRI_E_TRASFERISCI, TRASFERISCI, TRASFERISCI_E_CHIUDI, RIAPRI,
	VERIFICA_APERTURA, VERIFICA_AGGIORNAMENTO, VERIFICA_APERTURA_TRASFERIMENTO, 
	VERIFICA_TRASFERIMENTO, VERIFICA_TRASFERIMENTO_CHIUSURA, VERIFICA_RIAPERTURA
}