export enum EsitoValidazioneLavorazioneInCorso {
  NO_ESITO = 'NO_ESITO',
  ATTRIBUTI_MANCANTI = 'ATTRIBUTI_MANCANTI',
  RICHIESTA_CANCELLATA = 'RICHIESTA_CANCELLATA',
  POLIGONI_SOVRAPPOSTI = 'POLIGONI_SOVRAPPOSTI',
  ERRORI_ORACLE = 'ERRORI_ORACLE',
  POLIGONI_DEBORDANO_AREA_DI_LAVORO = 'POLIGONI_DEBORDANO_AREA_DI_LAVORO'
}