export enum PositionAccordion {
    //Step 1
    ACCORDION_STEP1_RICERCA_SUOLO_DICHIARATO = 0,
    ACCORDION_STEP1_SUOLO_DICHIARATO_IN_LAVORAZIONE = 1,

    //STEP2 
    ACCORDION_STEP2_SUOLO_VIGENTE_IN_LAVORAZIONE = 0,

    //STEP3

    //STEP4
    ACCORDION_STEP4_DATI_LAVORAZIONE = 0,
    ACCORDION_STEP4_SUOLO_DICHIARATO_IN_LAVORAZIONE = 1,
    ACCORDION_STEP4_SUOLO_VIGENTE_IN_LAVORAZIONE = 2,
    ACCORDION_STEP4_POLIGONI_WORKSPACE_IN_LAVORAZIONE = 3
}

