package it.tndigitale.a4g.richiestamodificasuolo.business.persistence.entity;

public enum StatoLavorazioneSuolo {

	IN_CREAZIONE, IN_CORSO, SOSPESA, CONSOLIDATA_SU_A4S, CONSOLIDATA_SU_AGS, CHIUSA, IN_MODIFICA, CONSOLIDAMENTO_IN_CORSO, ERRORE_CONSOLIDAMENTO, CONSOLIDATA_AGS_PROBLEMI_PARTICELLE, CONSOLIDATA_AGS_PROBLEMI_SUOLO,
	CONSOLIDATA_AGS_PROB
}
