
-- inserimento DLPCDD44C16E658A: persona fisica con ditta individuale
INSERT INTO A4GT_PERSONA
(ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(2, 0, 0, 'DLPCDD44C16E658A');

INSERT INTO A4GT_PERSONA_FISICA
(ID, ID_VALIDAZIONE, VERSIONE, NOME, COGNOME, SESSO, DATA_NASCITA, COMUNE_NASCITA, PROVINCIA_NASCITA, DECEDUTO, DENOMINAZIONE, PARTITA_IVA, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, DESCRIZIONE_ESTESA, TOPONIMO, VIA, NUMERO_CIVICO, CAP, CODICE_ISTAT, FRAZIONE, PROVINCIA, COMUNE, PEC, TELEFONO, FORMA_GIURIDICA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_PROVINCIA, SEDE_COMUNE, SEDE_FRAZIONE)
VALUES(2, 0, 0, 'CANDIDO', 'DALPONTE', 'MASCHIO', TIMESTAMP '1944-03-16 00:00:00.000000', 'LOMASO', 'TN', 0, 'DALPONTE                 CANDIDO', '00274690221', TIMESTAMP '1996-12-04 00:00:00.000000', 'TN', 150387, 0, 'descrizione estesa persona', 'viale', 'roma', 'SNC', '80123', '063049', 'frazione', 'TN', 'ROVERETO', 'CANDIDODALPONTE@PEC.IT', '0465701599', 'IMPRESA INDIVIDUALE', 'FRAZIONE VIGO 24', NULL, NULL, NULL, '38024', NULL, 'TN', 'COMANO TERME', NULL);

-- inserimento attività ateco per DLPCDD44C16E658A con fonte Anagrafe Tributaria
INSERT INTO A4GT_ATTIVITA_ATECO
(ID, VERSIONE, ID_SEDE, SEDE_ID_VALIDAZIONE, CODICE, DESCRIZIONE, IMPORTANZA, FONTE, ID_VALIDAZIONE)
VALUES(1812, 0, 2, 0, '46341', 'Commercio all ingrosso di bevande alcoliche', 'PRIMARIO_IMPRESA', 'ANAGRAFE_TRIBUTARIA', 0);

INSERT INTO A4GT_ATTIVITA_ATECO
(ID, VERSIONE, ID_SEDE, SEDE_ID_VALIDAZIONE, CODICE, DESCRIZIONE, IMPORTANZA, FONTE, ID_VALIDAZIONE)
VALUES(1814, 0, 2, 0, '7211', 'Ricerca e sviluppo sperimentale nel campo delle biotecnologie', 'SECONDARIO', 'ANAGRAFE_TRIBUTARIA', 0);

-- inserimento DPDNDR77B03L378L: persona fisica senza ditta individuale
INSERT INTO A4GT_PERSONA
(ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(2634, 0, 0, 'DPDNDR77B03L378L');

INSERT INTO A4GT_PERSONA_FISICA
(ID, ID_VALIDAZIONE, VERSIONE, NOME, COGNOME, SESSO, DATA_NASCITA, COMUNE_NASCITA, PROVINCIA_NASCITA, DECEDUTO, DENOMINAZIONE, PARTITA_IVA, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, DESCRIZIONE_ESTESA, TOPONIMO, VIA, NUMERO_CIVICO, CAP, CODICE_ISTAT, FRAZIONE, PROVINCIA, COMUNE, PEC, TELEFONO, FORMA_GIURIDICA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_PROVINCIA, SEDE_COMUNE, SEDE_FRAZIONE, SEDE_CC_DESCRIZIONE_ESTESA, SEDE_CC_TOPONIMO, SEDE_CC_VIA, SEDE_CC_NUMERO_CIVICO, SEDE_CC_CAP, SEDE_CC_CODICE_ISTAT, SEDE_CC_PROVINCIA, SEDE_CC_COMUNE, SEDE_CC_FRAZIONE)
VALUES(2634, 0, 0, 'ANDREA', 'DEPEDRI', 'MASCHIO', TIMESTAMP '1977-02-03 00:00:00.000000', 'TRENTO', 'TN', 0, NULL, NULL, NULL, NULL, NULL, NULL, 'VIA SANT''AGATA N 12 A', NULL, NULL, NULL, '38068', NULL, NULL, 'TN', 'TRENTO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- inserimento cuaa: persona fisica con ditta individuale iscritta in camera di commercio
INSERT INTO A4GT_PERSONA
(ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(2792, 0, 0, 'FNTDNL86E05L378J');

INSERT INTO A4GT_PERSONA_FISICA
(ID, ID_VALIDAZIONE, VERSIONE, NOME, COGNOME, SESSO, DATA_NASCITA, COMUNE_NASCITA, PROVINCIA_NASCITA, DECEDUTO, DENOMINAZIONE, PARTITA_IVA, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, DESCRIZIONE_ESTESA, TOPONIMO, VIA, NUMERO_CIVICO, CAP, CODICE_ISTAT, FRAZIONE, PROVINCIA, COMUNE, PEC, TELEFONO, FORMA_GIURIDICA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_PROVINCIA, SEDE_COMUNE, SEDE_FRAZIONE, SEDE_CC_DESCRIZIONE_ESTESA, SEDE_CC_TOPONIMO, SEDE_CC_VIA, SEDE_CC_NUMERO_CIVICO, SEDE_CC_CAP, SEDE_CC_CODICE_ISTAT, SEDE_CC_PROVINCIA, SEDE_CC_COMUNE, SEDE_CC_FRAZIONE)
VALUES(2792, 0, 0, 'DANIELE', 'FONTANA', 'MASCHIO', TIMESTAMP '1986-05-05 00:00:00.000000', 'TRENTO', 'TN', 0, 'FONTANA                  DANIELE', '01919650224', TIMESTAMP '2005-03-21 00:00:00.000000', 'TN', 187463, 0, 'VIA SANT''AGATA N 12 A', NULL, NULL, NULL, '38098', NULL, NULL, 'TN', 'SAN MICHELE ALL''ADIGE', 'daniele.fontana1986@pec.agritel.it', '0461669024', 'IMPRESA INDIVIDUALE', 'VIA S. AGATA 12/A', NULL, NULL, NULL, '38010', NULL, 'TN', 'SAN MICHELE ALL''ADIGE', NULL, NULL, 'VIA', 'S. AGATA', '12/A', '38010', '022080', 'TRENTO', 'FAEDO', NULL);
