import { TipoProcesso } from "src/app/istruttoria/istruttoria-antimafia/dto/TipoProcesso";

export const CONF_PROCESSI = {
    "DISACCOPPIATO": {
      "CALCOLO_PREMIO": {
        "RICHIESTO": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CALCOLO_DISACCOPPIATO_ISTRUTTORIA],
        "CONTROLLI_CALCOLO_OK": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CALCOLO_DISACCOPPIATO_ISTRUTTORIA],
        "CONTROLLI_CALCOLO_KO": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.NON_AMMISSIBILITA, TipoProcesso.CALCOLO_DISACCOPPIATO_ISTRUTTORIA],
        "NON_AMMISSIBILE": []
      },
      "CONTROLLI_LIQUIDABILITA": {
        "CONTROLLI_CALCOLO_OK": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA, TipoProcesso.CALCOLO_DISACCOPPIATO_ISTRUTTORIA],
        "LIQUIDABILE": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA],
        "CONTROLLI_LIQUIDABILE_KO": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA],
        "DEBITI": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
            TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA]
      },
      "LIQUIDAZIONE": {
        "LIQUIDABILE": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE, 
          TipoProcesso.LIQUIDAZIONE, TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA],
        "NON_LIQUIDABILE": [],
        "PAGAMENTO_NON_AUTORIZZATO": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE, TipoProcesso.LIQUIDAZIONE],
        "CONTROLLI_INTERSOSTEGNO_OK": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE, TipoProcesso.LIQUIDAZIONE],
        "PAGAMENTO_AUTORIZZATO": [TipoProcesso.INTEGRAZIONE_ISTRUTTORIE]
      }
    },
    "SUPERFICIE": {
      "CALCOLO_PREMIO": {
        "RICHIESTO": [TipoProcesso.CALCOLO_ACCOPPIATO_SUPERFICIE_ISTRUTTORIA],
        "INTEGRATO": [],
        "CONTROLLI_CALCOLO_OK": [TipoProcesso.CALCOLO_ACCOPPIATO_SUPERFICIE_ISTRUTTORIA,TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA],
        "CONTROLLI_CALCOLO_KO": [TipoProcesso.CALCOLO_ACCOPPIATO_SUPERFICIE_ISTRUTTORIA, TipoProcesso.NON_AMMISSIBILITA],
        "NON_AMMISSIBILE": []
      },
      "CONTROLLI_LIQUIDABILITA": {
        "CONTROLLI_CALCOLO_OK": [TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA, TipoProcesso.CALCOLO_ACCOPPIATO_SUPERFICIE_ISTRUTTORIA],
        "LIQUIDABILE": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA],
        "CONTROLLI_LIQUIDABILE_KO": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA],
        "DEBITI": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
            TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA]
      },
      "LIQUIDAZIONE": {
        "LIQUIDABILE": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE, 
          TipoProcesso.LIQUIDAZIONE, TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA],
        "NON_LIQUIDABILE": [],
        "PAGAMENTO_NON_AUTORIZZATO": [TipoProcesso.LIQUIDAZIONE, TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE],
        "CONTROLLI_INTERSOSTEGNO_OK": [TipoProcesso.LIQUIDAZIONE, TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE],
        "PAGAMENTO_AUTORIZZATO": []
      }
    },
    // TO DO: verificare corretta mappatura per ACZ
    "ZOOTECNIA": {
      "CALCOLO_PREMIO": {
        "RICHIESTO": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CALCOLO_CAPI_ISTRUTTORIE],
        "INTEGRATO": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CALCOLO_CAPI_ISTRUTTORIE, TipoProcesso.CALCOLO_ACCOPPIATO_ZOOTECNIA_ISTRUTTORIA],
        "CONTROLLI_CALCOLO_OK": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CALCOLO_ACCOPPIATO_ZOOTECNIA_ISTRUTTORIA, TipoProcesso.CALCOLO_PREMIO_ACCOPPIATO_ZOOTECNIA, TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA],
        "CONTROLLI_CALCOLO_KO": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CALCOLO_ACCOPPIATO_ZOOTECNIA_ISTRUTTORIA, TipoProcesso.NON_AMMISSIBILITA],
        "NON_AMMISSIBILE": [TipoProcesso.RESET_ISTRUTTORIA, TipoProcesso.CALCOLO_CAPI_ISTRUTTORIE,
          TipoProcesso.CALCOLO_ACCOPPIATO_ZOOTECNIA_ISTRUTTORIA]
      },
      "CONTROLLI_LIQUIDABILITA": {
        "CONTROLLI_CALCOLO_OK": [TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA, TipoProcesso.CALCOLO_ACCOPPIATO_ZOOTECNIA_ISTRUTTORIA],
        "LIQUIDABILE": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA],
        "CONTROLLI_LIQUIDABILE_KO": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
          TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA],
        "DEBITI": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE,
            TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA]
      },
      "LIQUIDAZIONE": {
        "LIQUIDABILE": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE, 
          TipoProcesso.LIQUIDAZIONE, TipoProcesso.CONTROLLO_LIQUIDABILITA_ISTRUTTORIA],
        "NON_LIQUIDABILE": [],
        "PAGAMENTO_NON_AUTORIZZATO": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE, TipoProcesso.LIQUIDAZIONE],
        "CONTROLLI_INTERSOSTEGNO_OK": [TipoProcesso.BLOCCO_ISTRUTTORIE, TipoProcesso.SBLOCCO_ISTRUTTORIE, TipoProcesso.LIQUIDAZIONE],
        "PAGAMENTO_AUTORIZZATO": []
      }
    },
    "CRUSCOTTO": [TipoProcesso.SINCRONIZZAZIONE_SUPERFICI_ACCERTATE, TipoProcesso.SINCRONIZZAZIONE_PAGAMENTI, TipoProcesso.STATISTICHE_CS21, TipoProcesso.STATISTICHE_CS22, TipoProcesso.STATISTICHE_CS25, TipoProcesso.STATISTICHE_CS27]
  };