package it.tndigitale.a4gistruttoria.repository.specification;

public enum RiservaNazionaleEnum {
	A_GIOVANE_AGRICOLTORE,
	B_NUOVO_AGRICOLTORE,
	C_ABBANDONO_TERRE,
	D_COMPENSAZIONE_SVANTAGGI_SPECIFICI,
	F_PROVVEDIMENTI_AMMINISTRATIVI_DECISIONI_GIUDIZIARIE,
	NON_RICHIESTA
}
