DROP ALL OBJECTS;

-- Schemas vari usati per le query
create schema SITI; 
create schema SITI_INTERFACCIA_PCK;
create schema DOMAGRAF;  

-- 1. Sequence
CREATE SEQUENCE SEQ_WOR_LOG_TR_TR_ID
  START WITH 1000  
  NOCYCLE
  NOCACHE
  ORDER;
  
CREATE SEQUENCE SDOM_DOMANDA_PKID
  START WITH 1000 
  NOCYCLE
  NOCACHE
  ORDER; 


CREATE ALIAS SITI_INTERFACCIA_PCK.GET_LABEL_COMUNE FOR "it.tndigitale.a4g.ags.DomandaApplicationTests.getLabelComune";    

CREATE ALIAS DOMAGRAF.GETCODIISOLA FOR "it.tndigitale.a4g.ags.DomandaApplicationTests.getCodIsola";

-- TABELLE SCHEMA DEFAULT, che in H2 si chiama PUBLIC
create table TFASCICOLO
(
  id_fascicolo     NUMBER(11) not null,
  id_soggetto      NUMBER(11) not null,
  id_modello       NUMBER(11) not null,
  protocollo       VARCHAR2(50),
  id_ente          NUMBER(11),
  dt_inizio        DATE not null,
  dt_fine          DATE not null,
  cod_op           VARCHAR2(6) default 'ORGPAG' not null,
  sco_op           VARCHAR2(6),
  cod_stato        VARCHAR2(6) default 'STAFAS' not null,
  sco_stato        VARCHAR2(6) default 'AGGIOR' not null,
  dt_aggiornamento DATE default sysdate
);
-- Create/Recreate indexes 
create unique index I1_FASCICOLO on TFASCICOLO (ID_SOGGETTO, ID_MODELLO);
create index I2_FASCICOLO on TFASCICOLO (SCO_STATO, ID_MODELLO);
-- Create/Recreate primary, unique and foreign key constraints 
alter table TFASCICOLO
  add constraint PK_TFASCICOLO primary key (ID_FASCICOLO);
  
-- Create table
create table CONS_SOGG_VIW
(
 pkid NUMBER(9) not null,
 pk_cuaa NUMBER(9),
 cuaa  VARCHAR2(16),
 cod_fiscale VARCHAR2(16),
 codi_fisc VARCHAR2(16),
 part_iva VARCHAR2(11),
 codi_piva VARCHAR2(11),
 ragi_soci VARCHAR2(2000),
 cognome VARCHAR2(150),
 nome VARCHAR2(50),
 sesso VARCHAR2(1),
 d_nascita DATE,
 d_costituzione DATE,
 data_nasc DATE,
 d_morte DATE,
 fkcod_comu_resi VARCHAR2(4),
 fkcod_comu_nasc VARCHAR2(4),
 comu_nasc VARCHAR2(4),
 fkcivico_resi INTEGER,
 fkcod_comu_recapito VARCHAR2(4),
 fkcivico_recapito INTEGER,
 flag_pers_fisica VARCHAR2(1),
 fkrapp_legale NUMBER(9),
 data_fine_val DATE,
 data_inizio_val DATE,
 data_lav DATE,
 utente_inizio VARCHAR2(100),
 utente_fine VARCHAR2(100),
 valido_inizio VARCHAR2(1),
 valido_fine VARCHAR2(1),
 atto_inizio NUMBER(9),
 atto_fine NUMBER(9),
 natura_giuridica VARCHAR2(10),
 resi_comu CHAR(4),
 cap VARCHAR2(5),
 cap_recap VARCHAR2(5),
 telefono VARCHAR2(20),
 fax VARCHAR2(20),
 mail VARCHAR2(100),
 indirizzo_est VARCHAR2(150),
 indirizzo_est_recap VARCHAR2(150),
 fl_part_iva VARCHAR2(1),
 localita VARCHAR2(50),
 cellulare VARCHAR2(20),
 fonte_inizio NUMBER,
 fonte_fine NUMBER,
 riferimento VARCHAR2(10),
 denominazione_int VARCHAR2(2000),
 localita_int VARCHAR2(50),
 indirizzo_est_int VARCHAR2(150),
 indirizzo_est_recap_int VARCHAR2(150)
);

-- Create/Recreate indexes 
create index CONS_SOGG_VIW_IDX1 on CONS_SOGG_VIW (ragi_soci);
create index CONS_SOGG_VIW_IDX2 on CONS_SOGG_VIW (COGNOME, NOME);
create index CONS_SOGG_VIW_IDX3 on CONS_SOGG_VIW (COD_FISCALE);
create index CONS_SOGG_VIW_IDX4 on CONS_SOGG_VIW (PART_IVA);
create index CONS_SOGG_VIW_IDX5 on CONS_SOGG_VIW (pk_cuaa, DATA_FINE_VAL);
create index I1_CONS_SOGG_VIW on CONS_SOGG_VIW (pk_cuaa);

-- Create/Recreate primary, unique and foreign key constraints 
alter table CONS_SOGG_VIW
  add constraint PK_SOGGETTI primary key (PKID);
  
-- Create table
create table TDECODIFICA_LANGUAGE
(
  codice        VARCHAR2(6 CHAR) not null,
  sotto_codice  VARCHAR2(6 CHAR) not null,
  locale        VARCHAR2(10 CHAR) default 'it' not null,
  ds_decodifica VARCHAR2(2000 CHAR) not null,
  de_decodifica VARCHAR2(2000 CHAR),
  fg_sistema    VARCHAR2(1 CHAR) default 'N' not null,
  ordine        NUMBER(11),
  fg_cessato    VARCHAR2(1 CHAR) default 'N' not null
);

-- Create/Recreate indexes 
create index IDX1_TDECODIFICA_LANGUAGE on TDECODIFICA_LANGUAGE (LOCALE);
-- Create/Recreate primary, unique and foreign key constraints 
alter table TDECODIFICA_LANGUAGE
  add constraint PK_TDECODIFICA_LANGUAGE primary key (CODICE, SOTTO_CODICE, LOCALE);

-- Create table
create table TQDO_ENTI
(
	PKID				NUMBER(11,0) not null,
	DT_INSERT			DATE default sysdate not null,
	DT_DELETE			DATE not null,
	ID_SOGGETTO			NUMBER(11,0) not null,
	ID_UTE				NUMBER(11,0),
	ID_ENTE_COMPILATORE	NUMBER(11,0) not null,
	ID_ENTE_DELEGATO	NUMBER(11,0) not null,
	COD_FONTE_DATI		VARCHAR2(6 BYTE) default 'FONDAT' not null,
	SCO_FONTE_DATI		VARCHAR2(6 BYTE) not null,
	DT_INIZIO			DATE default sysdate not null,
	DT_FINE				DATE not null,
	FG_VALIDO_INIZIO	VARCHAR2(1 BYTE) default 'N' not null,
	FG_VALIDO_FINE		VARCHAR2(1 BYTE) default 'N' not null,
	ID_ATTO_INIZIO		NUMBER(11,0),
	ID_ATTO_FINE		NUMBER(11,0),
	DT_ULTIMO_AGG		DATE default sysdate not null,
	UTENTE				VARCHAR2(20 BYTE) default 'ADMIN'  not null,
	ID_DOMANDA			NUMBER(11,0)
);

alter table TQDO_ENTI
  add constraint PK_QDO_ENTI primary key (PKID);

-- Create table
create table TDOMANDA
(
	pkid NUMBER(11) not null,
	id_soggetto NUMBER(11) not null,
	id_domanda NUMBER(11) not null,
	id_domanda_rettificata NUMBER(11),
	id_modulo NUMBER(11) not null,
	sco_stato VARCHAR2(6 CHAR),
	sco_settore VARCHAR2(11 CHAR),
	anno NUMBER(11) not null,
	de_modulo VARCHAR2(2000 CHAR),
	dt_insert DATE not null,
	dt_delete DATE not null,
	ds_dom_stato VARCHAR2(2000 CHAR) NOT NULL
);

alter table TDOMANDA
  add constraint PK_TDOMANDA primary key (pkid);

-- Create table
create table TDOM_MOVIMENTO
(
	ID_MOVIMENTO		NUMBER(11) not null,
	ID_DOMANDA			NUMBER(11) not null,
	ID_WORKFLOW			NUMBER(11) not null,
	COD_WORKFLOW		VARCHAR2(50) not null,
	DT_MOVIMENTO		DATE not null,
	ID_ATTO_INIZIO		NUMBER(11),
	ID_ATTO_FINE		NUMBER,
	FG_VALIDO_INIZIO	VARCHAR2(1) not null,
	FG_VALIDO_FINE		VARCHAR2(1) not null,	
	ID_REGISTRO			NUMBER,
	RULE_LOG_ID			NUMBER,
	UTENTE				VARCHAR2(20),
	NOTE				VARCHAR2(4000)
);

alter table TDOM_MOVIMENTO
  add constraint PK_TDOM_MOV primary key (ID_MOVIMENTO);

-- Create table
create table TDOM_MODULO_DECO
(
	ID_MODULO				NUMBER(11,0) not null,
	COD_SETTORE				VARCHAR2(11 CHAR) default 'SETDOM',
	SCO_SETTORE				VARCHAR2(11 CHAR),	
	ANNO					NUMBER(4,0),
	COD_TIPO_DOMANDA		VARCHAR2(6 CHAR) default 'TIPDOM',
	SCO_TIPO_DOMANDA		VARCHAR2(6 CHAR),
	FG_MULTIPLA				VARCHAR2(1 CHAR) default 'N',
	COD_FUNZIONE			VARCHAR2(100 CHAR),	
	DT_APERTURA_TER			DATE,
	DT_CHIUSURA_TER			DATE,	
	FG_UTE					VARCHAR2(1 CHAR) default 'N',
	DT_INIZIO				DATE default SYSDATE,
	DT_FINE					DATE,	
	FG_VALIDO_INIZIO		VARCHAR2(1 CHAR) default 'N',
	FG_VALIDO_FINE			VARCHAR2(1 CHAR)default 'N',
	ID_ATTO_INIZIO			NUMBER(11,0),
	ID_ATTO_FINE			NUMBER(11,0),	
	ID_STAMPA_MODELLO		VARCHAR2(50 CHAR),	
	DT_INIZIO_IMP			DATE,
	DT_FINE_IMP				DATE,	
	DURATA					NUMBER(11,0),
	COD_MODULO				VARCHAR2(50 BYTE) not null
);

alter table TDOM_MODULO_DECO
  add constraint PK_TDOM_MODULO_DECO primary key (ID_MODULO);  
create unique index UIDX_DOM_MODULO_DECO on TDOM_MODULO_DECO (COD_MODULO);  
  
--Create table  
CREATE TABLE TDOM_DOMANDA (
	PKID NUMBER(11,0) NOT NULL, 
	DT_INSERT DATE DEFAULT SYSDATE NOT NULL, 
	DT_DELETE DATE NOT NULL, 
	ID_SOGGETTO NUMBER(11,0) NOT NULL , 
	ID_UTE NUMBER(11,0), 
	ID_DOMANDA NUMBER(11,0) NOT NULL, 
	COD_DOMANDA VARCHAR2(50 BYTE), 
	ID_DOMANDA_RETTIFICATA NUMBER(11,0), 
	ID_MODULO NUMBER(11,0) NOT NULL, 
	ID_ENTE NUMBER(11,0), 
	COD_STATO VARCHAR2(6 BYTE) DEFAULT 'STADOM' NOT NULL, 
	SCO_STATO VARCHAR2(6 BYTE) NOT NULL, 
	COD_FONTE_DATI VARCHAR2(6 BYTE) DEFAULT 'FONDAT' NOT NULL, 
	SCO_FONTE_DATI VARCHAR2(6 BYTE) NOT NULL, 
	DT_INIZIO DATE DEFAULT SYSDATE NOT NULL, 
	DT_FINE DATE NOT NULL, 
	FG_VALIDO_INIZIO VARCHAR2(1 BYTE) DEFAULT 'S' NOT NULL, 
	FG_VALIDO_FINE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	ID_ATTO_INIZIO NUMBER(11,0), 
	ID_ATTO_FINE NUMBER(11,0), 
	DT_ULTIMO_AGG DATE DEFAULT SYSDATE NOT NULL, 
	UTENTE VARCHAR2(20 BYTE) NOT NULL
	);
-- Create/Recreate indexes 
CREATE INDEX I2_ID_DOMANDA ON TDOM_DOMANDA (ID_DOMANDA);
CREATE INDEX I2_TDOM_DOMANDA ON TDOM_DOMANDA (SCO_STATO, DT_INSERT, DT_DELETE);
CREATE INDEX IU2_ID_DOM_RETTIFICATA ON TDOM_DOMANDA (ID_DOMANDA_RETTIFICATA);
CREATE UNIQUE INDEX IU_ID_DOMANDA ON TDOM_DOMANDA (ID_DOMANDA, DT_DELETE);
CREATE INDEX I_ID_DOMANDA ON TDOM_DOMANDA (ID_SOGGETTO, ID_UTE, ID_DOMANDA);
CREATE UNIQUE INDEX PK_TDOM_DOMANDA ON TDOM_DOMANDA (PKID);  	
	
-- Create/Recreate primary, unique and foreign key constraints 
alter table TDOM_DOMANDA
  add constraint PK_TDOM_DOMANDA primary key (PKID);   

--Create table  
CREATE TABLE TWOR_DEF_WORKFLOW_GROUP (
	  GROUP_ID         NUMBER(11) NOT NULL,
	  COD_ENTITY       VARCHAR2(6) DEFAULT 'OGGFAS' NOT NULL,
	  SCO_ENTITY       VARCHAR2(6) NOT NULL,
	  COD_DESC_GRP     VARCHAR2(6) DEFAULT 'WORGRP' NOT NULL,
	  SCO_DESC_GRP     VARCHAR2(6) NOT NULL,
	  DECO_STATUS      VARCHAR2(6) NOT NULL,
	  DECO_TRANSITIONS VARCHAR2(6) NOT NULL,
	  DESCRIPTION      VARCHAR2(100),
	  COD_WOR_GROUP    VARCHAR2(50)
	);

-- Create/Recreate primary, unique and foreign key constraints 
alter table TWOR_DEF_WORKFLOW_GROUP add constraint PK_WOR_DEF_WORK_GROUP primary key (GROUP_ID);	

-- Create table
CREATE TABLE TDOM_DEF_WORKFLOW_GROUP (
	  ID_MODULO   NUMBER(11) NOT NULL,
	  GROUP_ID    NUMBER(11) NOT NULL,
	  COD_CONTEXT VARCHAR2(6) DEFAULT 'DOMWCT' NOT NULL,
	  SCO_CONTEXT VARCHAR2(6) NOT NULL,
	  DT_START    DATE DEFAULT SYSDATE NOT NULL,
	  DT_END      DATE NOT NULL
	);
	
-- Create/Recreate primary, unique and foreign key constraints 
alter table TDOM_DEF_WORKFLOW_GROUP add constraint PK_DOM_DEF_WORKFLOW_GROUP primary key (ID_MODULO, GROUP_ID);	

-- Create table
CREATE TABLE TWOR_DEF_WORKFLOW (
	  WORKFLOW_ID          NUMBER(11) NOT NULL,
	  GROUP_ID             NUMBER(11) NOT NULL,
	  FG_SYSTEM_RESTRICTED NUMBER DEFAULT 0 NOT NULL,
	  AUT_FUNCTION         VARCHAR2(100),
	  FG_REFERENCE         NUMBER DEFAULT 0 NOT NULL,
	  COD_STATUS_FROM      VARCHAR2(6) NOT NULL,
	  SCO_STATUS_FROM      VARCHAR2(6),
	  COD_TRANSITION_TO    VARCHAR2(6) NOT NULL,
	  SCO_TRANSITION_TO    VARCHAR2(6) NOT NULL,
	  RULE_ID              NUMBER(11),
	  COD_STATUS_TO        VARCHAR2(6) NOT NULL,
	  SCO_STATUS_TO        VARCHAR2(6) NOT NULL,
	  TASK_ID_TO           NUMBER(11),
	  DT_START             DATE NOT NULL,
	  DT_END               DATE NOT NULL,
	  WORKFLOW_ID_KO       NUMBER(11)
	); 

-- Create/Recreate indexes 
create index IDX1_WOR_DEF_WORKFLOW on TWOR_DEF_WORKFLOW (GROUP_ID);

-- Create/Recreate primary, unique and foreign key constraints 
alter table TWOR_DEF_WORKFLOW add constraint PK_WOR_DEF_WORKFLOW primary key (WORKFLOW_ID);	

-- Create table
CREATE TABLE TWOR_DEF_METADATA (
	  WORKFLOW_ID      NUMBER(11) NOT NULL,
	  COD_WORKFLOW     VARCHAR2(50),
	  ACT_TYPE_ID      NUMBER(11),
	  BATCH_ID_TO      NUMBER(11),
	  ID_DEF_CONTROLLO NUMBER(11),
	  FG_OVERWRITE     NUMBER(1) DEFAULT 0 NOT NULL,
	  FG_CLOSE         NUMBER DEFAULT 0 NOT NULL,
	  FG_DELETE        NUMBER DEFAULT 0 NOT NULL
	);
	
-- Create/Recreate primary, unique and foreign key constraints 
alter table TWOR_DEF_METADATA add constraint PK_WOR_DEF_METADATA primary key (WORKFLOW_ID);

-- Create table
CREATE TABLE TWOR_LOG_TRANSITION (
	  TRANSITION_ID        NUMBER(11) NOT NULL,
	  WORKFLOW_ID          NUMBER(11) NOT NULL,
	  DT_TRANSITION        DATE NOT NULL,
	  TRANS_USER           VARCHAR2(20) NOT NULL,
	  FG_VALID             NUMBER(1) DEFAULT 0 NOT NULL,
	  ACT_ID               NUMBER(11),
	  NOTE                 VARCHAR2(4000),
	  RULE_LOG_ID          NUMBER(11),
	  TASK_LOG_ID          NUMBER(11),
	  PARENT_TRANSITION_ID NUMBER(11)
	);	
	
-- Create/Recreate indexes 
create index IDX1_WOR_LOG_TRANSITION on TWOR_LOG_TRANSITION (WORKFLOW_ID);

-- Create/Recreate primary, unique and foreign key constraints 
alter table TWOR_LOG_TRANSITION add constraint PK_WOR_LOG_TRANSITION primary key (TRANSITION_ID);

-- Create table
CREATE TABLE TDOM_LOG_TRANSITION (
	  ID_DOMANDA    NUMBER(11) NOT NULL,
	  TRANSITION_ID NUMBER(11) NOT NULL
	);	
	
-- Create/Recreate primary, unique and foreign key constraints 
alter table TDOM_LOG_TRANSITION add constraint PK_DOM_LOG_TRANSITION primary key (ID_DOMANDA, TRANSITION_ID);	

-- Create table
CREATE TABLE TDES_DEF_DESTINAZIONE (	
	ID_DESTINAZIONE NUMBER(11,0) NOT NULL, 
	COD_DESTINAZIONE VARCHAR2(50 BYTE) NOT NULL, 
	DS_DESTINAZIONE VARCHAR2(200 BYTE) NOT NULL, 
	DE_DESTINAZIONE VARCHAR2(4000 BYTE), 
	DT_INIZIO DATE DEFAULT SYSDATE NOT NULL, 
	DT_FINE DATE NOT NULL, 
	ID_GRUPPO VARCHAR2(20 BYTE), 
	COD_UNIMIS VARCHAR2(6 BYTE) DEFAULT 'UNIMIS' NOT NULL, 
	SCO_UNIMIS VARCHAR2(6 BYTE), 
	FG_PARCEL NUMBER(1,0) DEFAULT -1 NOT NULL, 
	FG_UNITS_TYPE NUMBER(1,0) DEFAULT -1 NOT NULL, 
	MEASURE_ELIGIBLE_FUNC VARCHAR2(4000 CHAR), 
	FG_PREVIEW NUMBER(3,0) DEFAULT 0 NOT NULL); 

-- Create/Recreate primary, unique and foreign key constraints 	
ALTER TABLE TDES_DEF_DESTINAZIONE ADD CONSTRAINT PK_DES_DEF_DESTINAZIONE PRIMARY KEY (ID_DESTINAZIONE);
CREATE INDEX IDX1_TDES_DEF_DESTINAZIONE ON TDES_DEF_DESTINAZIONE (ID_GRUPPO);
CREATE INDEX IDX2_TDES_DEF_DESTINAZIONE ON TDES_DEF_DESTINAZIONE (COD_DESTINAZIONE);

-- Create table
CREATE TABLE TDU_DEF_INTERVENTO (	
ID_INTERVENTO NUMBER(11,0) NOT NULL,
COD_INTERVENTO VARCHAR2(50 BYTE) NOT NULL,
DS_INTERVENTO VARCHAR2(200 CHAR) NOT NULL,
DE_INTERVENTO VARCHAR2(4000 BYTE), 
DT_INIZIO DATE DEFAULT SYSDATE NOT NULL,
DT_FINE DATE NOT NULL,
ID_GRUPPO VARCHAR2(20 BYTE), 
SUP_MINIMA NUMBER(11,0) DEFAULT 0 NOT NULL);

-- Create/Recreate primary, unique and foreign key constraints 	
ALTER TABLE TDU_DEF_INTERVENTO ADD CONSTRAINT PK_TDU_DEF_INTERVENTO PRIMARY KEY (ID_INTERVENTO);

-- Create table
CREATE TABLE TDOM_GRAF_BLACKLIST_CUAA( 
	CUAA VARCHAR2(16 BYTE) NOT NULL, 
	COD_SETTORE VARCHAR2(11 BYTE) NOT NULL, 
	SCO_SETTORE VARCHAR2(11 BYTE) NOT NULL,
	ANNO VARCHAR2(4 BYTE) NOT NULL,
	DT_INIZIO_VAL DATE DEFAULT SYSDATE NOT NULL, 
	DT_FINE_VAL DATE DEFAULT TO_DATE('31-12-9999','DD-MM-YYYY') NOT NULL,
	DT_ULTIMO_AGG DATE DEFAULT SYSDATE NOT NULL );
	
-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE TDOM_GRAF_BLACKLIST_CUAA ADD CONSTRAINT PK_DEF_BLACKLIST_CUAA PRIMARY KEY (CUAA, COD_SETTORE, SCO_SETTORE, ANNO);

-- Create table
CREATE TABLE TQDO_DES_PC_DESTINAZIONE (	
	PKID NUMBER(11,0) NOT NULL , 
	DT_INSERT DATE DEFAULT SYSDATE NOT NULL , 
	DT_DELETE DATE NOT NULL , 
	ID_SOGGETTO NUMBER(11,0) NOT NULL , 
	ID_UTE NUMBER(11,0), 
	ID_DESTINAZIONE NUMBER(11,0) NOT NULL , 
	ID_PARTICELLA NUMBER(11,0), 
	ID_PIANO_COLTURE NUMBER(11,0) NOT NULL , 
	SUP_IMPEGNO NUMBER(11,0), 
	MTL_IMPEGNO NUMBER(11,0), 
	UNI_IMPEGNO NUMBER(11,0), 
	COD_FONTE_DATI VARCHAR2(6 BYTE) DEFAULT 'FONDAT' NOT NULL , 
	SCO_FONTE_DATI VARCHAR2(6 BYTE) NOT NULL , 
	DT_INIZIO DATE DEFAULT SYSDATE NOT NULL , 
	DT_FINE DATE NOT NULL , 
	FG_VALIDO_INIZIO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL , 
	FG_VALIDO_FINE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL , 
	ID_ATTO_INIZIO NUMBER(11,0), 
	ID_ATTO_FINE NUMBER(11,0), 
	DT_ULTIMO_AGG DATE DEFAULT SYSDATE NOT NULL , 
	UTENTE VARCHAR2(20 BYTE) DEFAULT 'ADMIN' NOT NULL , 
	ID_DOMANDA NUMBER(11,0), 
	ID_ISOLA NUMBER, 
	ID_PARC NUMBER); 

-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE TQDO_DES_PC_DESTINAZIONE ADD CONSTRAINT PK_DES_PC_DEST PRIMARY KEY (PKID); 
CREATE INDEX I1_DES_PC_DES ON TQDO_DES_PC_DESTINAZIONE(ID_SOGGETTO, ID_UTE, ID_DESTINAZIONE, ID_PIANO_COLTURE);
CREATE INDEX I2_DES_PC_DES ON TQDO_DES_PC_DESTINAZIONE(ID_DOMANDA);
CREATE INDEX I3_DES_PIANCOLT ON TQDO_DES_PC_DESTINAZIONE(ID_PIANO_COLTURE);
CREATE INDEX I4_DES_IDPARTIC ON TQDO_DES_PC_DESTINAZIONE(ID_PARTICELLA);
CREATE UNIQUE INDEX IU_DES_PC_DEST ON TQDO_DES_PC_DESTINAZIONE (ID_SOGGETTO, ID_DESTINAZIONE, ID_PIANO_COLTURE, DT_DELETE, ID_DOMANDA, ID_PARC);

-- Create table
CREATE TABLE TPIANO_COLTURE( 
	PKID NUMBER(11,0) NOT NULL , 
	DT_INSERT DATE NOT NULL , 
	DT_DELETE DATE NOT NULL , 
	ID_PIANO_COLTURE NUMBER(11,0) NOT NULL , 
	ANNO NUMBER(4,0) NOT NULL , 
	COD_NAZIONALE VARCHAR2(4 BYTE) NOT NULL , 
	FOGLIO NUMBER(4,0) NOT NULL , 
	PARTICELLA VARCHAR2(5 BYTE) NOT NULL , 
	SUB VARCHAR2(3 BYTE) NOT NULL , 
	ID_COLTURA_1 NUMBER(11,0) NOT NULL , 
	ID_COLTURA_2 NUMBER(11,0), 
	FG_BIOLOGICO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL , 
	SUP_DICHIARATA NUMBER(11,0) NOT NULL , 
	SUP_ACCERTATA NUMBER(11,0), 
	COD_TIPO_IMPIANTO VARCHAR2(6 BYTE) DEFAULT 'IMPCOL' NOT NULL , 
	SCO_TIPO_IMPIANTO VARCHAR2(6 BYTE), 
	ANNO_IMPIANTO NUMBER(4,0), 
	SESTO_SU_FILA NUMBER(11,0), 
	SESTO_TRA_FILE NUMBER(11,0), 
	NUMERO_PIANTE NUMBER(11,0), 
	COD_FONTE_DATI VARCHAR2(6 BYTE) DEFAULT 'FONDAT' NOT NULL , 
	SCO_FONTE_DATI VARCHAR2(6 BYTE) NOT NULL , 
	DT_INIZIO DATE NOT NULL , 
	DT_FINE DATE NOT NULL , 
	FG_VALIDO_INIZIO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL , 
	FG_VALIDO_FINE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL , 
	ID_ATTO_INIZIO NUMBER(11,0), 
	ID_ATTO_FINE NUMBER(11,0), 
	DT_ULTIMO_AGG DATE DEFAULT SYSDATE NOT NULL , 
	UTENTE VARCHAR2(20 BYTE) DEFAULT 'ADMIN' NOT NULL , 
	FG_OLIO_VARIETA_PREV VARCHAR2(1 CHAR), 
	COD_OLIO_TIPO_CERTIF VARCHAR2(6 CHAR) DEFAULT 'OLICER', 
	SCO_OLIO_TIPO_CERTIF VARCHAR2(6 CHAR), 
	COD_OLIO_MENZIONE VARCHAR2(6 CHAR) DEFAULT 'OLIMEN', 
	SCO_OLIO_MENZIONE VARCHAR2(6 CHAR), 
	COD_OLIO_TIPO_UTILIZZO VARCHAR2(6 CHAR) DEFAULT 'OLIUTI', 
	SCO_OLIO_TIPO_UTILIZZO VARCHAR2(6 CHAR), 
	CAPACITA_PRODUTTIVA_OLIO NUMBER(8,2), 
	COD_FORMA_ALLEVAMENTO VARCHAR2(6 CHAR) DEFAULT 'OLIALL', 
	SCO_FORMA_ALLEVAMENTO VARCHAR2(6 CHAR), 
	CUAA_OLIO VARCHAR2(16 CHAR), 
	ID_SOGGETTO NUMBER(11,0), 
	ID_PARTICELLA NUMBER(9,0) NOT NULL , 
	ID_PIANO_GCP NUMBER(11,0), 
	ID_POLIGONO_GCP NUMBER(11,0), 
	NOME_LOTTO_GCP VARCHAR2(250 BYTE), 
	ROT_GROUP NUMBER(11,0), 
	COD_CRIT_MANTENIMENTO VARCHAR2(6 CHAR), 
	SCO_CRIT_MANTENIMENTO VARCHAR2(6 CHAR), 
	COD_TIPO_SEMINA VARCHAR2(6 CHAR), 
	SCO_TIPO_SEMINA VARCHAR2(6 CHAR), 
	COD_EPOCA_SEMINA VARCHAR2(6 CHAR), 
	SCO_EPOCA_SEMINA VARCHAR2(6 CHAR), 
	ULTI_TURN_TAGL VARCHAR2(4 BYTE), 
	COD_FASE_ALLEVAMENTO VARCHAR2(6 CHAR), 
	SCO_FASE_ALLEVAMENTO VARCHAR2(6 CHAR));
	
-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE TPIANO_COLTURE 
 ADD CONSTRAINT PK_TPIANO_COLTURE PRIMARY KEY (PKID);
CREATE INDEX I1_PIANO_COLTURE ON TPIANO_COLTURE (COD_NAZIONALE, FOGLIO, PARTICELLA, SUB);
CREATE INDEX I2_PIANO_COLTURE ON TPIANO_COLTURE (ANNO, COD_NAZIONALE, FOGLIO, PARTICELLA, SUB);
CREATE INDEX I3_PIANO_COLTURE ON TPIANO_COLTURE (ID_PIANO_COLTURE);  
CREATE INDEX I4_PIANO_COLTURE ON TPIANO_COLTURE (ANNO, DT_DELETE);
CREATE INDEX I5_PIANO_COLTURE ON TPIANO_COLTURE (ANNO, ID_PARTICELLA);  
CREATE INDEX I6_PIANO_COLTURE ON TPIANO_COLTURE (ID_PARTICELLA);
CREATE INDEX I6_PIANO_COLTURE_COLT ON TPIANO_COLTURE (ID_COLTURA_1, DT_DELETE);
CREATE INDEX I7_PIANO_COLTURE ON TPIANO_COLTURE (ANNO, ID_SOGGETTO, COD_NAZIONALE, FOGLIO, PARTICELLA, SUB);
CREATE INDEX IDX_PIANO_COLTURE_PTANNO ON TPIANO_COLTURE (COD_NAZIONALE, FOGLIO, PARTICELLA, SUB, DT_FINE, ANNO, DT_DELETE);

-- Create table
CREATE TABLE TQDO_DU_ALLEVAMENTO_INTERVENTO (	
	PKID NUMBER(11,0) NOT NULL, 
	DT_INSERT DATE DEFAULT SYSDATE NOT NULL, 
	DT_DELETE DATE NOT NULL, 
	ID_SOGGETTO NUMBER(11,0) NOT NULL, 
	ID_UTE NUMBER(11,0), 
	ID_INTERVENTO NUMBER(11,0) NOT NULL, 
	ID_ALLEVAMENTO NUMBER(11,0) NOT NULL, 
	COD_FONTE_DATI VARCHAR2(6 BYTE) DEFAULT 'FONDAT' NOT NULL, 
	SCO_FONTE_DATI VARCHAR2(6 BYTE) NOT NULL, 
	DT_INIZIO DATE DEFAULT SYSDATE NOT NULL, 
	DT_FINE DATE NOT NULL, 
	FG_VALIDO_INIZIO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	FG_VALIDO_FINE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	ID_ATTO_INIZIO NUMBER(11,0), 
	ID_ATTO_FINE NUMBER(11,0), 
	DT_ULTIMO_AGG DATE DEFAULT SYSDATE NOT NULL, 
	UTENTE VARCHAR2(20 BYTE) DEFAULT 'ADMIN' NOT NULL, 
	ID_DOMANDA NUMBER(11,0));

-- Create table	
CREATE TABLE TCOLTURA_LANG (	
    ID_COLTURA NUMBER(11,0), 
	DE_COLTURA VARCHAR2(2000 CHAR), 
	CODUAGEA VARCHAR2(3 CHAR), 
	CODVAGEA VARCHAR2(3 CHAR), 
	COD_ELE VARCHAR2(4 CHAR), 
	COD_UTIL VARCHAR2(4 CHAR), 
	COD_VARI VARCHAR2(4 CHAR), 
	DT_INIZIO DATE DEFAULT SYSDATE, 
	DT_FINE DATE DEFAULT to_date('99991231','YYYYMMDD'), 
	DE_UAGEA VARCHAR2(2000 CHAR), 
	CODPAGEA VARCHAR2(3 CHAR), 
	DE_PAGEA VARCHAR2(2000 CHAR), 
	DE_VAGEA VARCHAR2(2000 CHAR), 
	ANNO_INIZIO NUMBER(4,0), 
	ANNO_FINE NUMBER(4,0), 
	COEFF_TARA NUMBER(11,2) DEFAULT 1, 
	LOCALE VARCHAR2(10 CHAR), 
	FG_SUCCESSIONE VARCHAR2(1 CHAR) DEFAULT 'N', 
	COD_FAM_BOTANICA VARCHAR2(20 CHAR), 
	COD_COLTURA VARCHAR2(2000 CHAR), 
	EXT_CODE VARCHAR2(20 CHAR));	

-- Create/Recreate primary, unique and foreign key constraints
ALTER TABLE TQDO_DU_ALLEVAMENTO_INTERVENTO ADD CONSTRAINT PKDU_ALLEVAMENTO_INTERVENTO PRIMARY KEY (PKID);
CREATE INDEX I1_ALLEVAMENTO_INTERVENTO ON TQDO_DU_ALLEVAMENTO_INTERVENTO (ID_SOGGETTO, ID_UTE, ID_INTERVENTO, ID_ALLEVAMENTO);  
CREATE UNIQUE INDEX IU_ALLEVAMENTO_INTERVENTO ON TQDO_DU_ALLEVAMENTO_INTERVENTO (ID_SOGGETTO, ID_INTERVENTO, ID_ALLEVAMENTO, DT_DELETE, ID_DOMANDA);

-- Create table
CREATE TABLE TALLEVAMENTO (
	PKID NUMBER(11,0) NOT NULL, 
	DT_INSERT DATE NOT NULL, 
	DT_DELETE DATE NOT NULL, 
	ID_SOGGETTO NUMBER(11,0) NOT NULL, 
	ID_UTE NUMBER(11,0), 
	ID_ALLEVAMENTO NUMBER(11,0) NOT NULL, 
	COD_ID_AZIENDALE VARCHAR2(16 BYTE), 
	COD_ID_BDN VARCHAR2(25 BYTE), 
	DE_ALLEVAMENTO VARCHAR2(50 BYTE), 
	COD_SPECIE VARCHAR2(6 BYTE) DEFAULT 'SPEALL' NOT NULL, 
	SCO_SPECIE VARCHAR2(6 BYTE) NOT NULL, 
	COD_PROD_ALLEV VARCHAR2(6 BYTE) DEFAULT 'PROALL' NOT NULL, 
	SCO_PROD_ALLEV VARCHAR2(6 BYTE), 
	COD_ASL VARCHAR2(6 BYTE) DEFAULT 'AZISAN' NOT NULL, 
	SCO_ASL VARCHAR2(6 BYTE), 
	ISTATP VARCHAR2(3 BYTE), 
	ISTATC VARCHAR2(3 BYTE), 
	COD_NAZIONALE VARCHAR2(4 BYTE), 
	FOGLIO NUMBER(4,0), 
	PARTICELLA VARCHAR2(5 BYTE), 
	SUB VARCHAR2(3 BYTE), 
	LOCALITA VARCHAR2(50 BYTE), 
	INDIRIZZO VARCHAR2(50 BYTE), 
	TELEFONO VARCHAR2(20 BYTE), 
	DT_CHIUSURA DATE, 
	FG_SOCCIDA VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	FG_AUT_LATTE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	FG_LIBRO_GEN VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	CAPI_TOTALI NUMBER(11,0), 
	DT_CALC_CAPI DATE, 
	CAPIENZA_CAPI NUMBER(15,4), 
	FG_PRESTITO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	FG_RURALE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	COD_FONTE_DATI VARCHAR2(6 BYTE) DEFAULT 'FONDAT' NOT NULL, 
	SCO_FONTE_DATI VARCHAR2(6 BYTE) NOT NULL, 
	DT_INIZIO DATE NOT NULL, 
	DT_FINE DATE NOT NULL, 
	FG_VALIDO_INIZIO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	FG_VALIDO_FINE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	ID_ATTO_INIZIO NUMBER(11,0), 
	ID_ATTO_FINE NUMBER(11,0), 
	DT_ULTIMO_AGG DATE DEFAULT SYSDATE NOT NULL, 
	UTENTE VARCHAR2(20 BYTE) DEFAULT 'ADMIN' NOT NULL, 
	COD_FISC_PROPR VARCHAR2(16 BYTE), 
	DENOM_PROPR VARCHAR2(2000 BYTE), 
	COD_FISC_DETENT VARCHAR2(16 BYTE), 
	DENOM_DETENT VARCHAR2(2000 BYTE), 
	NOTE VARCHAR2(4000 BYTE), 
	--SHAPE SDO_GEOMETRY, 
	ID_PARTICELLA NUMBER(11,0), 
	FG_MAIN NUMBER(1,0) DEFAULT 0);

-- Create/Recreate primary, unique and foreign key constraints
ALTER TABLE TALLEVAMENTO ADD CONSTRAINT PK_ALLEVAMENTO PRIMARY KEY (PKID);
CREATE INDEX I1_ALLEVAMENTO ON TALLEVAMENTO (ID_SOGGETTO, ID_UTE, ID_ALLEVAMENTO);
CREATE INDEX I2_ALLEVAMENTO ON TALLEVAMENTO (ID_ATTO_INIZIO);
CREATE UNIQUE INDEX IU_ALLEVAMENTO ON TALLEVAMENTO (ID_ALLEVAMENTO, DT_DELETE);

CREATE TABLE TPERSONA 
   (PKID NUMBER(11,0) NOT NULL, 
	DT_INSERT DATE NOT NULL, 
	DT_DELETE DATE NOT NULL, 
	ID_SOGGETTO NUMBER(11,0) NOT NULL, 
	ID_UTE NUMBER(11,0), 
	ID_PERSONA NUMBER(11,0) NOT NULL, 
	CODICE_FISCALE VARCHAR2(16 BYTE) NOT NULL, 
	COGNOME VARCHAR2(150 BYTE) NOT NULL, 
	NOME VARCHAR2(150 BYTE) NOT NULL, 
	SESSO VARCHAR2(1 BYTE) NOT NULL, 
	DT_NASCITA DATE, 
	DT_MORTE DATE, 
	COD_BELF_NASCITA VARCHAR2(4 BYTE), 
	COD_BELF_RESIDENZA VARCHAR2(4 BYTE), 
	LOCALITA_RESIDENZA VARCHAR2(50 BYTE), 
	CAP_RESIDENZA VARCHAR2(7 BYTE), 
	INDIRIZZO_RESIDENZA VARCHAR2(150 BYTE), 
	TELEFONO_RESIDENZA VARCHAR2(50 BYTE), 
	FAX_RESIDENZA VARCHAR2(50 BYTE), 
	CELLULARE_RESIDENZA VARCHAR2(50 BYTE), 
	EMAIL_RESIDENZA VARCHAR2(150 BYTE), 
	COD_BELF_DOMICILIO VARCHAR2(4 BYTE), 
	LOCALITA_DOMICILIO VARCHAR2(50 BYTE), 
	CAP_DOMICILIO VARCHAR2(7 BYTE), 
	INDIRIZZO_DOMICILIO VARCHAR2(150 BYTE), 
	TELEFONO_DOMICILIO VARCHAR2(50 BYTE), 
	FAX_DOMICILIO VARCHAR2(50 BYTE), 
	CELLULARE_DOMICILIO VARCHAR2(50 BYTE), 
	EMAIL_DOMICILIO VARCHAR2(150 BYTE), 
	COD_RUOLO VARCHAR2(6 BYTE) DEFAULT 'RUOPER' NOT NULL, 
	SCO_RUOLO VARCHAR2(6 BYTE) NOT NULL, 
	FG_RESPONSABILE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	COD_FONTE_DATI VARCHAR2(6 BYTE) DEFAULT 'FONDAT' NOT NULL, 
	SCO_FONTE_DATI VARCHAR2(6 BYTE) NOT NULL, 
	DT_INIZIO DATE NOT NULL, 
	DT_FINE DATE NOT NULL, 
	FG_VALIDO_INIZIO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	FG_VALIDO_FINE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL, 
	ID_ATTO_INIZIO NUMBER(11,0), 
	ID_ATTO_FINE NUMBER(11,0), 
	DT_ULTIMO_AGG DATE DEFAULT SYSDATE NOT NULL, 
	UTENTE VARCHAR2(20 BYTE) DEFAULT 'ADMIN' NOT NULL, 
	LOCALITA_NASCITA VARCHAR2(200 BYTE), 
	COD_SCOLARIZZAZIONE VARCHAR2(6 BYTE) DEFAULT 'SCLPER', 
	SCO_SCOLARIZZAZIONE VARCHAR2(6 BYTE), 
	FG_ACCESSO VARCHAR2(1 BYTE)
);	

CREATE TABLE SITICOMU_ISTAT (
	ISTATP VARCHAR2(3 BYTE) NOT NULL,
	ISTATC VARCHAR2(3 BYTE) NOT NULL,
	NOME VARCHAR2(35 BYTE) NOT NULL,
	DENO_PROV VARCHAR2(30 BYTE) NOT NULL,
	SIGLA_PROV VARCHAR2(2 BYTE) NOT NULL, 
	ISTATR VARCHAR2(2 BYTE) NOT NULL,
	CODI_FISC_LUNA VARCHAR2(4 BYTE) NOT NULL, 
	CAP VARCHAR2(5 BYTE), 
	USL NUMBER(11, 0), 
	ATTIVO CHAR(1 BYTE) DEFAULT 'Y',
	NOME_INT VARCHAR2(250 CHAR), 
	DENO_PROV_INT VARCHAR2(250 CHAR) 
);

CREATE TABLE SITICOMU (
	COD_NAZIONALE VARCHAR2(4 BYTE) NOT NULL,
	CODI_FISC_LUNA VARCHAR2(4 BYTE) NOT NULL,
	NOME_COMUNE VARCHAR2(250 CHAR)
);

-- Create table
create table TDOC_DEF_RIGA
(
  PKID               NUMBER(11) NOT NULL,
  DT_INSERT          DATE DEFAULT SYSDATE NOT NULL,
  DT_DELETE          DATE NOT NULL,
  COD_DOCUMENTO      VARCHAR2(100 CHAR) NOT NULL,
  ID_GRUPPO          VARCHAR2(100 CHAR) NOT NULL,
  ID_RIGA            VARCHAR2(100 CHAR) NOT NULL,
  ID_RIGA_PADRE      VARCHAR2(100 CHAR),
  COD_DESCRIZIONE    VARCHAR2(6 CHAR) NOT NULL,
  SCO_DESCRIZIONE    VARCHAR2(6 CHAR) NOT NULL,
  COD_TIPOLOGIA      VARCHAR2(6 CHAR) DEFAULT 'TIPRIG' NOT NULL,
  SCO_TIPOLOGIA      VARCHAR2(6 CHAR),
  COD_UNITA_MISURA   VARCHAR2(6 CHAR) DEFAULT 'UNIMIS' NOT NULL,
  SCO_UNITA_MISURA   VARCHAR2(6 CHAR),
  FG_EDITABILE       VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  FUNZIONE_AUTH_EDIT VARCHAR2(100 CHAR),
  FUNZIONE_AUTH_VIS  VARCHAR2(100 CHAR),
  FG_OBBLIGATORIO    VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  ORDINE             NUMBER(11),
  FG_PREVAL          VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  VAL_DEFAULT        VARCHAR2(2000 CHAR),
  COD_COMBO          VARCHAR2(6 CHAR),
  ID_LOOKUP          VARCHAR2(50 CHAR),
  COD_LOOKUP         VARCHAR2(6 CHAR) DEFAULT 'LOOKUP' NOT NULL,
  SCO_LOOKUP         VARCHAR2(6 CHAR),
  DT_INIZIO          DATE DEFAULT SYSDATE NOT NULL,
  DT_FINE            DATE NOT NULL,
  FG_VALIDO_INIZIO   VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  FG_VALIDO_FINE     VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  ID_ATTO_INIZIO     NUMBER(11),
  ID_ATTO_FINE       NUMBER(11),
  DT_ULTIMO_AGG      DATE DEFAULT SYSDATE NOT NULL,
  UTENTE             VARCHAR2(20 CHAR) NOT NULL
);	

-- Create table
create table TDOC_DOCUMENTO
(
  PKID             NUMBER(11) NOT NULL,
  DT_INSERT        DATE DEFAULT SYSDATE NOT NULL,
  DT_DELETE        DATE NOT NULL,
  ID_SOGGETTO      NUMBER(11) NOT NULL,
  ID_UTE           NUMBER(11),
  COD_DOCUMENTO    VARCHAR2(100 CHAR) NOT NULL,
  ANNO             NUMBER(4),
  ID_DOCUMENTO     NUMBER(11) NOT NULL,
  NOTE             VARCHAR2(2000 CHAR),
  COD_FONTE_DATI   VARCHAR2(6 CHAR) DEFAULT 'FONDAT' NOT NULL,
  SCO_FONTE_DATI   VARCHAR2(6 CHAR) NOT NULL,
  DT_INIZIO        DATE DEFAULT SYSDATE NOT NULL,
  DT_FINE          DATE NOT NULL,
  FG_VALIDO_INIZIO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  FG_VALIDO_FINE   VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  ID_ATTO_INIZIO   NUMBER(11),
  ID_ATTO_FINE     NUMBER(11),
  DT_ULTIMO_AGG    DATE DEFAULT SYSDATE NOT NULL,
  UTENTE           VARCHAR2(20 CHAR) NOT NULL,
  ID_DOMANDA       NUMBER(11)
);

-- Create table
create table TDOC_DOCUMENTO_RIGA
(
  PKID             NUMBER(11) NOT NULL,
  DT_INSERT        DATE DEFAULT SYSDATE NOT NULL,
  DT_DELETE        DATE NOT NULL,
  ID_SOGGETTO      NUMBER(11),
  ID_DOCUMENTO     NUMBER(11) NOT NULL,
  ID_RIGA          VARCHAR2(100 CHAR) NOT NULL,
  COD_DESCRIZIONE  VARCHAR2(6 CHAR) NOT NULL,
  SCO_DESCRIZIONE  VARCHAR2(6 CHAR) NOT NULL,
  VAL_CHECK        VARCHAR2(1 CHAR),
  VAL_TESTO        VARCHAR2(2000 CHAR),
  VAL_NUM          NUMBER(15,4),
  VAL_DATA         DATE,
  COD_COMBO        VARCHAR2(6 CHAR),
  SCO_COMBO        VARCHAR2(6 CHAR),
  COD_FONTE_DATI   VARCHAR2(6 CHAR) DEFAULT 'FONDAT' NOT NULL,
  SCO_FONTE_DATI   VARCHAR2(6 CHAR) NOT NULL,
  DT_INIZIO        DATE DEFAULT SYSDATE NOT NULL,
  DT_FINE          DATE NOT NULL,
  FG_VALIDO_INIZIO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  FG_VALIDO_FINE   VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  ID_ATTO_INIZIO   NUMBER(11),
  ID_ATTO_FINE     NUMBER(11),
  DT_ULTIMO_AGG    DATE DEFAULT SYSDATE NOT NULL,
  UTENTE           VARCHAR2(20 CHAR) NOT NULL
);

create table TDU_DEF_PASCOLO
(
  PKID             NUMBER(11) NOT NULL,
  DT_INSERT        DATE DEFAULT SYSDATE NOT NULL,
  DT_DELETE        DATE NOT NULL,
  COD_PASCOLO      VARCHAR2(20) NOT NULL,
  DENOMINAZIONE    VARCHAR2(2000) NOT NULL,
  COD_FONTE_DATI   VARCHAR2(6) DEFAULT 'FONDAT' NOT NULL,
  SCO_FONTE_DATI   VARCHAR2(6) NOT NULL,
  DT_INIZIO        DATE DEFAULT SYSDATE NOT NULL,
  DT_FINE          DATE NOT NULL,
  FG_VALIDO_INIZIO VARCHAR2(1) DEFAULT 'N' NOT NULL,
  FG_VALIDO_FINE   VARCHAR2(1) DEFAULT 'N' NOT NULL,
  ID_ATTO_INIZIO   NUMBER(11),
  ID_ATTO_FINE     NUMBER(11),
  DT_ULTIMO_AGG    DATE DEFAULT SYSDATE NOT NULL,
  UTENTE           VARCHAR2(20) DEFAULT 'ADMIN' NOT NULL
);

-- Create table
create table TQDO_DU_PASCOLO
(
  PKID             NUMBER(11) NOT NULL,
  DT_INSERT        DATE DEFAULT SYSDATE NOT NULL,
  DT_DELETE        DATE NOT NULL,
  ID_SOGGETTO      NUMBER(11) NOT NULL,
  ID_UTE           NUMBER(11),
  ID_DOMANDA       NUMBER(11) NOT NULL,
  COD_PASCOLO      VARCHAR2(20) NOT NULL,
  NOTE             VARCHAR2(4000),
  COD_FONTE_DATI   VARCHAR2(6) DEFAULT 'FONDAT' NOT NULL,
  SCO_FONTE_DATI   VARCHAR2(6) NOT NULL,
  DT_INIZIO        DATE DEFAULT SYSDATE NOT NULL,
  DT_FINE          DATE NOT NULL,
  FG_VALIDO_INIZIO VARCHAR2(1) DEFAULT 'N' NOT NULL,
  FG_VALIDO_FINE   VARCHAR2(1) DEFAULT 'N' NOT NULL,
  ID_ATTO_INIZIO   NUMBER(11),
  ID_ATTO_FINE     NUMBER(11),
  DT_ULTIMO_AGG    DATE DEFAULT SYSDATE NOT NULL,
  UTENTE           VARCHAR2(20) DEFAULT 'ADMIN' NOT NULL,
  UBA              NUMBER(13,2)
);

-- Create table
create table TQDO_DU_PASCOLO_PARTICELLA
(
  PKID             NUMBER(11) NOT NULL,
  DT_INSERT        DATE DEFAULT SYSDATE NOT NULL,
  DT_DELETE        DATE NOT NULL,
  ID_SOGGETTO      NUMBER(11) NOT NULL,
  ID_UTE           NUMBER(11),
  ID_DOMANDA       NUMBER(11) NOT NULL,
  COD_PASCOLO      VARCHAR2(20) NOT NULL,
  COD_NAZIONALE    VARCHAR2(4),
  FOGLIO           NUMBER(4),
  PARTICELLA       VARCHAR2(5),
  SUB              VARCHAR2(3),
  COD_FONTE_DATI   VARCHAR2(6) DEFAULT 'FONDAT' NOT NULL,
  SCO_FONTE_DATI   VARCHAR2(6) NOT NULL,
  DT_INIZIO        DATE DEFAULT SYSDATE NOT NULL,
  DT_FINE          DATE NOT NULL,
  FG_VALIDO_INIZIO VARCHAR2(1) DEFAULT 'N' NOT NULL,
  FG_VALIDO_FINE   VARCHAR2(1) DEFAULT 'N' NOT NULL,
  ID_ATTO_INIZIO   NUMBER(11),
  ID_ATTO_FINE     NUMBER(11),
  DT_ULTIMO_AGG    DATE DEFAULT SYSDATE NOT NULL,
  UTENTE           VARCHAR2(20) DEFAULT 'ADMIN' NOT NULL
);

-- Create table
CREATE TABLE COLTURE_CODICI_3_5 
   (ID_COLTURA NUMBER(11,0) NOT NULL, 
	DE_COLTURA VARCHAR2(2000 CHAR), 
	CODUAGEA VARCHAR2(3 CHAR), 
	CODPAGEA VARCHAR2(3 CHAR), 
	CODVAGEA VARCHAR2(3 CHAR), 
	COEFF_TARA NUMBER(11,2) NOT NULL, 
	ANNO NUMBER, 
	CODI_PROD VARCHAR2(3 BYTE), 
	CODI_DEST_USO VARCHAR2(3 BYTE), 
	CODI_USO VARCHAR2(3 BYTE), 
	CODI_QUAL VARCHAR2(3 BYTE), 
	CODI_LIVE VARCHAR2(10 BYTE), 
	CODI_VARI VARCHAR2(3 BYTE) );
	
CREATE TABLE TCLC_DEF_CALCOLO 
   (ID_DEF_CALCOLO NUMBER(11,0), 
	DS_CALCOLO VARCHAR2(50 BYTE), 
	COD_CALCOLO VARCHAR2(200 CHAR), 
	 CONSTRAINT TCLC_DEF_CALCOLO_PK PRIMARY KEY (ID_DEF_CALCOLO)
	);

 CREATE TABLE TCLC_REGISTRO
   (ID_CALCOLO NUMBER(11,0) NOT NULL, 
	COD_OGGETTO VARCHAR2(6 BYTE) DEFAULT 'OGGFAS' NOT NULL, 
	SCO_OGGETTO VARCHAR2(6 BYTE) NOT NULL, 
	ID_DEF_CALCOLO NUMBER(11,0), 
	DT_CALCOLO DATE DEFAULT SYSDATE NOT NULL, 
	PARAMETRI VARCHAR2(4000 BYTE), 
	UTENTE VARCHAR2(20 BYTE) NOT NULL, 
	 CONSTRAINT PK_CLC_REGISTRO PRIMARY KEY (ID_CALCOLO)
	);
	
CREATE TABLE VCLC_REGISTRO_PARAMS 
   (ID_CALCOLO NUMBER(11,0), 
	NOME   VARCHAR2(50 BYTE), 
	VALORE VARCHAR2(200 CHAR)
	);

CREATE TABLE VCLC_RISULTATO_CALCOLO
	(ID_DOMANDA	NUMBER,
	ID_CALCOLO	NUMBER(11),
	DT_CALCOLO	DATE,
	TIPO_CALCOLO	VARCHAR2(2000 CHAR),
	VARIABILE	VARCHAR2(20),
	DS_VARIABILE	VARCHAR2(100),
	VALORE	VARCHAR2(4000),
	VALORE_CHAR	VARCHAR2(4000),
	ORDINE	NUMBER(11),
	COD_GRUPPO	VARCHAR2(200 CHAR),
	FG_TOTALE	VARCHAR2(1)
	);

 -- Tabelle utenti AGS
CREATE TABLE SSO_USERS
(	
	USERID VARCHAR2(100 BYTE) NOT NULL, 
	PASSWORD VARCHAR2(32 BYTE) NOT NULL, 
	DESCR VARCHAR2(100 BYTE), 
	IS_LOCKED CHAR(1 BYTE) DEFAULT 'N' NOT NULL, 
	CREATED_ON DATE DEFAULT sysdate NOT NULL, 
	PASSWORD_LAST_MODIFIED_ON DATE DEFAULT sysdate NOT NULL, 
	USR_LOCALE VARCHAR2(20 BYTE) DEFAULT 'it' NOT NULL, 
	DATE_FORMAT VARCHAR2(10 BYTE) DEFAULT 'dd/MM/yyyy' NOT NULL, 
	FL_INTERNAL CHAR(1 BYTE) DEFAULT 'Y' NOT NULL, 
	PARENT_USERID VARCHAR2(100 BYTE), 
	IS_PARENT NUMBER(1,0) DEFAULT 0 NOT NULL
);
  
-- Create table  
CREATE TABLE SSO_USERS_PROPERTIES 
(	
	NAME VARCHAR2(256 BYTE) NOT NULL, 
	CONTENT VARCHAR2(4000 BYTE), 
	USERID VARCHAR2(100 BYTE) NOT NULL, 
	SKIP_AGG_GU NUMBER
 );

-- Create table
CREATE TABLE TPAGA_CONTROLLI_SIGECO 
(	
	ID_DOMANDA NUMBER(8,0), 
	CUAA VARCHAR2(16 BYTE), 
	ID_PARTICELLA NUMBER(11,0), 
	COD_NAZIONALE VARCHAR2(10 BYTE), 
	FOGLIO NUMBER(4,0), 
	PARTICELLA VARCHAR2(20 BYTE), 
	SUBALTERNO VARCHAR2(20 BYTE), 
	COD_COLTURA VARCHAR2(50 BYTE), 
	FG_SUPE_AMMI NUMBER, 
	DT_AGGIORNAMENTO DATE, 
	CAMPAGNA NUMBER(4,0), 
	COD_INTERVENTO VARCHAR2(200 CHAR), 
	DESC_INTERVENTO VARCHAR2(200 CHAR), 
	ID_ROW NUMBER, 
	DT_INIZIO DATE, 
	DT_FINE DATE
   );   
   
CREATE TABLE TPAGA_ESITI_ANTIMAFIA
(
   CUAA varchar2(16),
   ID_DOMANDA NUMBER(11,0),
   TIPO_DOMANDA NUMBER(1,0),
   DATA_INIZIO_SILENZIO_ASSENZO DATE,
   DATA_FINE_SILENZIO_ASSENZO DATE,
   DATA_INIZIO_ESITO_NEGATIVO DATE,
   DATA_FINE_ESITO_NEGATIVO DATE
);
CREATE UNIQUE INDEX TPAGA_ESITI_ANTIMAFIA_U01 ON TPAGA_ESITI_ANTIMAFIA(CUAA,ID_DOMANDA);
   
CREATE TABLE TMAPPING_INTERVENTI_AGEA_AGS (
	ID_INTERVENTO_AGEA VARCHAR2(3) NOT NULL,
	COD_INTERVENTO_AGEA VARCHAR2(50),
	ID_INTERVENTO_AGS NUMBER(3) NOT NULL,
	COD_INTERVENTO_AGS VARCHAR2(50),
	SETTORE VARCHAR2(11) NOT NULL
);

-- TABELLE SCHEMA SITI
set schema SITI;
 
-- Create table
create table CONS_CUAA_ENTE
(
  pk_cuaa           NUMBER(9) not null,
  data_inizio       DATE default SYSDATE,
  data_fine         DATE default TO_DATE('99991231000000','YYYYMMDDHH24MISS'),
  cod_ente          NUMBER(9) not null,
  data_richiesta    DATE default SYSDATE,
  id_atto_inizio    NUMBER(9),
  id_atto_fine      NUMBER(9),
  id_associazione   NUMBER(11) default 1 not null,
  tipo_associazione VARCHAR2(10) default 'MAN' not null,
  flag_gestione     VARCHAR2(1) default 'S' not null,
  note              VARCHAR2(2000),
  detentore         VARCHAR2(9),
  fl_detentore      NUMBER(1) default 1 not null
);

-- Create/Recreate indexes 
create unique index CONS_CUAA_ENTE_UDX1 on CONS_CUAA_ENTE (PK_CUAA, COD_ENTE, DATA_FINE);
create index CONS_CUAA_ENTE_UDX2 on CONS_CUAA_ENTE (COD_ENTE, TIPO_ASSOCIAZIONE);
create index CONS_CUAA_ENTE_UDX3 on CONS_CUAA_ENTE (COD_ENTE, ID_ASSOCIAZIONE);
-- Create/Recreate primary, unique and foreign key constraints 
alter table CONS_CUAA_ENTE
  add constraint PK_CONS_CUAA_ENTE primary key (ID_ASSOCIAZIONE);

-- Create table
create table SITIENTE
(
  cod_ente           NUMBER(9) not null,
  des_ente           VARCHAR2(150),
  data_inizio        DATE default sysdate,
  data_fine          DATE default To_Date('99991231','YYYYMMDD'),
  indirizzo          VARCHAR2(50),
  cap                VARCHAR2(5),
  provincia          VARCHAR2(2),
  comune             VARCHAR2(60),
  telefono           VARCHAR2(20),
  e_mail             VARCHAR2(100),
  fax                VARCHAR2(20),
  tipoente           VARCHAR2(10),
  cod_fiscale        VARCHAR2(16),
  cod_ente_sup       NUMBER(9),
  codi_tram          VARCHAR2(20) not null,
  utente             VARCHAR2(20),
  data_aggiornamento DATE
);

-- Create/Recreate indexes 
create index I1_SITIENTE on SITIENTE (COD_ENTE, COD_ENTE_SUP);
create index I2_SITIENTE on SITIENTE (TIPOENTE);
create index SITIENTE_IX1 on SITIENTE (DATA_AGGIORNAMENTO);
create unique index SITIENTE_UK1 on SITIENTE (CODI_TRAM);
-- Create/Recreate primary, unique and foreign key constraints 
alter table SITIENTE
  add constraint SITIENTE_PK primary key (COD_ENTE);

-- Create table
create table SITIFILE_DOCUMENTI_CAMPI_EXT
(
	FKID_DOC	NUMBER(38,0),
	CHK211_1	VARCHAR2(1 BYTE),
	CHK211_2	VARCHAR2(1 BYTE),
	CHK211_3	VARCHAR2(1 BYTE),
	CHK211_4	VARCHAR2(1 BYTE),
	PKID_PK		NUMBER	not null
);

alter table SITIFILE_DOCUMENTI_CAMPI_EXT
  add constraint SITIFILE_DOCUMENTI_CAMPI_EXTPK primary key (PKID_PK);

-- Create table
create table SITIFILE_ATTI_DOC
(
	FKID_ATTO			NUMBER(9,0) not null,
	FKID_DOC			NUMBER(9,0) not null,
	NOTE				VARCHAR2(4000 BYTE),
	UTENTE_INS			VARCHAR2(100 BYTE),
	DATA_AGGIORNAMENTO	DATE not null,
	UTENTE_FINE			VARCHAR2(100 BYTE),
	DATA_INIZIO_VAL		DATE not null,
	DATA_FINE_VAL		DATE not null
	
);
 
alter table SITIFILE_ATTI_DOC
  add constraint SITIFILE_ATTI_DOC_PK primary key (FKID_ATTO, FKID_DOC);

-- Create table
create table SITIFILE_DOCUMENTI
(
	PKID_DOC			NUMBER(9,0)	not null,	
	FKID_TIPO_DOC		NUMBER(9,0)	not null,	
	DESCRIZIONE_BREVE	VARCHAR2(100 BYTE),	
	DATA_LAV			DATE default sysdate,
	DATA_SCADENZA		DATE default TO_DATE('99991231', 'YYYYMMDD'),
	COD_ARCHIVIAZIONE	VARCHAR2(50 BYTE),	
	UTENTE_INS			VARCHAR2(100 BYTE),	
	DATA_AGGIORNAMENTO	DATE default sysdate,
	DESCRIZIONE_ESTESA	VARCHAR2(1000 BYTE),	
	VALIDO				CHAR(1 BYTE) default 'N',
	CHAIN_ID			NUMBER(9,0)	not null,	
	DATA_INIZIO_VAL		DATE not null,	
	DATA_FINE_VAL		DATE not null default to_date('99991231', 'yyyymmdd'), 
	UTENTE_FIN			VARCHAR2(100 BYTE),	
	LOCKED_BY			VARCHAR2(20 BYTE),	
	LOCK_DATE			DATE,	
	PK_CUAA				NUMBER,	
	OVL_ID				NUMBER(9,0)		
);

alter table SITIFILE_DOCUMENTI
  add constraint PK_SITIFILE_DOCUMENTI primary key (PKID_DOC);
  
-- Create table
create table SITIFILE_TIPIDOC
(
	PKID_TIPO_DOC				NUMBER(9,0) not null,	
	DESCRIZIONE					VARCHAR2(500 BYTE),	
	DATA_AGGIORNAMENTO			DATE default sysdate,
	FILE_RICHIESTO				CHAR(1 BYTE) not null default 'N', 
	URL_ESTERNO					VARCHAR2(100 BYTE),	
	EDITABILE					CHAR(1 BYTE) default 'Y',
	SYSTEM						CHAR(1 BYTE) not null default'N', 
	HAS_DESCRIZIONE_BREVE		CHAR(1 BYTE) not null default 'Y', 
	HAS_DESCRIZIONE_ESTESA		CHAR(1 BYTE) not null default 'Y', 
	HAS_COD_ARCHIVIAZIONE		CHAR(1 BYTE) not null default 'Y', 
	LEFT_COLUMN_PCT				NUMBER(2,0) default 30,
	RIGHT_COLUMN_PCT			NUMBER(2,0)	default 70,
	HAS_DATA_SCADENZA			CHAR(1 BYTE) not null default 'N', 
	HAS_COD_SOGGETTO			CHAR(1 BYTE) not null default 'Y', 
	DESCR_BREVE_REQUIRED		CHAR(1 BYTE) not null default 'Y',
	DESCR_ESTESA_REQUIRED		CHAR(1 BYTE) not null default 'N', 
	COD_ARCHIVIAZIONE_REQUIRED	CHAR(1 BYTE) not null default 'Y', 
	DATA_SCADENZA_REQUIRED		CHAR(1 BYTE) not null default 'Y', 
	CODICE						VARCHAR2(100 BYTE),
	FIELDS_TABLE_NAME			VARCHAR2(25 BYTE),	
	ACL_ENABLED					CHAR(1 BYTE) not null default 'N' 
);

alter table SITIFILE_TIPIDOC
  add constraint PK_SITIFILE_TIPIDOC primary key (PKID_TIPO_DOC);  

-- Create table  
CREATE TABLE T_DU_UTILIZZO_GIS 
(	
	ID_DOMANDA NUMBER(11,0), 
	CUAA VARCHAR2(16 BYTE), 
	COD_SETTORE VARCHAR2(9 BYTE), 
	ANNO_RIFERIMENTO NUMBER(4,0), 
	ID_PARTICELLA NUMBER(11,0), 
	ATTIVITA_UTILIZZO VARCHAR2(3 BYTE), 
	VERSIONE_UTILIZZO NUMBER(11,0), 
	ATTIVITA_PREMIO_PARTIC VARCHAR2(3 BYTE), 
	VERSIONE_PREMIO_PARTIC NUMBER(11,0), 
	PROG_RIGA NUMBER(11,0), 
	COD_COLTURA VARCHAR2(20 BYTE), 
	COD_VARIETA VARCHAR2(3 BYTE), 
	COD_UTILIZZO VARCHAR2(3 BYTE), 
	SUPERFICIE_UTILIZZ NUMBER(9,4), 
	COD_PREMIO NUMBER(3,0), 
	CODICE_INTERVENTO VARCHAR2(9 BYTE), 
	SUB_INTERVENTO VARCHAR2(2 BYTE), 
	CODICE_PRODOTTO VARCHAR2(3 BYTE), 
	CODICE_VARIETA VARCHAR2(3 BYTE), 
	DATA_PROTOCOLLO DATE, 
	COD_POSSESSO VARCHAR2(3 BYTE), 
	SCO_POSSESSO VARCHAR2(3 BYTE), 
	FG_P15 NUMBER(1,0), 
	FG_P16 NUMBER(1,0), 
	FG_P30 NUMBER(1,0), 
	FG_P36 NUMBER(1,0), 
	FG_P26 NUMBER(1,0), 
	FG_SUPE_AMMI NUMBER(9,4), 
	CONTROLLO_LOCO NUMBER(1,0) DEFAULT 0, 
	ID_ROW NUMBER(11,0), 
	CASO_PARTICOLARE VARCHAR2(3 BYTE), 
	COD_NAZIONALE VARCHAR2(4 BYTE), 
	FOGLIO NUMBER(4,0), 
	PARTICELLA VARCHAR2(5 BYTE), 
	SUB VARCHAR2(3 BYTE), 
	DATA_ULTIMO_RICALCOLO DATE, 
	DATA_CONTROLLO_GIS DATE, 
	DATA_INIZIO_IMP DATE, 
	DATA_FINE_IMP DATE, 
	NUM_PIANTE NUMBER(6,0), 
	SUPERFICIE_PC NUMBER(9,4), 
	FG_NOSEMI NUMBER, 
	CODI_PROV VARCHAR2(3 BYTE), 
	CODI_COMU VARCHAR2(3 BYTE), 
	SEZIONE VARCHAR2(1 BYTE), 
	NUM_FOGLIO VARCHAR2(4 BYTE), 
	NUM_PARTICELLA VARCHAR2(5 BYTE), 
	SUBALTERNO VARCHAR2(3 BYTE), 
	SUPERFICIE_CATA NUMBER(9,4), 
	FG_P36_10_PERC NUMBER(1,0), 
	FG_P15_PRE NUMBER(1,0), 
	FG_P16_PRE NUMBER(1,0), 
	FG_P30_PRE NUMBER(1,0), 
	FG_P36_PRE NUMBER(1,0), 
	FG_P26_PRE NUMBER(1,0), 
	FG_SUPE_AMMI_PRE NUMBER(9,4), 
	FG_TARA NUMBER(1,0), 
	FG_P18 NUMBER(1,0), 
	SUPERFICIE_COLTIVATA NUMBER(10,0), 
	ID_ILO NUMBER(9,0), 
	FG_I15 NUMBER(1,0), 
	FG_SUPE_AMMI_ILO NUMBER(9,4), 
	FG_I36 NUMBER(1,0), 
	SUPE_ILO NUMBER(11,2), 
	ID_PARTICELLA_ORIG NUMBER(11,0),
	FG_AN_COOR NUMBER(11,0)
   ); 
   
-- RESET allo schema default di H2
set schema PUBLIC;

-- CATASTO
CREATE TABLE TCAT_PIANI_COLTURE_2018
(	
	CODICE_FISCALE VARCHAR2(16 BYTE), 
	CAT_COMUNE_CO NUMBER(3,0), 
	CAT_COMUNE_DS VARCHAR2(250 BYTE), 
	COD_NAZIONALE VARCHAR2(4 BYTE), 
	SEZIONE VARCHAR2(1 BYTE), 
	COMUNE VARCHAR2(250 BYTE), 
	FOGLIO NUMBER(4,0), 
	PARTICELLA VARCHAR2(5 BYTE), 
	SUB VARCHAR2(3 BYTE), 
	TITOLO_POS_DE VARCHAR2(30 BYTE), 
	PERC_POSSESSO NUMBER(5,2), 
	DATA_INIZIO_COND DATE, 
	DATA_FINE_COND DATE, 
	SUP_GIS NUMBER(10,0), 
	COD_UTILIZZO VARCHAR2(3 BYTE), 
	COD_COLTURA VARCHAR2(3 BYTE), 
	COD_VARIETA VARCHAR2(3 BYTE), 
	DE_COLTURA VARCHAR2(2000 BYTE), 
	SUP_DICHIARATA NUMBER(10,0), 
	TIPO_DOCUMENTO NUMBER(9,0), 
	SCADENZA_DOC_DT DATE, 
	ID_PARTICELLA NUMBER(11,0), 
	PROTOCOLLO_DOC VARCHAR2(50 BYTE),
	NRO_ANOMALIE NUMBER(1,0),
	NRO_ANOMALIE_GIS NUMBER(1,0)
);

CREATE TABLE A4G_DU_PROTOCOLLATE (
	PKID NUMBER(11) NOT NULL,
	CUAA VARCHAR2(16) NOT NULL,
	ID_DOMANDA NUMBER(11) NOT NULL,
	ANNO NUMBER(4),
	COD_MODULO VARCHAR2(50) NOT NULL,
	DS_MODULO VARCHAR2(2000 CHAR)
);

CREATE TABLE A4GT_CONF_RICEVIBILITA (
   ID NUMBER(19) NOT NULL,
   VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
   ANNO_CAMPAGNA NUMBER(4) NOT NULL,
   DATA_RICEVIBILITA DATE NOT NULL,
   SCADENZA_DOM_INIZIALE_RITARDO DATE NOT NULL,
   SCADENZA_DOMANDA_RITIROPARZIAL DATE NOT NULL,
   SCADENZA_DOM_MODIFICA_RITARDO DATE,
);