-- Inserisco i CAA
INSERT INTO A4GT_CAA (ID,VERSIONE,CODICE_FISCALE,DENOMINAZIONE,PARTITA_IVA,FORMA_GIURIDICA,ATTO_RICONOSCIMENTO,SOCIETA_SERVIZI,CF_SOCIETA_SERVIZI,DESCRIZIONE_ESTESA,CODICE_ISTAT,FRAZIONE,TOPONIMO,VIA,NUMERO_CIVICO,CAP,PROVINCIA,COMUNE)
VALUES (1,0,'01896970223','CAA COOPTRENTO SRL','01896970223','SOCIETA A RESPONSABILITA LIMITATA','determinazione del Dirigente del Servizio Vigilanza e Promozione delle Attività Agricole n. 282 del 23 agosto 2011',NULL,NULL,NULL,NULL,NULL,'VIA BRENNERO 322','VIA BRENNERO','322','38121','TN','TRENTO');

-- Inserisco gli sportelli
INSERT INTO A4GT_SPORTELLO (ID,VERSIONE,IDENTIFICATIVO,DENOMINAZIONE,COMUNE,ID_CAA) VALUES (1,0,89,'CAA COOPTN - CS - ALA','ALA',1);
INSERT INTO A4GT_SPORTELLO (ID,VERSIONE,IDENTIFICATIVO,DENOMINAZIONE,COMUNE,ID_CAA) VALUES (2,0,90,'CAA COOPTN - CS - ALDENO','ALDENO',1);
INSERT INTO A4GT_SPORTELLO (ID,VERSIONE,IDENTIFICATIVO,DENOMINAZIONE,COMUNE,ID_CAA) VALUES (3,0,91,'CAA COOPTN - CS - AVIO','AVIO',1);
INSERT INTO A4GT_SPORTELLO (ID,VERSIONE,IDENTIFICATIVO,DENOMINAZIONE,COMUNE,ID_CAA) VALUES (4,0,92,'CAA COOPTN - CS - GROPPELLO','REVO`',1);
INSERT INTO A4GT_SPORTELLO (ID,VERSIONE,IDENTIFICATIVO,DENOMINAZIONE,COMUNE,ID_CAA) VALUES (5,0,93,'CAA COOPTN - CS - LAVIS','LAVIS',1);

--00123890220
INSERT INTO A4GT_PERSONA (ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(50, 0, 0, '00123890220');

INSERT INTO A4GT_PERSONA_GIURIDICA
(ID, ID_VALIDAZIONE, VERSIONE, PARTITA_IVA, DENOMINAZIONE, FORMA_GIURIDICA, OGGETTO_SOCIALE, DATA_COSTITUZIONE, DATA_TERMINE, CAPITALE_SOCIALE_DELIBERATO, CF_RAPPRESENTANTE_LEGALE, NOME_RAPPRESENTANTE_LEGALE, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_FRAZIONE, SEDE_PROVINCIA, SEDE_COMUNE)
VALUES(50, 0, 0, '00123890220', 'denominazione', '', '', NULL , NULL , 0, 'MRTLNZ72M30L378I', 'Lorenzo Martinelli', NULL , '', 0, 0, '', '', '', '', '', '', '', '', '');

INSERT INTO A4GT_FASCICOLO(ID, VERSIONE, CUAA, STATO, DENOMINAZIONE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, ORGANISMO_PAGATORE, DATA_MODIFICA, UTENTE_MODIFICA)
VALUES(11, 0 , '00123890220', 'IN_AGGIORNAMENTO', 'denominazione', 50, 0, 'APPAG', to_date('01-01-2020', 'dd-mm-yyyy'), 'Utente Test');

--00123890000
INSERT INTO A4GT_PERSONA (ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(51, 0, 0, '00123890000');

INSERT INTO A4GT_PERSONA_GIURIDICA
(ID, ID_VALIDAZIONE, VERSIONE, PARTITA_IVA, DENOMINAZIONE, FORMA_GIURIDICA, OGGETTO_SOCIALE, DATA_COSTITUZIONE, DATA_TERMINE, CAPITALE_SOCIALE_DELIBERATO, CF_RAPPRESENTANTE_LEGALE, NOME_RAPPRESENTANTE_LEGALE, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_FRAZIONE, SEDE_PROVINCIA, SEDE_COMUNE)
VALUES(51, 0, 0, '00123890000', 'denominazione', '', '', NULL , NULL , 0, 'MRTLNZ72M30L378I', 'Lorenzo Martinelli', NULL , '', 0, 0, '', '', '', '', '', '', '', '', '');

INSERT INTO A4GT_FASCICOLO(ID, VERSIONE, CUAA, STATO, DENOMINAZIONE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, ORGANISMO_PAGATORE, DATA_MODIFICA, UTENTE_MODIFICA)
VALUES(12, 0 , '00123890000', 'IN_AGGIORNAMENTO', 'denominazione', 51, 0, 'APPAG', to_date('01-01-2020', 'dd-mm-yyyy'), 'Utente Test');

--00123890111
INSERT INTO A4GT_PERSONA (ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(52, 0, 0, '00123890111');

INSERT INTO A4GT_PERSONA_GIURIDICA
(ID, ID_VALIDAZIONE, VERSIONE, PARTITA_IVA, DENOMINAZIONE, FORMA_GIURIDICA, OGGETTO_SOCIALE, DATA_COSTITUZIONE, DATA_TERMINE, CAPITALE_SOCIALE_DELIBERATO, CF_RAPPRESENTANTE_LEGALE, NOME_RAPPRESENTANTE_LEGALE, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_FRAZIONE, SEDE_PROVINCIA, SEDE_COMUNE)
VALUES(52, 0, 0, '00123890111', 'denominazione', '', '', NULL , NULL , 0, 'MRTLNZ72M30L378I', 'Lorenzo Martinelli', NULL , '', 0, 0, '', '', '', '', '', '', '', '', '');

INSERT INTO A4GT_FASCICOLO(ID, VERSIONE, CUAA, STATO, DENOMINAZIONE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, ORGANISMO_PAGATORE, DATA_MODIFICA, UTENTE_MODIFICA)
VALUES(13, 0 , '00123890111', 'CHIUSO', 'denominazione', 52, 0, 'APPAG', to_date('01-01-2020', 'dd-mm-yyyy'), 'Utente Test');

--00123890001
INSERT INTO A4GT_PERSONA (ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(53, 0, 0, '00123890001');

INSERT INTO A4GT_PERSONA_GIURIDICA
(ID, ID_VALIDAZIONE, VERSIONE, PARTITA_IVA, DENOMINAZIONE, FORMA_GIURIDICA, OGGETTO_SOCIALE, DATA_COSTITUZIONE, DATA_TERMINE, CAPITALE_SOCIALE_DELIBERATO, CF_RAPPRESENTANTE_LEGALE, NOME_RAPPRESENTANTE_LEGALE, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_FRAZIONE, SEDE_PROVINCIA, SEDE_COMUNE)
VALUES(53, 0, 0, '00123890001', 'denominazione', '', '', NULL , NULL , 0, 'MRTLNZ72M30L378I', 'Lorenzo Martinelli', NULL , '', 0, 0, '', '', '', '', '', '', '', '', '');

INSERT INTO A4GT_FASCICOLO(ID, VERSIONE, CUAA, STATO, DENOMINAZIONE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, ORGANISMO_PAGATORE, DATA_MODIFICA, UTENTE_MODIFICA)
VALUES(14, 0 , '00123890001', 'IN_AGGIORNAMENTO', 'denominazione', 51, 0, 'APPAG', to_date('01-01-2020', 'dd-mm-yyyy'), 'Utente Test');

--00123890002
INSERT INTO A4GT_PERSONA (ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(54, 0, 0, '00123890002');

INSERT INTO A4GT_PERSONA_GIURIDICA
(ID, ID_VALIDAZIONE, VERSIONE, PARTITA_IVA, DENOMINAZIONE, FORMA_GIURIDICA, OGGETTO_SOCIALE, DATA_COSTITUZIONE, DATA_TERMINE, CAPITALE_SOCIALE_DELIBERATO, CF_RAPPRESENTANTE_LEGALE, NOME_RAPPRESENTANTE_LEGALE, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_FRAZIONE, SEDE_PROVINCIA, SEDE_COMUNE)
VALUES(54, 0, 0, '00123890002', 'denominazione', '', '', NULL , NULL , 0, 'MRTLNZ72M30L378I', 'Lorenzo Martinelli', NULL , '', 0, 0, '', '', '', '', '', '', '', '', '');

INSERT INTO A4GT_FASCICOLO(ID, VERSIONE, CUAA, STATO, DENOMINAZIONE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, ORGANISMO_PAGATORE, DATA_MODIFICA, UTENTE_MODIFICA)
VALUES(15, 0 , '00123890002', 'CHIUSO', 'denominazione', 51, 0, 'APPAG', to_date('01-01-2020', 'dd-mm-yyyy'), 'Utente Test');
