--Test algoritmo capi richiesti
--Domanda
INSERT INTO A4GT_DOMANDA(ID, VERSIONE, NUMERO_DOMANDA, COD_MODULO_DOMANDA, DESC_MODULO_DOMANDA, CUAA_INTESTATARIO, DT_PROTOCOLLAZIONE, NUM_DOMANDA_RETTIFICATA, COD_ENTE_COMPILATORE, DESC_ENTE_COMPILATORE, RAGIONE_SOCIALE, DT_PRESENTAZIONE, DT_PRESENTAZ_ORIGINARIA, DT_PROTOCOLLAZ_ORIGINARIA, ANNULLO_RIDUZIONE, IBAN, ANNO_CAMPAGNA, STATO)
VALUES(8664187, 2, 212465, 'BPS_2019', 'PAGAMENTI DIRETTI', 'ZPPPLA84L17C794M', TIMESTAMP '2019-05-31 11:37:51.000000', NULL, 55, 'CAA ATS - 003 - CLES', 'AZIENDA AGRICOLA EL BASTON DI ZAPPINI PAOLO', TIMESTAMP '2019-05-31 11:37:06.000000', NULL, NULL, NULL, 'IT67S0816335001000240309129', 2019, 'IN_ISTRUTTORIA');
--Istruttoria
INSERT INTO A4GT_ISTRUTTORIA
(ID, VERSIONE, ID_DOMANDA, ID_STATO_LAVORAZIONE, BLOCCATA_BOOL, ERRORE_CALCOLO, DATA_ULTIMO_CALCOLO, TIPOLOGIA, ID_ELENCO_LIQUIDAZIONE, SOSTEGNO)
VALUES(8675888, 9, 8664187, (select id from A4GD_STATO_LAV_SOSTEGNO where identificativo = 'INTEGRATO'), 0, 0, TIMESTAMP '2020-03-27 17:07:06.000000', 'SALDO', NULL, 'ZOOTECNIA');
--Allevamenti
INSERT INTO A4GT_ALLEVAMENTO_IMPEGNATO
(ID, VERSIONE, ID_DOMANDA, CODICE_SPECIE, DATI_ALLEVAMENTO, DATI_PROPRIETARIO, DATI_DETENTORE, ID_INTERVENTO)
VALUES(8675566, 0, 8664187, 'BOVINI', '{"idAllevamento":17302,"codiceAllevamento":"110TN070","codiceAllevamentoBdn":"2020029","descrizioneAllevamento":"AZIENDA AGRICOLA \"EL BASTON\"","comune":null,"indirizzo":null}', '{"codFiscaleProprietario":null,"denominazioneProprietario":null}', '{"codFiscaleDetentore":null,"denominazioneDetentore":null}', (SELECT id from A4GD_INTERVENTO WHERE codice_agea=311));
INSERT INTO A4GT_ALLEVAMENTO_IMPEGNATO
(ID, VERSIONE, ID_DOMANDA, CODICE_SPECIE, DATI_ALLEVAMENTO, DATI_PROPRIETARIO, DATI_DETENTORE, ID_INTERVENTO)
VALUES(8675567, 0, 8664187, 'BOVINI', '{"idAllevamento":17302,"codiceAllevamento":"110TN070","codiceAllevamentoBdn":"2020029","descrizioneAllevamento":"AZIENDA AGRICOLA \"EL BASTON\"","comune":null,"indirizzo":null}', '{"codFiscaleProprietario":null,"denominazioneProprietario":null}', '{"codFiscaleDetentore":null,"denominazioneDetentore":null}', (SELECT id from A4GD_INTERVENTO WHERE codice_agea=313));
INSERT INTO A4GT_ALLEVAMENTO_IMPEGNATO
(ID, VERSIONE, ID_DOMANDA, CODICE_SPECIE, DATI_ALLEVAMENTO, DATI_PROPRIETARIO, DATI_DETENTORE, ID_INTERVENTO)
VALUES(8675568, 0, 8664187, 'BOVINI', '{"idAllevamento":17302,"codiceAllevamento":"110TN070","codiceAllevamentoBdn":"2020029","descrizioneAllevamento":"AZIENDA AGRICOLA \"EL BASTON\"","comune":null,"indirizzo":null}', '{"codFiscaleProprietario":null,"denominazioneProprietario":null}', '{"codFiscaleDetentore":null,"denominazioneDetentore":null}', (SELECT id from A4GD_INTERVENTO WHERE codice_agea=310));
--Importi Unitari
INSERT INTO A4GT_IMPORTO_UNITARIO (ID, VERSIONE, ID_INTERVENTO, VALORE_UNITARIO, ANNO_CAMPAGNA, PRIORITA) VALUES(12014247, 173, (SELECT id from A4GD_INTERVENTO WHERE codice_agea=310), 10, 2019, 3);
INSERT INTO A4GT_IMPORTO_UNITARIO (ID, VERSIONE, ID_INTERVENTO, VALORE_UNITARIO, ANNO_CAMPAGNA, PRIORITA) VALUES(8646866, 190, (SELECT id from A4GD_INTERVENTO WHERE codice_agea=311), 11, 2019, 2);
INSERT INTO A4GT_IMPORTO_UNITARIO (ID, VERSIONE, ID_INTERVENTO, VALORE_UNITARIO, ANNO_CAMPAGNA, PRIORITA) VALUES(8646867, 184, (SELECT id from A4GD_INTERVENTO WHERE codice_agea=313), 13, 2019, 1);
COMMIT;

