delete from A4GT_DOMANDA_INTEGRATIVA where id in (1, 2, 3, 4, 5, 6, 7);
delete from A4GT_ESITO_CALCOLO_CAPO where ID_ALLEVAM_DU in (select id from A4GT_ALLEVAMENTO_IMPEGNATO where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'BLLGPR66B27C372Y'));
delete from A4GT_ALLEVAMENTO_IMPEGNATO where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'BLLGPR66B27C372Y');
delete from A4GT_ISTRUTTORIA where id = 19999999991L;
delete FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'BLLGPR66B27C372Y';
