-- Creazione oggetti comuni del sistema a4gistruttoria
DROP ALL OBJECTS;

-- Versione 1.0
-- @CODE
CREATE ALIAS TO_NUMBER AS '
java.lang.Double toNumber(java.lang.String value, java.lang.String format, java.lang.String nls_character) {
    return value == null ? null : java.lang.Double.valueOf(value);
}
';

-- 1. Sequence
CREATE SEQUENCE NXTNBR
  START WITH 100000
  NOCYCLE
  NOCACHE
  ORDER;
  
CREATE ALIAS JSON_QUERY FOR "it.tndigitale.a4gistruttoria.DomandeApplicationTest.jsonQuery"; 
CREATE ALIAS JSON_VALUE FOR "it.tndigitale.a4gistruttoria.DomandaDettaglioApplicationTest.jsonValue";

-- 2. Tabella di Log
CREATE TABLE A4GT_LOGGING (
   ID NUMBER(19) NOT NULL,
   VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
   UTENTE VARCHAR2(500 CHAR) NOT NULL,
   TIPO_EVENTO VARCHAR2(500 CHAR) NOT NULL,
   TABELLA VARCHAR2(4000) NOT NULL,
   ID_ENTITA NUMBER(19) NOT NULL,
   DT_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
   CONSTRAINT A4GT_LOGGING_PK PRIMARY KEY (ID) 
);

CREATE TABLE A4GT_CONF_ISTR_DISACCOPPIATO (
   ID NUMBER(19) NOT NULL,
   VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
   ANNO_CAMPAGNA NUMBER(4) NOT NULL, 
   PERC_INCREMENTO_GREENING NUMBER(5,4) NOT NULL,
   PERC_INCREMENTO_GIOVANE NUMBER(5,4) NOT NULL,
   LIMITE_GIOVANE NUMBER(8,4) NOT NULL,
   PERC_RIDUZIONE_LIN_ART51_PAR2 NUMBER(5,4) NOT NULL,
   PERC_RIDUZIONE_LIN_ART51_PAR3 NUMBER(5,4) NOT NULL,
   PERC_RIDUZIONE_LIN_MASS_NETTO NUMBER(5,4) NOT NULL,
   PERC_RIDUZIONE_TITOLI NUMBER(7,6) NOT NULL,
   
   CONSTRAINT PK_CONFIG_ISTR_DISACCOPPIATO PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDU_CONF_ISTR_DIS_ANNO_CAMPAGNA ON A4GT_CONF_ISTR_DISACCOPPIATO (ANNO_CAMPAGNA);

CREATE TABLE A4GT_DATI_SETTORE (
 ID NUMBER(19) NOT NULL,
 VERSIONE NUMBER(10) NOT NULL,
 ANNO_RIFERIMENTO NUMBER(4) NOT NULL,
 CODICE_PAC VARCHAR2(50) NOT NULL,
 DESCRIZIONE_PAC VARCHAR2(500) NOT NULL,
 TIPO_DOMANDA VARCHAR2(50) NOT NULL,
 DESCRIZIONE_DOMANDA VARCHAR2(500) NOT NULL,
 DT_SCADENZA_DOMANDE DATE,
 DT_SCADENZA_DOMANDE_RITARDO DATE,
 DT_SCADENZA_DOMANDE_RITIROPARZ DATE,
 DT_SCADENZA_DOMANDE_RITIRO DATE,
 DT_RICEVIBILITA DATE,
 PERC_INCREMENTO_GREENING NUMBER(5,4),
 PERC_INCREMENTO_GIOVANE NUMBER(5,4),
 LIMITE_GIOVANE NUMBER,
 PERC_RIDUZIONE_LINEARE_1 NUMBER(5,4),
 PERC_RIDUZIONE_LINEARE_2 NUMBER(5,4),
 PERC_RIDUZIONE_LINEARE_3 NUMBER(7,6),
 PERC_RIDUZIONE_TITOLI	  NUMBER(7,6),
 TIPO_ISTRUTTORIA		VARCHAR2(20),
 PERC_PAGAMENTO 	  	NUMBER(20,8)
);

ALTER TABLE A4GT_DATI_SETTORE ADD CONSTRAINT PK_A4GT_DATI_SETTORE PRIMARY KEY (ID);

CREATE UNIQUE INDEX A4GT_DATI_SETTORE_UIDX ON A4GT_DATI_SETTORE (CODICE_PAC,ANNO_RIFERIMENTO,TIPO_DOMANDA);


CREATE TABLE A4GT_DOMANDA (
 ID NUMBER(19) NOT NULL,
 VERSIONE NUMBER(10) NOT NULL,
 NUMERO_DOMANDA NUMBER(10) NOT NULL,
 COD_MODULO_DOMANDA VARCHAR2(50) NOT NULL,
 DESC_MODULO_DOMANDA VARCHAR2(500) NOT NULL,
 ANNO_CAMPAGNA NUMBER(4) NOT NULL,
 STATO VARCHAR2(14) NOT NULL,
 CUAA_INTESTATARIO VARCHAR2(16) NOT NULL,
 DT_PRESENTAZIONE DATE NOT NULL,
 NUM_DOMANDA_RETTIFICATA NUMBER(10),
 COD_ENTE_COMPILATORE NUMBER(9) NOT NULL,
 DESC_ENTE_COMPILATORE VARCHAR2(500) NOT NULL,
 RAGIONE_SOCIALE VARCHAR2(4000),
 DT_PROTOCOLLAZIONE DATE NOT NULL,
 DT_PRESENTAZ_ORIGINARIA DATE,
 DT_PROTOCOLLAZ_ORIGINARIA DATE,
 ANNULLO_RIDUZIONE NUMBER(1),
 IBAN VARCHAR2(32),
 DT_PROTOCOLLAZ_ULT_MODIFICA DATE,
 NUMERO_DOMANDA_ULT_MODIFICA NUMBER(10),
);

ALTER TABLE A4GT_DOMANDA ADD CONSTRAINT PK_A4GT_DOMANDA PRIMARY KEY (ID);

CREATE UNIQUE INDEX A4GT_DOMANDA_UIDX ON A4GT_DOMANDA (ANNO_CAMPAGNA,CUAA_INTESTATARIO);
ALTER TABLE A4GT_DOMANDA ADD  BLOCCATA_BOOL number(1); 

CREATE TABLE A4GT_DATI_LAVORAZIONE (
 ID NUMBER(19) NOT NULL,
 VERSIONE NUMBER(10) NOT NULL,
 ID_DOMANDA NUMBER(10) NOT NULL,
 JSON_DATI_RICEVIBILITA CLOB NOT NULL,
 JSON_DATI_SINTESI_IMPEGNI CLOB
);

ALTER TABLE A4GT_DATI_LAVORAZIONE ADD CONSTRAINT PK_A4GT_DATI_LAVORAZIONE PRIMARY KEY (ID);
ALTER TABLE A4GT_DATI_LAVORAZIONE ADD CONSTRAINT FK_A4GT_DATI_LAVORAZIONE_0 FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID);

-- -- Versione 1.1

CREATE TABLE A4GD_TIPO_CONTROLLO (
 ID NUMBER(19) NOT NULL PRIMARY KEY,
 VERSIONE NUMBER(10) NOT NULL,
 CATEGORIA VARCHAR2(500) NOT NULL,
 IDENTIFICATIVO VARCHAR2(500) NOT NULL,
 DESCRIZIONE VARCHAR2(4000) NOT NULL
);

CREATE UNIQUE INDEX A4GD_TIPO_CONTROLLO_UIDX ON A4GD_TIPO_CONTROLLO (CATEGORIA,IDENTIFICATIVO);


CREATE TABLE A4GT_ERRORE_RICEVIBILITA (
 ID NUMBER(19) NOT NULL PRIMARY KEY,
 VERSIONE NUMBER(10) NOT NULL,
 TIPOLOGIA_CONTROLLO VARCHAR2(50) NOT NULL,
 ID_DOMANDA NUMBER(19) NOT NULL,
 DT_ESECUZIONE DATE NOT NULL,
 FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID)
);

CREATE UNIQUE INDEX A4GT_ERRORE_RICEVIBILITA_UIDX ON A4GT_ERRORE_RICEVIBILITA (TIPOLOGIA_CONTROLLO,ID_DOMANDA,DT_ESECUZIONE);

-- -- Versione 1.2


CREATE TABLE A4GT_PROCESSO (
 ID NUMBER(19) NOT NULL PRIMARY KEY,
 VERSIONE NUMBER(10) NOT NULL,
 ID_DATI_SETTORE NUMBER(19),
 TIPO VARCHAR2(50) NOT NULL,
 STATO VARCHAR2(50) NOT NULL,
 DT_INIZIO DATE DEFAULT SYSDATE NOT NULL,
 DT_FINE DATE,
 PERCENTUALE_AVANZAMENTO NUMBER(3) DEFAULT 0 NOT NULL,
 DATI_ELABORAZIONE CLOB,
);

CREATE INDEX A4GT_PROCESSO_IDX ON A4GT_PROCESSO (ID_DATI_SETTORE,TIPO);

CREATE TABLE A4GT_PICCOLO_AGRICOLTORE (
	ID NUMBER NOT NULL PRIMARY KEY,
	CUAA VARCHAR2(16 CHAR) NOT NULL,
	NOMINATIVO VARCHAR2(500 CHAR) NOT NULL,
	ANNO_INIZIO NUMBER(4) NOT NULL,
	ANNO_FINE NUMBER(4)
);

CREATE UNIQUE INDEX A4GT_PICCOLO_AGRICOLTORE_UIDX ON A4GT_PICCOLO_AGRICOLTORE (CUAA);

CREATE TABLE A4GD_INTERVENTO (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10)NOT NULL,
    SOSTEGNO VARCHAR2(50) NOT NULL,
    IDENTIFICATIVO_SETTORE VARCHAR2(50),
    DESCRIZIONE_SETTORE VARCHAR2(500),
    IDENTIFICATIVO VARCHAR2(50) NOT NULL,
    IDENTIFICATIVO_INTERVENTO VARCHAR2(50) NOT NULL,
    DESCRIZIONE_BREVE VARCHAR2(500),
    DESCRIZIONE_LUNGA VARCHAR2(4000),
    MISURA VARCHAR2(10),
    CODICE_AGEA VARCHAR2(10),
    CONSTRAINT PK_A4GD_INTERVENTO_DU PRIMARY KEY (ID)
);
			
CREATE UNIQUE INDEX A4GD_INTERVENTO_DU_UIDX ON A4GD_INTERVENTO (IDENTIFICATIVO_INTERVENTO);

CREATE UNIQUE INDEX A4GD_INTERVENTO_DU_IDENTIFY_UIDX ON A4GD_INTERVENTO (IDENTIFICATIVO);
			
ALTER TABLE A4GD_INTERVENTO ADD CONSTRAINT A4GD_INTERVENTO_DU_UQ UNIQUE (IDENTIFICATIVO_INTERVENTO);

ALTER TABLE A4GD_INTERVENTO ADD CONSTRAINT A4GD_INTERVENTO_DU_IDENTIFY_UQ UNIQUE (IDENTIFICATIVO);
				
CREATE TABLE A4GT_ALLEVAMENTO_IMPEGNATO (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) NOT NULL,
    ID_DOMANDA NUMBER(10) NOT NULL,
    ID_INTERVENTO NUMBER(19) NOT NULL,
    CODICE_SPECIE VARCHAR2(50) NOT NULL,
    DATI_ALLEVAMENTO CLOB,
    DATI_PROPRIETARIO CLOB,
    DATI_DETENTORE CLOB,
    STATO VARCHAR2(25),
    CONSTRAINT PK_A4GT_RICHIESTE_ALLEVAM_DU PRIMARY KEY (ID),
    FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID),
    FOREIGN KEY (ID_INTERVENTO) REFERENCES A4GD_INTERVENTO (ID)
);
				
				
CREATE TABLE A4GT_RICHIESTA_SUPERFICIE (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) NOT NULL,
    ID_DOMANDA NUMBER(10) NOT NULL,
    SUP_RICHIESTA NUMBER(10) NOT NULL,
    SUP_RICHIESTA_NETTA NUMBER(10),
    CODICE_COLTURA_3 CHAR(11) NOT NULL,
    CODICE_COLTURA_5 CHAR(19),
    INFO_CATASTALI CLOB,
    INFO_COLTIVAZIONE CLOB,
    RIFERIMENTI_CARTOGRAFICI CLOB,
    ID_INTERVENTO NUMBER(19) NOT NULL,
    CONSTRAINT PK_AG4T_RICHIESTE_SUPERFICIE PRIMARY KEY (ID),
    FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID),
    FOREIGN KEY (ID_INTERVENTO) REFERENCES A4GD_INTERVENTO (ID)
);
				
				
				
CREATE TABLE A4GT_DATI_PASCOLO (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) NOT NULL,
    ID_DOMANDA NUMBER(10) NOT NULL,
    CODICE_PASCOLO VARCHAR2(50) NOT NULL,
    DESCRIZIONE_PASCOLO VARCHAR2(500),
    UBA_DICHIARATE NUMBER(10) NOT NULL,
    PARTICELLE_CATASTALI CLOB,
    CONSTRAINT PK_A4GT_DATI_PASCOLO PRIMARY KEY (ID),
    FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID)
);
				
				
CREATE TABLE A4GT_DICHIARAZIONE_DU (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) NOT NULL,
    ID_DOMANDA NUMBER(10) NOT NULL,
    -- ID_TIPO_DICHIARAZIONE NUMBER(19) NOT NULL,
    QUADRO VARCHAR2(25) NOT NULL,
    CODICE VARCHAR2(50) NOT NULL,
    DESCRIZIONE VARCHAR2(500),
    VALORE_BOOL NUMBER(1),
    VALORE_DATA DATE,
    VALORE_NUMERO NUMBER(19),
    VALORE_STRINGA VARCHAR2(500),
    ORDINE NUMBER(10,0),
    CONSTRAINT PK_A4GT_DICHIARAZIONI_DU PRIMARY KEY (ID),
    FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID),
);
				
CREATE UNIQUE INDEX A4GT_DICHI_DU_UIDX ON A4GT_DICHIARAZIONE_DU (CODICE,ID_DOMANDA);
	
				
				
--- Creazione tabella titoli ---
			
CREATE TABLE A4GT_TITOLO_DU (
ID NUMBER(19) NOT NULL,
VERSIONE NUMBER(10) NOT NULL,
ID_DOMANDA NUMBER(19) NOT NULL,
ID_TITOLARE NUMBER(19) NOT NULL,
NUMERO_TITOLARE VARCHAR2(12) NOT NULL,
VALORE NUMBER(8,2) NOT NULL,
SUPERFICIE NUMBER(5,2) NOT NULL,
DATA_INIZIO_POSSESSO DATE,
DATA_FINE_POSSESSO DATE,
ANNO_CAMPAGNA_INIZIO NUMBER(4) NOT NULL,
ANNO_CAMPAGNA_FINE NUMBER(4),
CONSTRAINT PK_A4GT_TITOLO_DU PRIMARY KEY (ID),
FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID)
);


CREATE TABLE A4GD_STATO_LAV_SOSTEGNO (
ID NUMBER(19) NOT NULL,
VERSIONE NUMBER(10) NOT NULL,
IDENTIFICATIVO VARCHAR2(50) NOT NULL,
DESCRIZIONE VARCHAR2(500),
CONSTRAINT PK_A4GD_STATO_LAV_SOSTEGNO PRIMARY KEY (ID)
);

CREATE TABLE A4GT_ELENCO_LIQUIDAZIONE (
	ID NUMBER(19) NOT NULL,
	VERSIONE NUMBER(10) NOT NULL,
	COD_ELENCO VARCHAR2(50) NOT NULL,
	DT_CREAZIONE DATE NOT NULL,
	TRACCIATO_SOC CLOB,
	VERBALE_LIQUIDAZIONE BLOB,
	STATO VARCHAR2(50),
	CONSTRAINT PK_A4GT_ELENCO_LIQUIDAZIONE PRIMARY KEY (ID)
);



CREATE TABLE A4GT_ISTRUTTORIA (
	ID NUMBER(19) NOT NULL,
	VERSIONE NUMBER(10) NOT NULL,
	ID_DOMANDA NUMBER(19),
	SOSTEGNO VARCHAR(25),
	ID_STATO_LAVORAZIONE NUMBER(19),
	BLOCCATA_BOOL number(1) DEFAULT 0 NOT NULL,
	ERRORE_CALCOLO number(1) DEFAULT 0 NOT NULL,
	DATA_ULTIMO_CALCOLO DATE,
	TIPOLOGIA VARCHAR2(31) NOT NULL,
	ID_ELENCO_LIQUIDAZIONE NUMBER(19),
	CONSTRAINT PK_A4GT_ISTRUTTORIA PRIMARY KEY (ID),
	FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA(ID),
	FOREIGN KEY (ID_STATO_LAVORAZIONE) REFERENCES A4GD_STATO_LAV_SOSTEGNO(ID),
	FOREIGN KEY (ID_ELENCO_LIQUIDAZIONE) REFERENCES A4GT_ELENCO_LIQUIDAZIONE(ID)
);

CREATE TABLE A4GT_TRANSIZIONE_ISTRUTTORIA (
	ID NUMBER(19) NOT NULL,
	VERSIONE NUMBER(10) NOT NULL,
	ID_ISTRUTTORIA NUMBER(19) NOT NULL,	
	-- ID_DOMANDA NUMBER(19)
	ID_STATO_INIZIALE NUMBER(19) NOT NULL,
	ID_STATO_FINALE NUMBER(19),
	DATA_ESECUZIONE DATE NOT NULL,
	CONSTRAINT PK_A4GT_TRANSIZIONE_ISTRUTTORIA PRIMARY KEY(ID),
	FOREIGN KEY (ID_ISTRUTTORIA) REFERENCES A4GT_ISTRUTTORIA(ID),
	FOREIGN KEY (ID_STATO_INIZIALE) REFERENCES A4GD_STATO_LAV_SOSTEGNO(ID),
	FOREIGN KEY (ID_STATO_FINALE) REFERENCES A4GD_STATO_LAV_SOSTEGNO(ID)
);

CREATE TABLE A4GT_PASSO_TRANSIZIONE(
	ID NUMBER(19) NOT NULL,
	VERSIONE NUMBER(10) NOT NULL,
	ID_TRANSIZ_SOSTEGNO NUMBER(19) NOT NULL,
	CODICE_PASSO VARCHAR2(50) NOT NULL,
	ESITO VARCHAR2(2) NOT NULL,
	CODICE_ESITO VARCHAR2(50) NOT NULL,
	DATI_INPUT CLOB,
	DATI_OUTPUT CLOB,
	DATI_SINTESI_LAVORAZIONE CLOB,
	CONSTRAINT PK_A4GT_PASSO_TRANSIZIONE PRIMARY KEY(ID),
	FOREIGN KEY (ID_TRANSIZ_SOSTEGNO) REFERENCES A4GT_TRANSIZIONE_ISTRUTTORIA(ID)
);

CREATE TABLE A4GT_TRASMISSIONE_BDNA
(
   ID NUMBER(20) NOT NULL PRIMARY KEY,
	VERSIONE NUMBER(10) NOT NULL,
   CF_OPERATORE VARCHAR(50) NOT NULL,
   DT_CREAZIONE DATE NOT NULL,
   DT_CONFERMA DATE,
   TIPO_DOMANDA VARCHAR(50)
);

-- ALTER COLONNA CUUA IN CUAA
CREATE TABLE A4GT_DOMANDE_COLLEGATE(
 	ID NUMBER(22) NOT NULL,
 	VERSIONE NUMBER(22) NOT NULL,
    CUAA VARCHAR2(16) NOT NULL,
    TIPO_DOMANDA VARCHAR2(50),
    ID_DOMANDA NUMBER(19) NOT NULL,
    DT_DOMANDA DATE NOT NULL,
    CAMPAGNA NUMBER(4),
    IMPORTO_RICHIESTO DECIMAL(12,2) NOT NULL,
    DT_BDNA_OP DATE,
    DT_SILENZIO DATE,
    DT_BDNA DATE,
    PROTOCOLLO VARCHAR2(50),
    STATO_BDNA VARCHAR2(50),
    NOME_FILE_CSV VARCHAR2(40),
    FLAG_CONFERMATO NUMBER(1) DEFAULT 0,
    MISURE_PSR VARCHAR2(10),
    ID_TRASMISSIONE_BDNA NUMBER(19),
 	CONSTRAINT FK_BDNA_DOM_COL PRIMARY KEY (ID),
 	FOREIGN KEY (ID_TRASMISSIONE_BDNA) REFERENCES A4GT_TRASMISSIONE_BDNA (ID)
);
ALTER TABLE A4GT_DOMANDE_COLLEGATE ADD DT_INIZIO_SILENZIO_ASSENSO DATE;
ALTER TABLE A4GT_DOMANDE_COLLEGATE ADD DT_FINE_SILENZIO_ASSENSO DATE;
ALTER TABLE A4GT_DOMANDE_COLLEGATE ADD DT_INIZIO_ESITO_NEGATIVO DATE;
ALTER TABLE A4GT_DOMANDE_COLLEGATE ADD DT_FINE_ESITO_NEGATIVO DATE;
ALTER TABLE A4GT_DOMANDE_COLLEGATE ADD STATO_BDNA_AGGIORNATO VARCHAR2(50);
			
--ALTER TABLE A4GT_LOGGING RENAME TO A4GISTR_LOGGING;

CREATE TABLE A4GD_COLTURA_INTERVENTO (
 ID NUMBER(19) NOT NULL,
 VERSIONE NUMBER(10),
 ANNO_INIZIO NUMBER(4) NOT NULL,
 ANNO_FINE NUMBER(4),
 CODICE_COLTURA_3 CHAR(11),
 CODICE_COLTURA_5 CHAR(19),
 DESCRIZIONE_COLTURA VARCHAR2(500),
 ID_INTERVENTO NUMBER(19),
 LEGUMINOSE CHAR(1),
 COD_COLTURA_DIVERSA NUMBER(15,0),
 CONSTRAINT PK_A4GD_COLTURA_INTERVENTO PRIMARY KEY (ID),
 FOREIGN KEY (ID_INTERVENTO) REFERENCES A4GD_INTERVENTO (ID)
);

CREATE TABLE A4GT_CAMPIONE (
     ID NUMBER(19) NOT NULL,
     VERSIONE NUMBER(10) NOT NULL,
     ANNO_CAMPAGNA NUMBER(4) NOT NULL,
     CUAA VARCHAR2(16) NOT NULL,
     TIPO_CAMPIONE VARCHAR2(50) NOT NULL,
     TIPO VARCHAR2(50 BYTE),
     BOVINI NUMBER(1),
     OVINI NUMBER(1 BYTE),
     CONSTRAINT PK_A4GT_CAMPIONE PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX A4GT_CAMPIONE_UIDX ON A4GT_CAMPIONE (ANNO_CAMPAGNA,CUAA,TIPO_CAMPIONE);


CREATE TABLE A4GT_DATI_PARTICELLA_COLTURA (
 ID NUMBER(20,0) NOT NULL,
 VERSIONE NUMBER(10,0),
 ID_ISTRUTTORIA NUMBER(19),
 ID_DOMANDA NUMBER(19),
 INFO_CATASTALI CLOB,
 CODICE_COLTURA_3 CHAR(11),
 DATI_PARTICELLA CLOB,
 CONSTRAINT PK_A4GT_DATI_PART_COLT PRIMARY KEY (ID),
 FOREIGN KEY (ID_ISTRUTTORIA) REFERENCES A4GT_ISTRUTTORIA (ID),
 FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID)
);
	
  CREATE TABLE A4GT_DATI_FILTRO_DOMANDA 
   (	ID NUMBER(20,0) NOT NULL, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL, 
	ID_DOMANDA NUMBER(20,0) NOT NULL, 
	TIPO_FILTRO VARCHAR2(50) NOT NULL,
	VALORE VARCHAR2(500),
	 CONSTRAINT A4GT_DATI_FILTRO_DOMANDA_PK PRIMARY KEY (ID),
	 FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID)
   );
   
  CREATE UNIQUE INDEX A4GT_DFD_DT_UIDX ON A4GT_DATI_FILTRO_DOMANDA(ID_DOMANDA, TIPO_FILTRO) ;
  
  CREATE TABLE A4GT_PASCOLO_PARTICELLA
	(
	  ID                NUMBER(20) NOT NULL,
	  VERSIONE          NUMBER(10),
	  ID_DOMANDA        NUMBER(19),
	  ID_PASCOLO        NUMBER(19),
	  COD_PASCOLO       CHAR(11),
	  DESC_PASCOLO      CHAR(40),
	  INFO_PART_PASCOLO CLOB,
	  SUP_NETTA_PASCOLO NUMBER(10),
	  ESITO_MAN         CHAR(6),
	  DATI_INPUT		CLOB,
	  DATI_OUTPUT 		CLOB,
	  CONSTRAINT PK_A4GT_PASCOLO_PARTICELLA PRIMARY KEY (ID)
	);			
	
	ALTER TABLE A4GT_PASCOLO_PARTICELLA ADD FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID);
	
	
	CREATE TABLE A4GT_ESITO_CALCOLO_CAPO (
        ID NUMBER(22) NOT NULL,
        VERSIONE NUMBER(22) NOT NULL,
        ID_ALLEVAM_DU NUMBER(22) NOT NULL,
        ID_TRANSIZIONE NUMBER(22) NULL,
        CAPO_ID NUMBER(22) NOT NULL,
        CODICE_CAPO VARCHAR2 (25) NOT NULL,
        ESITO VARCHAR2 (25),
        MESSAGGIO VARCHAR2 (600),
        DUPLICATO NUMBER (1),
        CONTROLLO_NON_SUPERATO NUMBER (1),
        RICHIESTO NUMBER (1),
        CONSTRAINT PK_A4GT_ESITO_CALCOLO_CAPO PRIMARY KEY (ID),
        FOREIGN KEY (ID_ALLEVAM_DU) REFERENCES A4GT_ALLEVAMENTO_IMPEGNATO (ID)
	);
	
	
	ALTER TABLE A4GT_DATI_SETTORE ADD PERC_DISCIPLINA_FINANZIARIA NUMBER(7,6);
			
			CREATE TABLE A4GT_ETICHETTURA_CARNE (
			 	ID NUMBER(20) NOT NULL,
			 	VERSIONE NUMBER(10) NOT NULL,
			    CUAA VARCHAR2 (16),
			    DT_INIZIO_VALIDITA DATE,
			    CODICE_ASL VARCHAR2 (10),
			    DT_FINE_VALIDITA DATE,
			 	CONSTRAINT A4GT_ETICHETTURA_CARNE PRIMARY KEY (ID)
			);
			
			
			CREATE TABLE A4GT_ALLEV_MONTAGNA (
			 	ID NUMBER(20) NOT NULL,
			 	VERSIONE NUMBER(10) NOT NULL,
			    COD_ALLEV VARCHAR2 (16) NOT NULL,
			    FLAG_MONTAGNA NUMBER(1) DEFAULT 0,
			 	CONSTRAINT A4GT_ALLEV_MONTAGNA PRIMARY KEY (ID)
			);
			
			CREATE TABLE A4GD_REG_OLIO_NAZIONALE (
			 ID NUMBER(19) NOT NULL,
			 VERSIONE NUMBER(10) NOT NULL,
			 CUAA_INTESTATARIO VARCHAR2(16) NOT NULL,
			 INIZIO_CAMPAGNA NUMBER(4,0) NOT NULL,
			 FINE_CAMPAGNA NUMBER(4,0) NOT NULL,
			 CONSTRAINT A4GD_REG_OLIO_NAZIONALE_PK PRIMARY KEY (ID)
			);
			    
			CREATE TABLE A4GD_REG_OLIO_QUALITA (
			 ID NUMBER(19) NOT NULL,
			 VERSIONE NUMBER(10) NOT NULL,
			 CUAA_INTESTATARIO VARCHAR2(16) NOT NULL,
			 INIZIO_CAMPAGNA NUMBER(4,0) NOT NULL,
			 FINE_CAMPAGNA NUMBER(4,0) NOT NULL,
			 CONSTRAINT A4GD_REG_OLIO_QUALITA_PK PRIMARY KEY (ID)
			);		
		
	        CREATE TABLE A4GT_IMPORTO_UNITARIO (
			 	ID NUMBER(20) NOT NULL,
			 	VERSIONE NUMBER(10) NOT NULL,
			    ANNO_CAMPAGNA NUMBER(4,0) NOT NULL,
			    ID_INTERVENTO NUMBER(20) NOT NULL,
			    VALORE_UNITARIO DECIMAL(10,2) DEFAULT 0.00 NOT NULL,
			    PRIORITA NUMBER(4,0),
			 	CONSTRAINT FK_IMPORTO_UNITARIO FOREIGN KEY (ID_INTERVENTO) REFERENCES A4GD_INTERVENTO (ID),
 			 	CONSTRAINT PK_IMPORTO_UNITARIO PRIMARY KEY (ID)
			);
			
			
			CREATE UNIQUE INDEX INTERVENTO_PREMIO_UIDX ON A4GT_IMPORTO_UNITARIO (ID_INTERVENTO,ANNO_CAMPAGNA);
			
			
			CREATE TABLE A4GT_CONF_ISTR_ZOOTECNIA (
			 	ID NUMBER(20) NOT NULL,
			 	VERSIONE NUMBER(10) NOT NULL,
			 	ANNO_CAMPAGNA NUMBER(4) NOT NULL,
			    DT_APERTURA_DOMANDA DATE,
			    DT_CHIUSURA_DOMANDA DATE,
 			 	CONSTRAINT PK_SOSTEGNO_DU_DI PRIMARY KEY (ID)
			);
			
			CREATE UNIQUE INDEX CONF_ISTR_ZOOTECNIA_UIDX ON A4GT_CONF_ISTR_ZOOTECNIA (ANNO_CAMPAGNA);
			
			
			CREATE TABLE A4GT_ANOM_DOMANDA_SOSTEGNO (
			 ID NUMBER(19) NOT NULL,
			 VERSIONE NUMBER(19),
			 ID_PASSO_LAVORAZIONE NUMBER(19),
			 CODICE_ANOMALIA VARCHAR2(50),
			 LIVELLO_ANOMALIA VARCHAR2(50),
			 ESITO VARCHAR2(50),
			 CONSTRAINT PK_A4GT_ANOM_DOMANDA_SOSTEGNO PRIMARY KEY (ID),
			 CONSTRAINT FK_A4GT_ANOM_DOMANDA_PASSO FOREIGN KEY (ID_PASSO_LAVORAZIONE) REFERENCES A4GT_PASSO_TRANSIZIONE (ID)
			);

CREATE TABLE A4GT_ANALISI_LATTE(
    ID NUMBER(20,0) NOT NULL,
    VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL,
	CUAA VARCHAR2(16) NOT NULL,
	CELLULE_SOMATICHE NUMBER(10,2),
	CARICA_BATTERICA NUMBER(10,2),
	CONTENUTO_PROTEINA NUMBER(10,2),
	DT_ANALISI DATE,
	ANNO_CAMPAGNA NUMBER(4) NOT NULL,
	CONSTRAINT PK_ANALISI_LATTE PRIMARY KEY (ID)
);

CREATE TABLE A4GT_PRODUZIONE_LATTE(
	ID NUMBER(20,0) NOT NULL,
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL,
	CUAA VARCHAR2(16) NOT NULL,
	DT_CONS_VEND DATE,
	ANNO_CAMPAGNA NUMBER(4) NOT NULL,
	CONSTRAINT PK_PRODUZIONE_LATTE PRIMARY KEY (ID)
);

CREATE TABLE A4GT_REG_ALPEGGIO(
	ID NUMBER(20,0) NOT NULL,
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL,
	CUAA VARCHAR2(16) NOT NULL,
	DT_INIZIO DATE,
	DT_FINE DATE,
	ANNO_CAMPAGNA NUMBER(4) NOT NULL,
	CONSTRAINT PK_REG_ALPEGGIO PRIMARY KEY (ID)
);

   CREATE TABLE A4GT_DOMANDA_INTEGRATIVA(
	ID NUMBER(20,0) NOT NULL, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL,
	ID_RICH_ALLEVAM_ESITO NUMBER(20,0) NOT NULL,
	STATO VARCHAR2(50),
	DT_ULTIMO_AGGIORNAMENTO DATE,
	DUPLICATO NUMBER(1),
	CONTROLLO_SUPERATO NUMBER(1) DEFAULT 1,
	IDENTIFICATIVO VARCHAR2(255),
	CONSTRAINT FK_RICH_ALLEVAM_ESITO FOREIGN KEY (ID_RICH_ALLEVAM_ESITO) REFERENCES A4GT_ESITO_CALCOLO_CAPO (ID),
    CONSTRAINT PK_DOMANDA_INTEGRATIVA PRIMARY KEY (ID)
    );
    
    
    CREATE TABLE A4GT_COMUNI_LIMITROFI (
	 ID NUMBER(19) NOT NULL,
	 VERSIONE NUMBER(10) NOT NULL,
	 CODICE_PROVINCIA NUMBER(10) NOT NULL,
	 CODICE_COMUNE NUMBER(10),
	 COD_NAZIONALE_COMUNE VARCHAR2(50) NOT NULL,
	 NOME_COMUNE VARCHAR2(500),
	 CODICE_PROVINCIA_CONFINANTE NUMBER(10) NOT NULL,
	 CODICE_COMUNE_CONFINANTE NUMBER(10),
	 COD_NAZ_COMUNE_CONFINANTE VARCHAR2(50) NOT NULL,
	 NOME_COMUNE_CONFINANTE VARCHAR2(500),
	 CONSTRAINT PK_A4GT_COMUNI_LIMITROFI PRIMARY KEY (ID)
	);
	
	CREATE TABLE A4GT_CAPO_TRACKING (
	 ID NUMBER(19) NOT NULL,
	 VERSIONE NUMBER(10) NOT NULL,
	 ID_RICH_ALLEVAM_ESITO NUMBER(20) NOT NULL, 
	 DATI CLOB NOT NULL, 
	 DT_ULTIMO_AGGIORNAMENTO date, 
	 CONSTRAINT PK_CAPO_TRACKING PRIMARY KEY (ID), 
	 CONSTRAINT FK_TRK_RICH_ALLEVAM_ESITO FOREIGN KEY (ID_RICH_ALLEVAM_ESITO) REFERENCES A4GT_ESITO_CALCOLO_CAPO(ID)
	);


-- 2. Tabella di Log
CREATE TABLE A4GT_RICEVUTA_DOM_INT_ZOOT (
  ID                       NUMBER(20)           NOT NULL,
  VERSIONE                 NUMBER(10)           DEFAULT 0                     NOT NULL,
  ID_DOMANDA               NUMBER(20)           NOT NULL,
  RICEVUTA                 BLOB                 NOT NULL,
  DT_ULTIMO_AGGIORNAMENTO date, 
  CONSTRAINT PK_RICEVUTA_DOM_INT_ZOOT PRIMARY KEY (ID), 
  CONSTRAINT FK_RICEVUTA_DOM_INT_ZOOT_DOMAN FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA(ID)
);

CREATE UNIQUE INDEX RICEV_DOM_INT_ZOOT_DOMAN_UIX ON A4GT_RICEVUTA_DOM_INT_ZOOT (ID_DOMANDA);

CREATE UNIQUE INDEX A4GT_DOMANDA_INTEGRATIVA_UIDX ON A4GT_DOMANDA_INTEGRATIVA (ID_RICH_ALLEVAM_ESITO);

CREATE TABLE A4GT_STATISTICA_DU (
	ID NUMBER(20) NOT NULL,
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL,
	TIPO_STATISTICA VARCHAR2(5) NOT NULL, 
	ID_DOMANDA NUMBER(10,0), 
	STATO VARCHAR2(50), 
	IMP_AMM NUMBER(20,2), 
	C110 NUMBER(4,0), 
	C109 VARCHAR2(5), 
	C109A VARCHAR2(5), 
	F100 VARCHAR2(4), 
	F200 VARCHAR2(16), 
	F201 VARCHAR2(250), 
	F202A VARCHAR2(250), 
	F202B NUMBER(5,0), 
	F202C VARCHAR2(250), 
	F207 VARCHAR2(5), 
	F300 VARCHAR2(15), 
	C300A VARCHAR2(1), 
	F300B DATE, 
	C300C VARCHAR2(1), 
	C400 VARCHAR2(1), 
	C401 VARCHAR2(1), 
	C402 NUMBER(20,2), 
	C403 VARCHAR2(1), 
	C403A NUMBER(20,2), 
	C404 VARCHAR2(1), 
	C405 VARCHAR2(1), 
	C406 NUMBER(20,2), 
	C407 VARCHAR2(1), 
	C551 NUMBER(20,2), 
	C552 NUMBER(20,2), 
	C554 NUMBER(20,2), 
	C554A NUMBER(20,2), 
	C557 NUMBER(20,2), 
	C558 NUMBER(20,2), 
	C558A NUMBER(20,2), 
	C558B NUMBER(20,2), 
	C558C NUMBER(20,2), 
	C558D NUMBER(20,2), 
	C558E NUMBER(20,2), 
	C558F NUMBER(20,2), 
	C559 NUMBER(20,2), 
	C560 NUMBER(20,2), 
	C560A NUMBER(20,2), 
	C561 NUMBER(20,2), 
	C561A NUMBER(20,2), 
	C561B NUMBER(20,2), 
	C600 VARCHAR2(2), 
	C605 NUMBER(20,2), 
	C611 VARCHAR2(1), 
	C620 VARCHAR2(1), 
	C621 VARCHAR2(1), 
	C633 VARCHAR2(1), 
	C640 NUMBER(20,2), 
	C640A NUMBER(20,2),
	DATA_ELABORAZIONE DATE
);


CREATE TABLE A4GT_DATI_EREDE (
ID NUMBER(20) NOT NULL PRIMARY KEY,
VERSIONE NUMBER(10) NOT NULL,
ID_DOMANDA  NUMBER(20) NOT NULL,
CERTIFICATO NUMBER(1),
COGNOME VARCHAR(50 )NOT NULL,
NOME VARCHAR(50) NOT NULL,
CODICE_FISCALE VARCHAR(16) NOT NULL,
IBAN VARCHAR(34) NOT NULL,
INDIRIZZO VARCHAR(200) NOT NULL,
CODICE_ISTAT VARCHAR(10) NOT NULL,
PROVINCIA VARCHAR(2) NOT NULL,
CAP VARCHAR(5) NOT NULL,
SESSO VARCHAR(1),
DT_NASCITA DATE,
COD_ISTAT_NASCITA VARCHAR(10),
PROVINCIA_NASCITA VARCHAR(2),
DT_ULTIMO_AGGIORNAMENTO DATE,
FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID)
);

CREATE TABLE A4GT_SOGLIA_ACQUISIZIONE (
			 	ID NUMBER(20) NOT NULL PRIMARY KEY,
			 	VERSIONE NUMBER(10) NOT NULL,
			    SETTORE VARCHAR(20) NOT NULL,
				DATA_PRESENTAZIONE DATE NOT NULL,
				DATA_INIZIO_APPLICAZIONE DATE NOT NULL,
				DATA_FINE_APPLICAZIONE DATE NOT NULL,
				SOGLIA NUMBER(20) NOT NULL
	);
			
			
CREATE TABLE A4GD_CAPITOLO_SPESA
(
   ID NUMBER(20) NOT NULL PRIMARY KEY,
   VERSIONE NUMBER(10) NOT NULL,
   ID_INTERVENTO NUMBER(20) NOT NULL,
   TIPO VARCHAR(50) NOT NULL,
   CAPITOLO VARCHAR(50) NOT NULL,
   DESCRIZIONE_CAPITOLO VARCHAR(500),
   CODICE_PRODOTTO NUMBER(20) NOT NULL,
   ANNO_CAMPAGNA NUMBER(4) NOT NULL,
   FOREIGN KEY (ID_INTERVENTO) REFERENCES A4GD_INTERVENTO (ID)
);

CREATE TABLE A4GT_ISTRUTTORE_DISACCOPPIATO
   (	
    ID NUMBER(20,0) PRIMARY KEY, 
	VERSIONE NUMBER(10) NOT NULL, 
	BPS_SUPERFICIE NUMBER(20), 
	GREENING_SUPERFICIE NUMBER(20), 
	IMPORTO_SALARI NUMBER(20), 
	BPS_IMP_SAN NUMBER(20), 
	GIO_IMP_SAN NUMBER(20), 
	CONTROLLO_ANTIMAFIA NUMBER(1), 
	DOM_ANNO_PREC_NON_LIQ NUMBER(1), 
	BPS_SANZ_ANNO_PREC NUMBER(1), 
	GIO_SANZ_ANNO_PREC NUMBER(1), 
	NOTE_ISTRUTTORE CLOB,
    ANNULLO_RIDUZIONE NUMBER(1),
	ID_ISTRUTTORIA NUMBER(20) NOT NULL, 
	
	FOREIGN KEY (ID_ISTRUTTORIA)  REFERENCES A4GT_ISTRUTTORIA (ID)
);

CREATE TABLE A4GT_ESITO_MAN_PASCOLO (
   ID NUMBER(20) NOT NULL PRIMARY KEY,
   VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
   ID_PASCOLO_PARTICELLA NUMBER(20) NOT NULL,
   ID_ISTRUTTORIA NUMBER(20) NOT NULL,
   DATI_INPUT CLOB,
   DATI_OUTPUT CLOB,
   ESITO_MAN VARCHAR2(30)
);

CREATE TABLE A4GT_ISTRUTTORE_DIS_PASCOLI 
(	
	ID NUMBER(20,0) NOT NULL PRIMARY KEY, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL , 
	SUPERFICIE_DETERMINATA NUMBER(20,4), 
	CUAA_RESPONSABILE VARCHAR2(16), 
	DESCRIZIONE_PASCOLO VARCHAR2(40), 
	ESITO_CONTROLLO_MANTENIMENTO VARCHAR2(50), 
	VERIFICA_DOCUMENTAZIONE VARCHAR2(10), 
	ID_ISTRUTTORIA NUMBER(20,0) NOT NULL,
	
	FOREIGN KEY (ID_ISTRUTTORIA)  REFERENCES A4GT_ISTRUTTORIA (ID)
);

CREATE TABLE A4GT_ISTRUTTORE_SUPERFICIE 
(	
	ID NUMBER(20,0) NOT NULL PRIMARY KEY, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL , 
	CONTROLLO_SIGECO_LOCO NUMBER(1,0), 
	CONTROLLO_ANTIMAFIA NUMBER(1,0), 
	SUP_SOIA_M8 NUMBER(20,4), 
	SUP_FRUMENTO_M9 NUMBER(20,4), 
	SUP_PROTEAGINOSE_M10 NUMBER(20,4), 
	SUP_LEGUMINOSE_M11 NUMBER(20,4), 
	SUP_POMODORO_M14 NUMBER(20,4), 
	SUP_OLIVOSTANDARD_M15 NUMBER(20,4), 
	SUP_OLIVOPENDENZA_M16 NUMBER(20,4), 
	SUP_OLIVOQUALITA_M17 NUMBER(20,4),
    ANNULLO_RIDUZIONE NUMBER(1),
	ID_ISTRUTTORIA NUMBER(20,0) NOT NULL , 
	
	FOREIGN KEY (ID_ISTRUTTORIA)  REFERENCES A4GT_ISTRUTTORIA (ID)
);

CREATE TABLE A4GT_ISTRUTTORE_ZOOTECNIA 
(	
	ID NUMBER(20,0) NOT NULL PRIMARY KEY, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL , 
	CONTROLLO_SIGECO_LOCO NUMBER(1,0), 
	CONTROLLO_ANTIMAFIA NUMBER(1,0), 
	CUAA_SUBENTRANTE VARCHAR2(16),
    ANNULLO_RIDUZIONE NUMBER(1),
	ID_ISTRUTTORIA NUMBER(20,0) NOT NULL , 
	
	FOREIGN KEY (ID_ISTRUTTORIA)  REFERENCES A4GT_ISTRUTTORIA (ID)
);

CREATE TABLE A4GT_CONF_ISTRUTTORIA (
   ID NUMBER(19) NOT NULL,
   VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
   ANNO_CAMPAGNA NUMBER(4) NOT NULL,
   DT_SCADENZA_DOMANDE_INIZIALI DATE NOT NULL,
   PERC_PAGAMENTO NUMBER(3,2) NOT NULL,
   PERC_DISCIPLINA_FINANZIARIA NUMBER(9,8) NOT NULL,
   DT_SCADENZA_DOMANDE_MODIFICA DATE,

   CONSTRAINT PK_CONFIG_ISTRUTTORIA PRIMARY KEY (ID)
);


CREATE TABLE A4GT_POLITICA_AGRICOLA (
	ID NUMBER(20,0) NOT NULL, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL, 
	ANNO_INIZIO NUMBER(4,0) NOT NULL, 
	ANNO_FINE NUMBER(4,0) NOT NULL, 
	CODICE_PAC VARCHAR2(50) NOT NULL, 
	DESCRIZIONE_PAC VARCHAR2(500), 
	 CONSTRAINT PK_POLITICA_AGRICOLA PRIMARY KEY (ID)
);

CREATE TABLE A4GT_CONF_RICEVIBILITA (
   ID NUMBER(19) NOT NULL,
   VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
   ANNO_CAMPAGNA NUMBER(4) NOT NULL,
   DATA_RICEVIBILITA DATE NOT NULL,
   SCADENZA_DOM_INIZIALE_RITARDO DATE NOT NULL,
   SCADENZA_DOMANDA_RITIROPARZIAL DATE NOT NULL,
   SCADENZA_DOM_MODIFICA_RITARDO DATE,

   CONSTRAINT PK_CONF_RICEVIBILITA PRIMARY KEY (ID)
);

CREATE TABLE A4GT_SOSTEGNO (
	ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
	SOSTEGNO VARCHAR2(25) NOT NULL,
    ID_DOMANDA NUMBER(10) NOT NULL,
    CONSTRAINT PK_SOSTEGNO PRIMARY KEY (ID),
    FOREIGN KEY (ID_DOMANDA) REFERENCES A4GT_DOMANDA (ID)
);

CREATE UNIQUE INDEX A4GT_SOSTEGNO_UIDX ON A4GT_SOSTEGNO (SOSTEGNO,ID_DOMANDA);
