--  Creazione oggetti sistema A4G
--1. Sequence unica di generazione ID
CREATE SEQUENCE NXTNBR
  START WITH 1  
  NOCYCLE
  NOCACHE
  ORDER;

-- Tabella di Log unificata
CREATE TABLE A4GT_LOGGING (
   ID NUMBER(19) NOT NULL,
   VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
   UTENTE VARCHAR2(500 CHAR) NOT NULL,
   TIPO_EVENTO VARCHAR2(500 CHAR) NOT NULL,
   TABELLA VARCHAR2(4000) NOT NULL,
   ID_ENTITA NUMBER(19) NOT NULL,
   DT_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
   CONSTRAINT A4GT_LOGGING_PK PRIMARY KEY (ID)
);

-- Tabella gestione utenti
CREATE TABLE A4GT_UTENTE (
    ID NUMBER(19) NOT NULL,
    VERSIONE      NUMBER(10) DEFAULT 0 NOT NULL,
    IDENTIFICATIVO         VARCHAR2(50 CHAR) NOT NULL,
	CODICE_FISCALE         VARCHAR2(20 CHAR),
	NOME           VARCHAR2(50 CHAR),
	COGNOME           VARCHAR2(50 CHAR),
    CONSTRAINT A4GT_UTENTE_PK PRIMARY KEY (ID),
	CONSTRAINT A4GT_UTENTE_UIDX UNIQUE (IDENTIFICATIVO)
) ; 

-- Riferimenti aziende agricole
CREATE TABLE A4GT_AZIENDA_AGRICOLA (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    CUAA VARCHAR2(16) NOT NULL,
    CONSTRAINT A4GT_AZIENDA_AGRICOLA_UIDX UNIQUE (CUAA) ,
    CONSTRAINT A4GT_AZIENDA_AGRICOLA_PK PRIMARY KEY (ID) 
) ;

CREATE TABLE A4GR_UTENTE_AZIENDA (
    ID NUMBER(19) NOT NULL,
    VERSIONE      NUMBER(10) DEFAULT 0 NOT NULL,
    ID_UTENTE     NUMBER(19) NOT NULL,
    ID_AZIENDA    NUMBER(19) NOT NULL,
    ID_CARICA     NUMBER(19) NOT NULL,
    DATA_AGGIORNAMENTO DATE,
    CONSTRAINT A4GR_UTENTE_AZIENDA_PK PRIMARY KEY (ID),
    CONSTRAINT A4GR_UTENTE_AZIENDA_UIDX UNIQUE (ID_UTENTE, ID_AZIENDA),
	CONSTRAINT A4GR_UTENTE_AZIENDA_FK1 FOREIGN KEY (ID_UTENTE) REFERENCES A4GT_UTENTE (ID),
    CONSTRAINT A4GR_UTENTE_AZIENDA_FK2 FOREIGN KEY (ID_AZIENDA) REFERENCES A4GT_AZIENDA_AGRICOLA (ID)
) ; 

-- Codifiche stato compilazione dichiarazione antimafia
CREATE TABLE A4GD_STATO_DIC_ANTIMAFIA (
  ID NUMBER(19) NOT NULL,
  VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
  IDENTIFICATIVO VARCHAR2(500) NOT NULL,
  DESCRIZIONE VARCHAR2(4000) NOT NULL,
  CONSTRAINT A4GD_STATO_DIC_ANTIMAFIA_UIDX UNIQUE (IDENTIFICATIVO) ,
  CONSTRAINT A4GD_STATO_DIC_ANTIMAFIA_PK PRIMARY KEY (ID) 
) ;

-- Dati dichiarazioni antimafia aziende agricole
CREATE TABLE A4GT_DICHIARAZIONE_ANTIMAFIA (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    ID_AZIENDA_AGRICOLA NUMBER(19) NOT NULL,
    DATI_DICHIARAZIONE CLOB,
    ID_STATO NUMBER(19) NOT NULL,
    PDF_GENERATO BLOB,
    DT_GENERAZIONE_PDF DATE,
    PDF_FIRMATO BLOB,
    DT_UPLOAD_PDF_FIRMATO DATE,
    ID_DOC_PROTOCOLLATO NUMBER,
    RIF_PROTOCOLLO VARCHAR2(500),
    DT_INIZIO_COMPILAZIONE DATE,
    DT_ULTIMO_AGGIORNAMENTO DATE,
    ESITO VARCHAR2(2),
    ESITO_DATA_ELABORAZIONE DATE,
    ESITO_DESCRIZIONE VARCHAR2(500),
    ESITO_INVIO_AGEA VARCHAR2(2),
    ESITO_INVIO_BDNA VARCHAR2(2),
    CONSTRAINT A4GT_DIC_ANTIMAFIA_FK1 FOREIGN KEY (ID_AZIENDA_AGRICOLA) REFERENCES A4GT_AZIENDA_AGRICOLA (ID),
    CONSTRAINT A4GT_DIC_ANTIMAFIA_FK2 FOREIGN KEY (ID_STATO) REFERENCES A4GD_STATO_DIC_ANTIMAFIA (ID),
    CONSTRAINT A4GT_DIC_ANTIMAFIA_PK PRIMARY KEY (ID) 
);

-- Codifiche tipo allegato dichiaraizone antimafia
CREATE TABLE A4GD_TIPO_ALLEGATO (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    IDENTIFICATIVO VARCHAR2(500) NOT NULL,
    DESCRIZIONE VARCHAR2(4000) NOT NULL,
    CONSTRAINT A4GD_TIPO_ALLEGATO_UIDX UNIQUE (IDENTIFICATIVO) ,
    CONSTRAINT A4GD_TIPO_ALLEGATO_PK PRIMARY KEY (ID) 
) ;

-- Dati allegati alla dichiarazione antimafia
CREATE TABLE A4GT_ALLEGATO_DIC_ANTIMAFIA (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    ID_DICHIARAZIONE_ANTIMAFIA NUMBER(19) NOT NULL,
    ID_TIPO_ALLEGATO NUMBER(19) NOT NULL,
    PDF_ALLEGATO BLOB,
    DT_UPLOAD_PDF_ALLEGATO DATE,
    CONSTRAINT A4GT_ALLEGATO_DIC_AMF_FK1 FOREIGN KEY (ID_DICHIARAZIONE_ANTIMAFIA) REFERENCES A4GT_DICHIARAZIONE_ANTIMAFIA (ID),
    CONSTRAINT A4GT_ALLEGATO_DIC_AMF_FK2 FOREIGN KEY (ID_TIPO_ALLEGATO) REFERENCES A4GD_TIPO_ALLEGATO (ID),
    CONSTRAINT A4GT_ALLEGATO_DIC_AMF_PK PRIMARY KEY (ID)   
);

CREATE TABLE A4GT_ALLEGATO_DIC_FAM_CONV (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    ID_DICHIARAZIONE_ANTIMAFIA NUMBER(19) NOT NULL,
    CF_SOGGETTO_IMPRESA VARCHAR2(16) NOT NULL,
    COD_CARICA VARCHAR2(50) NOT NULL,
    PDF_DIC_FAM_CONV BLOB,
    DT_PDF_DIC_FAM_CONV DATE,
    ID_TIPO_ALLEGATO NUMBER(19) NOT NULL,
    CONSTRAINT A4GT_ALLEGATO_DIC_FAM_CONV_FK1 FOREIGN KEY (ID_DICHIARAZIONE_ANTIMAFIA) REFERENCES A4GT_DICHIARAZIONE_ANTIMAFIA (ID),
    CONSTRAINT A4GT_ALLEGATO_DIC_FAM_CONV_FK2 FOREIGN KEY (ID_TIPO_ALLEGATO) REFERENCES A4GD_TIPO_ALLEGATO (ID),
    CONSTRAINT A4GT_ALLEGATO_DIC_FAM_CONV PRIMARY KEY (ID)
);

alter table
   A4GT_DICHIARAZIONE_ANTIMAFIA
add
   ASSENZA_DT NUMBER(1);

ALTER TABLE A4GT_DICHIARAZIONE_ANTIMAFIA DROP COLUMN ID_DOC_PROTOCOLLATO;
ALTER TABLE A4GT_DICHIARAZIONE_ANTIMAFIA DROP COLUMN RIF_PROTOCOLLO;
		
ALTER TABLE A4GT_DICHIARAZIONE_ANTIMAFIA ADD DT_PROTOCOLLAZIONE DATE;
ALTER TABLE A4GT_DICHIARAZIONE_ANTIMAFIA ADD ID_PROTOCOLLO VARCHAR2(255);

ALTER TABLE A4GT_DICHIARAZIONE_ANTIMAFIA ADD DT_FINE DATE;

CREATE TABLE A4GT_NOTA (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    NOTA CLOB NOT NULL,
    TIPO VARCHAR2(32) NOT NULL,
    CHIAVE_ESTERNA VARCHAR2(50) NOT NULL,
    DT_INSERIMENTO DATE NOT NULL,
    UTENTE VARCHAR2(80),
    CONSTRAINT A4GT_NOTA PRIMARY KEY (ID)
);


CREATE TABLE A4GR_UTENTE_ENTE (
    ID_UTENTE     NUMBER(19) NOT NULL,
    ID_ENTE NUMBER(19) NOT NULL
);

CREATE TABLE A4GT_ENTE (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    IDENTIFICATIVO NUMBER(9) NOT NULL,
    DESCRIZIONE VARCHAR2(150),
    CAA VARCHAR2(100)
);

CREATE TABLE A4GT_PROCEDIMENTO_AMF 
(	
	ID NUMBER(20,0) NOT NULL, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL, 
	ID_DICHIARAZIONE NUMBER(20,0) NOT NULL, 
	PROCEDIMENTO VARCHAR2(50) NOT NULL, 
	 CONSTRAINT PK_PROCEDIMENTO_AMF PRIMARY KEY ("ID")
);

CREATE TABLE A4GT_EVENTSTORED(
	ID NUMBER(20,0) NOT NULL,
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL,
	EVENTO VARCHAR2(500) NOT NULL,
	JSON_EVENT CLOB NOT NULL,
   	USER_NAME VARCHAR2(100) NOT NULL,
	DATA_INSERIMENTO DATE NOT NULL,
	NUMERO_RETRY NUMBER(3,0) DEFAULT 0 NOT NULL,
	ERRORE CLOB,
	CONSTRAINT PK_EVENTSTORED PRIMARY KEY ("ID")

);

-- TODO: DA IMPLEMENTARE 
CREATE ALIAS JSON_VALUE AS '
String nextPrime(String value, String value2) {
    return "";
}';
