Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-656-000', '656-003-000-000-000', 
    'SUPERFICI SEMINABILI - POMODORINO DA DESTINARE ALLA TRASFORMAZIONE - POMODORINO DA DESTINARE ALLA TRASFORMAZIONE', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-656-001', '656-003-000-000-001', 
    'POMODORINO DA DESTINARE ALLA TRASFORMAZIONE-CANNELLINO FLEGREO (cod. Agea: 656-001)', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-656-002', '656-003-000-000-002', 
    'SUPERFICI SEMINABILI - POMODORINO DA DESTINARE ALLA TRASFORMAZIONE - CENTOSCOCCHE', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-656-003', '656-003-000-000-003', 
    'SUPERFICI SEMINABILI - POMODORINO DA DESTINARE ALLA TRASFORMAZIONE - PIENNOLO POLLENA', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-656-004', '656-003-000-000-004', 
    'SUPERFICI SEMINABILI - POMODORINO DA DESTINARE ALLA TRASFORMAZIONE - PIENNOLO VESUVIANO', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-656-005', '656-003-000-000-005', 
    'SUPERFICI SEMINABILI - POMODORINO DA DESTINARE ALLA TRASFORMAZIONE - PRINCIPE BORGHESE', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-656-006', '656-003-000-000-006', 
    'SUPERFICI SEMINABILI - POMODORINO DA DESTINARE ALLA TRASFORMAZIONE - PIENNOLO GIALLO', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-656-007', '656-003-000-000-007', 
    'SUPERFICI SEMINABILI - POMODORINO DA DESTINARE ALLA TRASFORMAZIONE - CORBARINO', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-656-009', '656-003-000-000-009', 
    'POMODORINO DA DESTINARE ALLA TRASFORMAZIONE-VESUVIANO  (cod. Agea: 656-009)', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-000', '134-003-000-001-000', 
    'SUPERFICI SEMINABILI - POMODORO - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-011', '134-003-000-001-011', 
    'SUPERFICI SEMINABILI - POMODORO - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONES. MARZANO', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-012', '134-003-000-001-012', 
    'POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE-S.MARZANO 20SMEC (cod. Agea: 658-012)', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-013', '134-003-000-001-013', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - PENDOLINO MARCHIGIANO', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-014', '134-003-000-001-014', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - POMODORO A PERA', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-015', '134-003-000-001-015', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - POMODORO CUOR DI BUE �ATIPICO�', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-016', '134-003-000-001-016', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - POMODORO VALENTINO', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-017', '134-003-000-001-017', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - QUARANTINO GRANDE', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-018', '134-003-000-001-018', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - QUARANTINO PICCOLO', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-019', '134-003-000-001-019', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - A CANCEDD', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-020', '134-003-000-001-020', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - A FOGLIA DI PATATA', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-021', '134-003-000-001-021', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - DARSECULO', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-022', '134-003-000-001-022', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - DELLA MARINA', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-023', '134-003-000-001-023', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - DI MOLA', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-024', '134-003-000-001-024', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - DI MORCIANO', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-025', '134-003-000-001-025', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - DI PANNI', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-026', '134-003-000-001-026', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - FIASCHELLO BATTIPAGLIESE', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-027', '134-003-000-001-027', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - FIASCHETTO', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-028', '134-003-000-001-028', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - GIALLO INVERNALE', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-029', '134-003-000-001-029', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - INVERNALE', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-030', '134-003-000-001-030', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - MANDURESE', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-031', '134-003-000-001-031', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - PIZZUTELLO', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-032', '134-003-000-001-032', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - PRUNILL''', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-033', '134-003-000-001-033', 
    'Superfici seminabili - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE - REGINA', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-658-999', '134-003-000-001-999', 
    'SUPERFICI SEMINABILI - POMODORO - POMODORO ALLUNGATO DA DESTINARE ALLA TRASFORMAZIONE ALTRE VARIETA', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-659-000', '134-003-000-003-000', 
    'SUPERFICI SEMINABILI - POMODORO - POMODORO TONDO DA DESTINARE ALLA TRASFORMAZIONE', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
Insert into A4GD_COLTURA_INTERVENTO
   (ID, VERSIONE, ANNO_INIZIO, CODICE_COLTURA_3, CODICE_COLTURA_5, 
    DESCRIZIONE_COLTURA, ID_INTERVENTO, LEGUMINOSE, COD_COLTURA_DIVERSA)
 Values
   (NXTNBR.NEXTVAL, 0, 2018, '040-659-999', '134-003-000-003-999', 
    'SUPERFICI SEMINABILI - POMODORO - POMODORO TONDO DA DESTINARE ALLA TRASFORMAZIONE ALTRE VARIETA', (SELECT ID FROM A4GD_INTERVENTO WHERE IDENTIFICATIVO_INTERVENTO = 'POMOD'), '0', 56175002);
COMMIT;
