--- Domanda acs FLMWFG75M12C794h - FLAIM WOLFGANG - DOMANDA 180955

Insert into A4GT_DOMANDA
   (ID, VERSIONE, NUMERO_DOMANDA, COD_MODULO_DOMANDA, DESC_MODULO_DOMANDA, 
    ANNO_CAMPAGNA, STATO, CUAA_INTESTATARIO, DT_PROTOCOLLAZIONE, COD_ENTE_COMPILATORE, 
    DESC_ENTE_COMPILATORE, RAGIONE_SOCIALE, DT_PRESENTAZIONE, ANNULLO_RIDUZIONE)
 Values (
 	NXTNBR.NEXTVAL, 3, 180955, 'BPS_2018', 'PAGAMENTI DIRETTI', 
    2018, 'IN_ISTRUTTORIA', 
    'FLMWFG75M12C794h', TO_DATE('04/16/2018 16:50:22', 'MM/DD/YYYY HH24:MI:SS'), 4, 
    'CAA COLDIRETTI DEL TRENTINO - 003', 'FLAIM WOLFGANG',
    TO_DATE('04/16/2018 16:49:51', 'MM/DD/YYYY HH24:MI:SS'),
    1);


Insert into A4GT_ISTRUTTORIA( ID, VERSIONE, ID_DOMANDA, SOSTEGNO, ID_STATO_LAVORAZIONE, TIPOLOGIA)
values(
	144144144,
	0,
	( SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'FLMWFG75M12C794h' ),
	'SUPERFICIE',
	( select id from a4gd_stato_lav_sostegno where identificativo = 'INTEGRATO' ),
	'SALDO');

COMMIT;
