package it.tndigitale.a4g.fascicolo.anagrafica.business.service.mail;

public enum EmailTemplateList {
	CAMBIO_SPORTELLO,
	REVOCA_ORDINARIA_MANDATO,
	NOTIFICA_RIFIUTA_REVOCA_IMMEDIATA_AL_TITOLARE,
	NOTIFICA_RIFIUTA_REVOCA_IMMEDIATA_A_APPAG,
	NOTIFICA_ACCETTA_REVOCA_IMMEDIATA_AL_TITOLARE,
	NOTIFICA_ACCETTA_REVOCA_IMMEDIATA_A_APPAG,
	NOTIFICA_RESPINTA_VALIDAZIONE_CAA,
	NOTIFICA_VALIDAZIONE_APPROVATA_CAA,
	NOTIFICA_VALIDAZIONE_APPROVATA_AZIENDA
}
