INSERT INTO A4GD_TIPO_CONDUZIONE VALUES (nxtnbr.nextval, 0, 'PRO', 'PROPRIETÀ');
INSERT INTO A4GD_TIPO_CONDUZIONE VALUES (nxtnbr.nextval, 0, 'AFF', 'AFFITTO');
INSERT INTO A4GD_TIPO_CONDUZIONE VALUES (nxtnbr.nextval, 0, 'MEZ', 'MEZZADRIA');
INSERT INTO A4GD_TIPO_CONDUZIONE VALUES (nxtnbr.nextval, 0, 'ALT', 'ALTRO');


			
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'PRO'), 0, 'IND', 'PROPRIETÀ INDIVISA');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'PRO'), 0, 'NUD', 'NUDA PROPRIETÀ');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'PRO'), 0, 'IRR', 'IRREPERIBILITÀ');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'PRO'), 0, 'COM', 'COMPROPRIETÀ');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'PRO'), 0, 'CBC', 'COMUNIONE DEI BENI FRA CONIUGI');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'PRO'), 0, 'USC', 'USUCAPIONE');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'PRO'), 0, 'CON', 'CONFERIMENTO DI SUPERFICIDA PARTE DI UN SOCIO');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'AFF'), 0, 'GIO', 'AFFITTO A "GIOVANI AGRICOLTORI"');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'AFF'), 0, 'SCR', 'AFFITTO SCRITTO');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'AFF'), 0, 'VER', 'AFFITTO VERBALE');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'MEZ'), 0, 'MEZ', 'MEZZADRIA');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'MEZ'), 0, 'COL', 'COLONIA PARZIARIA');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'ALT'), 0, 'ENF', 'ENFITEUSI');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'ALT'), 0, 'AFE', 'AFFRANCAZIONE DELL''ENFITEUSI');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'ALT'), 0, 'CIV', 'USO CIVICO');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'ALT'), 0, 'USU', 'USUFRUTTO');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'ALT'), 0, 'CLB', 'CONCESSIONE E LOCAZIONE DI BENI IMMOBILI DEMANIALI');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'ALT'), 0, 'CSR', 'COMODATO SCRITTO');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'ALT'), 0, 'CVR', 'COMODATO VERBALE');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'ALT'), 0, 'OGG', 'USO OGGETTIVO');
INSERT INTO A4GD_SOTTOTIPO_CONDUZIONE VALUES (nxtnbr.nextval, (SELECT id FROM A4GD_TIPO_CONDUZIONE WHERE codice = 'ALT'), 0, 'MON', 'ZONE MONTANE');
 

COMMIT;