-- Creazione oggetti comuni del sistema fascicolo-anagrafica
DROP ALL OBJECTS;

-- Versione 1.0

CREATE ALIAS TO_DATE_ALT AS '
java.util.Date toDate(String s, String dateFormat) throws Exception { 
  return new java.text.SimpleDateFormat(dateFormat).parse(s); 
} 
';

-- 1. Sequence
CREATE SEQUENCE NXTNBR
    START WITH 100000
    NOCYCLE
    NOCACHE;

-- 2. Tabella di Log
CREATE TABLE A4GT_LOGGING (
    ID BIGINT NOT NULL,    
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    UTENTE VARCHAR2(500 CHAR) NOT NULL,
    TIPO_EVENTO VARCHAR2(500 CHAR) NOT NULL,
    TABELLA VARCHAR2(4000) NOT NULL,
    ID_ENTITA BIGINT NOT NULL,
    DT_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT A4GT_LOGGING_PK PRIMARY KEY (ID)
);

CREATE TABLE A4GT_LOGGING_VALIDAZIONE (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    UTENTE VARCHAR2(500 CHAR) NOT NULL,
    TIPO_EVENTO VARCHAR2(500 CHAR) NOT NULL,
    TABELLA VARCHAR2(4000) NOT NULL,
    ID_ENTITA BIGINT NOT NULL,
    DT_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT A4GT_LOGGING_VALIDAZIONE_PK PRIMARY KEY (ID)
);


CREATE TABLE A4GT_EVENTSTORED(
    ID NUMBER(20,0) NOT NULL,
    VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL,
    EVENTO VARCHAR2(500) NOT NULL,
    JSON_EVENT CLOB NOT NULL,
    USER_NAME VARCHAR2(100) NOT NULL,
    DATA_INSERIMENTO DATE NOT NULL,
    NUMERO_RETRY NUMBER(3,0) DEFAULT 0 NOT NULL,
    ERRORE CLOB,
    CONSTRAINT PK_EVENTSTORED PRIMARY KEY (ID)
);

