DELETE FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA = (
	SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CHNRLB69M46F000I'
);

DELETE FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CHNRLB69M46F000I';

DELETE FROM A4GT_PROCESSO WHERE ID = 986789;

COMMIT;
