DELETE FROM A4GT_ISTRUTTORIA WHERE ID_DOMANDA in (
	SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CHNRLB69M46F000Y'
);

DELETE FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CHNRLB69M46F000Y';

DELETE FROM A4GT_PROCESSO WHERE ID = 986789;

COMMIT;
