INSERT INTO A4GT_DOMANDA (
	ID, VERSIONE, NUMERO_DOMANDA, COD_MODULO_DOMANDA, DESC_MODULO_DOMANDA,
	ANNO_CAMPAGNA,
	STATO,
	CUAA_INTESTATARIO,
	DT_PRESENTAZIONE,
	NUM_DOMANDA_RETTIFICATA, COD_ENTE_COMPILATORE, DESC_ENTE_COMPILATORE, RAGIONE_SOCIALE,
	DT_PROTOCOLLAZIONE,
	DT_PRESENTAZ_ORIGINARIA, DT_PROTOCOLLAZ_ORIGINARIA,
	IBAN
) VALUES (
	300, 0, 123456, 'BPS_2018', 'PAGAMENTI DIRETTI',
	2018,
	'IN_ISTRUTTORIA',
	'CHNRLB69M46F000I',
	to_date('13/04/2018 02:00:00','dd/mm/yyyy hh24:mi:ss'),
	null, '4', 'CAA COLDIRETTI DEL TRENTINO - 003', 'BONADIMAN CLAUDIO',
	to_date('13/04/2018 02:00:00','dd/mm/yyyy hh24:mi:ss','DD-MON-RR'),
	null, null,
	'IT10G0585634270081571373413'
);

INSERT INTO A4GT_ISTRUTTORIA (
	ID, VERSIONE,
	ID_DOMANDA,
	SOSTEGNO,
	ID_STATO_LAVORAZIONE,
	BLOCCATA_BOOL, ERRORE_CALCOLO, TIPOLOGIA
) VALUES (
	300, 0,
	(SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CHNRLB69M46F000I'),
	'DISACCOPPIATO',
	(select id from a4gd_stato_lav_sostegno where identificativo = 'RICHIESTO'),
	1, 1, 'SALDO'
);

INSERT INTO A4GT_PROCESSO (
	ID, VERSIONE, ID_DATI_SETTORE,
	TIPO,
	STATO,
	DT_INIZIO,
	DT_FINE,
	PERCENTUALE_AVANZAMENTO,
	DATI_ELABORAZIONE
) VALUES (
	986789, 0, NULL,
	'SBLOCCO_ISTRUTTORIE',
	'RUN',
	to_date('07-FEB-19','DD-MON-RR'),
	to_date('08-FEB-19','DD-MON-RR'),
	0,
	'{"totaleDomandeGestite":"0","domandeGestite":[],"domandeConProblemi":[],"numeroDomandeDaElaborare":"1"}'
);


COMMIT;