-- Inserisco i CAA
INSERT INTO A4GT_CAA
(ID, VERSIONE, CODICE_FISCALE, DENOMINAZIONE, PARTITA_IVA, FORMA_GIURIDICA, ATTO_RICONOSCIMENTO, SOCIETA_SERVIZI, CF_SOCIETA_SERVIZI, DESCRIZIONE_ESTESA, CODICE_ISTAT, FRAZIONE, TOPONIMO, VIA, NUMERO_CIVICO, CAP, PROVINCIA, COMUNE , EMAIL)
VALUES(693, 0, '01896970223', 'CAA COOPTRENTO SRL', '01896970223', 'SOCIETA A RESPONSABILITA LIMITATA', 'determinazione del Dirigente del Servizio Vigilanza e Promozione delle Attività Agricole n. 282 del 23 agosto 2011', NULL, NULL, NULL, NULL, NULL, 'VIA BRENNERO 322', 'VIA BRENNERO', '322', '38121', 'TN', 'TRENTO' , 'pippo@pippo.com');

INSERT INTO A4GT_CAA
(ID, VERSIONE, CODICE_FISCALE, DENOMINAZIONE, PARTITA_IVA, FORMA_GIURIDICA, ATTO_RICONOSCIMENTO, SOCIETA_SERVIZI, CF_SOCIETA_SERVIZI, DESCRIZIONE_ESTESA, CODICE_ISTAT, FRAZIONE, TOPONIMO, VIA, NUMERO_CIVICO, CAP, PROVINCIA, COMUNE)
VALUES(697, 0, '01159210226', 'AGRICOLTURA TRENTINA SERVIZI S.R.L.', '01159210226', 'SOCIETA A RESPONSABILITA LIMITATA', 'determinazione del Dirigente del Servizio Vigilanza e Promozione delle Attività Agricole n. 283 del 24 agosto 2011', 'AGRISERVICE SOCIETA COOPERATIVA', '01075220226', NULL, NULL, NULL, 'VIA GUARDINI 73', 'VIA GUARDINI', '73', '38121', 'TN', 'TRENTO');

INSERT INTO A4GT_CAA
(ID, VERSIONE, CODICE_FISCALE, DENOMINAZIONE, PARTITA_IVA, FORMA_GIURIDICA, ATTO_RICONOSCIMENTO, SOCIETA_SERVIZI, CF_SOCIETA_SERVIZI, DESCRIZIONE_ESTESA, CODICE_ISTAT, FRAZIONE, TOPONIMO, VIA, NUMERO_CIVICO, CAP, PROVINCIA, COMUNE)
VALUES(694, 0, '01904670229', 'CENTRO ASSISTENZA IMPRESE COLDIRETTI DEL TRENTINO S.R.L.', '01904670229', 'SOCIETA A RESPONSABILITA LIMITATA', 'determinazione del Dirigente del Servizio Vigilanza e Promozione delle Attività Agricole n. 284 del 25 agosto 2011', 'IMPRESA VERDE TRENTINO ALTO ADIGE S.R.L.', '01676700220', NULL, NULL, NULL, 'VIA KUFSTEIN 2', 'VIA KUFSTEIN', '2', '38121', 'TN', 'TRENTO');

-- Inserisco gli sportelli
INSERT INTO A4GT_SPORTELLO
(ID, VERSIONE, IDENTIFICATIVO, DENOMINAZIONE, COMUNE, ID_CAA)
VALUES(722, 0, 93, 'CAA COOPTN - CS - LAVIS', 'LAVIS', 693);
INSERT INTO A4GT_SPORTELLO
(ID, VERSIONE, IDENTIFICATIVO, DENOMINAZIONE, COMUNE, ID_CAA)
VALUES(723, 0, 94, 'CAA COOPTN - CS - TRENTO', 'TRENTO', 693);
INSERT INTO A4GT_SPORTELLO
(ID, VERSIONE, IDENTIFICATIVO, DENOMINAZIONE, COMUNE, ID_CAA)
VALUES(733, 0, 104, 'CAA COOPTN - CS - ISERA', 'ISERA', 693);
INSERT INTO A4GT_SPORTELLO
(ID, VERSIONE, IDENTIFICATIVO, DENOMINAZIONE, COMUNE, ID_CAA)
VALUES(716, 0, 56, 'CAA ATS - 004 - MEZZOLOMBARDO', 'MEZZOLOMBARDO', 697);
INSERT INTO A4GT_SPORTELLO
(ID, VERSIONE, IDENTIFICATIVO, DENOMINAZIONE, COMUNE, ID_CAA)
VALUES(717, 0, 57, 'CAA ATS - 005 - ROVERETO', 'ROVERETO', 697);
INSERT INTO A4GT_SPORTELLO
(ID, VERSIONE, IDENTIFICATIVO, DENOMINAZIONE, COMUNE, ID_CAA)
VALUES(698, 0, 3, 'CAA COLDIRETTI DEL TRENTINO - 001', 'TRENTO', 694);
INSERT INTO A4GT_SPORTELLO
(ID, VERSIONE, IDENTIFICATIVO, DENOMINAZIONE, COMUNE, ID_CAA)
VALUES(699, 0, 4, 'CAA COLDIRETTI DEL TRENTINO - 003', 'CLES', 694);



INSERT INTO A4GT_PERSONA (ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(50, 0, 0, 'LRCPLA50M11H612B');
INSERT INTO A4GT_PERSONA (ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(1747, 0, 0, '00123890220');


INSERT INTO A4GT_PERSONA_FISICA
(ID, ID_VALIDAZIONE, VERSIONE, NOME, COGNOME, SESSO, DATA_NASCITA, COMUNE_NASCITA, PROVINCIA_NASCITA, DECEDUTO,
    DESCRIZIONE_ESTESA, TOPONIMO, VIA, NUMERO_CIVICO, CAP, CODICE_ISTAT, FRAZIONE, PROVINCIA, COMUNE,
    DENOMINAZIONE, PARTITA_IVA, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA,
    SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT,
    SEDE_FRAZIONE, SEDE_PROVINCIA, SEDE_COMUNE, PEC)
VALUES(50, 0 , 0, 'nome', 'cognome', 'MASCHIO', to_date('21-09-2018', 'dd-mm-yyyy'), '', '', 0,
    '', '', '', '', '', '', '', '', '',
    '', '', to_date('21-09-2018', 'dd-mm-yyyy'), '', 0, 0,
    '', '', '', '', '',
    '', '', '', '', 'pec@example.com');

INSERT INTO A4GT_PERSONA_GIURIDICA
(ID, ID_VALIDAZIONE, VERSIONE, PARTITA_IVA, DENOMINAZIONE, FORMA_GIURIDICA, OGGETTO_SOCIALE, DATA_COSTITUZIONE, DATA_TERMINE, CAPITALE_SOCIALE_DELIBERATO, CF_RAPPRESENTANTE_LEGALE, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_FRAZIONE, SEDE_PROVINCIA, SEDE_COMUNE, NOME_RAPPRESENTANTE_LEGALE, PEC, TELEFONO)
VALUES(1747, 0, 0, '00123890220', 'FERRARI F.LLI LUNELLI S.P.A.', 'SOCIETA'' PER AZIONI', 'OGGETTO_SOCIALE', NULL, NULL, NULL, 'LNLMTB74A31F205S', to_date('16-11-1970', 'dd-mm-yyyy'), 'TN', 76693, 0, 'VIA DEL PONTE 15', NULL, NULL, NULL, '38123', NULL, NULL, 'TN', NULL, 'LUNELLI MATTEO BRUNO', 'INFO@PEC.CANTINEFERRARI.IT', '081081081');


INSERT INTO A4GT_FASCICOLO(ID, VERSIONE, CUAA, DENOMINAZIONE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, STATO, ORGANISMO_PAGATORE, UTENTE_MODIFICA, DATA_MODIFICA)
VALUES(11, 0 , 'LRCPLA50M11H612B', 'denominazione', 50 , 0, 'IN_AGGIORNAMENTO', 'APPAG', 'Utente Modifica', to_date('01-01-2020', 'dd-mm-yyyy'));

INSERT INTO A4GT_FASCICOLO(ID, VERSIONE, CUAA, DENOMINAZIONE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, STATO, ORGANISMO_PAGATORE, UTENTE_MODIFICA, DATA_MODIFICA)
VALUES(12, 0 , '00123890220', 'denominazione', 1747, 0, 'IN_AGGIORNAMENTO', 'APPAG', 'Utente Modifica', to_date('01-01-2020', 'dd-mm-yyyy'));

-- detenzione corrente
INSERT INTO A4GT_DETENZIONE
(ID, ID_VALIDAZIONE, VERSIONE, DATA_INIZIO, DATA_FINE, ID_FASCICOLO, FASCICOLO_ID_VALIDAZIONE)
VALUES(1857, 0, 0, to_date('17-10-2018', 'dd-mm-yyyy'), to_date('20-09-2020', 'dd-mm-yyyy'), 11, 0);


INSERT INTO A4GT_MANDATO
(ID, ID_VALIDAZIONE, VERSIONE, CONTRATTO, IDENTIFICATIVO_SPORTELLO, DATA_SOTTOSCRIZIONE)
VALUES(1857, 0, 0, 'AAAA', 93, to_date('17-10-2018', 'dd-mm-yyyy'));

-- detenzione programmata
INSERT INTO A4GT_DETENZIONE
(ID, ID_VALIDAZIONE, VERSIONE, DATA_INIZIO, DATA_FINE, ID_FASCICOLO, FASCICOLO_ID_VALIDAZIONE)
VALUES(1858, 0, 0, to_date('21-09-2020', 'dd-mm-yyyy'), NULL, 11, 0);

INSERT INTO A4GT_MANDATO
(ID, ID_VALIDAZIONE, VERSIONE, CONTRATTO, IDENTIFICATIVO_SPORTELLO, DATA_SOTTOSCRIZIONE)
VALUES(1858, 0, 0, 'AAAA', 94 , to_date('21-09-2020', 'dd-mm-yyyy'));

-- detenzione non dell'azienda
--INSERT INTO A4GT_DETENZIONE
--(ID, ID_VALIDAZIONE, VERSIONE, DATA_INIZIO, DATA_FINE, ID_FASCICOLO, FASCICOLO_ID_VALIDAZIONE)
--VALUES(1859, 0, 0, to_date('02-05-2020', 'dd-mm-yyyy'), to_date('01-09-2020', 'dd-mm-yyyy'), 12, 0);

--INSERT INTO A4GT_MANDATO
--(ID, ID_VALIDAZIONE, VERSIONE, CONTRATTO, IDENTIFICATIVO_SPORTELLO, DATA_SOTTOSCRIZIONE)
--VALUES(1859, 0, 0, 'AAAA', 57, to_date('02-05-2020', 'dd-mm-yyyy'));


-- ... che ha già fatto una revoca
--INSERT INTO A4GT_DETENZIONE
--(ID, ID_VALIDAZIONE, VERSIONE, DATA_INIZIO, DATA_FINE, ID_FASCICOLO, FASCICOLO_ID_VALIDAZIONE)
--VALUES(1860, 0, 0, to_date('01-01-2020', 'dd-mm-yyyy'), NULL, 12, 0);

--INSERT INTO A4GT_MANDATO
--(ID, ID_VALIDAZIONE, VERSIONE, CONTRATTO, IDENTIFICATIVO_SPORTELLO, DATA_SOTTOSCRIZIONE)
--VALUES(1860, 0, 0, 'AAAA', 56, to_date('01-01-2020', 'dd-mm-yyyy'));


INSERT INTO A4GT_REVOCA_IMMEDIATA
(ID, VERSIONE, DATA_SOTTOSCRIZIONE, STATO, ID_MANDATO, MANDATO_ID_VALIDAZIONE, CODICE_FISCALE, ID_PROTOCOLLO, DT_PROTOCOLLO, DATA_VALUTAZIONE, MOTIVAZIONE_RIFIUTO, CAUSA_RICHIESTA)
VALUES
(4681, 1, TO_DATE('11/18/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'DA_VALUTARE', 1858, 0, 'LRCPLA50M11H612B', 'PAT_TEST/XXXXXX-XX/XX/XXXX-XXXXXX1', TO_DATE('11/18/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), null, null, null);

INSERT INTO A4GT_REVOCA_IMMEDIATA
(ID, VERSIONE, DATA_SOTTOSCRIZIONE, STATO, ID_MANDATO, MANDATO_ID_VALIDAZIONE, CODICE_FISCALE, ID_PROTOCOLLO, DT_PROTOCOLLO, DATA_VALUTAZIONE, MOTIVAZIONE_RIFIUTO, CAUSA_RICHIESTA)
VALUES
(4682, 1,TO_DATE('11/18/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'RIFIUTATA', 1858, 0, 'LRCPLA50M11H612B', 'PAT_TEST/XXXXXX-XX/XX/XXXX-XXXXXX2', TO_DATE('11/18/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('11/20/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), null, null);


INSERT INTO A4GT_REVOCA_IMMEDIATA
(ID, VERSIONE, DATA_SOTTOSCRIZIONE, STATO, ID_MANDATO, MANDATO_ID_VALIDAZIONE, CODICE_FISCALE, ID_PROTOCOLLO, DT_PROTOCOLLO, DATA_VALUTAZIONE, MOTIVAZIONE_RIFIUTO, CAUSA_RICHIESTA)
VALUES
(4683, 1, TO_DATE('11/19/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'DA_VALUTARE', 1858, 0, 'LRCPLA50M11H612B', 'PAT_TEST/XXXXXX-XX/XX/XXXX-XXXXXX3', TO_DATE('11/19/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), null, null, null);

INSERT INTO A4GT_REVOCA_IMMEDIATA
(ID, VERSIONE, DATA_SOTTOSCRIZIONE, STATO, ID_MANDATO, MANDATO_ID_VALIDAZIONE, CODICE_FISCALE, ID_PROTOCOLLO, DT_PROTOCOLLO, DATA_VALUTAZIONE, MOTIVAZIONE_RIFIUTO, CAUSA_RICHIESTA)
VALUES
(4684, 1, TO_DATE('11/19/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'RIFIUTATA', 1858, 0, 'LRCPLA50M11H612B', 'PAT_TEST/XXXXXX-XX/XX/XXXX-XXXXXX4', TO_DATE('11/19/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('11/20/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), null, null);

-- revoca per altro mandato
--INSERT INTO A4GT_REVOCA_IMMEDIATA
--(ID, VERSIONE, DATA_SOTTOSCRIZIONE, STATO, ID_MANDATO, MANDATO_ID_VALIDAZIONE, CODICE_FISCALE, ID_PROTOCOLLO, DT_PROTOCOLLO, DATA_VALUTAZIONE, MOTIVAZIONE_RIFIUTO, CAUSA_RICHIESTA)
--VALUES
--(4685, 1, TO_DATE('11/19/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'RIFIUTATA', 1859, 0, 'ZZZZZZ50Z11Z612Z', 'PAT_TEST/ZZZZZZ-ZZ/ZZ/ZZZZ-ZZZZZZ1', TO_DATE('11/19/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('11/19/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), null, null);

