-- inserisco i CAA
INSERT INTO A4GT_CAA
(ID, VERSIONE, CODICE_FISCALE, DENOMINAZIONE, PARTITA_IVA, FORMA_GIURIDICA, ATTO_RICONOSCIMENTO, SOCIETA_SERVIZI, CF_SOCIETA_SERVIZI, DESCRIZIONE_ESTESA, CODICE_ISTAT, FRAZIONE, TOPONIMO, VIA, NUMERO_CIVICO, CAP, PROVINCIA, COMUNE , EMAIL)
VALUES(693, 0, '01896970223', 'CAA COOPTRENTO SRL', '01896970223', 'SOCIETA A RESPONSABILITA LIMITATA', 'determinazione del Dirigente del Servizio Vigilanza e Promozione delle Attività Agricole n. 282 del 23 agosto 2011', NULL, NULL, NULL, NULL, NULL, 'VIA BRENNERO 322', 'VIA BRENNERO', '322', '38121', 'TN', 'TRENTO' , 'pippo@pippo.com');

INSERT INTO A4GT_CAA
(ID, VERSIONE, CODICE_FISCALE, DENOMINAZIONE, PARTITA_IVA, FORMA_GIURIDICA, ATTO_RICONOSCIMENTO, SOCIETA_SERVIZI, CF_SOCIETA_SERVIZI, DESCRIZIONE_ESTESA, CODICE_ISTAT, FRAZIONE, TOPONIMO, VIA, NUMERO_CIVICO, CAP, PROVINCIA, COMUNE)
VALUES(694, 0, '01904670229', 'CENTRO ASSISTENZA IMPRESE COLDIRETTI DEL TRENTINO S.R.L.', '01904670229', 'SOCIETA A RESPONSABILITA LIMITATA', 'determinazione del Dirigente del Servizio Vigilanza e Promozione delle Attività Agricole n. 284 del 25 agosto 2011', 'IMPRESA VERDE TRENTINO ALTO ADIGE S.R.L.', '01676700220', NULL, NULL, NULL, 'VIA KUFSTEIN 2', 'VIA KUFSTEIN', '2', '38121', 'TN', 'TRENTO');

-- inserisco gli sportelli
INSERT INTO A4GT_SPORTELLO
(ID, VERSIONE, IDENTIFICATIVO, DENOMINAZIONE, COMUNE, ID_CAA)
VALUES(722, 0, 93, 'CAA COOPTN - CS - LAVIS', 'LAVIS', 693);

INSERT INTO A4GT_SPORTELLO
(ID, VERSIONE, IDENTIFICATIVO, DENOMINAZIONE, COMUNE, ID_CAA)
VALUES(698, 0, 3, 'CAA COLDIRETTI DEL TRENTINO - 001', 'TRENTO', 694);

-- creo la persona
INSERT INTO A4GT_PERSONA (ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(50, 0 , 0,'LRCPLA50M11H612B');

INSERT INTO A4GT_PERSONA_FISICA
(ID, ID_VALIDAZIONE, VERSIONE, NOME, COGNOME, SESSO, DATA_NASCITA, COMUNE_NASCITA, PROVINCIA_NASCITA, DECEDUTO,
    DESCRIZIONE_ESTESA, TOPONIMO, VIA, NUMERO_CIVICO, CAP, CODICE_ISTAT, FRAZIONE, PROVINCIA, COMUNE,
    DENOMINAZIONE, PARTITA_IVA, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA,
    SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_FRAZIONE, SEDE_PROVINCIA, SEDE_COMUNE)
VALUES(50, 0, 0, 'nome', 'cognome', 'MASCHIO', to_date('21-09-2018', 'dd-mm-yyyy'), '', '', 0,
    '', '', '', '', '', '', '', '', '',
    '', '', to_date('21-09-2018', 'dd-mm-yyyy'), '', 0, 0,
    '', '', '', '', '', '', '', '', '');

-- creo il fascicolo
INSERT INTO A4GT_FASCICOLO(ID, VERSIONE, CUAA, DENOMINAZIONE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, STATO, ORGANISMO_PAGATORE, UTENTE_MODIFICA, DATA_MODIFICA)
VALUES(11, 0 , 'LRCPLA50M11H612B', 'denominazione', 50 , 0, 'IN_AGGIORNAMENTO', 'APPAG', 'Utente Modifica', to_date('01-01-2020', 'dd-mm-yyyy'));

-- detenzione corrente
INSERT INTO A4GT_DETENZIONE (ID, ID_VALIDAZIONE, VERSIONE, DATA_INIZIO, DATA_FINE, ID_FASCICOLO, FASCICOLO_ID_VALIDAZIONE)
VALUES(1857, 0, 0, to_date('17-10-2020', 'dd-mm-yyyy'), null, 11, 0);

INSERT INTO A4GT_MANDATO
(ID, VERSIONE, CONTRATTO, IDENTIFICATIVO_SPORTELLO, DATA_SOTTOSCRIZIONE)
VALUES(1857, 0, 'AAAA', 93, to_date('17-10-2018', 'dd-mm-yyyy'));