package it.tndigitale.a4gistruttoria.dto.domandaunica;

public enum ErroreControlloRicevibilitaDomanda {

	// PRESENTAZIONE_NEI_TERMINI
	PRESENTAZIONE_NEI_TERMINI,

	// DOMANDA_CARTACEA_FIRMATA
	DOMANDA_CARTACEA_FIRMATA,

	// ANOMALIE_COMPILAZIONE_AGS
	ANOMALIE_COMPILAZIONE_AGS,

	// FASCICOLO_AGGIORNATO
	FASCICOLO_AGGIORNATO,

	// ARCHIVIAZIONE_DOCUMENTI_OK
	ARCHIVIAZIONE_DOCUMENTI_OK;

}
