INSERT INTO A4GT_PERSONA
(ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(2792, 0, 0, 'FNTDNL86E05L378J');

INSERT INTO A4GT_PERSONA
(ID, ID_VALIDAZIONE, VERSIONE, CODICE_FISCALE)
VALUES(2792, 1, 0, 'FNTDNL86E05L378J');

INSERT INTO A4GT_PERSONA_FISICA
(ID, ID_VALIDAZIONE, VERSIONE, NOME, COGNOME, SESSO, DATA_NASCITA, COMUNE_NASCITA, PROVINCIA_NASCITA, DECEDUTO, DENOMINAZIONE, PARTITA_IVA, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, DESCRIZIONE_ESTESA, TOPONIMO, VIA, NUMERO_CIVICO, CAP, CODICE_ISTAT, FRAZIONE, PROVINCIA, COMUNE, PEC, TELEFONO, FORMA_GIURIDICA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_PROVINCIA, SEDE_COMUNE, SEDE_FRAZIONE, SEDE_CC_DESCRIZIONE_ESTESA, SEDE_CC_TOPONIMO, SEDE_CC_VIA, SEDE_CC_NUMERO_CIVICO, SEDE_CC_CAP, SEDE_CC_CODICE_ISTAT, SEDE_CC_PROVINCIA, SEDE_CC_COMUNE, SEDE_CC_FRAZIONE)
VALUES(2792, 0, 0, 'DANIELE', 'FONTANA', 'MASCHIO', TIMESTAMP '1986-05-05 00:00:00.000000', 'TRENTO', 'TN', 0, 'FONTANA                  DANIELE', '01919650224', TIMESTAMP '2005-03-21 00:00:00.000000', 'TN', 187463, 0, 'VIA SANT''AGATA N 12 A', NULL, NULL, NULL, '38098', NULL, NULL, 'TN', 'TRENTO', 'daniele.fontana1986@pec.agritel.it', '0461669024', 'IMPRESA INDIVIDUALE', 'VIA S. AGATA 12/A', NULL, NULL, NULL, '38010', NULL, 'TN', 'TRENTO', NULL, NULL, 'VIA', 'S. AGATA', '12/A', '38010', '022080', 'TRENTO', 'FAEDO', NULL);

INSERT INTO A4GT_PERSONA_FISICA
(ID, ID_VALIDAZIONE, VERSIONE, NOME, COGNOME, SESSO, DATA_NASCITA, COMUNE_NASCITA, PROVINCIA_NASCITA, DECEDUTO, DENOMINAZIONE, PARTITA_IVA, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, DESCRIZIONE_ESTESA, TOPONIMO, VIA, NUMERO_CIVICO, CAP, CODICE_ISTAT, FRAZIONE, PROVINCIA, COMUNE, PEC, TELEFONO, FORMA_GIURIDICA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_PROVINCIA, SEDE_COMUNE, SEDE_FRAZIONE, SEDE_CC_DESCRIZIONE_ESTESA, SEDE_CC_TOPONIMO, SEDE_CC_VIA, SEDE_CC_NUMERO_CIVICO, SEDE_CC_CAP, SEDE_CC_CODICE_ISTAT, SEDE_CC_PROVINCIA, SEDE_CC_COMUNE, SEDE_CC_FRAZIONE)
VALUES(2792, 1, 0, 'DANIELE', 'FONTANA', 'MASCHIO', TIMESTAMP '1986-05-05 00:00:00.000000', 'TRENTO', 'TN', 0, 'FONTANA                  DANIELE', '01919650224', TIMESTAMP '2005-03-21 00:00:00.000000', 'TN', 187463, 0, 'VIA SANT''AGATA N 12 A', NULL, NULL, NULL, '38098', NULL, NULL, 'TN', 'ROVERETO', 'daniele.fontana1986@pec.agritel.it', '0461669024', 'IMPRESA INDIVIDUALE', 'VIA S. AGATA 12/A', NULL, NULL, NULL, '38010', NULL, 'TN', 'ROVERETO', NULL, NULL, 'VIA', 'S. AGATA', '12/A', '38010', '022080', 'TRENTO', 'FAEDO', NULL);