insert into A4GT_PERSONA (ID, ID_VALIDAZIONE,VERSIONE,CODICE_FISCALE) values (NXTNBR.NEXTVAL,0,0,'DPDNDR77B03L378X');

insert into A4GT_PERSONA_FISICA (ID, ID_VALIDAZIONE,VERSIONE,NOME,COGNOME,SESSO,DATA_NASCITA,COMUNE_NASCITA,PROVINCIA_NASCITA,DECEDUTO) values (NXTNBR.CURRVAL,0,0,'ANDREA','DEPEDRI','MASCHIO',SYSDATE,'TRENTO','TRENTINO',0);

INSERT INTO A4GT_FASCICOLO (ID, ID_VALIDAZIONE, VERSIONE,  CUAA, STATO, DENOMINAZIONE, ORGANISMO_PAGATORE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, UTENTE_MODIFICA, DATA_MODIFICA)
	VALUES (NXTNBR.NEXTVAL, 0, 0, 'DPDNDR77B03L378X', 'IN_AGGIORNAMENTO','DEPEDRI ANDREA', 'APPAG', NXTNBR.CURRVAL-1, 0, 'Utente Modifica', to_date('01-01-2020', 'dd-mm-yyyy'));
	
insert into A4GT_PERSONA (ID, ID_VALIDAZIONE,VERSIONE,CODICE_FISCALE) values (NXTNBR.NEXTVAL,0,0,'00959460221');

INSERT INTO A4GT_PERSONA_GIURIDICA (ID, ID_VALIDAZIONE, VERSIONE, PARTITA_IVA, DENOMINAZIONE, FORMA_GIURIDICA, OGGETTO_SOCIALE, DATA_COSTITUZIONE, DATA_TERMINE, CAPITALE_SOCIALE_DELIBERATO, CF_RAPPRESENTANTE_LEGALE, NOME_RAPPRESENTANTE_LEGALE, DATA_ISCRIZIONE, PROVINCIA_CCIAA, NUMERO_REPERTORIO, CESSATA, SEDE_DESCRIZIONE_ESTESA, SEDE_TOPONIMO, SEDE_VIA, SEDE_NUMERO_CIVICO, SEDE_CAP, SEDE_CODICE_ISTAT, SEDE_FRAZIONE, SEDE_PROVINCIA, SEDE_COMUNE) 
VALUES(NXTNBR.CURRVAL, 0, 0, '00959460221', 'denominazione', '', '', NULL , NULL , 0, 'DPDNDR77B03L378X', 'Mario Rossi', NULL , '', 0, 0, '', '', '', '', '', '', '', '', '');

INSERT INTO A4GT_FASCICOLO (ID, ID_VALIDAZIONE, VERSIONE,  CUAA, STATO, DENOMINAZIONE, ORGANISMO_PAGATORE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, UTENTE_MODIFICA, DATA_MODIFICA)
VALUES (NXTNBR.NEXTVAL, 0, 0, '00959460221', 'IN_AGGIORNAMENTO','SEVEN S.P.A.', 'APPAG', NXTNBR.CURRVAL-1, 0, 'Utente Modifica', to_date('01-01-2020', 'dd-mm-yyyy'));

COMMIT;