insert into A4GT_PERSONA (ID, ID_VALIDAZIONE,VERSIONE,CODICE_FISCALE)
	values (NXTNBR.NEXTVAL,0,0,'DPDNDR77B03L378X');

insert into A4GT_PERSONA_FISICA (ID, ID_VALIDAZIONE,VERSIONE,NOME,COGNOME,SESSO,DATA_NASCITA,COMUNE_NASCITA,PROVINCIA_NASCITA,DECEDUTO)
	values (NXTNBR.CURRVAL,0,0,'ANDREA','DEPEDRI','MASCHIO',SYSDATE,'TRENTO','TRENTINO',0);

INSERT INTO A4GT_FASCICOLO (ID, ID_VALIDAZIONE, VERSIONE,  CUAA, STATO, DENOMINAZIONE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, ORGANISMO_PAGATORE, UTENTE_MODIFICA, DATA_MODIFICA)
	VALUES(NXTNBR.NEXTVAL, 0, 0, 'DPDNDR77B03L378X', 'IN_AGGIORNAMENTO','DEPEDRI ANDREA', NXTNBR.CURRVAL-1, 0, 'APPAG', 'Utente Modifica', to_date('01-01-2020', 'dd-mm-yyyy'));

COMMIT;