Insert into A4GT_PERSONA (ID, ID_VALIDAZIONE,VERSIONE,CODICE_FISCALE) values (5,0,0,'12345678901');

Insert into A4GT_PERSONA_GIURIDICA (ID, ID_VALIDAZIONE,VERSIONE,PARTITA_IVA,DENOMINAZIONE,CF_RAPPRESENTANTE_LEGALE,NOME_RAPPRESENTANTE_LEGALE)
values (5,0,0,'00000000000','PIPPO PLUTO SPA','MRTLNZ72M30L378I','Rappresentante di test');
							
Insert into A4GT_PERSONA (ID, ID_VALIDAZIONE,VERSIONE,CODICE_FISCALE) values (10,0,0,'07343031006');

INSERT INTO A4GT_CAA (ID, VERSIONE, CODICE_FISCALE, DENOMINAZIONE, PARTITA_IVA, FORMA_GIURIDICA, ATTO_RICONOSCIMENTO, SOCIETA_SERVIZI, CF_SOCIETA_SERVIZI, DESCRIZIONE_ESTESA, CODICE_ISTAT, FRAZIONE, TOPONIMO, VIA, NUMERO_CIVICO, CAP, PROVINCIA, COMUNE, EMAIL)
VALUES (1, 0, '07343031006', 'CAA - TEST', '07343031006', 'SOCIETA A RESPONSABILITA LIMITATA', 'determinazione del Dirigente del Servizio Vigilanza e Promozione delle Attività Agricole n. 282 del 23 agosto 2011', NULL, NULL, NULL, NULL, NULL, 'VIA BRENNERO 322', 'VIA BRENNERO', '322', '38121', 'TN', 'TRENTO', 'a4g-test@tndigit.it');

insert into A4GT_SPORTELLO (ID,VERSIONE,IDENTIFICATIVO,DENOMINAZIONE,ID_CAA) 
values (11,0,11,'SPORTELLO - OLD', 1);

insert into A4GT_SPORTELLO (ID,VERSIONE,IDENTIFICATIVO,DENOMINAZIONE,ID_CAA) 
values (13,0,13,'SPORTELLO - NEW', 1);

INSERT INTO A4GT_FASCICOLO (ID, ID_VALIDAZIONE, VERSIONE, CUAA, STATO, DENOMINAZIONE, ID_PERSONA, PERSONA_ID_VALIDAZIONE, ORGANISMO_PAGATORE, UTENTE_MODIFICA, DATA_MODIFICA)
VALUES(1, 0, 0, '12345678901', 'IN_AGGIORNAMENTO','PIPPO PLUTO SPA', 5, 0, 'APPAG', 'Utente Modifica', to_date('01-01-2020', 'dd-mm-yyyy'));

INSERT INTO A4GT_DETENZIONE (ID, ID_VALIDAZIONE, VERSIONE, DATA_INIZIO, DATA_FINE, ID_FASCICOLO)
VALUES(30, 0, 0, to_date('01/06/2020 22:00:00', 'dd/mm/yyyy HH24:MI:SS'), NULL, 1);

INSERT INTO A4GT_MANDATO (ID, VERSIONE, IDENTIFICATIVO_SPORTELLO, CONTRATTO, DATA_SOTTOSCRIZIONE)
VALUES(30, 0, 11, 'AAAA', to_date('01/06/2020 22:00:00', 'dd/mm/yyyy HH24:MI:SS'));


