package it.tndigitale.a4gistruttoria.util;

public enum GruppoControllo {
	AMMISSIBILITA, MAN, GREENING, RIDUZIONE, SANZIONI, GIOVANE, FINALE, LIQUIDABILE, INTERSOSTEGNO, ACC_SUPERFICIE, ACC_ZOOTECNIA
}
