package it.tndigitale.a4gistruttoria.util;

public enum TipoStatoLavorazioneSostegno {

	CALCOLO_PREMIO_ACCOPPIATO_ZOOTECNIA, CALCOLO_ACCOPPIATO_SUPERFICIE, CONTROLLO_LIQUIDABILITA_ACCOPPIATO_SUPERFICIE, CONTROLLO_LIQUIDABILITA_ACCOPPIATO_ZOOTECNIA, NON_AMMISSIBILITA, LIQUIDAZIONE
}
