DELETE FROM A4GT_FATTURE_CLIENTI;
DELETE FROM A4GT_CLIENTE;
DELETE FROM A4GT_ALLEGATI_CONSUNTIVI;
DELETE FROM A4GT_CONSUNTIVI_CONSUMI;
DELETE FROM A4GT_TRASFERIMENTI;
DELETE FROM A4GT_PRELIEVI;
DELETE FROM A4GT_DICHIARAZIONE_CONSUMI;
DELETE FROM A4GT_UTILIZZO_MACCHINARI;
DELETE FROM A4GT_FABBISOGNO_FABBRICATI;
DELETE FROM A4GT_FABBISOGNO;
DELETE FROM A4GT_FABBRICATI;
DELETE FROM A4GT_RICHIESTA_CARBURANTE;

COMMIT;