delete from TAB_AGRI_UMAL_ALLEGATI_CONSUNTIVI;
DELETE FROM TAB_AGRI_UMAL_CONSUNTIVI_CONSUMI;
DELETE FROM TAB_AGRI_UMAL_DICHIARAZIONE_CONSUMI;
DELETE FROM TAB_AGRI_UMAL_FABBISOGNO_FABBRICATI;
DELETE FROM TAB_AGRI_UMAL_FABBISOGNO;
DELETE FROM TAB_AGRI_UMAL_FABBRICATI;
DELETE FROM TAB_AGRI_UMAL_RICHIESTA_CARBURANTE;

COMMIT;