export const environment = {
  production: false,
  backendUrl: 'http://localhost:4200/',
  frontendUrl: 'http://localhost:4200/',
  srTrentoUrl: 'https://srt-test.infotn.it/private/welcome.aspx',
  mobileUrl: "http://localhost:4200/",
  agsUrl: 'http://siap-test.infotn.it',
  tipoLogin: 'cittadino',
  indexPage: 'http://localhost:4201',
  annoInizioCampagnaUma: 2021,
  dtAperturaRevocaImmediata: new Date(new Date().getFullYear(), 0, 1),
  dtChiusuraRevocaImmediata: new Date(new Date().getFullYear(), 11, 31, 23, 59, 59),
  TIMEOUT_SPINNER: 120000,
  anniGis: [2022],
  annoCorrenteGis: 2022,
  verificaFirmaFascicolo: false,
};
