export enum VerificaFirmaErrorEnum {
    FIRMATARIO_TITOLARE_DIVERSI = 'FIRMATARIO_TITOLARE_DIVERSI',
    FILE_NON_FIRMATO = 'FILE_NON_FIRMATO',
    FIRMA_NON_VALIDA = 'FIRMA_NON_VALIDA',
    DATI_FIRMATARIO_MANCANTI = 'DATI_FIRMATARIO_MANCANTI',
    FIRMATARIO_NON_UNIVOCO = 'FIRMATARIO_NON_UNIVOCO'
}