delete FROM A4GT_ISTRUTTORE_ZOOTECNIA where ID_ISTRUTTORIA in (SELECT id FROM A4GT_ISTRUTTORIA  where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CHNRLB69M46F000I'));
delete FROM A4GT_ISTRUTTORE_SUPERFICIE where ID_ISTRUTTORIA in (SELECT id FROM A4GT_ISTRUTTORIA  where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CHNRLB69M46F000I'));
delete FROM A4GT_ISTRUTTORE_DIS_PASCOLI where ID_ISTRUTTORIA in (SELECT id FROM A4GT_ISTRUTTORIA  where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CHNRLB69M46F000I'));
delete FROM A4GT_ISTRUTTORE_DISACCOPPIATO where ID_ISTRUTTORIA in (SELECT id FROM A4GT_ISTRUTTORIA  where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CHNRLB69M46F000I'));

delete FROM A4GT_ANOM_DOMANDA_SOSTEGNO where ID_PASSO_LAVORAZIONE in (20,21,22,23,24,25,26,27, 28);
delete FROM A4GT_PASSO_TRANSIZIONE where ID_TRANSIZ_SOSTEGNO in (10,11,12,13,14,15,16,17, 18);
delete FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA in (400,401,402,403,404,405,406,407, 408);

delete FROM A4GT_ISTRUTTORIA where id_domanda = (SELECT ID FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CHNRLB69M46F000I');
delete FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'CHNRLB69M46F000I';

COMMIT;