delete from A4GT_ANOM_DOMANDA_SOSTEGNO
where id_passo_lavorazione in (select id
FROM A4GT_PASSO_TRANSIZIONE where ID_TRANSIZ_SOSTEGNO in 
(select id FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA = 999111));

delete FROM A4GT_PASSO_TRANSIZIONE where id_transiz_sostegno in (SELECT ID FROM A4GT_TRANSIZIONE_ISTRUTTORIA WHERE ID_ISTRUTTORIA = 999111);
delete FROM A4GT_TRANSIZIONE_ISTRUTTORIA where ID_ISTRUTTORIA = 999111;
delete FROM A4GT_ISTRUTTORIA where id = 999111;
delete FROM A4GT_DATI_EREDE where id = 999111;
delete FROM A4GT_DOMANDA WHERE CUAA_INTESTATARIO = 'BNDCLD69S12C999Z';

COMMIT;