DROP ALL OBJECTS;
-- Versione 1.0

CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR "org.h2gis.functions.factory.H2GISFunctions.load";
CALL H2GIS_SPATIAL();

-- 1. Sequence
CREATE SEQUENCE NXTNBR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
    
-- 2. Tabella di Log
CREATE TABLE A4GT_LOGGING (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    UTENTE VARCHAR2(500 CHAR) NOT NULL,
    TIPO_EVENTO VARCHAR2(500 CHAR) NOT NULL,
    TABELLA VARCHAR2(4000) NOT NULL,
    ID_ENTITA NUMBER(19) NOT NULL,
    DT_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT A4GT_LOGGING_PK PRIMARY KEY (ID)
);


CREATE TABLE A4SD_CODI_RILE_PCG 
   (	ID NUMBER(20,0) NOT NULL ENABLE, 
	VERSIONE NUMBER(10,0) NOT NULL ENABLE, 
	CODI_RILE VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	DESC_RILE VARCHAR2(500 BYTE), 
	CODI_PROD_RILE VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	DESC_PROD_RILE VARCHAR2(500 BYTE), 
	DATA_INIZIO DATE, 
	DATA_FINE DATE, 
	CODI_RILE_PREVALENTE VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	DESC_RILE_PREVALENTE VARCHAR2(500 BYTE), 
	 CONSTRAINT A4SD_CODI_RILE_PCG_PK PRIMARY KEY (ID), 
	 CONSTRAINT A4SD_CODI_RILE_PCG__UN UNIQUE (CODI_RILE, CODI_PROD_RILE)
   ) ;

CREATE TABLE a4sr_supporto_tag_tipo_suolo (
	ID NUMBER(20,0) NOT NULL ENABLE, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	id_suolo_dichiarato   NUMBER(10) NOT NULL,
	id_suolo_rilevato     NUMBER(10) NOT NULL,
	upas_dichiarato       NUMBER(1),
	upas_rilevato         NUMBER(1),
	CONSTRAINT a4sr_supp_tag_tipo_s_pk PRIMARY KEY ( id ),
	CONSTRAINT a4s_s_tag_pr_un UNIQUE ( id_suolo_dichiarato ),
	CONSTRAINT a4s_s_tag_pr_rich_un UNIQUE ( id_suolo_dichiarato, id_suolo_rilevato )
);

CREATE TABLE a4st_suolo_rilevato (
	ID NUMBER(20,0) NOT NULL ENABLE, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	id_richiesta           NUMBER(10) NOT NULL,
	id_isola               NUMBER(10),
	id_suol_gis_rilevato   NUMBER(10),
	shape                  geometry,
	note_caricamento       VARCHAR2(500),
	AREA number (20,6),
	codi_rile_rilevato  VARCHAR2(3),
	codi_prod_rile_rilevato   VARCHAR2(3),
	CONSTRAINT a4s_suolo_ril_pk PRIMARY KEY ( id )
);

CREATE TABLE A4ST_RICHIESTA_MODIFICA_SUOLO (
	ID NUMBER(20,0) NOT NULL ENABLE, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	UTENTE VARCHAR2(50 BYTE), 
	DATA_RICHIESTA DATE, 
	TIPO VARCHAR2(50 BYTE), 
	STATO VARCHAR2(50 BYTE), 
	ESITO VARCHAR2(50 BYTE), 
	CUAA VARCHAR2(16 BYTE), 
	AZIENDA VARCHAR2(100 BYTE), 
	CAMPAGNA NUMBER(4,0) NOT NULL ENABLE, 
	ID_ISTANZA_RIESAME NUMBER, 
	VISIBILE_IN_ORTOFOTO NUMBER(1,0), 
	TIPO_INTERVENTO_COLTURALE VARCHAR2(50 BYTE), 
	INTERVENTO_INIZIO DATE, 
	INTERVENTO_FINE DATE
);

CREATE TABLE a4st_lavorazione_suolo (
	id                 		  NUMBER(10) NOT NULL ENABLE,
    versione           		  NUMBER(10) NOT NULL ENABLE,
	utente                    VARCHAR2(50),
	stato                     VARCHAR2(50),
	data_inizio_lavorazione   DATE,
	data_fine_lavorazione     DATE,
	note                      VARCHAR2(4000),
	titolo                    VARCHAR2(50),
	sopralluogo               VARCHAR2(100),
	data_ultima_modifica	  DATE,
	utente_ags				  VARCHAR2(100),
	campagna                  NUMBER(4, 0) DEFAULT 2022 NOT NULL ENABLE,
	MODALITA_ADL 			  VARCHAR2(50) DEFAULT 'POLIGONI_INTERI' NOT NULL ENABLE,
	X_ULTIMO_ZOOM 			  NUMBER(20, 8),
	Y_ULTIMO_ZOOM 			  NUMBER(20, 8),
	SCALA_ULTIMO_ZOOM 		  NUMBER(20, 8),
	ID_LAVORAZIONE_PADRE  	  NUMBER(10, 0)
);

CREATE TABLE A4ST_SUOLO_DICHIARATO(	
	ID NUMBER(20,0) NOT NULL ENABLE, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	ID_RICHIESTA NUMBER(20,0) NOT NULL ENABLE, 
	ID_ISOLA NUMBER(10,0) NOT NULL ENABLE, 
	COD_ISOLA VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	COD_SEZIONE VARCHAR2(10 BYTE), 
	ID_SUOL_GIS NUMBER(10,0) NOT NULL ENABLE, 
	CODI_RILE_DICHIARATO VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	CODI_PROD_RILE_DICHIARATO VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	TIPO_SUOLO_DICHIARATO VARCHAR2(50 BYTE), 
	TIPO_SUOLO_RILEVATO VARCHAR2(50 BYTE), 
	ID_LAVORAZIONE NUMBER(10,0), 
	NOTE_CARICAMENTO VARCHAR2(500 BYTE),
	SHAPE geometry,
    NUOVA_MODIFICA_BO NUMBER(1) DEFAULT 0 NOT NULL ,
    NUOVA_MODIFICA_CAA NUMBER(1) DEFAULT 0 NOT NULL,
    VISIBILE_IN_ORTOFOTO NUMBER(1),
    TIPO_INTERVENTO_COLTURALE VARCHAR2(50 BYTE),
    INTERVENTO_INIZIO DATE,
    INTERVENTO_FINE DATE
);
ALTER TABLE a4st_suolo_dichiarato ADD CONSTRAINT A4S_SUOLO_DIC_RICH_M_FK FOREIGN KEY ( ID_RICHIESTA )    REFERENCES A4ST_RICHIESTA_MODIFICA_SUOLO ( ID );
ALTER TABLE a4st_suolo_dichiarato ADD CONSTRAINT A4S_SUOLO_DIC_LAV_SUOLO_FK FOREIGN KEY ( ID_LAVORAZIONE )        REFERENCES A4ST_LAVORAZIONE_SUOLO ( ID );
ALTER TABLE a4st_suolo_dichiarato ADD CONSTRAINT a4st_s_dich_codi_rile_pcg_fk FOREIGN KEY ( codi_rile_dichiarato,
																				  codi_prod_rile_dichiarato )
						REFERENCES a4sd_codi_rile_pcg ( codi_rile,
														codi_prod_rile );

CREATE TABLE a4st_messaggio_richiesta (
    id                     NUMBER(10) NOT NULL,
    versione               NUMBER(10) NOT NULL,
    id_richiesta           NUMBER(10),
    id_poligono_dichiarato NUMBER(10),
    utente                 VARCHAR2(50) NOT NULL,
    profilo_utente         VARCHAR2(50) NOT NULL,
    data_inserimento       DATE NOT NULL,
    testo                  VARCHAR2(4000) NOT NULL
);
ALTER TABLE a4st_messaggio_richiesta ADD CONSTRAINT a4st_mess_rich_m_dic_fk FOREIGN KEY ( id_poligono_dichiarato ) REFERENCES a4st_suolo_dichiarato ( id ) NOT DEFERRABLE;
ALTER TABLE a4st_messaggio_richiesta ADD CONSTRAINT a4st_mess_rich_m_suolo_fk FOREIGN KEY ( id_richiesta ) REFERENCES a4st_richiesta_modifica_suolo ( id );

CREATE TABLE a4st_documentazione_richiesta (
    id                     NUMBER(10) NOT NULL,
    versione               NUMBER(10) NOT NULL,
    id_richiesta           NUMBER(10),
    id_poligono_dichiarato NUMBER(10),
    nome_file              VARCHAR2(500) NOT NULL,
    descrizione            VARCHAR2(500),
    dimensione             NUMBER(10) NOT NULL,
    utente                 VARCHAR2(50) NOT NULL,
    profilo_utente         VARCHAR2(50) NOT NULL,
    data_inserimento       DATE NOT NULL,
    doc_content            BLOB
);
ALTER TABLE a4st_documentazione_richiesta ADD CONSTRAINT a4s_doc_rich_m_dic_fk FOREIGN KEY ( id_poligono_dichiarato ) REFERENCES a4st_suolo_dichiarato ( id ) NOT DEFERRABLE;
ALTER TABLE a4st_documentazione_richiesta ADD CONSTRAINT a4s_doc_rich_m_suolo_fk FOREIGN KEY ( id_richiesta ) REFERENCES a4st_richiesta_modifica_suolo ( id );

CREATE TABLE A4ST_GRIGLIA_SUOLO (
    ID               NUMBER(20, 0)       NOT NULL ENABLE,
    VERSIONE         NUMBER(10, 0)        NOT NULL ENABLE,
    AREA             NUMBER(20,6),
    INTERSECA_SUOLO  NUMBER(1, 0),
    CONFINE          NUMBER(1, 0),
    SHAPE geometry 
);

CREATE TABLE A4SD_STATO_COLT (
    ID                  NUMBER(20, 0)        NOT NULL ENABLE,
    VERSIONE            NUMBER(10, 0) DEFAULT 0        NOT NULL ENABLE,
    STATO_COLT          NUMBER(3, 0),
    DESCRIZIONE         VARCHAR2(500 BYTE),
    DESC_BREVE          VARCHAR2(50 BYTE),
    DATA_INIZIO         DATE,
    DATA_FINE           DATE,
    DATA_AGGIORNAMENTO  DATE,
    NOTE                VARCHAR2(500 BYTE)
);

CREATE TABLE A4SD_USO_SUOLO (
    ID             NUMBER(20, 0)        NOT NULL ENABLE,
    VERSIONE       NUMBER(10, 0)        NOT NULL ENABLE,
    COD_USO_SUOLO  VARCHAR2(3 BYTE),
    DESCRIZIONE    VARCHAR2(500 BYTE),
    DATA_INIZIO    DATE,
    DATA_FINE      DATE,
    VISUALIZZA_BO  NUMBER
  );
  
CREATE TABLE A4ST_SUOLO (
    ID                       NUMBER(20, 0)        NOT NULL ENABLE,
    VERSIONE                 NUMBER(10, 0)        NOT NULL ENABLE,
    ID_GRID                  NUMBER(3, 0)        NOT NULL ENABLE,
    ISTATP                   VARCHAR2(3 BYTE)        NOT NULL ENABLE,
    COD_USO_SUOLO            VARCHAR2(3 BYTE)        NOT NULL ENABLE,
    STATO_COLT               NUMBER(2, 0)        NOT NULL ENABLE,
	area_colt                NUMBER(20,6),    
    SORGENTE                 VARCHAR2(50 BYTE),
    ID_LAVORAZIONE_INIZIO    NUMBER(10, 0)        NOT NULL ENABLE,
    ID_LAVORAZIONE_FINE      NUMBER(10, 0),
    DATA_INIZIO_VALIDITA     DATE        NOT NULL ENABLE,
    DATA_FINE_VALIDITA       DATE,
    CAMPAGNA                 NUMBER(4, 0),
    ID_LAVORAZIONE_IN_CORSO  NUMBER(10, 0),
    NOTE                     VARCHAR2(4000 BYTE),
    SHAPE GEOMETRY 
);
ALTER TABLE A4ST_SUOLO ADD CONSTRAINT A4S_USO_SUOLO_GRIGLIA_SUOLO_FK FOREIGN KEY ( ID_GRID )     REFERENCES A4ST_GRIGLIA_SUOLO ( ID );
ALTER TABLE A4ST_SUOLO ADD CONSTRAINT A4S_USO_SUOLO_L_SUOLO_FKV1 FOREIGN KEY ( ID_LAVORAZIONE_FINE )        REFERENCES A4ST_LAVORAZIONE_SUOLO ( ID );
ALTER TABLE A4ST_SUOLO ADD  CONSTRAINT A4S_USO_SUOLO_L_SUOLO_FKV2 FOREIGN KEY ( ID_LAVORAZIONE_IN_CORSO )        REFERENCES A4ST_LAVORAZIONE_SUOLO ( ID );
ALTER TABLE A4ST_SUOLO ADD  CONSTRAINT A4S_USO_SUOLO_LAV_SUOLO_FK FOREIGN KEY ( ID_LAVORAZIONE_INIZIO )        REFERENCES A4ST_LAVORAZIONE_SUOLO ( ID );
ALTER TABLE A4ST_SUOLO ADD  CONSTRAINT A4ST_SUOLO_DEC_S_COLT_FK FOREIGN KEY ( STATO_COLT )        REFERENCES A4SD_STATO_COLT ( STATO_COLT );
ALTER TABLE A4ST_SUOLO ADD  CONSTRAINT  A4ST_SUOLO_DEC_COU_US_FK FOREIGN KEY ( COD_USO_SUOLO )        REFERENCES A4SD_USO_SUOLO ( COD_USO_SUOLO );
   
 

CREATE TABLE A4ST_WORKSPACE_LAV_SUOLO (
    ID                      NUMBER(20, 0)        NOT NULL ENABLE,
    VERSIONE                NUMBER(10, 0)        DEFAULT 0         NOT NULL ENABLE,
    ID_LAVORAZIONE          NUMBER(20, 0)        NOT NULL ENABLE,
    SHAPE                   GEOMETRY,
    COD_USO_SUOLO           VARCHAR2(3 BYTE)     NOT NULL ENABLE,
    STATO_COLT              NUMBER(3, 0)         NOT NULL ENABLE,
    NOTE                    VARCHAR2(4000 BYTE),
    data_ultima_modifica    DATE ,
    AREA                    number (20,6),
    ISTATP                  VARCHAR2(3),
    ID_GRID                 number(20,0),
    id_lavorazione_orig     NUMBER(20),
    sorgente                VARCHAR2(50 BYTE)
);
ALTER TABLE A4ST_WORKSPACE_LAV_SUOLO ADD CONSTRAINT A4S_WS_L_SU_DEC_S_COLT_FK FOREIGN KEY ( STATO_COLT )  REFERENCES A4SD_STATO_COLT ( STATO_COLT );
ALTER TABLE A4ST_WORKSPACE_LAV_SUOLO ADD CONSTRAINT A4S_L_SUOLO_FK FOREIGN KEY ( ID_LAVORAZIONE )        REFERENCES A4ST_LAVORAZIONE_SUOLO ( ID );
ALTER TABLE A4ST_WORKSPACE_LAV_SUOLO ADD CONSTRAINT A4ST_W_L_SUOLO_DEC_COD_US_FK FOREIGN KEY ( COD_USO_SUOLO )        REFERENCES A4SD_USO_SUOLO ( COD_USO_SUOLO );
ALTER TABLE A4ST_WORKSPACE_LAV_SUOLO ADD CONSTRAINT A4ST_W_L_ID_GRID_FK FOREIGN KEY ( ID_GRID )    REFERENCES A4ST_GRIGLIA_SUOLO ( ID );
ALTER TABLE A4ST_WORKSPACE_LAV_SUOLO ADD CONSTRAINT A4S_WS_L_SUOLO_ORIG_FK FOREIGN KEY (ID_LAVORAZIONE_ORIG) REFERENCES A4ST_LAVORAZIONE_SUOLO (ID);

ALTER TABLE A4ST_SUOLO_DICHIARATO add AREA number (20,6);
ALTER TABLE A4ST_SUOLO_DICHIARATO add AREA_ORI number (20,6);
ALTER TABLE A4ST_SUOLO_DICHIARATO add ESITO VARCHAR2(100) default 'DA_LAVORARE' NOT NULL;

ALTER TABLE a4sr_supporto_tag_tipo_suolo
	ADD CONSTRAINT a4s_su_tag_tipo_s_dic_fk FOREIGN KEY ( id_suolo_dichiarato )
		REFERENCES a4st_suolo_dichiarato ( id )
	NOT DEFERRABLE;
ALTER TABLE a4sr_supporto_tag_tipo_suolo
	ADD CONSTRAINT a4s_su_tag_tipo_s_rilevato_fk FOREIGN KEY ( id_suolo_rilevato )
		REFERENCES a4st_suolo_rilevato ( id )
	NOT DEFERRABLE;
ALTER TABLE a4st_suolo_rilevato
	ADD CONSTRAINT a4s_suolo_ril_rich_m_fk FOREIGN KEY ( id_richiesta )
		REFERENCES a4st_richiesta_modifica_suolo ( id )
	NOT DEFERRABLE;
	
CREATE VIEW A4SV_SUOLO_DICH_LAVORAZIONE (ID_SUOLO_DICH,
					ID_RICHIESTA,
					STATO_RICHIESTA,
					CUAA,
					AZIENDA,
					CAMPAGNA,
					TIPO_SUOLO_DICHIARATO,
					TIPO_SUOLO_RILEVATO,
					SHAPE,
					AREA_ORI,
					CODI_RILE_DICHIARATO,
					DESC_RILE_DICHIARATO,
					CODI_PROD_RILE_DICHIARATO,
					DESC_PROD_RILE_DICHIARATO,
					CODI_RILE_PREVALENTE_DICH,
					DESC_RILE_PREVALENTE_DICH,
					COD_SEZIONE,
					CODI_RILE_RILEVATO,
					DESC_RILE_RILEVATO,
					CODI_PROD_RILE_RILEVATO,
					DESC_PROD_RILE_RILEVATO,
					CODI_RILE_PREVALENTE_RIL,
					DESC_RILE_PREVALENTE_RIL,
					ESITO_DICHIARATO,
					ID_LAVORAZIONE,
					STATO_LAVORAZIONE,
                    UTENTE_LAVORAZIONE,
					NUOVA_MODIFICA_BO,
                    NUOVA_MODIFICA_CAA,
                    VISIBILE_IN_ORTOFOTO,
                    TIPO_INTERVENTO_COLTURALE,
                    INTERVENTO_INIZIO,
                    INTERVENTO_FINE) AS
		  select
						D.ID              ID_SUOLO_DICH,
						R.ID              ID_RICHIESTA,
						R.STATO STATO_RICHIESTA,
						R.CUAA,
						R.AZIENDA,
						R.CAMPAGNA,
						D.TIPO_SUOLO_DICHIARATO,
						D.TIPO_SUOLO_RILEVATO,
						d.shape,
						D.AREA_ORI,
						D.CODI_RILE_DICHIARATO ,
						V.DESC_RILE DESC_RILE_DICHIARATO,
						D.CODI_PROD_RILE_DICHIARATO,
						V.DESC_PROD_RILE DESC_PROD_RILE_DICHIARATO,
						V.CODI_RILE_PREVALENTE CODI_RILE_PREVALENTE_DICH,
						V.DESC_RILE_PREVALENTE  DESC_RILE_PREVALENTE_DICH,
						D.COD_SEZIONE,
						SR.CODI_RILE_RILEVATO,
						VR.DESC_RILE DESC_RILE_RILEVATO,
						SR.CODI_PROD_RILE_RILEVATO,
						VR.DESC_PROD_RILE DESC_PROD_RILE_RILEVATO,
						VR.CODI_RILE_PREVALENTE CODI_RILE_PREVALENTE_RIL,
						VR.DESC_RILE_PREVALENTE    DESC_RILE_PREVALENTE_RIL,
						D.ESITO ESITO_DICHIARATO,
						D.ID_LAVORAZIONE,
						LAVORAZIONE.STATO STATO_LAVORAZIONE,
						LAVORAZIONE.UTENTE UTENTE_LAVORAZIONE,
						D.NUOVA_MODIFICA_BO,
                        D.NUOVA_MODIFICA_CAA,
                        D.VISIBILE_IN_ORTOFOTO,
                        D.TIPO_INTERVENTO_COLTURALE,
                        D.INTERVENTO_INIZIO,
			            D.INTERVENTO_FINE
					FROM
						A4ST_RICHIESTA_MODIFICA_SUOLO R
						INNER JOIN A4ST_SUOLO_DICHIARATO         D ON R.ID = D.ID_RICHIESTA
						LEFT JOIN A4SD_CODI_RILE_PCG  V ON V.CODI_RILE = D.CODI_RILE_DICHIARATO AND  V.CODI_PROD_RILE = D.CODI_PROD_RILE_DICHIARATO
						LEFT JOIN A4SR_SUPPORTO_TAG_TIPO_SUOLO  ST ON ST.ID_SUOLO_DICHIARATO = D.ID
						LEFT JOIN A4ST_SUOLO_RILEVATO           SR ON SR.ID = ST.ID_SUOLO_RILEVATO
						LEFT JOIN A4SD_CODI_RILE_PCG  VR ON VR.CODI_RILE = SR.CODI_RILE_RILEVATO AND  VR.CODI_PROD_RILE = SR.CODI_PROD_RILE_RILEVATO
						LEFT JOIN A4ST_LAVORAZIONE_SUOLO        LAVORAZIONE ON LAVORAZIONE.ID = D.ID_LAVORAZIONE;
						
CREATE TABLE A4ST_LAYER (
	ID          NUMBER(20, 0)        NOT NULL ENABLE,
    VERSIONE    NUMBER(10, 0) DEFAULT 0        NOT NULL ENABLE,
    NOME_LAYER  VARCHAR2(200 BYTE)        NOT NULL ENABLE,
    URL         VARCHAR2(500 BYTE)        NOT NULL ENABLE,
    WORKSPACE   VARCHAR2(100 BYTE),
    CODICE      VARCHAR2(50 BYTE)        NOT NULL ENABLE,
    CONSTRAINT A4ST_LAYER_PK PRIMARY KEY ( ID ),
    CONSTRAINT A4ST_LAYER_COD_INT_UQ UNIQUE ( CODICE )
);

CREATE TABLE A4ST_PROPRIETA_LAYER (
    ID        NUMBER(20, 0)       NOT NULL ENABLE,
    VERSIONE  NUMBER(10, 0) DEFAULT 0        NOT NULL ENABLE,
    ID_LAYER  NUMBER(20, 0)        NOT NULL ENABLE,
    NOME      VARCHAR2(100 BYTE),
    VALORE    VARCHAR2(500 BYTE),
    CONSTRAINT A4ST_PROPRIETA_LAYER_PK PRIMARY KEY ( ID ) ,
    CONSTRAINT A4ST_PROPRIETA_LAYER_FK FOREIGN KEY ( ID_LAYER ) REFERENCES A4ST_LAYER ( ID )
)	;



CREATE TABLE A4SR_LAYER_PROFILO (
    ID              NUMBER(20, 0)        NOT NULL ENABLE,
    VERSIONE        NUMBER(10, 0) DEFAULT 0        NOT NULL ENABLE,
    ID_LAYER        NUMBER(20, 0)        NOT NULL ENABLE,
    PROFILO_UTENTE  VARCHAR2(50 BYTE)        NOT NULL ENABLE,
    CONSTRAINT A4SR_LAYER_PROFILO_PK PRIMARY KEY ( ID ),
    CONSTRAINT A4SR_ID_LAYER_FK FOREIGN KEY ( ID_LAYER )   REFERENCES A4ST_LAYER ( ID )
);


CREATE TABLE A4ST_ATTRIBUTI_LAYER (
    ID              NUMBER(20, 0)        NOT NULL ENABLE,
    VERSIONE        NUMBER(10, 0) DEFAULT 0        NOT NULL ENABLE,
    ID_LAYER        NUMBER(20, 0)        NOT NULL ENABLE,
    NOME            VARCHAR2(500 BYTE)        NOT NULL ENABLE,
    VALORE_DEFAULT  VARCHAR2(500 BYTE)        ,
    EDITABILE       NUMBER(1)        NOT NULL ENABLE,
    CONSTRAINT A4ST_ATTRIBUTI_LAYER_PK PRIMARY KEY ( ID ),
    CONSTRAINT A4ST_ATTRIBUTI_LAYER_FK FOREIGN KEY ( ID_LAYER )
        REFERENCES A4ST_LAYER ( ID )
);
		

CREATE TABLE A4ST_ANOMALIA_VALIDAZIONE (
    ID              			NUMBER(20, 0)        NOT NULL ENABLE,
    VERSIONE        			NUMBER(10, 0) DEFAULT 0        NOT NULL ENABLE,
    ID_LAVORAZIONE        		NUMBER(20, 0)        NOT NULL ENABLE,
    TIPO_ANOMALIA            	VARCHAR2(300 BYTE)        NOT NULL ENABLE,
    DETTAGLIO_ANOMALIA  		VARCHAR2(300 BYTE)        ,
    AREA 						number (20,6),
    SHAPE           GEOMETRY,
    CONSTRAINT A4ST_ANOMALIA_VALIDAZIONE_PK PRIMARY KEY ( ID )
);


 CREATE TABLE A4SR_ANOMALIA_WORKSPACE (
    ID                  NUMBER(20, 0)        NOT NULL ENABLE,
    VERSIONE            NUMBER(10, 0) DEFAULT 0        NOT NULL ENABLE,
    ID_WORKSPACE      NUMBER(20, 0)        NOT NULL ENABLE,
    ID_ANOMALIA       NUMBER(20, 0)        NOT NULL ENABLE,
    CONSTRAINT A4SR_ANOMALIA_WORKSPACE_PK PRIMARY KEY ( ID ),
    CONSTRAINT A4SR_ANOMALIA_WORKSPACE_FK FOREIGN KEY ( ID_WORKSPACE )  REFERENCES a4st_workspace_lav_suolo ( ID ),
    CONSTRAINT A4SR_ANOMALIA_WORKSPACE_FK_2 FOREIGN KEY ( ID_ANOMALIA ) REFERENCES A4ST_ANOMALIA_VALIDAZIONE ( ID )
);

CREATE TABLE A4ST_TMP_WORKSPACE (
    ID              NUMBER(20, 0)        NOT NULL ENABLE,
    VERSIONE        NUMBER(10, 0) DEFAULT 0        NOT NULL ENABLE,
    ID_LAVORAZIONE  NUMBER(20, 0)        NOT NULL ENABLE,
    SHAPE           GEOMETRY,
    COD_USO_SUOLO   VARCHAR2(3 BYTE)        NOT NULL ENABLE,
    STATO_COLT      NUMBER(3, 0)        NOT NULL ENABLE,
    NOTE            VARCHAR2(4000 BYTE),
    data_ultima_modifica DATE ,
    AREA number (20,6),
    ISTATP VARCHAR2(3),
    ID_GRID number(20,0)
);

CREATE TABLE A4SR_JOB_FME_LAVORAZIONE (
			id                 NUMBER(20, 0) NOT NULL,
			versione           NUMBER(20, 0) NOT NULL,
			id_lavorazione     NUMBER(20, 0) NOT NULL,
			id_job_fme         NUMBER(10) NOT NULL,
			tipo_job_fme       VARCHAR2(50) NOT NULL,
			data_inizio_esecuzione   DATE
			);
ALTER TABLE a4sr_job_fme_lavorazione ADD CONSTRAINT a4sr_job_lav_pk PRIMARY KEY ( id );
ALTER TABLE a4sr_job_fme_lavorazione ADD CONSTRAINT a4sr_job_lav_fk FOREIGN KEY ( id_lavorazione ) REFERENCES a4st_lavorazione_suolo ( id );

CREATE TABLE A4ST_SYNC_SUOLO_CATASTO (
    data_ultima_esecuzione  DATE NOT NULL,
    esito   VARCHAR2(2),
    msg     VARCHAR2(100)
    );

CREATE TABLE A4ST_SYNC_SUOLO_ESITO_PART (
    cod_nazionale               VARCHAR2(4 BYTE),
    foglio                      NUMBER(4,0) DEFAULT 9999,
    particella                  VARCHAR2(5 BYTE) NOT NULL,
	sub                         VARCHAR2(3 BYTE) NOT NULL,
	id_particella               NUMBER(9,0) NOT NULL,
	data_ultimo_agg_particella  DATE NOT NULL,
	esito                       VARCHAR2(2),
	data_ultimo_tentativo       DATE
	);

					
CREATE TABLE A4ST_AREA_DI_LAVORO 
   (	ID NUMBER(20,0) NOT NULL, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL, 
	ID_LAVORAZIONE NUMBER(20,0) NOT NULL, 
	SHAPE GEOMETRY , 
	CONSTRAINT A4ST_AREA_DI_LAVORO_PK PRIMARY KEY (ID)
   );	
   
CREATE TABLE A4ST_TEMP_CLIP_SU_ADL 
   (	ID NUMBER(20,0) NOT NULL, 
    VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL, 
	ID_GRID NUMBER(3,0), 
	ISTATP VARCHAR2(3 BYTE), 
	COD_USO_SUOLO VARCHAR2(3 BYTE), 
	STATO_COLT NUMBER(2,0), 
	SORGENTE VARCHAR2(50 BYTE), 
	NOTE VARCHAR2(4000 BYTE), 
	CAMPAGNA NUMBER(4,0), 
	UTENTE VARCHAR2(500 CHAR),
	DATA_INIZIO_VALIDITA DATE NOT NULL, 
	AREA NUMBER(20,6), 
	SHAPE GEOMETRY , 
	ESITO_VALIDAZIONE VARCHAR2(50 BYTE), 
	POSIZIONE_POLIGONO VARCHAR2(3 BYTE), 
	POLIGONO_INTERO NUMBER(1,0), 
	ID_SUOLO_ORIGINALE NUMBER(20,0), 
	ID_LAVORAZIONE NUMBER(20,0), 
	 CONSTRAINT A4S_TMP_CLIP_ADL_PK PRIMARY KEY (ID),
	 CONSTRAINT A4S_TMP_CLIP_ADL_GRID_SUOLO_FK FOREIGN KEY (ID_GRID)
	  REFERENCES A4ST_GRIGLIA_SUOLO (ID), 
	 CONSTRAINT A4S_TMP_CLIP_ADL_LAV_SUOLO_FK FOREIGN KEY (ID_LAVORAZIONE)
	  REFERENCES A4ST_LAVORAZIONE_SUOLO (ID), 
	 CONSTRAINT A4S_TMP_CLIP_ADL_DEC_SCOLT_FK FOREIGN KEY (STATO_COLT)
	  REFERENCES A4SD_STATO_COLT (STATO_COLT), 
	 CONSTRAINT A4S_TMP_CLIP_ADL_DEC_USO_FK FOREIGN KEY (COD_USO_SUOLO)
	  REFERENCES A4SD_USO_SUOLO (COD_USO_SUOLO)
   );
   
 CREATE TABLE A4ST_TEMP_POLIGONI_IN_OUT_ADL 
   (	ID NUMBER(20,0) NOT NULL ENABLE, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	ID_LAVORAZIONE NUMBER(20,0) NOT NULL ENABLE, 
	COD_USO_SUOLO VARCHAR2(3) NOT NULL ENABLE, 
	STATO_COLT NUMBER(3,0) NOT NULL ENABLE, 
	NOTE VARCHAR2(4000), 
	AREA NUMBER(20,6), 
	ID_GRID NUMBER(6,0), 
	ISTATP VARCHAR2(3), 
	SORGENTE VARCHAR2(50), 
	SHAPE GEOMETRY , 
	ESITO_VALIDAZIONE VARCHAR2(100));
   
   
   
   
