-- 1. Sequence
CREATE SEQUENCE NXTNBR
  START WITH 100000
  NOCYCLE
  NOCACHE
  ORDER;
    
  
--Tabella per la gestione del retry	
   CREATE TABLE A4GT_BDN_SYNC_DATI (	
		ID NUMBER NOT NULL,
		ANNO NUMBER(4), 
		CUAA VARCHAR2(16), 
		STATO_ESECUZIONE VARCHAR2(20), 
		DATA_ESECUZIONE DATE,
		CONSTRAINT A4GT_BDN_SYNC_DATI_PK PRIMARY KEY (ID)
	);
   
--Tabelle per il salvataggio delle movimentazioni pascolo	
   CREATE TABLE A4GT_BDN_MOVIMENTI_PASCOLO(
	  ID_MOVI        NUMBER NOT NULL,
	  ID_ALLE        NUMBER,
	  CODI_ASLL      VARCHAR2(8),
	  CODI_FISC_ALLE VARCHAR2(16),
	  CODI_SPEC      VARCHAR2(4),
	  CODI_FISC_DETE VARCHAR2(16),
	  CODI_ASL_AZIE  VARCHAR2(4),
	  ID_PASC        NUMBER,
	  CODI_PASC      VARCHAR2(8),
	  DESC_COMU_PASC VARCHAR2(150),
	  ASL_PASC       VARCHAR2(4),
	  DATA_INGR_PASC DATE,
	  DATA_USCI_PASC DATE,
	  NUME_OVIN      NUMBER,
	  DATA_COMU_AUTO DATE,
	  CODI_DOCU      VARCHAR2(80),
	  DATA_DOCU      DATE,
	  TIPO_MOVI      VARCHAR2(2),
	  NUME_CAMP      NUMBER(4),
	  FLAG_CONT      NUMBER(1),
	  DATA_INSE      DATE,
	  DATA_REVI      DATE,
	  DATA_FINE      DATE,
	  CONSTRAINT A4GT_BDN_MOVIMENTI_PASCOLO_PK PRIMARY KEY (ID_MOVI)
	);
	 
--Tabelle per il salvataggio della consistenza pascolo	 
	create table A4GT_BDN_CONSIST_PASCOLO (
	  ID_CPWS        NUMBER NOT NULL,
	  CODI_FISC_SOGG VARCHAR2(16),
	  NUME_CAMP      NUMBER,
	  CODI_PASC      CHAR(8),
	  FASC_ETAA      VARCHAR2(10),
	  NUME_CAPI      NUMBER(9,3),
	  NUME_CAPI_MEDI NUMBER(9,3),
	  GIOR_PASC      NUMBER,
	  CODI_GRUP_SPEC VARCHAR2(4),
	  CODI_SPEC      VARCHAR2(4),
	  DESC_SPEC      VARCHAR2(250),
	  COOR_LATI      NUMBER,
	  COOR_LONG      NUMBER,
	  NUME_FOGL      NUMBER(5),
	  NUME_PART      CHAR(5),
	  CODI_SEZI      CHAR(1),
	  CODI_SUBA      CHAR(4),
	  CODI_SIGL_PROV CHAR(2),
	  CODI_PROV      CHAR(3),
	  CODI_COMU      CHAR(3),
	  DESC_LOCA      VARCHAR2(250),
	  CODI_FISC_RESP VARCHAR2(16),
	  DECO_STAT      NUMBER,
	  DATA_INIZ      DATE,
	  DATA_FINE      DATE,
	  DATA_AGGI      DATE,
	  USER_NAME      VARCHAR2(20),
	  CONSTRAINT A4GT_BDN_CONSIST_PASCOLO_PK PRIMARY KEY (ID_CPWS)
	);
	
	--Tabelle per il salvataggio della consistenza allevamento
	CREATE TABLE A4GT_BDN_CONS_ALLEVAMENTO
		(
		  ID_CAWS           NUMBER NOT NULL,
		  CODI_FISC_SOGG    VARCHAR2(16),
		  NUME_CAMP         NUMBER(4),
		  ID_ALLE_BDN       NUMBER,
		  CODI_SPEC         VARCHAR2(4),
		  CODI_ASLL         CHAR(8),
		  CODI_FISC_PROP    VARCHAR2(16),
		  CODI_FISC_DETE    VARCHAR2(16),
		  CONS_CAPI_0_6     NUMBER(9,3),
		  CONS_CAPI_6_24    NUMBER(9,3),
		  CONS_CAPI_OVER_24 NUMBER(9,3),
		  CONS_TOTA         NUMBER(9,3),
		  CONS_VACC_OVER_20 NUMBER(9,3),
		  DATA_INIZ_DETE    DATE,
		  DATA_FINE_DETE    DATE,
		  DECO_STAT         NUMBER,
		  DATA_INIZ         DATE,
		  DATA_FINE         DATE,
		  DATA_AGGI         DATE,
		  USER_NAME         VARCHAR2(20),
		  CONSTRAINT A4GT_BDN_CONS_ALLEVAMENTO_PK PRIMARY KEY (ID_CAWS)
		);
	
	
	  CREATE TABLE A4GT_BDN_AZIENDA
   		(	
   			ID 				NUMBER(20,0) NOT NULL, 
			CODICE_AZIENDA 	VARCHAR2(8), 
			CODICE_COMUNE 	VARCHAR2(3) NOT NULL, 
	 		CONSTRAINT A4GT_BDN_AZIENDA_PK PRIMARY KEY (ID)
   		);
   		CREATE UNIQUE INDEX A4GT_BDN_AZIENDA_UIDX ON A4GT_BDN_AZIENDA (CODICE_AZIENDA);