--Domanda
INSERT INTO A4GT_DOMANDA
(ID, VERSIONE, NUMERO_DOMANDA, COD_MODULO_DOMANDA, DESC_MODULO_DOMANDA, CUAA_INTESTATARIO, DT_PROTOCOLLAZIONE, NUM_DOMANDA_RETTIFICATA, COD_ENTE_COMPILATORE, DESC_ENTE_COMPILATORE, RAGIONE_SOCIALE, DT_PRESENTAZIONE, DT_PRESENTAZ_ORIGINARIA, DT_PROTOCOLLAZ_ORIGINARIA, ANNULLO_RIDUZIONE, IBAN, ANNO_CAMPAGNA, STATO)
VALUES(844491, 2, 187720, 'BPS_2018', 'PAGAMENTI DIRETTI', 'BRSMNC68R58H330G', TIMESTAMP '2018-05-25 11:02:35.000000', NULL, 7, 'CAA COLDIRETTI DEL TRENTINO - 006', 'BRESCIANI MONICA', TIMESTAMP '2018-05-25 11:02:06.000000', NULL, NULL, NULL, 'IT40L0801634310000000954702', 2018, 'IN_ISTRUTTORIA');
--Stato Lav Sostegno
INSERT INTO A4GD_STATO_LAV_SOSTEGNO
(ID, VERSIONE, IDENTIFICATIVO, DESCRIZIONE)
VALUES(13122, 0, 'PAGAMENTO_AUTORIZZATO', 'Pagamento autorizzato a seguito dei controlli intersostegno');
INSERT INTO A4GD_STATO_LAV_SOSTEGNO
(ID, VERSIONE, IDENTIFICATIVO, DESCRIZIONE)
VALUES(13118, 0, 'NON_AMMISSIBILE', 'Domanda non ammissibile per il sostegno');
--Istruttoria
INSERT INTO A4GT_ISTRUTTORIA 
(ID, VERSIONE, ID_DOMANDA, ID_STATO_LAVORAZIONE, BLOCCATA_BOOL, ERRORE_CALCOLO, DATA_ULTIMO_CALCOLO, TIPOLOGIA, ID_ELENCO_LIQUIDAZIONE, SOSTEGNO)
VALUES(969997, 6, 844491, 13122, 0, 0, NULL, 'SALDO', null, 'DISACCOPPIATO');
INSERT INTO A4GT_ISTRUTTORIA
(ID, VERSIONE, ID_DOMANDA, ID_STATO_LAVORAZIONE, BLOCCATA_BOOL, ERRORE_CALCOLO, DATA_ULTIMO_CALCOLO, TIPOLOGIA, ID_ELENCO_LIQUIDAZIONE, SOSTEGNO)
VALUES(969998, 2, 844491, 13118, 0, 0, NULL, 'SALDO', NULL, 'SUPERFICIE');

COMMIT;