DROP ALL OBJECTS;
-- Versione 1.0

-- 1. Sequence
CREATE SEQUENCE NXTNBR
    START WITH 100000
    NOCYCLE
    NOCACHE;

-- 2. Tabella di Log
CREATE TABLE A4GT_LOGGING (
    ID NUMBER(19) NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    UTENTE VARCHAR2(500 CHAR) NOT NULL,
    TIPO_EVENTO VARCHAR2(500 CHAR) NOT NULL,
    TABELLA VARCHAR2(4000) NOT NULL,
    ID_ENTITA NUMBER(19) NOT NULL,
    DT_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT A4GT_LOGGING_PK PRIMARY KEY (ID)
);

CREATE TABLE A4GT_EVENTSTORED(
    ID NUMBER(20,0) NOT NULL,
    VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL,
    EVENTO VARCHAR2(500) NOT NULL,
    JSON_EVENT CLOB NOT NULL,
    USER_NAME VARCHAR2(100) NOT NULL,
    DATA_INSERIMENTO DATE NOT NULL,
    NUMERO_RETRY NUMBER(3,0) DEFAULT 0 NOT NULL,
    ERRORE CLOB,
    CONSTRAINT PK_EVENTSTORED PRIMARY KEY ("ID")

);

CREATE TABLE A4GT_LOGGING_VALIDAZIONE (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    UTENTE VARCHAR2(500 CHAR) NOT NULL,
    TIPO_EVENTO VARCHAR2(500 CHAR) NOT NULL,
    TABELLA VARCHAR2(4000) NOT NULL,
    ID_ENTITA BIGINT NOT NULL,
    DT_EVENTO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT A4GT_LOGGING_VALIDAZIONE_PK PRIMARY KEY (ID)
);

CREATE TABLE A4GT_FASCICOLO (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    CUAA VARCHAR2(16) NOT NULL,
    DT_AGGIORNAMENTO_FONTI_ESTERNE DATE,
    CONSTRAINT PK_FASCICOLO_DT PRIMARY KEY (ID, ID_VALIDAZIONE)
);

CREATE TABLE A4GD_TIPOLOGIA
   (	ID NUMBER(20,0) NOT NULL, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL, 
	DESCRIZIONE VARCHAR2(150), 
	DATA_INIZIO DATE, 
	DATA_FINE DATE, 
	AMBITO VARCHAR2(20) NOT NULL, 
	 CONSTRAINT PK_TIPOLOGIA_MACCHINARIO PRIMARY KEY (ID)
   );

CREATE TABLE A4GD_CLASSE_FUNZIONALE 
	(	ID NUMBER(20,0) NOT NULL,
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL,
	DESCRIZIONE VARCHAR2 (50),
	ID_TIPOLOGIA NUMBER(20,0) NOT NULL,
	DATA_INIZIO DATE,
	DATA_FINE DATE,
	CONSTRAINT PK_CLASSE_FUNZIONALE PRIMARY KEY ("ID"),
	CONSTRAINT FK_TIPOLOGIA_CLF FOREIGN KEY (ID_TIPOLOGIA) REFERENCES
	a4gd_tipologia (ID)
);   
   
CREATE TABLE A4GD_SOTTOTIPO
   (	ID NUMBER(20,0) NOT NULL, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL, 
	DESCRIZIONE VARCHAR2(200), 
	ID_TIPOLOGIA NUMBER(20,0), 
	DATA_INIZIO DATE, 
	DATA_FINE DATE,
	ID_CLASSE_FUNZIONALE NUMBER(20,0),
	 CONSTRAINT PK_TIPOLOGIA PRIMARY KEY (ID),
	 CONSTRAINT FK_TIPOLOGIA FOREIGN KEY (ID_TIPOLOGIA) REFERENCES A4GD_TIPOLOGIA (ID),
	 CONSTRAINT FK_CLASSE_FUNZIONALE FOREIGN KEY (ID_CLASSE_FUNZIONALE) REFERENCES A4GD_CLASSE_FUNZIONALE (ID)
   );

CREATE TABLE A4GT_MACCHINA (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    ID_FASCICOLO BIGINT,
    ID_VALIDAZIONE_FASCICOLO INTEGER DEFAULT 0,
    ID_SOTTOTIPO NUMBER(20) NOT NULL,
    MARCA VARCHAR2(50),
    MODELLO VARCHAR2(50),
    NUMERO_MATRICOLA VARCHAR2(50),
    NUMERO_TELAIO VARCHAR2(50),
    ANNO_DI_COSTRUZIONE NUMBER(4),
    TIPO_POSSESSO VARCHAR2(16),
    DOCUMENTO_POSSESSO VARCHAR2(50),
    TARGA VARCHAR2(50),
    DATA_IMMATRICOLAZIONE DATE,
    CF_PROPRIETARIO VARCHAR2(16),
    DENOMINAZIONE VARCHAR2(150),
    FLAG_MIGRATO NUMBER(1),
    CONSTRAINT PK_MACCHINA PRIMARY KEY (ID, ID_VALIDAZIONE),
    FOREIGN KEY (ID_FASCICOLO, ID_VALIDAZIONE_FASCICOLO) REFERENCES A4GT_FASCICOLO (ID, ID_VALIDAZIONE),
    CONSTRAINT FK_SOTTOTIPO FOREIGN KEY (ID_SOTTOTIPO) REFERENCES A4GD_SOTTOTIPO (ID)
);

CREATE TABLE A4GT_MACCHINA_MOTORIZZATA (
    ID BIGINT NOT NULL,
    ID_VALIDAZIONE INTEGER DEFAULT 0 NOT NULL,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
    MARCA_MOTORE VARCHAR2(50),
    TIPO_MOTORE VARCHAR2(50),
    ALIMENTAZIONE VARCHAR2(50),
    POTENZA NUMBER(20),
    MATRICOLA VARCHAR2(50),
    CONSTRAINT PK_MACCHINA_MOTORIZZATA  PRIMARY KEY (ID, ID_VALIDAZIONE),
    FOREIGN KEY (ID, ID_VALIDAZIONE) REFERENCES A4GT_MACCHINA (ID, ID_VALIDAZIONE)
);

-- Creazione A4GT_FABBRICATO
CREATE TABLE "A4GT_FABBRICATO" 
   (	"ID" NUMBER(20,0) NOT NULL , 
	"VERSIONE" NUMBER(10,0) DEFAULT 0 NOT NULL , 
	"ID_VALIDAZIONE" NUMBER(20,0) NOT NULL , 
	"ID_FASCICOLO" NUMBER(20,0) NOT NULL , 
	"ID_VALIDAZIONE_FASCICOLO" NUMBER(20,0) NOT NULL , 
	"ID_SOTTOTIPO" NUMBER(20,0) NOT NULL , 
	"DENOMINAZIONE" VARCHAR2(100), 
	"INDIRIZZO" VARCHAR2(50) , 
	"COMUNE" VARCHAR2(50) NOT NULL , 
	"VOLUME" NUMBER(10,0), 
	"SUPERFICIE" NUMBER(20,0), 
	"DESCRIZIONE" VARCHAR2(200), 
	"TIPO_CONDUZIONE" VARCHAR2(50),  
	 CONSTRAINT "A4GT_FABBRICATO_PK" PRIMARY KEY ("ID", "ID_VALIDAZIONE"), 
	 CONSTRAINT "FK_FASCICOLO_FABBRICATO" FOREIGN KEY ("ID_FASCICOLO", "ID_VALIDAZIONE_FASCICOLO")
	  REFERENCES "A4GT_FASCICOLO" ("ID", "ID_VALIDAZIONE") , 
	 CONSTRAINT "FK_SOTTOTIPO_FABBRICATO" FOREIGN KEY ("ID_SOTTOTIPO")
	  REFERENCES "A4GD_SOTTOTIPO" ("ID") 
   );

   -- Creazione A4GT_STRUMENTALI
CREATE TABLE "A4GT_STRUMENTALI" 
   (	"ID" NUMBER(20,0) NOT NULL , 
	"ID_VALIDAZIONE" NUMBER(20,0) NOT NULL , 
	"VERSIONE" NUMBER(10,0) DEFAULT 0 NOT NULL , 
	"SUPERFICIE_COPERTA" NUMBER(20,0), 
	"SUPERFICIE_SCOPERTA" NUMBER(20,0), 
	 CONSTRAINT "PK_FABBRICATO_CATASTO" PRIMARY KEY ("ID", "ID_VALIDAZIONE"), 
	 CONSTRAINT "FK_FABBRICATO_CATASTO" FOREIGN KEY ("ID", "ID_VALIDAZIONE")
	  REFERENCES "A4GT_FABBRICATO" ("ID", "ID_VALIDAZIONE") 
   );
   
   --Creazione A4GT_STOCCAGGIO
CREATE TABLE "A4GT_STOCCAGGIO" 
   (	"ID" NUMBER(20,0) NOT NULL, 
	"ID_VALIDAZIONE" NUMBER(20,0) NOT NULL, 
	"VERSIONE" NUMBER(10,0) DEFAULT 0 NOT NULL, 
	"COPERTURA" VARCHAR2(50), 
	"ALTEZZA" NUMBER(20,0), 
	 CONSTRAINT "PK_STOCCAGGIO" PRIMARY KEY ("ID", "ID_VALIDAZIONE"), 
	 CONSTRAINT "FK_STOCCAGGIO" FOREIGN KEY ("ID", "ID_VALIDAZIONE")
	  REFERENCES "A4GT_FABBRICATO" ("ID", "ID_VALIDAZIONE")
   );
   
   -- Creazione A4GT_SERRE
CREATE TABLE "A4GT_SERRE" 
   (	"ID" NUMBER(20,0) NOT NULL , 
	"ID_VALIDAZIONE" NUMBER(20,0) NOT NULL , 
	"VERSIONE" NUMBER(10,0) DEFAULT 0 NOT NULL , 
	"IMPIANTO_RISCALDAMENTO" NUMBER(1,0), 
	"ANNO_COSTRUZIONE" NUMBER(4,0), 
	"TIPOLOGIA_MATERIALE" VARCHAR2(100), 
	"ANNO_ACQUISTO" NUMBER(4,0), 
	"TITOLO_CONFORMITA_URBANISTICA" VARCHAR2(50), 
	 CONSTRAINT "PK_FABBRICATO_SERRE" PRIMARY KEY ("ID", "ID_VALIDAZIONE"), 
	 CONSTRAINT "FK_FABBRICATO_SERRE" FOREIGN KEY ("ID", "ID_VALIDAZIONE")
	  REFERENCES "A4GT_FABBRICATO" ("ID", "ID_VALIDAZIONE") 
   );
   
    -- Creazione A4GD_MAPPING_MACCHINA_AGS
CREATE TABLE "A4GD_MAPPING_AGS" 
   (
   	"ID" NUMBER(20,0), 
	"SCO_CLASSE" VARCHAR2(50), 
	"DE_CLASSE" VARCHAR2(50), 
	"SCO_SOTTO_CLASSE" VARCHAR2(50), 
	"DE_SOTTO_CLASSE" VARCHAR2(200), 
	"ID_TIPO_MACCHINA" NUMBER(50,0), 
	"DE_MACCHINA" VARCHAR2(200), 
	"ID_MACCHINA" NUMBER(50), 
	"ID_TIPOLOGIA" NUMBER(50,0), 
	"TIPOLOGIA" VARCHAR2(200), 
	"ID_CLASSE_FUNZIONALE" NUMBER(50,0), 
	"CLASSE_FUNZIONALE" VARCHAR2(200), 
	"ID_SOTTOTIPO" NUMBER(50,0), 
	"SOTTOTIPO" VARCHAR2(200), 
	 CONSTRAINT "PK_ID_MAPPING" PRIMARY KEY ("ID"), 
	 CONSTRAINT "FK_TIPOLOGIA_MAPPING" FOREIGN KEY ("ID_TIPOLOGIA")
	 	REFERENCES "A4GD_TIPOLOGIA" ("ID"),	 
	 CONSTRAINT "FK_CLASSE_FUNZIONALE_MAPPING" FOREIGN KEY ("ID_CLASSE_FUNZIONALE") 
	 	REFERENCES "A4GD_CLASSE_FUNZIONALE" ("ID"),
	 CONSTRAINT "FK_SOTTOTIPO_MAPPING" FOREIGN KEY ("ID_SOTTOTIPO")
	 	REFERENCES "A4GD_SOTTOTIPO" ("ID")
   );

   -- Creazione A4GT_DATI_CATASTALI
CREATE TABLE "A4GT_DATI_CATASTALI" 
   ("ID" NUMBER(20,0) NOT NULL,
	"ID_VALIDAZIONE" NUMBER(20,0) NOT NULL,
	"VERSIONE" NUMBER(10,0) DEFAULT 0 NOT NULL,
	"TIPOLOGIA" VARCHAR2(50),
	"PARTICELLA" VARCHAR2(10),
	"DENOMINATORE" VARCHAR2(50),
	"IN_TRENTINO" NUMBER(20,0),
	"SEZIONE" VARCHAR2(10),
	"FOGLIO" NUMBER(20,0),
	"COMUNE" VARCHAR2(50),
	"SUB" VARCHAR2(10),
	"INDIRIZZO" VARCHAR2(100),
	"SUPERFICIE" NUMBER(20,0),
	"CONSISTENZA" VARCHAR2(50),
	"CATEGORIA" VARCHAR2(50),
	"NOTE" VARCHAR2(200),
	"FABBRICATO_ID" NUMBER(20,0),
	"FABBRICATO_ID_VALIDAZIONE" NUMBER(20,0),
	"ESITO" VARCHAR(20),
	 CONSTRAINT "PK_DATI_CATASTALI" PRIMARY KEY ("ID", "ID_VALIDAZIONE"),
	 CONSTRAINT "FK_DATI_CATASTALI_FABBRICATO" FOREIGN KEY ("FABBRICATO_ID", "FABBRICATO_ID_VALIDAZIONE")
	 REFERENCES "A4GT_FABBRICATO" ("ID", "ID_VALIDAZIONE")
   );
   
   
 CREATE TABLE A4GT_CONTROLLO_COMPLETEZZA (
   ID BIGINT NOT NULL,
   VERSIONE NUMBER(10,0) DEFAULT 0,
   CUAA VARCHAR2(16 BYTE) NOT NULL,
   TIPO_CONTROLLO VARCHAR2(100 BYTE) NOT NULL,
   ESITO INTEGER,
   ID_CONTROLLO INTEGER,
   DATA_ESECUZIONE DATE,
   UTENTE VARCHAR2(100 BYTE) NOT NULL,
   CONSTRAINT PK_CONTROLLO_COMPLETEZZA PRIMARY KEY (ID)
);

	CREATE TABLE A4GD_MAPPING_FABBRICATI_AGS (
		ID NUMBER(20),
		ID_SOTTOTIPO NUMBER(20),
		CODICE_AGS VARCHAR2(50),
		CONSTRAINT PK_MAPPING_AGS PRIMARY KEY (ID)
	);