DROP ALL OBJECTS;

CREATE SEQUENCE NXTNBR
  START WITH 1100
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE A4G_IMPORTO_LIQUIDATO (
   CUAA VARCHAR2(16 CHAR) NOT NULL,
   NUMERO_DOMANDA VARCHAR2(15 CHAR) NOT NULL,
   NUMERO_ELENCO NUMBER(10),
   TIPO_BILANCIO VARCHAR2(2 CHAR) NOT NULL,
   ANNO_ESERCIZIO NUMBER(11) NOT NULL,
   PROGRESSIVO_CREDITO NUMBER(11) NOT NULL,
   NUMERO_AUTORIZZAZIONE VARCHAR2(15),
   DATA_AUTORIZZAZIONE DATE,
   TIPO_PAGAMENTO VARCHAR2(500 CHAR) NOT NULL,
   CAPITOLO NUMBER(11) NOT NULL,
   CODICE_PRODOTTO VARCHAR2(6),
   DATA_ESECUZIONE DATE,
   PROGRESSIVO_PAGAMENTO NUMBER(11),
   INCASSATO_NETTO NUMBER(10,2) NOT NULL
);

CREATE TABLE A4G_IMPORTO_RECUPERATO (
   TIPO_BILANCIO VARCHAR2(2 CHAR) NOT NULL,
   ANNO_ESERCIZIO NUMBER(11) NOT NULL,
   PROGRESSIVO_CREDITO NUMBER(11) NOT NULL,
   IMPORTO_INCASSO NUMBER(13,2) NOT NULL,
   DESCRIZIONE_CAPITOLO VARCHAR2(150 CHAR) NOT NULL
);


