 SET REFERENTIAL_INTEGRITY FALSE;
 DROP ALL OBJECTS;
 SET REFERENTIAL_INTEGRITY TRUE;


 CREATE TABLE AABAANTI_TAB 
   (ID_ANTI        NUMBER NOT NULL, 
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
	CUAA           VARCHAR2(16 BYTE) NOT NULL, 
	ID_SOGG        NUMBER, 
	TIPO_PERS      NUMBER NOT NULL, 
	DATA_INIZ_VALI DATE NOT NULL, 
	DATA_FINE_VALI DATE, 
	DATA_INVI_PREF DATE, 
	ID_ORPA        NUMBER, 
	DATA_INSE      DATE, 
	DATA_AGGI      DATE, 
	ID_ALL1        NUMBER, 
	ID_ALL2        NUMBER, 
	 CONSTRAINT PK_AABAANTI_TAB PRIMARY KEY (ID_ANTI)
   ) 
;

 CREATE SEQUENCE AABAESAN_SEQ
	  START WITH 1
	  NOCYCLE
	  NOCACHE
	  ORDER;
  
 CREATE TABLE AABAESAN_TAB 
   (ID_ESAN        NUMBER NOT NULL , 
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
	ID_ANTI        NUMBER NOT NULL , 
	DECO_ESIT      NUMBER, 
	PROT_ESIT      VARCHAR2(50 BYTE), 
	CUAA           VARCHAR2(16 BYTE) NOT NULL , 
	DATA_INIZ_VALI DATE NOT NULL , 
	DATA_FINE_VALI DATE NOT NULL , 
	 CONSTRAINT PK_AABAESAN_TAB PRIMARY KEY (ID_ESAN),
	 FOREIGN KEY (ID_ANTI) REFERENCES AABAANTI_TAB (ID_ANTI) 
   ) 
;

 CREATE SEQUENCE AABAALL1_SEQ
	  START WITH 1
	  NOCYCLE
	  NOCACHE
	  ORDER;

CREATE TABLE AABAALL1_TAB 
   (	ID_ALL1 NUMBER, 
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,   
	DESC_IMPR VARCHAR2(300 BYTE), 
	DESC_PROV_IMPR VARCHAR2(300 BYTE), 
	CODI_NUME_ISCR VARCHAR2(100 BYTE), 
	DATA_ISCR DATE, 
	DESC_OGGE_SOCI VARCHAR2(4000 BYTE), 
	CODI_FISC VARCHAR2(16 BYTE), 
	CODI_PART_IVAA VARCHAR2(11 BYTE), 
	DESC_PEC VARCHAR2(300 BYTE), 
	DATA_INSE DATE, 
	DATA_AGGI DATE, 
	CUAA VARCHAR2(16 BYTE), 
	DESC_COGN VARCHAR2(100 BYTE), 
	DESC_NOME VARCHAR2(100 BYTE), 
	CODI_SEX VARCHAR2(1 BYTE), 
	DATA_NASC DATE, 
	CODI_NATU_GIUR VARCHAR2(10 BYTE), 
	CODI_BELF_NASC VARCHAR2(4 BYTE), 
	CODI_SIGL_PROV_NASC VARCHAR2(2 BYTE), 
	DESC_COMU_NASC VARCHAR2(100 BYTE), 
	CODI_BELF_RECA VARCHAR2(4 BYTE), 
	CODI_SIGL_PROV_RECA VARCHAR2(2 BYTE), 
	DESC_COMU_RECA VARCHAR2(100 BYTE), 
	CODI_CAPP_RECA VARCHAR2(5 BYTE), 
	DESC_INDI_RECA VARCHAR2(100 BYTE), 
	NUME_CIVI_RECA VARCHAR2(10 BYTE),
	CONSTRAINT PK_AABAALL1_TAB_NA PRIMARY KEY (ID_ALL1)
   )  ;

 CREATE SEQUENCE AABAALL2_SEQ
	  START WITH 1
	  NOCYCLE
	  NOCACHE
	  ORDER;
				  
CREATE TABLE AABAALL2_TAB 
   (	ID_ALL2 NUMBER, 
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL, 
	DESC_IMPR VARCHAR2(300 BYTE), 
	DESC_PROV_IMPR VARCHAR2(300 BYTE), 
	CODI_NUME_ISCR VARCHAR2(100 BYTE), 
	DATA_ISCR DATE, 
	DESC_FORM_GIUR VARCHAR2(300 BYTE), 
	DESC_ATTO_COST VARCHAR2(300 BYTE), 
	DESC_CAPI_SOCI VARCHAR2(300 BYTE), 
	DESC_DURA_SOCI VARCHAR2(300 BYTE), 
	DESC_OGGE_SOCI VARCHAR2(4000 BYTE), 
	CODI_FISC VARCHAR2(16 BYTE), 
	DESC_PEC VARCHAR2(300 BYTE), 
	DATA_INSE DATE, 
	DATA_AGGI DATE, 
	CUAA VARCHAR2(16 BYTE),
	DESC_RAGI_SOCI VARCHAR2(100 BYTE), 
	CODI_NATU_GIUR VARCHAR2(10 BYTE), 
	CODI_BELF_RECA VARCHAR2(2 BYTE), 
	CODI_SIGL_PROV_RECA VARCHAR2(2 BYTE), 
	DESC_COMU_RECA VARCHAR2(100 BYTE), 
	CODI_CAPP_RECA VARCHAR2(5 BYTE), 
	DESC_INDI_RECA VARCHAR2(100 BYTE), 
	NUME_CIVI_RECA VARCHAR2(10 BYTE),
	CONSTRAINT PK_AABAALL2_TAB_NA PRIMARY KEY (ID_ALL2)
   ) ;

 CREATE SEQUENCE AABAAZCO_SEQ
	  START WITH 1
	  NOCYCLE
	  NOCACHE
	  ORDER;
				  
 CREATE TABLE AABAAZCO_TAB 
   (ID_AZCO             NUMBER, 
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
	ID_ALL2             NUMBER, 
	ID_SOGG             NUMBER, 
	FLAG_VISURA         NUMBER DEFAULT 0,
	CUAA                VARCHAR2(16 BYTE),
	CODI_CARI           VARCHAR2(10 BYTE),
				DATA_INIZ_CARI DATE, 
				DATA_INIZ_VALI DATE, 
				DATA_FINE_VALI DATE,
	DATA_INSE           DATE, 
	DATA_AGGI           DATE, 
	 CONSTRAINT PK_AABAAZCO_TAB PRIMARY KEY (ID_AZCO),
	 FOREIGN KEY (ID_ALL2) REFERENCES AABAALL2_TAB (ID_ALL2) 
   ) 
;

 CREATE SEQUENCE AABASGCA_SEQ
	  START WITH 1
	  NOCYCLE
	  NOCACHE
	  ORDER;

  CREATE TABLE AABASGCA_TAB 
   (	ID_SGCA NUMBER, 
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,   
	ID_ALL1 NUMBER, 
	ID_ALL2 NUMBER, 
	FLAG_VISURA NUMBER DEFAULT 0, 
	CUAA VARCHAR2(16 BYTE), 
	CODI_CARI VARCHAR2(10 BYTE), 
	DATA_INIZ_VALI DATE, 
	DATA_INSE DATE, 
	DATA_AGGI DATE, 
	DESC_COGN VARCHAR2(100 BYTE), 
	DESC_NOME VARCHAR2(100 BYTE), 
	CODI_SEX VARCHAR2(1 BYTE), 
	DATA_NASC DATE, 
	CODI_NATU_GIUR VARCHAR2(10 BYTE), 
	CODI_BELF_NASC VARCHAR2(4 BYTE), 
	CODI_SIGL_PROV_NASC VARCHAR2(2 BYTE), 
	DESC_COMU_NASC VARCHAR2(100 BYTE), 
	CODI_BELF_RECA VARCHAR2(4 BYTE), 
	CODI_SIGL_PROV_RECA VARCHAR2(2 BYTE), 
	DESC_COMU_RECA VARCHAR2(100 BYTE), 
	CODI_CAPP_RECA VARCHAR2(5 BYTE), 
	DESC_INDI_RECA VARCHAR2(100 BYTE), 
	NUME_CIVI_RECA VARCHAR2(10 BYTE),
	CONSTRAINT PK_AABASGCA_TAB_NA PRIMARY KEY (ID_SGCA)
   ) ;
 CREATE SEQUENCE AABAALL3_SEQ
	  START WITH 1
	  NOCYCLE
	  NOCACHE
	  ORDER;
				  
 CREATE TABLE AABAALL3_TAB 
   (ID_ALL3        NUMBER NOT NULL ,
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,
	ID_SGCA        NUMBER  , 
	ID_ALL1        NUMBER  , 
	DESC_PEC       VARCHAR2(300 BYTE), 
	DATA_INSE      DATE, 
	USER_NAME_INSE VARCHAR2(50 BYTE), 
	DATA_AGGI      DATE, 
	 CONSTRAINT PK_AABAALL3_TAB PRIMARY KEY (ID_ALL3), 
	 FOREIGN KEY (ID_ALL1) REFERENCES AABAALL1_TAB (ID_ALL1) 
   ) 
;

 CREATE SEQUENCE AABAFACO_SEQ
	  START WITH 1
	  NOCYCLE
	  NOCACHE
	  ORDER;

 CREATE TABLE AABAFACO_TAB 
   (	ID_FACO NUMBER, 
    VERSIONE NUMBER(10) DEFAULT 0 NOT NULL,   
	CUAA VARCHAR2(16 BYTE), 
	DATA_NASC DATE, 
	DESC_COMU_NASC VARCHAR2(100 BYTE), 
	CODI_SIGL_PROV_NASC VARCHAR2(2 BYTE), 
	CODI_BELF_NASC CHAR(4 BYTE), 
	CODI_SEX CHAR(1 BYTE), 
	DESC_INDI_STRD VARCHAR2(100 BYTE), 
	DESC_GEOG_CIVI VARCHAR2(20 BYTE), 
	CODI_GEOG_BELF CHAR(4 BYTE), 
	CODI_GEOG_CAPP CHAR(5 BYTE), 
	DESC_GEOG_FRAZ VARCHAR2(50 BYTE), 
	CODI_GEOG_SIGL_PROV CHAR(2 BYTE), 
	DESC_GEOG_COMU VARCHAR2(60 BYTE), 
	ID_ALL3 NUMBER, 
	DECO_TIPO_PARE NUMBER, 
	CODI_NATU_GIUR VARCHAR2(10 BYTE), 
	CODI_BELF_RECA VARCHAR2(4 BYTE), 
	CODI_SIGL_PROV_RECA VARCHAR2(2 BYTE), 
	DESC_COMU_RECA VARCHAR2(100 BYTE), 
	CODI_CAPP_RECA VARCHAR2(5 BYTE), 
	DESC_INDI_RECA VARCHAR2(100 BYTE), 
	NUME_CIVI_RECA VARCHAR2(10 BYTE), 
	DESC_COGN VARCHAR2(100 BYTE), 
	DESC_NOME VARCHAR2(100 BYTE),
	CONSTRAINT PK_AABAFACO_TAB_NA PRIMARY KEY (ID_FACO)
   )  ;
 
CREATE TABLE ANOM_DU_GRAF_SETT_RIC_PRE (
	ID_ATTO_AMMI NUMBER,
	ID_ANOM NUMBER,
	DESC_ANOM VARCHAR2(150 BYTE),
	ID_PARC_AGRI NUMBER,
	ID_PARC_OP NUMBER,
	DATA_INIZ_VALI DATE,
	DATA_FINE_VALI DATE,
	CODI_TIPO_ANOM VARCHAR2(3 BYTE),
	VALO_ANOM VARCHAR2(2 BYTE),
	NUME_ANNO_CAMP NUMBER(4),
	DT_INS DATE,
	DT_UPD DATE,
	CONSTRAINT PK_ANOM_DU_GRAF_SETT_RIC_PRE PRIMARY KEY (ID_ATTO_AMMI)
);

CREATE TABLE APPO_SUPE_ACCERT (	
   	ID_SUPE_ACCERT NUMBER(20,0),
	VERSIONE NUMBER(10,0) DEFAULT 0,
	CUAA VARCHAR2(16),
	NUME_CAMP NUMBER(4,0),
	ID_UFFI_ORPA NUMBER(4,0),
	CODI_ATTO_OPR VARCHAR2(20),
	CODI_INTE VARCHAR2(32),
	SUPE_ACCE_AMMI NUMBER(12,2),
	SUPE_DETE NUMBER(12,2),
	MOTIVAZIONE_A1 VARCHAR2(2),
	MOTIVAZIONE_A2 VARCHAR2(2),
	MOTIVAZIONE_A3 VARCHAR2(2),
	MOTIVAZIONE_B0 VARCHAR2(2),
	MOTIVAZIONE_B1 VARCHAR2(2),
	DATA_INIZIO_VAL DATE, 
	DATA_FINE_VAL DATE,
	FONTE VARCHAR2(5) NOT NULL, 
	CONSTRAINT PK_ID_SUPE_ACCERT PRIMARY KEY (ID_SUPE_ACCERT)
);
   
CREATE SEQUENCE APPO_SUPE_ACCERT_SEQ
	  START WITH 1
	  NOCYCLE
	  NOCACHE
	  ORDER;

CREATE TABLE PAGAMENTI (	
	PK_ID_PAGAM NUMBER(20,0) NOT NULL, 
	VERSIONE NUMBER(10,0) DEFAULT 0 NOT NULL, 
	NUME_PROG_DECR NUMBER(6,0) NOT NULL, 
	NUME_CAMP_RIFE NUMBER(4,0), 
	ID_ENTE NUMBER(4,0), 
	DESC_ENTE VARCHAR2(128), 
	BC_ATTO_AMMI VARCHAR2(10), 
	ID_ATTO_AMMI NUMBER(1,0), 
	CODI_FISC VARCHAR2(16) NOT NULL, 
	CODI_ATTO_OPR VARCHAR2(20) NOT NULL, 
	ID_INTE NUMBER(1,0), 
	CODI_INTE NUMBER(38,0), 
	IMPO_DETE NUMBER(14,2), 
	IMPO_LIQUI NUMBER(14,2), 
	IMPO_RICHIESTO NUMBER(14,2), 
	DATA_AGGI DATE, 
	DECO_STAT_PAGA NUMBER(4,0), 
	DATA_INIZ_VALI DATE, 
	DATA_FINE_VALI DATE, 
	DECO_STAT NUMBER(4,0), 
	FONTE VARCHAR2(5) NOT NULL,
	CONSTRAINT PK_ID_PAGAM_PK PRIMARY KEY (PK_ID_PAGAM)
);

CREATE SEQUENCE PAGAMENTI_SEQ
	  START WITH 1
	  NOCYCLE
	  NOCACHE
	  ORDER;