DELETE FROM A4GT_SERRE;
DELETE FROM A4GT_STRUMENTALI;
DELETE FROM A4GT_STOCCAGGIO;
DELETE FROM A4GT_DATI_CATASTALI;
DELETE FROM A4GT_FABBRICATO;

DELETE FROM A4GT_MACCHINA_MOTORIZZATA;
DELETE FROM A4GT_MACCHINA;
DELETE FROM A4GT_FASCICOLO;
DELETE FROM A4GD_MAPPING_AGS;
DELETE FROM A4GD_SOTTOTIPO;
DELETE FROM A4GD_CLASSE_FUNZIONALE;
DELETE FROM A4GD_TIPOLOGIA;

delete from A4GT_CONTROLLO_COMPLETEZZA;
delete from A4GT_EVENTSTORED;

DELETE FROM A4GT_FASCICOLO;

COMMIT;